### ISSUE TITLE
Distribution through F-Droid

### ISSUE THREAD

**Issue by rugk** [mozilla-tw/FirefoxLite#1050]
It would be nice to have this app on F-Droid.

**Comment by joechengla** [comment]
thanks for the feedback. APKs will be made available on github soon when we start opening up

**Comment by rugk** [comment]
APKs are one thing. F-Droid is another. See: https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

Firefox Focus/Klar is already on F-Droid, BTW.

**Comment by chianger** [comment]
For non-GooglePlay distribution we're counting on https://github.com/mozilla-tw/Rocket/releases
at this moment.

**Comment by Rudloff** [comment]
The app seems to have some non-free dependencies: https://github.com/mozilla-tw/Rocket/blob/master/app/build.gradle#L166
This means it can't be included in F-Droid unless there is an option to build the app without these dependencies.

**Comment by dimqua** [comment]
I've openned a request here: https://gitlab.com/fdroid/rfp/issues/786

The app has so many non-free deps, so I afraid It can't be included without a specific [FOSS](https://en.wikipedia.org/wiki/Free_and_open-source_software) build flavour. :-(

**Comment by Rudloff** [comment]
I managed to build the app without Google Analytics or Firebase (you can have a look at the changes I made [here](https://gitlab.com/fdroid/fdroiddata/blob/3a41aa6ad981e6cac08d8110e2b03ad956b2d77a/metadata/org.mozilla.rocket.yml#L29)) so it now complies with our inclusion policy.

The only thing that is missing now is your approval. Would you be OK with us publishing the app with these changes?

**Comment by mTwTm** [comment]
I think I can take a look at the change when I have some time (currently busy working on other things.)
I'll take a look at if it's easy to create a flavor that is suitable for fdroid with your change in the lite repository, if no, I'll still try to take a look at if we can build one with your changes.

**Comment by mTwTm** [comment]
Oh it's actually some yml? I'm not sure if I'm familiar with these prebuild techniques but I think this seems a lot simpler than I expected. Will reply soon.

**Comment by mTwTm** [comment]
I think this workaround is workable, I'll take a look at if the built version with these workaround will lead to any trouble when I have some more time.

All green! I'll talk to the owner of the product and check if there's anything else he/she has concern with.

Just to make sure: so all builds if this apk on fdroid will pull directly from Github with this setting right? All future changes will be applied as long as we don't break these pre-builds and we dont need to provide a signed version of the built apk?

**Comment by Rudloff** [comment]
Thank you for taking the time to look at this!

Yes, our build server fetches the latest Git tag, applies our changes and builds the APK ; then we sign it with our own key and publish it.

**Comment by mTwTm** [comment]
So I think there's no red flag from the owner but we're also making sure other functions such as legal is aware of this change. I'll get back when it's all green.

**Comment by mTwTm** [comment]
@joechengla any update?

**Comment by thoroughbredg** [comment]
This issue can be closed. FF Lite is now on F-Droid:  
• https://staging.f-droid.org/packages/org.mozilla.rocket
• https://www.reddit.com/r/firefox/comments/b6h9fr/firefox_lite_now_available_on_fdroid_android/
• https://www.reddit.com/r/firefox/comments/b75isi/firefox_lite_is_finally_available_without_jumping/

The description/metadata can be improved though: https://gitlab.com/fdroid/fdroiddata/issues/1580

Thanks.

**Comment by rugk** [comment]
As for the ID: So Firefox Rocket == Firefox Light, okay…

**Comment by dimqua** [comment]
> However, we can not build 1.5.0 because upstream removed the `firebase_no_op` build variant we were using to build the app without Firebase: https://github.com/mozilla-tw/FirefoxLite/commit/ffe5c1e473e48993f0e92f6a55fb12390b683fd2

https://gitlab.com/fdroid/fdroiddata/issues/1609#note_164903681

**Comment by Bubu** [comment]
See https://github.com/mozilla-tw/FirefoxLite/issues/3827#issuecomment-574892773
