### ISSUE TITLE
The loading progress bar stuck at 10% sometimes

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#1487]
STR:
 1. Launch Rocket
 2. Navigate to Facebook with your account and password
 3. Tap any photos randomly 
 4. Tap system Back key
 5. Repeat step3 and step4

Expected result:
 - The loading progress bar will not stuck at 10%

Actual result: 
 - The loading progress bar stuck at 10% sometimes.

Device: Redmi Note 4X
Rocket nightly: 1.0.4 (2333)
Android version: 7.0
WebView version: 64.0.3282.137

**Comment by chianger** [comment]
I'm giving it S1 because the progress bar is very obvious user facing feature.
Need triage to determine the priority.

**Comment by weslyhuang** [comment]
may relevant to Webview design, and not 100% reproducible for this case (FB repeat in/out)

**Comment by weslyhuang** [comment]
removed from 2.1. but would like to check further later (about progress bar display issue)
