### ISSUE TITLE
[dogfooding] blank bar above url bar

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#168]
only happened on Oppo A37.

Build 213

**Comment by chianger** [comment]
investigate before we can decide the priority

**Comment by Conjuror** [comment]
may releted to #284

**Comment by mTwTm** [comment]
Could be fixed after fixing #2100, QAwanted.

**Comment by Daisy-pliu** [comment]
Verify ✅
related ticekt #2100
