### ISSUE TITLE
would be nice to support to close tabs

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#1714]
(Issued by Eddie)

Same above (issue 1713), since most mobile browser supports that, and it's easier to close than the 'x' button

**Comment by pharspher** [comment]
We have a discussion with UX before, and they prefer to have a more comprehensive plan about swipe gesture instead of providing only "swipe to dismiss"

**Comment by pharspher** [comment]
Close since swipe-to-dismiss and close-all-tabs were already implemented
