### ISSUE TITLE
Experiment: Remote configurable push notification on Day 1 to urge users to come back

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#1788]
Problem:
 - Around 70% users stop using Firefox Lite on 1st day of install

User Story
 - As PMM, I would like to find the best timing/messaging to retain users on Day 1

Hypothesis:
 - If we push relevant message on Day 1 (e.g. features users don't have the chance to learn), we can improve Day 1 retention

three remote configurable:

    of/off (default off)
    delay time (after onboarding finish, unit: hour, e.g., 20hr later)
    message string

AC:
1. apply to new users only . (upgrade users won't get such message)
2. installs whoever have such Day1 notification displayed, won't get the message anymore.
3. Clean install will be treated as new users.
4. Need to be able to compare retention rate of users who didn't get the push or get pushed with specific message/time

Notes after some discussions:
 - Very likely that the remote config isn't available when first run for partial users, so we need to send telemetry event for successful remote config reception so we can measure only users that received the config.
 - Schedule timer when click on onboarding finish (of new user) may have better chance to receive the remote config? also the timing is more aligned regarding initial product usage.

Suggested telemetry event structure (format: event name/method/object/value{extra})
 - Firstrun Fetch Push config/get/firstrun_push/null {delay: , message: }
 - Firstrun Push notification shown/show/firstrun_push/null {delay: , message: }

**Comment by elin-moco** [comment]
This might need to be implemented with RemoteConfig

**Comment by elin-moco** [comment]
@mxlius may I know if it's possible to implement a notification with remote config on/off,
to notify user when they installed after 1 day, no matter Rocket is in background or foreground?

**Comment by elin-moco** [comment]
Maybe what we need in the config is "reminder days after install"
so that we can A/B test what time is best to remind user to increase retention rate

**Comment by elin-moco** [comment]
Also will need to avoid users who have seen the feedback dialog

**Comment by weslyhuang** [comment]
notification style: use system's.

**Comment by joechengla** [comment]
One idea is that we will use remote config to configure a delayed notification and the message.
Through remote config, we can configure how long is the delay (likely in hours), and the content of the notification.

**Comment by weslyhuang** [comment]
three configurable:
1. of/off
2. delay time (e.g., 20hr later)
3. msg

**Comment by elin-moco** [comment]
@chianger are we able to prioritize this?
It would be great if we can have this by mid-November.

**Comment by chianger** [comment]
@mxlius is investigating this as #2496

**Comment by chianger** [comment]
carry over to sprint L.

**Comment by chianger** [comment]
Eddie and I had consolidate the requirements on the comment 0.

**Comment by chianger** [comment]
Spike created to assess the efforts so I'm pushing this to future sprint.

**Comment by elin-moco** [comment]
Just added my suggestions regarding the telemetry event: (format: event name/method/object/value{extra})

 - Receive Firstrun Push config/get/firstrun_push/null {delay: , message: }
 - Firstrun Push notification shown/show/firstrun_push/null {delay: , message: }

**Comment by Daisy-pliu** [comment]
@elin-moco  please let us know , (cc: @mxlius)
1. Do you need "timer" set by minutes?
2. Please specify the expectation of each scenario as following.
3. Any cases you want to add but missing?

Test scenario:
SC1 : Set timer to "1"-> Fresh install
1. Set timer to "1" 
2. Uninstall
3. Install

SC2 : Fresh install  -> Set timer to "1"
1. Uninstall
2. Install
3. Set timer to "1" 

SC2: Change text ->Fresh install
1. Set timer to 1 with new text “Be brave, set as default, help us to be better!”
2. Uninstall
3. Install

SC3 : Fresh install->Change text
1. Given timer to 1 with text “Be brave, set as default”
2. Uninstall
3. Install
4. Wait 20 min
5. Set timer to 1 with new text “Be brave, set as default, help us to be better!”

SC4: Upgrade app -> set timer to 1
  1. Given app installed
  2. Set timer to 1 
  3. Upgrade 

SC5: Fresh install -> set timer to floating number
1. Uninstall
2. Set timer to 0.2
3. install

SC6: Fresh install -> set timer to String
1. Uninstall
2. Set timer to "Hello"
3. install

SC6: Fresh install-> set timer to -1
1. Set timer is 1 
2. Uninstall
3. Install
4. Wait 20 min, set timer to -1

SC7: Fresh install -> set timer to 0 
1. Given timer is 1
2. Uninstall
3. Install
4. Wait 20 min, set timer to 0

**Comment by elin-moco** [comment]
@Daisy-pliu 

1. Pardon me for not making thing clearer in the beginning of this ticket, but seeing some experiments (like desktop) around first few minutes of install, I feel like we will need to be able to figure out the best "minute" to push after install.
2. My expectations to each scenario
 - SC1: see push notification “Be brave, set as default!” around 1 hour later
 - SC2: see push notification “Be brave, set as default!” around 1 hour later
 - SC3: the result should based on the config before install, if no config previously we should not see the push notification after 1 hour
 - SC4: see push notification “Be brave, set as default, help us to be better!” around 1 hour later
 - SC5: see push notification “Be brave, set as default" around 1 hour later
 - SC6: not see the push notification after 1 hour
 - SC7: not see the push notification
 - SC8: not see the push notification
 - SC9: see push notification “Be brave, set as default!” around 1 hour later
 - SC10: if the message is set, user should not see the push notification, if message is set to “Be brave, set as default!”, user should see push notification “Be brave, set as default!” around 1 hour later
3. May be update the precondition of SC3/SC10? or maybe new scenarios based on these:
 - SC3 previously no config
 - SC10 previously no message config

**Comment by Daisy-pliu** [comment]
Per discussion with @elin-moco , spec may need change to Integer input with minutes unit

**Comment by Daisy-pliu** [comment]
After requirement change we have timer set in minutes

Env:
[Crashlytics remote config for nighlty](https://console.firebase.google.com/u/0/project/rocketnightly/config)

Test scenario:
**SC1 : Time is "-1" -> Uninstall -> Set timer to "4"->  install** ❌
1. Set timer to "-1" in Firebase with text "SC1-pre!" 
2. Uninstall Zerda
3. Set timer to "4" in Firebase with text "SC1-after!" 
4. Install Zerda, keep screen on 

Expect: see push notification "SC1-after" after 4 min
Verify: 11:46~11:50 it shows "Be brave, set us default!"

**SC2 : Set timer to "3"-> Fresh install**
1. Given timer to "3" in Firebase with text "Be brave, set as default,SC2"
2. Uninstall Lite
3. Install Lite

Expect: see push notification "Be brave, set as default,SC2" after 3 min

**SC3 : Time is "0" -> Uninstall -> Set timer to "4"->  install**
1. Set timer to "0" in Firebase with text "SC3-pre" 
2. Uninstall Lite
3. Set timer to "4" in Firebase with text "SC3-after" 
4. Install Lite

Expect: see push notification "in Firebase with text "SC3-after" after 4 min

**SC4: Change text ->Fresh install**
1. Given timer is 4 with text “SC4-pre”
2. Set timer to 4 with new text “SC4-after”
3. Uninstall Lite
4. Install Lite

Expect: see push notification “SC4-after!” after 4 min


**SC5 : Fresh install->Change text**
1. Given timer is 4 with text “SC5-pre”
2. Uninstall Lite
3. Install Lite
4. Wait 1 min
5. Set timer to 4 with new text “ SC5-after!”

Expect: see push notification “SC5-after!” after 4 min

**SC6: Upgrade app -> set timer to 1**
  1. Given Lite installed, time is 1 with text  "SC6-pre"
  2. Set timer to 1 with new text “SC6-after!”
  3. Upgrade  Lite

Expect: not see any push notification with “SC6-pre!” or "SC6-after!"

**SC7: Fresh install -> set timer to floating number**
1. Given Lite installed, time is 4 with text “Be brave, set as default, SC7-pre"
2 Uninstall Lite
3. Set timer to 0.2 in Firebase with text “Be brave, set as default,SC7-after!”
4. install Lite

Expect: not see  push notification with text “Be brave, set as default,SC7-after!”

**SC8: Fresh install -> set timer to String**
1. Given Lite installed, time is 1 with text “Be brave, set as default, SC8-pre"
2. Uninstall Lite
2. Set timer to "Hello" in Firebase with text “Be brave, set as default,SC8-after!”
3. install Lite

Expect: not see  push notification with text “Be brave, set as default,SC8-after!”

**SC9: Fresh install-> set timer to -1**
1. Set timer is 1  in Firebase with text “Be brave, set as default,SC9-pre!”
2. Uninstall Lite
3. Install Lite
4. Wait 20 min, set timer to -1 with text “Be brave, set as default,SC9-after!”
5. Uninstall Lite
6. Install Lite

Expect: 
1. not see push notification “Be brave, set as default,SC9-pre!” after 1 housr
2. not see push notification “Be brave, set as default,SC9-after!” after 1.5 hour

**SC10: Fresh install -> set timer to 0** 
1. Given timer is 1 in Firebase  with text “Be brave, set as default,SC10-pre!”
2. Uninstall Lite
3. Install Lite
4. Wait 20 min, set timer to 0 with text “Be brave, set as default,SC10-after!”
5. Uninstall Lite
6. Install Lite

Expect: 
1.  not see push notification “Be brave, set as default,SC10-pre!”
2. not see push notification “Be brave, set as default,SC10-after!”

**Comment by Daisy-pliu** [comment]
**Device:**
Google Pixel 2 (9.0)
**Test scenario:**
**SC1 : Time is "-1" -> Uninstall -> Set timer to "4"->  install** 
Expect: see push notification "SC1-after" after 4 min
Actual : 2019.3.4 11:46~11:50 -> notification shows "Be brave, set us default!" 
Verify: ❌


**SC2 : Set timer to "3"-> Fresh install**
Expect: see push notification "Be brave, set as default,SC2" after 3 min
Actual : 2019.3.4 12:00~12:04 -> notififcation shows "Be brave, set us default!"
Verify: ❌

**Comment by Daisy-pliu** [comment]
Test scenario:
**[SC5 : Fresh install->Change text](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)** 
Verify: ❓ 2019.3.4 15:23~15:30 (15:26 change config as step 6) -> show "SC5-pre" cc: @elin-moco 

**[SC6: Upgrade app -> set timer to 4](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)**
Verify: ✅ 2019.3.4 14:36~ 14:40 -> not show any notification

**[SC7: Fresh install -> set timer to floating number](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)**
Verify: ✅ 2019.3.4 14:43 ~ 14:40 -> not show any notification

**[SC8: Fresh install -> set timer to String](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)**
Verify: ✅ 2019.3.4 14:48 ~ 14:52 -> not show any notification

**[SC9: Fresh install-> set timer to -1](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)**
Verify: ✅ 2019.3.4 15:53 ~ 16:00 (15:56 change config as step 5)-> not show any notification

**[SC10: Fresh install -> set timer to 0](https://github.com/mozilla-tw/FirefoxLite/issues/1788#issuecomment-469109592)**
Verify: ✅ 2019.3.4 16:01 ~ 16:08 (16:04 change config as step 5)-> not show any notification
