### ISSUE TITLE
(meta) Content Portal

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#1819]
- News
- Videos
- Games
- Sponsored Sites
- Product Promotions (E-Commerce)

**Comment by weslyhuang** [comment]
copied from# 1828:

1. fixed tile(s) in home, for partner site promotion.
2. need a mechanism so the partner can tell users are from Rocket.

**Comment by Jacklin-ux** [comment]
The proposal is here: https://mozilla.invisionapp.com/d/main#/loading

**Comment by Jacklin-ux** [comment]
Transition reference: https://freefrontend.com/css-arrows/
(MOUSE SCROLL ANIMATION)
![image](https://user-images.githubusercontent.com/22672569/43449305-ae68b19e-94e2-11e8-8744-182d713048e5.png)

**Comment by Jacklin-ux** [comment]
News: https://github.com/mozilla-tw/Rocket/issues/2712
Games: https://github.com/mozilla-tw/Rocket/issues/2818

**Comment by chianger** [comment]
This is a too big meta bug that we don't really need it to track now.
