### ISSUE TITLE
While a user paste a link to search bar, it'll display as a link

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#197]
as title. My expectation is to display as pure text.

STR:
1. choose a image and long press
2. choose "copy link address"
3. tap on search bar
4. long press on search bar
5. tap on "paste"

Actual Result:

5. url address displays as link

Expected Result:

5. url address displays as pure text

Build 264

**Comment by NashTung** [comment]
It can be reproduced
Video: https://drive.google.com/open?id=1cWYXTE6C1kzOGLPGUGc6NTV_JNv5n2Yq

Device: Redmi 4A
Rocket: 2.1.1(4587)
Android: 7.1.2
Android Webview: 66.0.3359.158

**Comment by mTwTm** [comment]
Won't fix, @Jacklin-ux to reaffirm.
