### ISSUE TITLE
Experiment: Test product promotion from e-commerce partners as part of Content Portal

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#1999]
**User story**
As Mozilla, we'd like to offer e-commerce contents to users as part of the content portal offering

**Acceptance Criteria (how do I know when I’m done?)**
1. On the UI level, users can access the content portal and e-commerce offerings will be seen
2. We have properly implemented UI event telemetry
3. We have properly implemented partner referral code, if applicable

**Comment by Jacklin-ux** [comment]
Content portal concept "Subscribe your favorite categories" : https://drive.google.com/drive/folders/1yEHc8-KV1iwx8VXHNYELUViJml4r6Sae?usp=sharing

**Comment by chianger** [comment]
QAWanted for @Daisy-pliu to design test cases.

**Comment by Daisy-pliu** [comment]
checked with @Jacklin-ux that the detail flow is not yet finalized, QA will wait until the UX design is locked is done.

**Comment by elin-moco** [comment]
@joechengla Do we want to track user-defined interests here?
Or just suggested ones for now?

**Comment by chianger** [comment]
not yet able to design cases given current limited spec.

**Comment by Jacklin-ux** [comment]
ux spec: https://drive.google.com/file/d/1Ik6lQDLHOrJKcbF-NCphcVUVO6hcaBm3/view?usp=sharing

(WIP)
Need to pick up what coupons/promo we would like to show in Life feed?
 
Some questions want to know:
1. Who is our target users?
2. What kind of coupons/promo they like? 
3. Do we design "sort by category" feature? or just show by due date?
...

**Comment by TLHuang** [comment]
The visual spec is ready, link https://drive.google.com/drive/folders/1uVpAp7RC3Je9lZ5-Zo2dYKnCjsbV_TrX?usp=sharing

**Comment by chianger** [comment]
Changed to Size: wanted since we split some efforts to a separate spike #3229

**Comment by Jacklin-ux** [comment]
UX spec of "E-Voucher & Tiket": https://drive.google.com/file/d/1qGuGcZK4VM6qD8klaf-xfMFLeLvQhbT3/view?usp=sharing

**Comment by elin-moco** [comment]
From marketing perspective, we may need this ping to help answer which kind of promotion have better performance (CTR/revenue).

Per discussion with Nevin, the suggested event structure would be:
 - Open lifefeed promo: open/panel/lifefeed_promo
 - Click on promo item: click/panel/lifefeed_promo {pos, id=(custom sequence number), feed=(banner|list), source=(bukalapak|tokopedia), category=(product|coupons), subcategory=(smartphones|computer|limited-time|credit-card)}

where the information of id, feed, source, category, subcategory may come from the json file we provided.

**Comment by Daisy-pliu** [comment]
[coupon & banner test case ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D328) (TC0220~TC0225)  is ready

**Comment by chianger** [comment]
Close this as meta bug

**Comment by Daisy-pliu** [comment]
This ticket manly focus on coupon UI.
**Version :** Nightly 1.4.0 (11590)
**Verify :** ✅
**Test case in full run:** TC0220, TC0222,TC0224,   (TC0225 not ship)

**Verify :** ❌
**Test case in details:** backward compatibility
1. Current version:  nightly1.4.0 (11590) 
    1. VPN in Indo
    - ticket, Coupon  (00) -> nothing
    - ticket, Coupon  (01) -> nothing  -> which should be coupon ([fix PR](https://github.com/mozilla-tw/FirefoxLite/pull/3513) is on the way)
    - ticket, Coupon (10) -> ticket
    - ticket, Coupon (11) -> coupon


    2. VPN in India
    - news, (1)-> news
    - news, (0)-> nothing

2. Last release version: nighlty 1.4.0 (11336) 
    1.  VPN in Indo
    - ticket, Coupon  (00) -> nothing
    - ticket, Coupon (01)-> nothing
    - ticket, Coupon (10)-> ticket
    - ticket, Coupon (11)-> ticket


    2.  VPN in India
    - news, (1)-> news
    - news, (0)-> nothing

**Note:** 
In this sprint, we split out Coupon validation when no network but has cache to next sprint, #3523 is opened to track this sub-feature
