### ISSUE TITLE
download manager enhancement v1

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2002]

**Comment by joechengla** [comment]
User feedback: For the download process, please add the download percentage

**Comment by joechengla** [comment]
To support
1. Pause/Resume
2. Download Progress

**Comment by weslyhuang** [comment]
multiple XLs, create a spike for it.

**Comment by chianger** [comment]
I've been told that android components have 'download' we can look at.

**Comment by Jacklin-ux** [comment]
UX proposal: https://drive.google.com/file/d/1dqwaBq_efvjgUJsul_TmmUqoB24J0F9g/view?usp=sharing

Please let me know if any not clear design :)

**Comment by josephyu1110** [comment]
After looking into [android components download feature](https://github.com/mozilla-mobile/android-components/tree/master/components/feature/downloads), it doesn't support file pause/resume and progress update.
We might still need to write our own download manager, or leverage some existing third party libraries:
- [PRDownloader](https://github.com/MindorksOpenSource/PRDownloader)
- [Android-Download-Manager-Pro](https://github.com/majidgolshadi/Android-Download-Manager-Pro)

**Comment by TLHuang** [comment]
The visual spec and assets are updated, let me know if any questions! https://drive.google.com/drive/folders/1N_y3ZvH_EXyOVfWGI0WGNT_OyNMXWrNL?usp=sharing

**Comment by josephyu1110** [comment]
@TLHuang I didn't see pause/resume button on visual spec. Please help to confirm if they are missing. Thanks.
<img width="300" alt="screen shot 2018-12-05 at 12 05 36 pm" src="https://user-images.githubusercontent.com/16300853/49489578-adcd0200-f886-11e8-9d4b-52337b3204b7.png">

**Comment by josephyu1110** [comment]
@Jacklin-ux Currently, I'm evaluating the effort to implement all the feature listed in UX spec. It might not be able to accomplish in this sprint. Once the evaluation is done, I'll confirm with @cnevinc about the scope. Thanks.

**Comment by josephyu1110** [comment]
[Effort estimation](https://docs.google.com/spreadsheets/d/1Yxv9KbbMgqf5DVp-3MPsgCpxvNJYxxmLV3w8J6Yr8GM/edit?usp=sharing).

**Comment by chianger** [comment]
per offline discussion, it roughly takes one full sprint to implement and one more to test. tagging XL.

**Comment by chianger** [comment]
l10n wanted to indicate that there's new string. 
telemetry-wanted for @elin-moco , there's a "long-press" user interaction.

**Comment by elin-moco** [comment]
Here is my suggested event structure (event name/method/object/value {extra})
Long-press Toolbar Downloads/longpress/toolbar/download

**Comment by chianger** [comment]
QAWanted for @Daisy-pliu to design test cases.

**Comment by joechengla** [comment]
follow up bug https://github.com/mozilla-tw/Rocket/issues/3043

**Comment by joechengla** [comment]
another follow up https://github.com/mozilla-tw/Rocket/issues/3044

**Comment by Jacklin-ux** [comment]
Update ux spec: https://drive.google.com/file/d/1mPcu92pkkvWHpX165hvaNJ8E7KuyCXAp/view?usp=sharing

**Comment by Daisy-pliu** [comment]
Hi @Jacklin-ux  for contextual message, can user open a new tab to close contexual message or only when user open tab from external app ?

**Comment by elin-moco** [comment]
Here are all of my suggested event structure (event name/method/object/value {extra})
Long-press Toolbar Downloads/longpress/toolbar/download
Pause download/pause/download/null
Resume download/resume/download/null
Cancel download/cancel/download/null

Some things to consider whether we need to track or not:
 - Understand download usage so we can estimate cost if we plan to host data compression/proxy/VPN etc
   - Recent average download speed
   - Recent average download size 
 - Understand whether user need further help to complete download?
   - Track failed download
@joechengla thoughts?

**Comment by elin-moco** [comment]
After some discussion, we decided we would like to understand whether user need further help to complete download:
 - Track failed/discontinued download
 - Error message

**Comment by Daisy-pliu** [comment]
Verified: ✅
Test case: [Download manager test case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D277)
Device: Pixel 2 (9.0)
Version: Nightly 1.0.9 (9598)

**Comment by chianger** [comment]
1. What questions will you answer with this data?
We want to know how user interacts with the "download manager" function.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
We need more information from the user so we can enhance the user experience on the "download manager" feature and also further make plan for new features

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
Category 2 “Interaction data”

6. How long will this data be collected? Choose one of the following:
We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

7. What populations will you measure?
All users in all channels.

8. If this data collection is default on, what is the opt-out mechanism for users?
The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
We'll use Firebase and STMO. Comparing retention rate and the usage over time.

10. Where do you intend to share the results of your analysis?
N/A. Data is for internal feature planning evaluation only

**Comment by chianger** [comment]
@cnevinc please see above comment as my request to data review.

**Comment by Daisy-pliu** [comment]
Verified : ✅
Test case: Download manager test case
Device : Redmi 4X (7.1.2)
Version : RC 1.0.10 (9617)
WebView : 71.0.3578.99
