### ISSUE TITLE
(meta) Setup Amplitude for Rocket

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#2068]
My plan is 
A. Connect to Frank
B. Setup the scrip
C. Done~

**Comment by joechengla** [comment]
1. we will study Amplitude on Focus first
2. Once we decide the use case we will plan next steps

**Comment by chianger** [comment]
@cnevinc to further break-down this into sub-tasks

**Comment by chianger** [comment]
Engineering efforts are tracked under #2711 so this one is meta for other tasks. 
Currently we're identifying what the best practice is to categorize, report, ...etc.

**Comment by chianger** [comment]
we can close this once data team finishes dumping data from telemetry.

**Comment by chianger** [comment]
this is meta bug, and the remaining effort is very small so i'm changing it to s.

**Comment by chianger** [comment]
Recently we discovered issues around data correctness, so the efforts aren't done yet.
changing size:s to size wanted.
see also:
https://github.com/mozilla/telemetry-streaming/pull/225

**Comment by chianger** [comment]
this meta's remaining efforts is validating that the amplitude integration and data correctness.

**Comment by chianger** [comment]
Confirm there's no further action item.
