### ISSUE TITLE
Can't install apk downloaded from Rocket

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2214]
2.3.0 (5344)
Rocket isn't showing in "Install Unknown Apps" list in System Settings

**Comment by mTwTm** [comment]
Haven't tried yet but I recall this used to work on my phone too.

**Comment by joechengla** [comment]
it looks like installs are being blocked automatically. 
i don't see the UI that asks me to goto settings to allow "Install Unknown Apps"

**Comment by mTwTm** [comment]
https://android-developers.googleblog.com/2017/08/making-it-safer-to-get-apps-on-android-o.html

We've updated to target Android O in April.
