### ISSUE TITLE
Pinned preset top sites (by Mozilla) 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2263]

**Comment by weslyhuang** [comment]
1. customize only the initial top sites, and the sites will still be changed per user's usage.
2. updatable via GooglePlay? Need Dev investigation.
3. MCC dependent.

**Comment by joechengla** [comment]
User story:
1.  As Mozilla, we want to customize the initial 8 top sites per partner discussions and deliver the APK package to partner for distribution. (The actual top site behavior does not change)
2. As Mozilla, we want the customized 8 top sites to persist even after user updates the app from Google Play before first use.

Telemetry:
No change; Just like how it currently works to track top site positions without tracking the actual URL

**Comment by mTwTm** [comment]
Split into #2437 and #2438.

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/10IUabA1Tp7fUhaLzNiIDAB4T_8iQmVMQ/view?usp=sharing

**Comment by chianger** [comment]
clearing the original assignee since the design spec came out and is different from the original scope.

**Comment by TLHuang** [comment]
https://drive.google.com/open?id=1cGg0_qajJJOnhwvbz1I8FdNjZTU65D8u
Visual spec is ready, let me know if any questions!

**Comment by chianger** [comment]
Per latest spec we're sizing it to L

**Comment by joechengla** [comment]
latest discussion captured in the doc https://docs.google.com/document/d/1RqOTCq5GORZpvwxfTKIWv_LqaY0fvwN-OS9uZ7fF1JI/edit

**Comment by joechengla** [comment]
Only applying this to users in Indonesia

New top site order for Indonesia (for all new users), existing users only get (the first 3 with *)
1. Tokopedia*
2. Bukalapak*
3. GameLoft*
4. Triunnews
5. YouTube
6. Detik
7 https://www.okezone.com/
8 https://www.sindonews.com/

**Comment by Jacklin-ux** [comment]
Update ux spec: https://drive.google.com/file/d/1QM2CwPAu_sm_sWzv64YOQMCS_qY_cv7v/view?usp=sharing

Add page 5 and 6

**Comment by Daisy-pliu** [comment]
[Pinned Top Site in Indonesia Test Case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D317)  is ready

**Comment by TLHuang** [comment]
Update visuals for top sites onboarding, please refer to the latest visual spec.
https://drive.google.com/drive/u/1/folders/1cGg0_qajJJOnhwvbz1I8FdNjZTU65D8u

**Comment by Daisy-pliu** [comment]
based on [UI change](https://github.com/mozilla-tw/FirefoxLite/issues/2263#issuecomment-475487074) the[ test case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D318) is updated.

**Comment by Jacklin-ux** [comment]
@joechengla 
A question about the naming of the new top sites for Indonesia. Do you agree with the name I propose?

6. https://www.okezone.com/ 
(Okezone)
7. https://www.sindonews.com/
(SINDOnews)

**Comment by Daisy-pliu** [comment]
as we won't do duplicate top site detection , only [TC0209~ TC0212](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B319) are  kept

**Comment by Daisy-pliu** [comment]
verify:❌
test step:
1. install 1.1.3 Lite
2. launch app to see 8 topsites (1. Tribunnews 2. Youtube 3. Detik 4. Tokopedia 5. Buka 6. Liputan 7.Komas 8. FB)
3. upgrade to lastest (1.2.1)
4. see [pin site onboarding ] 
5. tap [got it]

Actual result:
see 8 top sites (1. pinned Tokopedia 2. pinned Buka 3. Tribunnews 4. Youtube 5. Derik 6. Buka 7.Liputan 8. Komas)

Expect result :
see 8 top sites (1. pinned Tokopedia 2. pinned Buka 3. Tribunnews 4. Youtube 5. Derik 6. Tokopedia 7.Buka 8. Liputan)

**Comment by Daisy-pliu** [comment]
Per discussion as Tokopedia has same link before and after upgrade so that it remains one site.
