### ISSUE TITLE
Show "Page not found" in the learn more page when the language is Basa

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#2483]
1. Launch Rocket for the first time use 
2. Set the language to be Basa Jawa
3. Visit a webpage
4. Take a screenshot --> it will show the screenshot onboarding
5. Tap Learn more

Actual result: 
 - Show "Page not found"
 - the URL is https://support.mozilla.org/en-US/jv/kb/screenshot-categories-firefox-rocket
<img src="https://user-images.githubusercontent.com/12458450/44643354-cebdc580-aa02-11e8-82fd-93255d4db462.png" width="50%" height="50%">

Expected result:
 - show Learn more page in Basa or English
 - 
<img src="https://user-images.githubusercontent.com/12458450/44643261-74bd0000-aa02-11e8-8f79-9d0923dd255c.png" width="50%" height="50%">

Sony Z3C
Android 6.0.1
Rocket 3.1.0(6481)
WebView 68.0.3440.91

**Comment by chianger** [comment]
Thai, Indonesia both works (though display English page).
Javanese and Sundanese cases are 404.

**Comment by chianger** [comment]
https://support.mozilla.org/1/mobile/3.1/Android/th/screenshot-telemetry  --> redirect to English page
https://support.mozilla.org/1/mobile/3.1/Android/jv/screenshot-telemetry  --> 404
https://support.mozilla.org/1/mobile/3.1/Android/su/screenshot-telemetry  --> 404
