### ISSUE TITLE
Can't download file in private mode 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#2519]
I can't download files from "https://speed.hetzner.de/" 
Device
Pixel2, Android 9

**Comment by chianger** [comment]
Interesting, it works in normal browsing mode.

**Comment by chianger** [comment]
@mlwang32 @cynthiatang can QA try more websites or devices?

**Comment by chianger** [comment]
something similar with #2653  ?

**Comment by mlwang32** [comment]
Device: Nexus 5
Android: 6.0.1
WebView: 69.0.3497.100
Rocket 3.3.0(7295).nightly

Normal mode download from https://www.pexels.com and https://speed.hetzner.de -> pass
Private mode download from https://www.pexels.com and https://speed.hetzner.de > fail

**Comment by chianger** [comment]
per the findings it's behavior inconsistency so tagging S1.
