### ISSUE TITLE
Find in page - Would be nice to have seach field& suggestions when users tap mini URL bar 

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#2644]
1. Launch Rocket
2. Visit a webpage
3. Tap Menu -> Find in page
4. Make sure that keyboard is opened
5. Tap mini-URL bar

Expected Result:
 - There are the search field and suggestion

Actual Result:
 - No search field and suggestion
 - https://drive.google.com/open?id=1xmXmkiFIWTGYAwy17fLJqdNPB4f980A1

Rocket: 3.2.0(7075).nightly
Pixel 2
Android 8.1.0

**Comment by chianger** [comment]
Seems more like a feature request and it could be hard to implement.
Search suggestion for web browsing is actually given by search engine, but here it's in-page search.

**Comment by chianger** [comment]
Per discussion it's a valid bug. 
In "find in page" mode if user taps on the upper mini URL bar, the situation becomes strange.

**Comment by Daisy-pliu** [comment]
Consult with @Jacklin-ux  we don't need this feature so it is a won't fix issue.
