### ISSUE TITLE
"Find in page" should be gray and disable when users tap Menu in Home

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#2647]
1. Launch Rocket
2. Go to Rocket's Home 
3. Tap Menu
4. Tap "Find in page"

Expected: 
 - "Find in page" should be gray and disable

Actual Result:
 - It will close Menu
 - https://drive.google.com/open?id=1jNozJ7sDBel73W-HxmMYUgLMYLgGP-od

Pixel2
Android 8.1.0
Rocket 3.2.0(7075).nightly
WebView 69.0.3497.100

**Comment by ivantw08** [comment]
same issue 

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by Daisy-pliu** [comment]
Consult with @Jacklin-ux we should fix this feature so I made it higher priority. Test case TC0150 will not be executed and ultimately removed.

**Comment by Daisy-pliu** [comment]
verify: ✅
Verison: 1.9.1 (13459) nightly
Test step: [TC0149](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B235)
Test device: samsung 8.0
