### ISSUE TITLE
Close user feedback page then back to Rocket Home via system back key

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-tw/FirefoxLite#2674]
(Issued by @mTwTm )
1. Launch Rocket 
2. Go to Menu -> Settings -> Give feedback -> No, send feedback
3. Tap system Back key

Expected Result: 
 - Back to Rocket Home

Actual Result:
 - Close Rocket (The behavior should be the same as opening a link from history)
 - Video: https://drive.google.com/open?id=1lmpKpmLPiezlnZV1k3w0t41CFzEsP_OQ

pixel2 
Android 8.1.0
Rocket 3.3.0(7183).nightly
WebView: 69.0.3497.100

**Comment by cynthiatang** [comment]
@mlwang32 could you please add this test case to the test suite? Thanks

**Comment by chianger** [comment]
It's a regression #1116

**Comment by mlwang32** [comment]
@cynthiatang added to the full run test suite, thanks.

**Comment by chianger** [comment]
expected behavior: back to home

**Comment by Daisy-pliu** [comment]
Consult with @Jacklin-ux we don't need this feature so it is a won't fix issue. Test case TC0130 will not be executed and ultimately removed.
