### ISSUE TITLE
When already in Rocket, back after "Search in Firefox Rocket" quits App.

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#2675]
STR:

1. Open Rocket and browse a webpage
2. select some text and "Search in Firefox Rocket"
3. Press back

Expected:
Return to the page that I was viewing in step 1

Actual:
Rocket quits.

**Comment by cynthiatang** [comment]
@mlwang32 , could you please revise the test case for this issue? Thank you.

**Comment by mlwang32** [comment]
@cynthiatang test case modified (long press on a text), thank you.

**Comment by Daisy-pliu** [comment]
Consult with @Jacklin-ux we don't need this feature so it is a won't fix issue. Test case TC0130 will not be executed and ultimately removed.
