### ISSUE TITLE
(post-Nov1)[Brand change] Update Github, WIKI

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#2702]
sub-task of #2299 
AC: 
1. Rocket renamed to FirefoxLite 
2. existing services linking to Github/moz-tw/rocket shall still work.

**Comment by mTwTm** [comment]
These pages link to the repo so we might want to make sure these still works:

/en-US/privacy/firefox-lite/
/th/privacy/firefox-lite/ 
/id/privacy/firefox-lite/ 
/zh-CN/privacy/firefox-lite/

**Comment by chianger** [comment]
QAwanted to verify the comment above.

**Comment by chianger** [comment]
tested together with daisy, and it works. let's close this bug.
