### ISSUE TITLE
Content portal - News (Single Src selection, for India)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#2712]
Part of #1819
Prototype efforts in #2603

We will want to be able to remote config to enable/disable this feature.
For India, we will offer news content.

**Comment by Jacklin-ux** [comment]
ux spec: https://drive.google.com/file/d/1rXUWiQtWFn-f6v48v_kAgU0PxkT1rLIX/view?usp=sharing

**Comment by Jacklin-ux** [comment]
visual spec: https://drive.google.com/file/d/1G-ClFp6EqhWKtzYm_O4DqftDZuUu68zK/view?usp=sharing

**Comment by Jacklin-ux** [comment]
Update ux spec: https://drive.google.com/file/d/1ckYjX8Wk_EIpxCBE_a2rSCazBfguRVsm/view?usp=sharing

Add
1. First time loading content
2. Open panel if having content in cache & check new news
3. No support half panel when there is no content

**Comment by elin-moco** [comment]
@cnevinc @chianger here is my suggested event structure (in the format of method/object/value {extra})
Open News Portal open/panel/news {from: home/tab/back_btn, result: success|failure}
Click on News Portal click/panel/news {on: [0-9]+|retry}

**Comment by cnevinc** [comment]
Hi @mxlius, Could you please help with the news items? I might not be able to finish them on time. Thank you!

**Comment by chianger** [comment]
mark P2 because there's discussion ongoing. this is nonblocking to sprint Isarog release

**Comment by Daisy-pliu** [comment]
test case is ready in [content portal-news test case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D307)

**Comment by Jacklin-ux** [comment]
Update ux spec:https://drive.google.com/file/d/1SRI7GKhU0SV5owUWiDFEERQdFDn8BW1N/view?usp=sharing

.No provide "New update" button, so load news content in the server every time when open content portal

**Comment by chianger** [comment]
URL for the learn more : https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/firefox-lite-feed

**Comment by elin-moco** [comment]
Per discussion in meetings, we would want to answer these questions with corresponding metrics:
 - Is content portal working properly? (event analysis)
 - (How) does users adapt to content portal? (conversion rate, funnels, feature engagement time, click position distribution)
 - How does it affect users' overall usage? (retention rate, engagement rate, engagement time)
We also need to be able to compare these metrics whenever there's new UI/UX/content updates.

So we'll need instrument following information to answer these questions:
 - News item clicks
   - Feed (provider of the news feed/list, could be an aggregation of multiple sources)
   - Source (the source website of the news item)
   - Category/Sub-category
   - Click Position (position in the list from beginning)
 - Engagement time
   - Time stayed on news portal
   - Time stayed on news page (TBD)

**Comment by elin-moco** [comment]
The suggested event structure would be:
 - Open lifefeed news: open/panel/lifefeed_news
 - Click on news item: click/panel/lifefeed_news {pos, feed, source, category, subcategory}

For tracking engagement time, we might need to consider whether to track it on close, or [use Firebase's screenview tracking mechanism](https://github.com/mozilla-tw/FirefoxLite/issues/3268), if we track it with event, it would be:
 - Close lifefeed news close/panel/lifefeed_news {duration}

**Comment by cnevinc** [comment]
> For tracking engagement time, we might need to consider whether to track it on close, or [use Firebase's screenview tracking mechanism](https://github.com/mozilla-tw/FirefoxLite/issues/3268), if we track it with event


This may be another bug. If we really want to look at those measurements, more engineering designed (assume XL) @weslyhuang

**Comment by cnevinc** [comment]
> * Open lifefeed news: open/panel/lifefeed_news
Does this only counts user swipe up the content portal in Home Screen?
or also consider when the user navigates from Browser Screen back to Home Screen?
> * Click on news item: click/panel/lifefeed_news {pos, feed, source, category, subcategory}
Does "pos" mean the visible position or the position in the data set?
I'll need to know the category and subcategory @mTwTm

**Comment by chianger** [comment]
data review request to @cnevinc :
1. What questions will you answer with this data?
    We want to know how user interacts with the "life feed" (a.k.a content portal) function. (see 
https://bugzilla.mozilla.org/show_bug.cgi?id=1529868 )

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
    We need more information from the user so we can enhance the user experience on the "life feed" feature and also further make plan for new features

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
    We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
    No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
    Category 2 “Interaction data” 

6. How long will this data be collected? Choose one of the following:
    We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

7. What populations will you measure?
    Users in targets markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)

8. If this data collection is default on, what is the opt-out mechanism for users?
    The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
    We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and the usage over time.

10. Where do you intend to share the results of your analysis?
    N/A. Data is for internal feature planning evaluation only

**Comment by Daisy-pliu** [comment]
Verification: ❌
[Content news test case:](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D307)
TC0198 Load more news automatically-> ✅
TC0199 No network & no news in cache-> ❌
https://github.com/mozilla-tw/FirefoxLite/issues/3297
https://github.com/mozilla-tw/FirefoxLite/issues/3300
TC0201 Close all tabs -> ❌
https://github.com/mozilla-tw/FirefoxLite/issues/3296
TC0200 click news -> ✅
TC0202 add to home screen -> ✅

**Comment by cnevinc** [comment]
For the late review:

1) Is there or will there be **documentation** that describes the schema for the ultimate data set available publicly, complete and accurate? 

[yes](https://github.com/mozilla-tw/FirefoxLite/commit/86da749c2caf5fd2367601a3da62e4bcdb9c428c#diff-833b6d7070c26b0f7548f4ffdc70eb8eR74)

2) Is there a control mechanism that allows the user to turn the data collection on and off?  
"Send Usage Date" will do the job

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

permanent. @elin-moco  

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?  **

Category 3. As the category is provided by 3rd. party, not Mozilla.

5) Is the data collection request for default-on or default-off?

In Lite it's default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

no

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
Will need @joechengla to confirm.

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**

No

9) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

No

**Comment by Daisy-pliu** [comment]
move test case to vertical test case naming start with [NEWS001 ](move test case to vertical test case naming start with NEWS001 )
