### ISSUE TITLE
Remove "find in page" cancel telemetry

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2736]
**Describe the bug**
we are receiving tons of "find in page" cancel telemetry

**Steps To Reproduce**
See redash

**Comment by elin-moco** [comment]
I found that after this bug fixed, the "cancel_find_in_page" event did drop,
but still weird, should it not be lower then "click_menu_find_in_page"?
<img width="973" alt="screen shot 2018-12-17 at 6 31 24 pm" src="https://user-images.githubusercontent.com/3771202/50081661-ff33a480-0229-11e9-91ee-bcaf7e36e15d.png">

**Comment by chianger** [comment]
solution: consider remove "cancel" event.

**Comment by josephyu1110** [comment]
Currently, there are three dismiss events in "Find In Page":
DISMISS_BY_BACK -> cancelFindInPage("back_button")
DISMISS_BY_CLOSE -> cancelFindInPage("close_button")
DISMISS -> cancelFindInPage("other") 
=> Called by back, close(duplicate call) event and BrowserFragment(frequently call)
