### ISSUE TITLE
Games on Content Portal

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#2818]
for tracking first.

**Why/User Benefit/User Problem**
To make something easier ...etc

**User story**
As a ..., I would like ...

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by weslyhuang** [comment]
UX design first, also BD input

**Comment by Jacklin-ux** [comment]
ux spec : https://drive.google.com/file/d/1PHBYttUtWp9KjCs4CP1aahhwrsa9NdnL/view?usp=sharing

**Comment by chianger** [comment]
action needed: confirm whether we can get API from partner or is it just a taylor-made link

**Comment by elin-moco** [comment]
@chianger here is my suggested event structure (in the format of method/object/value {extra})
Open Game Portal open/panel/games {from: home/tab/back_btn, result: success|failure}
Click on Game Portal click/panel/games {on: [0-9]+|retry}

**Comment by elin-moco** [comment]
@chianger here is my suggested event structure (in the format of method/object/value {extra})
Open News Portal open/panel/news {from: home/tab/back_btn, result: success|failure}
Click on News Portal click/panel/news {on: [0-9]+|retry}

**Comment by Jacklin-ux** [comment]
Add banner to Games portal:
https://drive.google.com/drive/folders/1C1qar2q6tH9DySdxdZapP2ktNPyFrpP0?usp=sharing

**Comment by joechengla** [comment]
we now have game vertical
