### ISSUE TITLE
No notification when pressing  setting 2ed time

### ISSUE THREAD

**Issue by ivantw08** [mozilla-tw/FirefoxLite#2830]
**Steps To Reproduce**
1. Launch Rocket 
2. Press settings 2ed time

**Expected behavior**
Show "Make default browser" notification

**Actual behavior**
show nothing

**Device info (please complete the following information):**

- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by weslyhuang** [comment]
it works with my S8+, Android 8. (OS version should only affect the behavior when user tab the "make default browser" notification, per the test case[1])

@ivantw08 would you also post a video for it? we may need to fix the issue or update TC. tks.

[1] TC in row 106/107. https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit#gid=792121503

**Comment by ivantw08** [comment]
https://drive.google.com/open?id=1OhuQdfVEgVfCiYNrDo_m9--9dupnDC5Z

Device:
- Device:nexus 5
- OS: Android: 6.0.1
- WebView: 69.0.3497.100
- Firefox Lite: 1.0.0(7855)

**Comment by chianger** [comment]
So per discussion this wasn't config by Firebase. 
@ivantw08 at the device you can reproduce, was rocket already set as default?

**Comment by ivantw08** [comment]
here is it 
https://drive.google.com/open?id=1SbGJiYRuJMRRkmFlDtLaY5thT0uRLoLm
The second time didn't show the notification. But cellphone vibrated.

**Comment by chianger** [comment]
So it can still be reproduced even Ivan configures default browser to other browser.
Actual result: no notification appears, but there does a vibration. 

QAWanted to check other testing devices.
