### ISSUE TITLE
Force tracking protection when in Private Mode

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2834]
Force tracking protection in PB even if the user turned off Turbo Mode in normal browsing to enhance privacy in PB

**Comment by Daisy-pliu** [comment]
[private mode enhancement test case](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D336) is ready

**Comment by Daisy-pliu** [comment]
verify in #3186
