### ISSUE TITLE
Alternate VPN recommender entry

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2913]
VPN recommender may disappear on the Lite Home screen. We can provide another entry to access VPN if users decide to want it after they their initial rejection

**Comment by Jacklin-ux** [comment]
Proposal: VPN icon is always on the home screen no matter users have rejected or uninstalled. What do you think?

**Comment by chianger** [comment]
sounds a little overwhelming

**Comment by joechengla** [comment]
n/a in 2.0
