### ISSUE TITLE
When Lite is killed by users or system and open Lite again, go to home page instead of previous tab.

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#2926]

**Comment by Jacklin-ux** [comment]
UX Proposal: When Lite is killed by users or system and open Lite again, go to home page instead of previous tab.

**Comment by Daisy-pliu** [comment]
**Test case**
1. fresh install app
2. search site 
3. kill in app manager
4. launch 
5. search site 

**Result**
4. see [home page]

**Comment by Daisy-pliu** [comment]
TC0230 will be covered in full run ,test step as below

**Verify:** ✅
**Version**
nightly 1.5.1 (11964)

**Device**
pixel 2 (9.0)

**Test step**
1. install older version 
2. upgrade app 
3. search site
4. upgrade & launch
5. fresh install app
6. search site 
7. kill in app manager & launch 
8. search site 
9. tap [more]-> [exit]
10. launch 

**Result**
4. 7. 10 see [home page]

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version: 1.6.0 (12105)
Device: vivo 6.0.1
Test steps: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/2926#issuecomment-491178193)

**Comment by Daisy-pliu** [comment]
Verify: ✅
version : 1.6.1 (12179)
Device: Pixel 2 (9.0)
test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3605#issue-445249146)
