### ISSUE TITLE
A/B Test bottom bar options; "screenshot" button versus add to homescreen and bookmark

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#2934]
Currently the browser bottom bar has options below 
"Tabs", "New Tab",  "Search", "Screenshot", "Settings"

As Mozilla, we would like to A/B test the "screenshot" button and replace with other options such as "add to homescreen" and "add bookmark" in different markets and see which feature will drive higher retention and engagement

**Comment by chianger** [comment]
design is in place per above comment

**Comment by chianger** [comment]
we shall get better assessment after spike #3080 and #3079

**Comment by chianger** [comment]
Open question: do we really need to block this by  #3080 and #3079 ?   Probably not, because this is for experiment only and we can target a small portion of user base.

**Comment by chianger** [comment]
telemetry-wanted for there will be changes at least we need versioning

**Comment by chianger** [comment]
This is size: L and devs already take various bugs. Expecting to see this done in next sprint (U).

**Comment by Daisy-pliu** [comment]
**Test case for bottom bar A/B test:** 
This verification will be conducted in Nightly and production remote config.

**Test A Add home:** 
1. launch app 
2. visit some page
3.tap [more]

Result:
2. see [tab tray], [+] , [add to home] ,[more] on bottom
3. see [next] , [reload] , [search], [bookmark],[screenshot],[share]


Test B Bookmark: 
1. launch app 
2. visit some page
3.tap [more]

Result: 
2. see [tab tray], [+] , [search],[bookmark] ,[more] on bottom
3. see [next] , [reload] , [screenshot], [add home],[share]

Test C: Reload
1. launch app 
2. visit some page
3.tap [more]

Result: 
2. see [tab tray], [+] , [search], [reload] ,[more] on bottom
3. see [next] , [reload] , [scerenshot], [add home], [share]

**Comment by elin-moco** [comment]
As per discussion,
we'll need to add some extra parameters in click toolbar events
extra={mode = webview|menu, pos = [0-5]}

**Comment by chianger** [comment]
merged in Nightly

**Comment by Daisy-pliu** [comment]
the config doc for bottom bar remote config is [here](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_bottom_bar_items-and-str_menu_bottom_bar_items)

**Comment by Daisy-pliu** [comment]
After second through, I decide to add [Test C](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B348) in full run.
Verify: ✅
Test case :[ test case](https://github.com/mozilla-tw/FirefoxLite/issues/2934#issuecomment-489913641)
Test version : nightly 1.6.0 (12400) webview: 74.0.3729.157
Test device: Samsung 8.0

Note: 
@elin-moco
I tested error handling as well and there are 2 scenarios will crash (which is not in requirement) so please be aware of the setting before submit.
1. input more than 5 buttons in json 
2. input duplicate button number in json

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test case : test case TC0237
Test version : nightly 1.7.0 (12628) webview: 75.0.3770.67
Test device: vivo1606

**Comment by elin-moco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Toolbar A/B testing metrics](https://trello.com/c/97GS3vBw/34-toolbar-a-b-testing-metrics)
