### ISSUE TITLE
Quick-search engines bar

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3028]
**Why/User Benefit/User Problem**
To make search easier as it's the most used feature within a browser

**User story**
As a user, I would like to quickly search from different search providers (search engine, e-commerce platforms) as I'm searching.
Similar to https://bit.ly/2R5oThi

**Acceptance Criteria (how do I know when I’m done?)** 
1. On the UI level, we provide quick access to users
2. We have properly implemented UI event telemetry
3. We have properly implemented partner referral code, if applicable
4. We can customize Search Options per market

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by joechengla** [comment]
Search options:
Facebook
YouTube
Instagram
Yahoo
DuckDuckGo
Buakalapak (Indonesia)

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1ONnyrt8A21I8Gqed-aQ9rKOMQxQ5lxf9/view?usp=sharing

**Comment by TLHuang** [comment]
The visual spec is ready! Please find it here https://drive.google.com/open?id=1eroTCmFCZMNqWXNEskXwPOea8KcXRsIA
Let me know if any questions, thank you!

**Comment by cnevinc** [comment]
1. How to define the order? Is there a user option?
2. The telemetry for this feature?
3. When dragging, is there a scrollbar hint?

**Comment by elin-moco** [comment]
Let me list out some questions we may need to answer with data:
 - Does quick search works properly?
 - (How) does user adapt to quick search?

Suggested event structure:
 - Search with alt engine/click/search/(engine)

**Comment by josephyu1110** [comment]
As mentioned in [PR](https://github.com/mozilla-tw/FirefoxLite/pull/3134), icons are required to determine how to apply round corner effect. Will these icons are round, square, or rounded corner?

**Comment by elin-moco** [comment]
Suggested event naming:
Click on quick search/click/quicksearh/null{engine: Facebook|Youtube|Instagram}

**Comment by chianger** [comment]
QAWanted to prepare test cases.

**Comment by josephyu1110** [comment]
There's no icon for Shopee and Snapdeal in top site icons folder that we can leverage to quick search. Currently, we use fake icon instead.

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.0 (10022)
SC1 India quick search : [TC0197 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B306)  
Device:  LAVA A76Plus(6.0) with India SIM
webview: 68.0.3440.91

SC2 Indonesia quick search :[TC0196 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B305)  
Device: Redmi 4x (7.1.2) with Indo SIM
webview: 72.0.3626.105

SC2 Global quick search :[TC0195 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B304)  
Device: Samsung S7 edge (8.0) without SIM
webview: 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.0 (10097)
SC1 India quick search
Test Step: [TC0197 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B306)
Device: LAVA A76Plus(6.0) with India SIM
webview: 68.0.3440.91

SC2 Indonesia quick search :
Test Step: [TC0196 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B305)
Device: Redmi 4x (7.1.2) with Indo SIM
webview: 72.0.3626.105

SC3 Global quick search
Test Step: :[TC0195 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B304)
Device: Samsung S7 edge (8.0) without SIM
webview: 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.1 (10140)
SC1 India quick search
Test Step: [TC0197 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B306)
Device: LAVA A76Plus(6.0) with India SIM
webview: 68.0.3440.91

SC2 Indonesia quick search :
Test Step: [TC0196 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B305)
Device: Redmi 4x (7.1.2) with Indo SIM
webview: 72.0.3626.105

SC3 Global quick search
Test Step: :[TC0195 test step](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B304)
Device: Samsung S7 edge (8.0) without SIM
webview: 72.0.3626.105
