### ISSUE TITLE
[meta] Expand Firefox Lite to more markets in 2019-H1

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3030]
As Mozilla, we'd like to start testing the water in more markets in Southeast Asia in 2019H1. It will be a low profile launch without much promotions and we will use English version of the app to launch in new markets

**Comment by madb1lly** [comment]
Hi,
I don't understand why the rollout to global is so slow. I have family with old Android tablets for which Firefox Lite would be a perfect lightweight browser. FYI, this is in the UK, if you want to add it your list of markets :D 
Cheers.

**Comment by swfsql** [comment]
Could you also enable it for brazilians (and other countries) who use playstore?

**Comment by chianger** [comment]
@swfsql @madb1lly currently this product Firefox Lite is targeted and designed for Asian markets. Given limited resource we are not able to expand too quickly.

**Comment by swfsql** [comment]
Ok! I'm not sure what direction you guys have in mind, but I was referring to the English version, which I assume is working properly (I use it everyday and it works perfectly - from the apk on Releases here on Github)

So I expect that a lot of people would gladly use it as well, even if it's in English

**Comment by chianger** [comment]
Upcoming plans: 
1. Singapore and Malaysia in Early March
2. Bangladesh, Myanmar, Cambodia, Laos, Brunei in Mid March

**Comment by madb1lly** [comment]
@chianger, @swfsql is totally right: I don't understand why a browser which uses the English language cannot be made available in the UK! Is there some hidden logistical reason why you can't just make this browser available more widely? Is it a marketing reason? Honestly I think you'd be better off just make it available and letting word-of-mouth/viral marketing do the work.
