### ISSUE TITLE
[spike] for affiliate triggered by search #3028

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3057]
spike for #3028
to understand if affiliate link works when the session is triggered by search

**Comment by chianger** [comment]
There's affiliate link and API for search queries. 
We can further confirm with partner that API works.

**Comment by chianger** [comment]
Charles helped to raised the question to partner thru email on Jan17. Waiting for reply.

**Comment by cnevinc** [comment]
Confirmed below link will work for keyword "pixel 3 xl"

http://bukalapak.go2cloud.org/aff_c?offer_id=15&aff_id=4287&aff_sub=LiteBanner&url=https%3A%2F%2Fwww.bukalapak.com%2Fproducts%3Futf8%3D%25E2%259C%2593%26search%255Bkeywords%255D%3Dpixel%2B3%2Bxl%26ho_offer_id%3D{offer_id}%26ho_trx_id%3D{transaction_id}%26affiliate_id%3D{affiliate_id}%26utm_source%3Dhasoffers%26utm_medium%3Daffiliate%26utm_campaign%3D{offer_id}%26aff_sub%3D{aff_sub}%26ref%3D{referer}
