### ISSUE TITLE
Support Remote Config on "Share Dialog"

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3088]
**Why/User Benefit/User Problem**
To make something easier ...etc
To be completed 

**User story**
As a Mozilla, we would like to remote config the content of the "Share Dialog" to A/B test the conversion rate and observe if we can increase "referral" installs 

**Acceptance Criteria (how do I know when I’m done?)** 
1. Being able to remote config the share dialog message
2. Being able to remote config the share link of the share dialog
3. Being able to remote config the share message of the share dialog

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by chianger** [comment]
Per discussion, this feature is about making the message of sharing dialog remote configurable.

**Comment by elin-moco** [comment]
I just updated in the AC section with these:
 - Being able to remote config the share dialog message
 - Being able to remote config the share link of the share dialog
 - Being able to remote config the share message of the share dialog

**Comment by josephyu1110** [comment]
https://github.com/mozilla-tw/FirefoxLite/blob/master/app/src/main/res/values/strings.xml#L407-L414

**Comment by josephyu1110** [comment]
`  
    
    <string name="share_app_dialog_text_title">Share %1$s with friends!</string>
    <string name="share_app_dialog_text_content">- Fast and lightweight\n- Data saving\n- Powerful screenshots</string>
    <string name="share_app_dialog_btn_share">Share</string>
    <string name="share_app_google_play_url" translatable="false">https://mzl.la/2kScptw</string>
    
    <string name="share_app_promotion_text">Hey, check out this fast and lightweight browser from %3$s. %1$s %2$s</string>`

**Comment by josephyu1110** [comment]
See what strings are used in share dialog:
https://github.com/mozilla-tw/FirefoxLite/blob/master/app/src/main/res/values/strings.xml#L407-L414
I'll make "share_app_dialog_text_content", "share_app_google_play_url" and "share_app_promotion_text" remotely configurable.

**Comment by cnevinc** [comment]
> I just updated in the AC section with these:
> 
> * Being able to remote config the share dialog message
Done
> * Being able to remote config the share link of the share dialog
> * Being able to remote config the share message of the share dialog
Current the share message contains text, the link, and the App name. So we may just want to remote config them in one remote config field

**Comment by Daisy-pliu** [comment]
Test result: ✅
Test step:
1. open [Remote Config](str_share_app_dialog_title)
2. str_share_app_dialog_title= title <a href="http://google.com">link</a>
3. str_share_app_dialog_content = 1😊\n 2\uD83D\uDE0A\n <BR> <BR>  3 \u000a😊 
4. str_share_app_dialog_msg = I'm a happy url <a href="http://google.com">link</a>

Test result:
1. share dialog
![screenshot_20190304-165218](https://user-images.githubusercontent.com/44990878/53726623-551efc80-3ea9-11e9-9ca2-c76c7e9c2f9d.png)
2. intent with text
![screenshot_20190304-165246](https://user-images.githubusercontent.com/44990878/53726785-b2b34900-3ea9-11e9-845d-0a5c171f50aa.png)
