### ISSUE TITLE
When downloading a file and leave the app for a while, back to Lite but download hint disappeared?

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3096]
**Describe the bug**

**Steps To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what you actually discovered.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**
Is it a regression? Regression window?
3rd party app's behavior.

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
Need triage - does this issue need to be triaged?
S1/S2/S3 - can determine the severity based on the existing criteria

**Comment by Daisy-pliu** [comment]
Need UI design for this scenario.

**Comment by chianger** [comment]
Need visual to provide the asset. This is feature enhancement so S2 it.

**Comment by TLHuang** [comment]
Update the asset [here](https://drive.google.com/open?id=1WQmIiU_msrxjOCWjCwwR-9xfD28jt4P7 ) and mockup for previewing https://drive.google.com/open?id=1LDlSjZrzUWxdWL57znHDQEigEbGEexUT

**Comment by Jacklin-ux** [comment]
Currently we have 3 download status: Downloading, Finish download and Pause/Failed. If encounter many status need to be shown at the same time, we just display one status and the priority is Downloading > Finish download > Pause/Failed

**Comment by Daisy-pliu** [comment]
verify :✅
Test step:
1. launch app
2. when file is downloading I cut off network
Result:
download  status is "paused" with warning icon shows on menu 
Device: 
Redmi 4X (7.1.2)
Pixel 2 (9.0)
