### ISSUE TITLE
Samsung J7 - Download Always Fail

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3097]
Android 6.0.1
Nevin has the device 

1. Goto Download Test Site https://www.thinkbroadband.com/download
2. Download a file
3. System notification shortly will show download failed (100%)

**Comment by cnevinc** [comment]
When I tried it this morning without the debugger, I can reproduce the issue.
And I found only links with http will fail, links with https will still work.

But when I tried it in the afternoon and try to use debugger [here](https://github.com/mozilla-tw/FirefoxLite/blob/fa9b9daf8ea1b82628e9ff45ca72b578366cb784/app/src/main/java/org/mozilla/focus/download/DownloadInfoManager.java#L389), it works suddenly (Both http and https).  The WebView version is 71.0.3578.99.

Need to test further with older WebView version.

**Comment by mTwTm** [comment]
In some earlier test I've seen this:

```
13:48:09.244217 IP (tos 0x0, ttl 52, id 47605, offset 0, flags [DF], proto TCP (6), length 608)
    download.thinkbroadband.com.http > 10.247.26.130.50237: Flags [FP.], cksum 0xb98a (correct), seq 1:557, ack 448, win 235, options [nop,nop,TS val 1315537589 ecr 640896674], length 556: HTTP, length: 556
	HTTP/1.1 403 Forbidden
	Server: nginx
	Date: Thu, 27 Sep 2018 05:48:09 GMT
	Content-Type: text/html
	Content-Length: 391
	Connection: close
	ETag: "58b56102-187"
	
	<html>
	<head>
	<title>Not Authorized</title>
	</head>
	
	<body>
	
	<h2>Not Authorised</h2>
	
	<p>We cannot provide this file at this time.</p>
	
	<p>
	This may be because we are detecting abuse from your network; these files
	are primarily intended for UK broadband users and although we do not
	prohibit their use from other services, we do not allow scripted/automated
	downloads.
	</p>
	
	</body>
	</html>
```

I would suggest we avoid using thinkbroadband as a testing reference.

**Comment by cnevinc** [comment]
If we want to show the error reason/code to the user, here's the info
`managerCursor.getInt(managerCursor.getColumnIndex(DownloadManager.COLUMN_REASON))`
and source code:
https://chromium.googlesource.com/android_tools/+/refs/heads/master/sdk/sources/android-25/android/app/DownloadManager.java#232

**Comment by chianger** [comment]
QAWanted to check if this is regression?

**Comment by mTwTm** [comment]
Confirmed
1. When I failed to download on thinkbroadband.com after a clean install, I did see the warning message in the packet.
2. I can successfully download from other places.

**Comment by chianger** [comment]
It's non-regression but more of a website's intended behavior.
We don't really have actionable item here.
