### ISSUE TITLE
l10n efforts for enabling traditional Chinese, and Vietnamese.

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3099]

**Comment by chianger** [comment]
note: need new automated tests for new locales.

**Comment by mTwTm** [comment]
Also a very small task: enable new locales in release build.

**Comment by Delphine** [comment]
I will reach out to these two localization communities today and communicate this out to them.
Once I receive their replies, I will enable both locales in Pontoon. I expect this to be done some time this week - will update here

**Comment by chianger** [comment]
one more dependency on the PN https://bugzilla.mozilla.org/show_bug.cgi?id=1523873

**Comment by chianger** [comment]
task to update side-by-side screenshot mechanism https://github.com/mozilla-tw/FirefoxLite/issues/3132

**Comment by chianger** [comment]
tracking for SUMO: https://bugzilla.mozilla.org/show_bug.cgi?id=1524144

**Comment by chianger** [comment]
In product string localization is done. SUMO and privacy page will be tracked in parallel (on bugzilla) and both are not blocking open beta.
