### ISSUE TITLE
Sample Project for Dynamic Delivery Workshop

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3123]
Goal
1. Understand feature-sync
2. Unblock AAB issues:  UX / on-demand feature-module testing/development best practice / on-demand configuration module

Proposal: https://docs.google.com/document/d/1f8geU95b6CjlOGSl5AgCLjgxbmTf25rRbgesjZUgmho/edit

**Comment by chianger** [comment]
Workshop done
