### ISSUE TITLE
Screenshot Viewer loads slowly with roaming data connection

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3124]

**Comment by joechengla** [comment]
https://drive.google.com/a/mozilla.com/file/d/1qkZMjWcNShXTT5qhGQuYTblF_vV813VS/view?usp=drivesdk

**Comment by chianger** [comment]
Might be because that screenshot viewer needs to load the "Screenshot Category".

**Comment by cnevinc** [comment]
culprit?
https://github.com/mozilla-tw/FirefoxLite/blob/4383037f187d151b5dfed315ec19b2a3610a90d4/app/src/main/java/org/mozilla/focus/screenshot/ScreenshotViewerActivity.java#L499

**Comment by cnevinc** [comment]
After we had timeout, this should be fixed?
https://github.com/mozilla-tw/Rocket/commit/c8568bfbbf7cf54201d4429174bdfa413818d957
or improvement wanted?

**Comment by chianger** [comment]
Let's land it in sprint R.

**Comment by chianger** [comment]
@cnevinc let's land it early in the sprint.

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**Test version :** 1.4.0 (11307)
**test step:**
1. launch app
2. tap any site
3. tap screenshot icon
4. tap menu -> myshots
5. tap the screenshot 

**expected /actual result:**
1. show screenshot in screenshot viewer in 2 sec.
