### ISSUE TITLE
String truncation in zh-TW (MyShots)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3133]
**Describe the bug**
String truncation in zh-TW (MyShots)

**Steps To Reproduce**
1. Go to settings and set locale to zh-TW
2. Be sure MyShots is empty
3. Check the layout of the MyShots panel
4. See string truncation,

**Screenshots/videos**
![screenshot_20190131-104016](https://user-images.githubusercontent.com/9859809/52027121-309bd180-2545-11e9-9b25-eba5f7b47d1f.png)

**Device info (please complete the following information):**
 - Device: PixelXL

 - Version 1.0.10(9745)

**Reproduce rate**
5/5

**Comment by Daisy-pliu** [comment]
After running script through Screengrab we can inspect every translation result (side-by-side screenshot ) for TW and Vietnam [here](https://drive.google.com/drive/u/0/folders/1aH--mFVJgbmKN97MrPjKuomQPA4eHyLA)

**Comment by mTwTm** [comment]
No simple fix as I expected. (Some workarounds though) Pushback to the next sprint.

**Comment by chianger** [comment]
per discussion we can make it not ITALIC then this truncation can be solved. We'll need visual to look at this when the build comes out.

**Comment by Daisy-pliu** [comment]
Verify:✅
Test case:
1. launch app with TW language
2. tap menu -> myshots
Test result:
no truncates with TW text
