### ISSUE TITLE
Update tokopedia top site link and icon

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3138]
Update Indonesia top site Tokopedia's URL to a partner provided one

**Comment by chianger** [comment]
PR was merged. see #3144

**Comment by Daisy-pliu** [comment]
I am not sure the provided link is PM expected as requirement not stated it. Please help verify . @joechengla 
Verify: ❓
Test step:
1. insert indonesia SIM card
2. launch lite
3. tap Tokopedia top site

Test result:
Displyed Url is 
https://m.bukalapak.com/?ho_offer_id=15&ho_trx_id=102a1746b3cb0a9852559385b85b54&affiliate_id=4287&ho_clk_id=&aff_sub1=&aff_sub2=&aff_sub3=&aff_sub4=&aff_sub5=&aff_src=&ref=&utm_source=hasoffers-4287&utm_medium=affiliate&utm_campaign=15

Test Version: 
1.0.11(9915)

Test Device:
Redmi 4x (7.1.2)

**Comment by chianger** [comment]
Confirmed that icon is still valid and the URL is as expected.

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.0 (10022)
Device: Redmi 4x (7.1.2)
webview: 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.0 (10097)
Test step: [refer steps here](https://github.com/mozilla-tw/FirefoxLite/issues/3138#issuecomment-462695550)
Device: Redmi 4x (7.1.2)
webview: 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verification :✅
Test version : 1.1.1(10140)
Test step: [refer steps here](https://github.com/mozilla-tw/FirefoxLite/issues/3138#issuecomment-462695550)
Device: Redmi 4x (7.1.2)
webview: 72.0.3626.105
