### ISSUE TITLE
Regression: User is not taken to the new tab when a link (that opens new tab) is tapped 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3139]
Steps
1. Goto https://mobile.twitter.com/firefox/status/1091052524738617346
2. Tap on the link
3. Nothing happens (except tab number increases)

Expected behavior for 3. user is taken to the new tab with the links content opened (chrome and Firefox behaves this way)

**Comment by manddy** [comment]
@mTwTm  I just saw android file downloader project on mozilla brainstroming page for gsoc .Is this repo link for the android file downloader project ?.If yes kindly help me out ,I am interested in contributing to this project .Also can you please provide your official mail id which will make it easy to ask about the details of the android file downloader project.Thanks in advance

**Comment by mTwTm** [comment]
Hi @manddy ! We don't currently have a repo for the project so I've updated both mentors' mail address. Feel free to send us queries but I'd also like to remind you the GSOC submission for Mozilla is not finalized so we don't know yet if this project will be an official GSOC project. (From the [schedule ](https://summerofcode.withgoogle.com/how-it-works/) I belive we shall know the acceptence of this project on Feb 27th.)
Nonetheless, contibution outside of GSOC is definitely welcomed as well so fell free to drop any question. (One slight thing though is @cnevinc and I are currently enjoying the Lunar New Year so will be inactive before Feb 11th.)

**Comment by mTwTm** [comment]
FYI @joechengla tested and belived it is a Webview regression.

**Comment by Daisy-pliu** [comment]
possibly dup of # [3065](https://github.com/mozilla-tw/FirefoxLite/issues/3065)

**Comment by Daisy-pliu** [comment]
If user update chrome (the webview upgrade to 72.0.3626.96) and then kill Lite to relaunch again , this issue will not happen.
Verify : ✅
Device: Pixel 2 (9.0)
Webview: 72.0.3626.96
Build:1.0.10 (9617)
Scenario: 
1. [link in Twitter page](https://github.com/mozilla-tw/FirefoxLite/issues/3139#issue-405728789) 
Test result: open tab successfully
Note : dup #3065

**Comment by mxlius** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=927254

The root cause is on Chrome/WebView side. It's a regression caused by new feature: UserActivationV2. They disabled the new feature through the remote config and cause us not always reproducible on every device.

We might need to inform the user to upgrade their Chrome/WebView version when the hotfix is rolled out, or we can just depend on their remote config and do nothing.
