### ISSUE TITLE
Screenshot  on bording event not show when resume app

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3154]
**Describe the bug**
Screenshot  on bording event not show when resume app 

**Precondition**
Never used screenshot 

**SC1 : Show screenshot on-boarding after going back from other app**
1. Launch Lite
2. Visit a website
3. Tap screenshot button
4. Tap Task manager
5. Switch to other app
6. Switch back to Rocket

**SC1 : Show screenshot on-boarding and menu after going back from Home**
1. Launch Lite
2. Visit a website
3. Tap screenshot button
4. Tap system Home
5. Tap Lite

**Expected behavior**
Screenshot on-boarding and menu are still there

**Actual behavior**
Screenshot on-boarding and menu not show

**Device info**
 - Device: Redmi 4x (7.1.2)
 - Webview: 72.0.3626.96
 - Version : 1.0.11 (9915)

**Reproduce rate**
5/5

### Note ###
it is not happening on 
1. Samsung S7 edge (8.0) ,webview: 72.0.3626.96, version : 1.0.11 (9915)
2. Pixel 2 (9.0) webview:72.0.3626.105,  version : 1.0.11 (9915)
3. Vivo 1606 (6.0.1), webview:71.0.3578.99 ,  version : 1.0.11 (9915)

**Comment by chianger** [comment]
To be clear, so far only the Redmi 4X can reproduce. I wonder if it's something to do with MIUI.

**Comment by chianger** [comment]
Besides Xiaomi devices this could be reproduce in other devices with different repro rate. 
This is system behavior to close activities in the background.
Decision : WONTFIX 
QAWanted to update test case.

**Comment by Daisy-pliu** [comment]
Mark [TC0131](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B208), [TC0132](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B209) WONT in the full run
