### ISSUE TITLE
When back to private home page, does not show toast msg and private browsing notification still display

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/FirefoxLite#3170]
**Describe the bug**
When back to private home page, does not show toast msg and private browsing notification still display

**Steps To Reproduce**
1. Reset Rocket and launch it
2. Switch to private browsing mode
3. Visit some websites 
4. Tap system Back until back to Private - Home page

**Expected behavior**
There is no browsing history in the stack.
    Remove private browsing notification 
    Show a toast to remind user.
      - Your private browsing history has been erased.

**Actual behavior**
1. Private browsing notification still display
2. Does not show the toast msg

**Screenshots/videos**
https://drive.google.com/file/d/1nqN27YU2SlIi5HL56eV1OCfrYCkzfvyq/view?usp=sharing

**Device info (please complete the following information):**
 - Device: Samsung S8
 - OS: Android 8.0.0
 - Webview: 72.0.3626.105
 - Version: Lite 1.1.0 (10022)

**Reproduce rate**
3/3

**Additional context**
N/A

### put correct labels ###
S2

**Comment by witsmo** [comment]
Can reproduce on -
* Device & OS:
Advan i5C (Android 5.1) 
Nexus 6 (Android 6.0.1)
Redmi 4A (Android 7.1.2)
Pixal XL (Android 9.0)

* Webview: 72.0.3626.105
* Version: Lite 1.1.0 (10022)

**Comment by chianger** [comment]
It's a regression. It works on v1.0.1(8249)

**Comment by witsmo** [comment]
Verified Pass:
Device : Samsung S8 (Android 8.0)
Version : Lite 1.1.0 (10097)
WebView : 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verified :✅
Device : Samsung S7 Edge (Android 8.0)
Version : Lite 1.1.1 (10140)
WebView : 72.0.3626.105
