### ISSUE TITLE
Tap trash icon in private mode, does not show toast msg and private browsing notification still display

### ISSUE THREAD

**Issue by witsmo** [mozilla-tw/FirefoxLite#3171]
**Describe the bug**
Tap trash icon in private mode, does not show toast msg and private browsing notification still display

**Steps To Reproduce**
1 Launch Rocket
2 Switch to private mode
3 Open a website 
4 Tap trash icon 

**Expected behavior**
4. Toast message is shown with the message: Your private browsing history has been erased
 4.1 back to main private page
 4.2 notification icon disappears

**Actual behavior**
1. Does not show the toast msg
2. Private browsing notification still display

**Screenshots/videos**
https://drive.google.com/file/d/1Nt4gX_fcl-l3hFSAg18Qod7WOwJIG7id/view?usp=sharing

**Device info (please complete the following information):**
* Device: Samsung S8
* OS: Android 8.0.0
* Webview: 72.0.3626.105
* Version: Lite 1.1.0 (10022)

**Reproduce rate**
3/3

**Additional context**
N/A

### put correct labels
S2

**Comment by witsmo** [comment]
Can reproduce on -

* Device & OS:
  Advan i5C (Android 5.1)
  Nexus 6 (Android 6.0.1)
  Redmi 4A (Android 7.1.2)
  Pixal XL (Android 9.0)
* Webview: 72.0.3626.105
* Version: Lite 1.1.0 (10022)

**Comment by chianger** [comment]
It's a regression. It works on v1.0.1(8249)

**Comment by witsmo** [comment]
Verified Pass:
Device : Samsung S8 (Android 8.0)
Version : Lite 1.1.0 (10097)
WebView : 72.0.3626.105

**Comment by Daisy-pliu** [comment]
Verified :✅
Device : Samsung S7 Edge (Android 8.0)
Version : Lite 1.1.1 (10140)
WebView : 72.0.3626.105
