### ISSUE TITLE
User feedback: Quick Search

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3172]
Here's my first impression/feedback

1. the fact that I can tap on Facebook/Instagram/YouTube as shortcut to their website when I didn't type in anything in search field feels interesting 
2. Fennec behavior is that there has to be at least one character typed in order for the quick search to show up

**Comment by Jacklin-ux** [comment]
We did a quick survey to understand users' expectations about current design, found that
1) users think showing Quick search engines directly feel like showing Top Sites and won't support search by keywords (like two separate area)
2) To design like what Fennec does has better connection between keyword and Quick search engines (after input keyword then show search suggestions and Quick search engines at the same time) 

So based on the result, we will modify our design to what Fennec does.

Thanks for this user's feedback :)

**Comment by Jacklin-ux** [comment]
ux spec: https://drive.google.com/file/d/1ECVryo1ZrVBCyEoz_zdHF7x7YzCcsfsD/view?usp=sharing

**Comment by chianger** [comment]
design ready.

**Comment by Daisy-pliu** [comment]
testing done by @weslyhuang on build 1.1.2

**Comment by Daisy-pliu** [comment]
Test build:
1.1.2(10240)

Test case:

    1. tap search bar without showing quick search icon

    2. input some text so it shows quick search icon

Test Device:
Samsung S7 edge without SIM card

Note : Add this test case to [TC0195](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B304)

**Comment by witsmo** [comment]
Test build:
1.1.3(10310)

Test case:
1. tap search bar without showing quick search icon
2. input some text so it shows quick search icon

Test Device:
Samsung S8 without SIM card
