### ISSUE TITLE
Content Portal Onboarding + Setting

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3173]
**Why/User Benefit/User Problem**
Once we introduce the content portal feature, we will want to onboard the user to introduce the feature. 

**User story**
1. As Mozilla, we would like onboard/inform existing users of the new content portal feature (News in India and E-Commerce in Indonesia)
2. As Mozilla, we would like onboard/inform new users of the new content portal feature (News in India and E-Commerce in Indonesia)
3. As Mozilla, we would like to have a way to provide information to the users about what contents they are seeing, who's the providing the contents, any data concerns they should be aware of.

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

### put correct labels ###
Add corresponding labels from the right panel to make it clearer
telemetry wanted - does this introduce adding or modifying telemetry?
UX/VD wanted - does this require UX/VD input to make the story ready for development
l10n wanted - does this introduce adding or modifying in-product strings?
help wanted - does this feature suitable for people other than the core team to wok on?

**Comment by chianger** [comment]
one more acceptance criteria per discussion from the meeting:
4. As a user, I can configure my preference (select from different source, or pref off)

**Comment by Jacklin-ux** [comment]
ux spec:https://drive.google.com/file/d/1sHuHl4sqgwzFlh8DfnXQKwap9K5tsC7_/view?usp=sharing

Waiting for source name provided by partners

**Comment by TLHuang** [comment]
Visual spec is ready, link https://drive.google.com/drive/folders/1DsvqW0B3d1gzEooxAXTflv9Ks-FOLpQp?usp=sharing

**Comment by chianger** [comment]
One open issue: which will be the default source?

**Comment by chianger** [comment]
this makes #2712 complete.

**Comment by chianger** [comment]
The UX spec covers #3233

**Comment by elin-moco** [comment]
My suggested event naming would be: 
Enter landscape mode/change/landscape_mode/enter
Enter landscape mode/change/landscape_mode/exit {duration}
which exit may happen when:
 - back to portrait mode
 - app exit/background

Duration in milliseconds to track how much time user stays in landscape mode

**Comment by elin-moco** [comment]
Here are my suggested event structure:

For Onboarding:
 - show/firstrun/finish {on: [total_duration], time_on_page: [time_on_1st_page, time_on_2nd_page, ...], mode: new|existing}

For Settings:
 - click/setting/pref_lifefeed_news_source
 - change/setting/pref_lifefeed_news_source {to: [source]}
 - click/setting/learn_more {source: pref_lifefeed}

**Comment by Daisy-pliu** [comment]
[test case for news portal on boarding page](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B314) is ready

**Comment by Daisy-pliu** [comment]
Need India SIM to test on boarding page

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test device: Redmi 5x (7.1.2)
Test case: [TC0204](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B314),[TC0205](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B315)

**Comment by Daisy-pliu** [comment]
move test case to vertical test case naming start with [NEWS001 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=85206289&range=C284)
