### ISSUE TITLE
Need to be able to track preset topsites clicks in telemetry

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/FirefoxLite#3179]
**User story**
As a PM (I'm writing on behave of Joe), I would like to precisely track partner link clicks and preset top site icon clicks () so that we can cross compare with partners' report and verify the integration, and make sure we are getting real conversions/revenue without being affected by integration issues.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Verified partner link click event ping on Firebase debugging console.
2. Be able to create reports/dashboards with the event ping on data tools we have (Amplitude/Redash)
3. Be able to cross compare with reports from partners

**Comment by chianger** [comment]
I modified the original user story to cover #3189

**Comment by cnevinc** [comment]
Also, updated the WIKI
https://github.com/mozilla-tw/FirefoxLite/wiki/Telemetry/575f84ff0ad5538777f42f544167183638190476#event-ping

**Comment by cnevinc** [comment]
I think the pinned top site feature will still need to follow this

**Comment by chianger** [comment]
Per discussion yesterday we can close this as this commit has done
https://github.com/mozilla-tw/FirefoxLite/commit/eb3feaa942f978e53bc715c0fea7658ef16f5021
