### ISSUE TITLE
Track organic users in telemetry

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/FirefoxLite#3181]
**User story**
As a PM (I'm writing on behave of Joe), I would like to track product usage of organic users separately, so the usage trend will less likely to be affected by acquisition campaigns/activities, and we will be able to better track the progress of product improvements by metrics change over time/build.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Verified attribute representing organic(or other channel) users in user properties on Firebase debugging console.
2. Be able to create reports/dashboards with the user properties using the data tools we have (Amplitude/Redash).
3. Be able to track product improvements by metrics change over time/build.

**Comment by cnevinc** [comment]
I only send adjust tracker token as part of the important settings.
We didn't create another field in core ping cause changing the schema is tedious.

for 
> Verified attribute representing organic(or other channel) users in user properties on Firebase debugging console.

It's not in the PR cause we'll send Adjust tracker token to Firebase.  Are we allowed to do this?

**Comment by chianger** [comment]
this has merged by #3406

**Comment by Daisy-pliu** [comment]
As we would like to verify this feature in advance, a release APK built is handover to data engineer to make final verification.
Furthermore, on release day @Conjuror will take the effort to make sure the feature is good to ship.
