### ISSUE TITLE
Display Number of Trackers Blocked in PB

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3186]
**User story**
As a user, I would like see information on how effective private browsing is

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

**Comment by chianger** [comment]
prerequisite #2834

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1-hWrmCpK6wjmIg82tP9rmN9Z6o6MOft5/view?usp=sharing

**Comment by chianger** [comment]
@Jacklin-ux will update the onboarding page #2 to denote that private mode enhancement.

**Comment by Daisy-pliu** [comment]
[test case private mode enhancement ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D336) is ready

**Comment by Jacklin-ux** [comment]
@Daisy-pliu 
Update ux spec: https://drive.google.com/file/d/1-hWrmCpK6wjmIg82tP9rmN9Z6o6MOft5/view?usp=sharing

Updated items:
- Reload current website when switch on "Block tracker" in private mode (use case 2-3)
- Remove use case 4

**Comment by Daisy-pliu** [comment]
thanks. test case updated.

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**version**: 1.4.0 (11611) nightly
**device:** google pixel XL (9.0)
**test case:**  [TC0227 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B338)
**test step:**
1. launch app
2. tap [settings]-> [turn off turbo mode]
3. tap [settings]-> [private tab]
4. browse nba page
5. click [shield icon]
6. toggle [off]
7. toggle [on]
8. tap [anywhere] expect popup
 
**test result**
"4. show [private icon] [next] [trash] [reload] [shield] icons in the bar
5. show [number of trckers blocked] pop up
6.1 show [minus] in the number
6.2 switch is [off] and page reloaded
6.3 shield icon is [strikethrough]
7.1 once it is blocking, it shows [dot] on shield. 
7.2 show [number of trckers blocked] dynamically changed
7.3 switch is [on] and page reloaded
7.4 [shield] icon
8. popup disappears

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 1.5.0 (11653)
test step: [TC0227 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B338)
Device info: sony xperia (5.0.1), webview: 73.0.3683.90

**Comment by lanyliu** [comment]
Telemetry is needed:
click events on toolbar in private mode
distinguisher for searching in private mode


1. Click Toolbar - Block Tracker
method=show, object=toolbar, value=block_tracker, extra={n_blocked = 0,1,2,3...; mode = private_mode}

2. Click Toolbar - Reload
method=click, object=toolbar, value=reload, extra={mode = private_mode}

3. Click Toolbar - Clear Cache
method=click, object=toolbar, value=clear_cache, extra={mode = private_mode}

4. Click Toolbar - forward
method=click, object=toolbar, value=forward, extra={mode = private_mode}

5. Turn on Block Tracker
method=change, object=popup, value=block_tracker, extra={to = true,false; mode = private_mode}         

6. Show SearchBar from Home
method=show, object=search_bar, value=search_box, extra={mode = private_mode}

7. Dismiss SearchBar
method=cancel, object=search_bar, value="", extra={mode = private_mode}

8. Clear SearchBar
method=clear, object=search_bar, value="", extra={mode = private_mode}

9. Use SearchSuggestion SearchBar
method=select_query, object=search_bar, value="", extra={mode = private_mode}

10. Search with text in SearchBar
method=type_query, object=search_bar, value="", extra={mode = private_mode}

11. Show SearchBar by clicking MINI_URLBAR
method=show, object=search_bar, value=mini_urlbar, extra={mode = private_mode}

12. Enter an url in SearchBar
method=open, object=search_bar, value=link, extra={mode = private_mode}
