### ISSUE TITLE
Hanging when quick search with space 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3188]
**Describe the bug**
crash when search word with space on quick search feature

**Steps To Reproduce**
1. tap search bar
2. type "red skirt"
3. tap "FB" icon

**Expected behavior**
open FB with "red skirt" search result

**Actual behavior**
do nothing and hanging

Note: 
This is not happening on private mode quick search

**Comment by witsmo** [comment]
Verified Pass
Device : Samsung S8 (8.0)
Version : Lite 1.1.1 (10140)
WebView : 72.0.3626.105
