### ISSUE TITLE
Handling searches with space on instagram

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#3202]
Related to #3188, we can force search space with Instagram pages but it will not give result.

**Comment by Jacklin-ux** [comment]
I just did a quick survey for IG users. They prefer throwing the word which removed the space between input keywords automatically to IG than showing  "Sorry....". By doing so, they feel comfortable and easy use. So for IG case, I suggest to remove the space automatically.

**Comment by chianger** [comment]
this one together with #3172 is major improvement for new feature: quick search.

**Comment by cnevinc** [comment]
@Jacklin-ux is this rule only applies to IG?

**Comment by Jacklin-ux** [comment]
So far just IG uses tag system to search, so the answer is yes.

**Comment by Daisy-pliu** [comment]
testing done by @weslyhuang on build 1.1.2

**Comment by Daisy-pliu** [comment]
adding test case to [TC0195](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B304)
