### ISSUE TITLE
Content Portal Sumo Page

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3213]
related to https://github.com/mozilla-tw/FirefoxLite/issues/3173
3. As Mozilla, we would like to have a way to provide information to the users about what contents they are seeing, who's the providing the contents, any data concerns they should be aware of.

**Comment by chianger** [comment]
tracking bug on bugzilla 
https://bugzilla.mozilla.org/show_bug.cgi?id=1529868

**Comment by chianger** [comment]
draft content portal guide
https://docs.google.com/document/d/1V_aZZugC9kI3z6nxkysNj2bpEKRWx0ekf5pCyCSAZyg/edit#heading=h.4zs2q1c79n5b

**Comment by chianger** [comment]
URL to the SUMO article: https://support.mozilla.org/1/mobile/%VERSION%/%OS%/%LOCALE%/firefox-lite-feed
