### ISSUE TITLE
Update E-Commerce Tracking Link with Tags

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3235]
As we have multiple entry to affiliated e-commerce sites, we'd like to be able to distinguish where the traffic is coming from (e.g. Top Sites, Quick Search, Life Feed...etc)

New links will need to be generated for each different entry point.

**Comment by chianger** [comment]
assuming the URL for quick search doesn't need encoding, or we're not adding sub-id for quick search this is size:s

**Comment by Daisy-pliu** [comment]
not sure if we can verify this on [Affiliate Panel](https://www.bukalapak.com/affiliate/conversion-report) . An email question is sent to partner and wait for their confirmation.

**Comment by Daisy-pliu** [comment]
After confirmation, partner mentioned it can be checked in the conversion report  from [Affiliate Panel](https://www.bukalapak.com/affiliate/conversion-report) but the data record will have 4~7 days delay depends on the order status and listing is virtual or not. So will keep monitor on it.

**Comment by Daisy-pliu** [comment]
**Test verify:** ❌
**Test version:** RC 1.3.0(11070)
**Test device:** Samsung 8.0
**Test case:**
1. launch app with SIM
2. tap pinned "Bukalapak" site
**Result:**
url does not contain tag "aff_sub1=topsite"
**Expect:**
url has tag "aff_sub1=topsite"

**Note:**
this tag shows on 1.2.1(11047)nighty not RC build

**Comment by Daisy-pliu** [comment]
Test verify: ✅
Test version: RC 1.3.0(11073)
Test device: Oppo (7.1.1)
Test case:
    1. upgrade & launch app with Indonesia SIM
    2. see [pin your sites on boarding] and tap [ok, got it]
    3. tap pinned "Bukalapak" site -> url has tag "aff_sub1=topsite" 
    4. search "red dress" in search bar 
    5. tap "Bukalapak" icon  -> url has tag "aff_sub1=quicksearch"
