### ISSUE TITLE
Changing an autocompleted site to search will still visit the site

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#3239]
**Describe the bug**

**Steps To Reproduce**
1. Type moz in the search bar
2. Tap on the bar to un-highlight autocomplete
3. Tap backspace to remove .org
4. Type " firefox"
5. Press enter

**Expected behavior**
"mozilla firefox" is searched in the search engine

**Actual behavior**
mozilla.org is browsed

**Device info (please complete the following information):**
 - Device: Nokia 5.1plus
 - OS: Android 9
 - Version: 1.1.3(10310)

**Reproduce rate**
100%

**Comment by chianger** [comment]
Looks pretty bad. 
Not sure if this is a regression. I have 1.0.1 that can reproduce this so it has been there for a while.

**Comment by josephyu1110** [comment]
Related to [this one.](https://github.com/mozilla-mobile/focus-android/issues/2854)

**Comment by josephyu1110** [comment]
https://github.com/mozilla-mobile/focus-android/issues/2854

**Comment by josephyu1110** [comment]
Related to [this one](https://github.com/mozilla-mobile/focus-android/issues/2854).

**Comment by chianger** [comment]
working alright with my nightly 10964

**Comment by Daisy-pliu** [comment]
Verify :✅
Test version: 1.2.1 (10858)
Test step
SC1: [mozilla firefox test step](https://github.com/mozilla-tw/FirefoxLite/issues/3239#issue-416608744)
SC2: [reddit.com chess test step](https://github.com/mozilla-mobile/focus-android/issues/2854#issue-338694290)
Test result:
it can search the expected keyword correctly

**Comment by Daisy-pliu** [comment]
verify:✅
Test version: 1.3.0 (11070)
Test step: [3 scenario](https://github.com/mozilla-tw/FirefoxLite/issues/3239#issuecomment-477005805)
