### ISSUE TITLE
Basic authentication not asking the user for a login/password

### ISSUE THREAD

**Issue by mossroy** [mozilla-tw/FirefoxLite#3256]
**Describe the bug**
When a website needs a login/password through Basic Authentication, Firefox Lite does not asks the user to enter them. So the website usually fails with an HTTP code 40x

**Steps To Reproduce**
1. Go to 'https://httpbin.org/basic-auth/test/test', or any other URL that asks for a Basic Authentication
2. The browser does not ask for a user/password

**Expected behavior**
Firefox Lite should let the user enter a login/password, and pass it in the HTTP request headers

**Actual behavior**
Firefox Lite does not ask for a user/password

**Device info (please complete the following information):**
 - Device: Samsung S2 and ZTE Open C
 - OS: LineageOS 14.1
 - Webview : 69.0.3497.109 and 71.0.3578.99
 - Version : 1.1.3

**Reproduce rate**
Every time

**Comment by mTwTm** [comment]
I can reproduce with my device.

**Comment by chianger** [comment]
I can reproduce with latest nightly v1.1.4. Actually It can also be reproduced on v1.0.1.

Reference:
Firefox Focus, Fennec both working fine.

**Comment by cnevinc** [comment]
We need UX to confirm the text and design. Currently it's aligned with Focus
![image](https://user-images.githubusercontent.com/1287363/54890649-4e523b00-4ee5-11e9-8bcd-d37830b329fc.png)

**Comment by chianger** [comment]
per discussion over slack we can land this feature but next sprint let's request localization. (since we've missed the string freeze of this sprint)

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version: 1.2.1 (10982)Nightly
Test device: Redmi 5X(7.0), Vivo 1606 (6.0.1)
![Screenshot_2019-03-27-14-48-11-237_gro allizom zelda beta](https://user-images.githubusercontent.com/44990878/55055968-adf44600-509f-11e9-889d-5a49259a2007.png)

**Comment by elin-moco** [comment]
Currently I can only think of debugging usage for this event.
If we need to log event for this, I'll suggest that we best log with website domain for debugging purpose, if there's privacy concern, we can still use it to narrow down issues by device/app version.
Show Auth Prompt/show/auth/null {on: website domain}
@Jacklin-ux @cnevinc let me know if there are anything else you want to know about the auth prompt.

**Comment by elin-moco** [comment]
e.g. whether we want to know the success/failure ratio of user's authentication? for what purpose?

**Comment by elin-moco** [comment]
Just synced with Jack and Nevin offline, confirmed we don't need telemetry ping for this for now.

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test device : Samsung 8.0
Test version : 1.3.0(11070)
Test step: [3 scenarios ](https://github.com/mozilla-tw/FirefoxLite/issues/3256#issuecomment-477004210)
