### ISSUE TITLE
[Crashlytics] HomeFragment.java crash

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3262]
**Crashlytics:**
[Crash report](https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5c7ed457f8b88c29630611a0?time=last-seven-days&sessionId=5C7FA144032600013B741D0E733F59EC_DNE_0_v2)

android.app.Instrumentation.execStartActivity (Instrumentation.java:1525)
android.app.Activity.startActivityForResult (Activity.java:4271)
android.support.v4.app.FragmentActivity.startActivityForResult (FragmentActivity.java:767)
android.support.v4.app.ActivityCompat.startActivityForResult (ActivityCompat.java:234)
android.support.v4.app.FragmentActivity.startActivityFromFragment (FragmentActivity.java:881)
android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment (FragmentActivity.java:995)
android.support.v4.app.Fragment.startActivity (Fragment.java:1084)
android.support.v4.app.Fragment.startActivity (Fragment.java:1073)
org.mozilla.focus.home.HomeFragment.lambda$initFeatureSurveyViewIfNecessary$10 (HomeFragment.java:796)
org.mozilla.focus.home.-$$Lambda$HomeFragment$nlfAxB7z5QaCwWqy-em29goHoZI.onClick (lambda)
android.view.View.performClick (View.java:5643)
android.view.View$PerformClick.run (View.java:22519)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6165)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:933)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:823)

**Build version:**
1.1.4 (104373)

**Slack Discussion:**
[analyze with low severity](https://mozilla.slack.com/archives/G5QBPEK4J/p1551940090113800)

**Comment by chianger** [comment]
per discussion over slack this can be considered in the next sprint planning

**Comment by chianger** [comment]
Not really impacting. We won't take further action.
