### ISSUE TITLE
[Updated] Send user's current settings to Firebase User Properties for Experiments and Debugging

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/FirefoxLite#3272]
**User story**
As a Data Guy, I would like to be able to select audience based on Settings in Firebase for FCM/Remote config experiments, and be able to verify settings (like default browser) in Firebase Debug View in real time.

**Acceptance Criteria (how do I know when I’m done?)** 
1. Being able to select audience based on user's current settings in Firebase
2. Being able to see current user settings in real time in Firebase Debug View -> current user properties
3. Attributes including:
    - Current Settings like default browser, language, etc
    - Some metadata like capture count, current theme

**Comment by elin-moco** [comment]
This is important to our "default browser" benchmark and development of future settings/metadata.
Please prioritize ASAP.

**Comment by elin-moco** [comment]
https://github.com/mozilla-tw/FirefoxLite/issues/3399
This may help with the webview bug by notifying affected users by targeting their webview version

**Comment by Daisy-pliu** [comment]
@elin-moco  will help on the verification.
