### ISSUE TITLE
Separate Remote Config from telemetry

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3277]
purpose of this is to make "remote config" not turned off by pref off "send usage data".

**Comment by chianger** [comment]
Update comment 0: purpose of this is to make "remote config" not turned off by pref off "send usage data".

**Comment by chianger** [comment]
action: check from policy/legal side.

**Comment by chianger** [comment]
QAWanted for test case and testing since #3375 has merged.

**Comment by Daisy-pliu** [comment]
Refactor [life feed switch scenario TC0204 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B314) and  [E-commerce switch scenario TC0218](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B326)

**Comment by Daisy-pliu** [comment]
Additional test case which will not include in the full run, only for detailed verification.
**Test case 1: check rate_app_dialog_text_positive,rate_app_dialog_text_negative**
1. reset app on nightly
2. go to [settings]-> [give feedback]
3.1 see rate_app_dialog_text_positive is same with config on Nightly 
3.2 see rate_app_dialog_text_negative is same with config on Nightly 
4. reset app on nightly
5. go to [settings]-> turn off [send usage data ]
6. go to [settings]-> [give feedback]
6.1 see rate_app_dialog_text_positive is same with config on Nightly 
6.2 see rate_app_dialog_text_negative is same with config on Nightly 

**Test case 1: check enable private mode**
0. set enable_private_mode to FALSE on Nightly
1. reset app on nightly
2. go to [settings]-> [private mode]
3. see. private mode disabled is same with config on Nightly 
4. reset app on nightly
5. go to [settings]-> turn off [send usage data ]
6. see private mode disabled is same with config on Nightly 

@cnevinc  please help to check test case are valid.

**Comment by Daisy-pliu** [comment]
Verify :✅
Test version : 1.4.0 (11524) nightly
Test case:  [cases 1,2](https://github.com/mozilla-tw/FirefoxLite/issues/3277#issuecomment-484360751) , [case 3,4](https://github.com/mozilla-tw/FirefoxLite/issues/3277#issuecomment-484806054)
device: Pixel XL 9.0

**Comment by Daisy-pliu** [comment]
per discussion we can remove enable_private_mode remote config feature as it is not used any more. This issue can be tracked in #3521

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 1.5.0 (11653)
test step:  [cases 1,2,3](https://github.com/mozilla-tw/FirefoxLite/issues/3277#issuecomment-484360751) 
Device info: sony xperia (5.0.1), webview: 73.0.3683.90
