### ISSUE TITLE
The second line of news title is cut

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3278]

**Comment by chianger** [comment]
seems fixed?  i can't reproduce.

**Comment by chianger** [comment]
this can be reproduce if setting system font size to large.

**Comment by Daisy-pliu** [comment]
Verify:✅
Test device: Redmi 5X (7.0)
![Screenshot_2019-03-25-14-03-29-040_gro allizom zelda beta](https://user-images.githubusercontent.com/44990878/54898353-dc8ae900-4f06-11e9-9473-335c548e732d.png)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: remote life_feed feature and url is on and mobile with India SIM 
Test step:
1. launch app
2. swipe up to see news
