### ISSUE TITLE
Support swiping up "from arrow" to show content portal panel 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3283]
To do this but block by "clicking arrow to show content portal", I agree to remove "clicking arrow to show content portal" behavior and just provide swiping up gesture.

**Comment by chianger** [comment]
to be verified.

**Comment by Daisy-pliu** [comment]
Verify: ❌
Test version: 1.2.0 (10730)
**SC1 Test step :** 
1. launch app
2. swipe up over the arrow
Test result: 
see news

**SC2 Test step** 
1. launch app
2. swipe up right to the arrow
Test result: 
see empty news panel with reload icon

**Note:**
This fix has side effect if i swipe up right (or left) next to arrow, it shows only reload button without news.
![Screenshot_20190314-131943_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/54333066-e76a9180-465b-11e9-9083-9d47781a1520.jpg)

**Comment by mTwTm** [comment]
Expected to be fixed in #10749

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version: 1.2.0 (10749)
**SC1 ** ✅
[swipe up over arrow test step ](https://github.com/mozilla-tw/FirefoxLite/issues/3283#issuecomment-472708576)

**SC2 Test step**  ✅
[swipe up next to arrow](https://github.com/mozilla-tw/FirefoxLite/issues/3283#issuecomment-472708576)
