### ISSUE TITLE
Open Life Feed's SUMO page on a new tab than press system back key, expect to go to Lite's home page instead of close the app

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3285]

**Comment by mTwTm** [comment]
From setting?

**Comment by Jacklin-ux** [comment]
Sorry for describing not so clear. This issue is about tapping "Learn more" on the onboarding...

**Comment by chianger** [comment]
For reference: while viewing the onboarding slide, "back" will close the app.

**Comment by chianger** [comment]
to be verified.

**Comment by chianger** [comment]
UX input: back to redirect to onboarding is also acceptable.

**Comment by mTwTm** [comment]
Closed in #3292

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test device: Redmi 5x (7.1.2) with India SIM
Test case: 
1. launch app
2. click [learn more about life feed ] on boarding page
