### ISSUE TITLE
News photo's UI layout should follow visual spec design

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3287]
If can't follow visual spec because of implementation limitation, visual designer can adjust current design. So need developers' input for this issue.

**Comment by chianger** [comment]
major visual defect. we at least need the icon to be not at the leftmost.

**Comment by TLHuang** [comment]
![Spec_firefox lite_content portal_02](https://user-images.githubusercontent.com/4092794/54262657-b3369880-45a9-11e9-856f-61fbc46f8975.jpg)
Spec is updated!

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version: 1.2.0(10749).Nightly
