### ISSUE TITLE
When Close all tab it should show only home screen

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3296]
**Steps To Reproduce**
1. launch app
2. swipe up to click any [news]
3. tap [tab number]
4. tap [close all tabs]

**Expected behavior**
see home page

**Actual behavior**
see home page with content news portal

**Device info (please complete the following information):**
 - Device: Redmi (7.1.1), Pixel 2.0 (9.0)

**Test version**
1.1.4 (10676).nightly 

**Reproduce rate**
10/10

**Comment by chianger** [comment]
Saw PR fixing this under review

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version : 1.2.0(10730) Nightly
Test step: [close all tab steps](https://github.com/mozilla-tw/FirefoxLite/issues/3296#issue-420288763)

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version : 1.2.0(10730) Nightly
Test step: [close all tab steps](https://github.com/mozilla-tw/FirefoxLite/issues/3296#issue-420288763)

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version: 1.2.0(10749).Nightly
Test step: [close all tab steps](https://github.com/mozilla-tw/FirefoxLite/issues/3296#issue-420288763)
