### ISSUE TITLE
No reloading icon when tab retry button on news panel

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3297]
**Steps To Reproduce**

0. turn off WIF & clear app storage on system settings
1. launch app 
2. swipe [up] to show news 
3. tap [try again] icon 

**Expected behavior**
it shows [reloading icon]

**Actual behavior**
it does not show [reloading icon]

**Device info (please complete the following information):**
Pixel 3 (9.0)
Redmi 5X (7.1)

**Test version**
1.1.4 (10676).nightly
**Reproduce rate**
10/10

**Comment by chianger** [comment]
S2: ux enhancement.

**Comment by witsmo** [comment]
Same issue on :
 - Device: Advan i5C/ Nexus 5 / Samsung S8
 - OS: Android 5.1 / Android 6.0.1 / Android 8.0.0
 - Webview : 72.0.3626.112
 - Version : Lite 1.1.4(10676).nightly

**Comment by Daisy-pliu** [comment]
The current practice is no [arrow] when no cache and wifi is off.
**Verify** ✅
**Version:** 1.0.4(11624)
**test step:**
1. no network & no cache
2. launch app
**result**
2. see no [arrow]
