### ISSUE TITLE
[Life feed][News] order of the listed item isn't sorted by time

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3298]
**Describe the bug**
[Life feed][News] order of the listed item isn't sorted by time

**Steps To Reproduce**

1. Go to settings and switch news source, relaunch Lite and check the news feed
2. Repeat step 1 a few times. 

**Expected behavior**
The listed news articles are sorted by time

**Actual behavior**
The order was not in time order 

**Screenshots/videos**
![Screenshot_20190313-111254](https://user-images.githubusercontent.com/9859809/54251427-33490800-4582-11e9-8398-d961539fec28.png)

**Device info (please complete the following information):**
 - Device: Pixel XL, Pixel 3
 - Webview 72
 - Version 1.1.4(10676).nightly

**Reproduce rate**
3/3

**Comment by Daisy-pliu** [comment]
Verify: ❌
Test version : 1.2.0(10730) Nightly
Test step: [change news source steps](https://github.com/mozilla-tw/FirefoxLite/issues/3298#issue-420299424)
![Screenshot_20190314-130350_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/54332612-f4868100-4659-11e9-8ec0-9b532a83562d.jpg)

**Comment by mTwTm** [comment]
Expected to be fixed in #10749

**Comment by Daisy-pliu** [comment]
Verify: ❌
Test version : 1.2.0(10749) Nightly
Test step: change news source steps

**Comment by Daisy-pliu** [comment]
It is the source API response not act as expected - not sort the news properly by time, so affecting this ticket
refer : [slack discussion](https://mozilla.slack.com/archives/G5QBPEK4J/p1552546717284500)

**Comment by chianger** [comment]
Known issue due to API limitation.
