### ISSUE TITLE
When WIFI turn on, it shows stale news

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3300]
**Steps To Reproduce**

0. turn off WIFI & clear app storage on system settings
1. launch app 
2. swipe [up] to show [retry icon]
3. turn on WIFI

**Expected behavior**
it shows latest news 

**Actual behavior**
it shows stale news (2 hours before)

**Device info (please complete the following information):**
 - Pixel 3 (9.0)
 - Redmi 5X( 7.1)

**Test build**
1.1.4 (10676).nightly

**Reproduce rate**
10/10

**Comment by cnevinc** [comment]
should be fixed by #3315

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version : 1.2.0(10730) Nightly
Test step: [wifi turn on steps](https://github.com/mozilla-tw/FirefoxLite/issues/3300#issue-420301393)

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test version : 1.2.0(10749) Nightly
Test step: [wifi turn on steps](https://github.com/mozilla-tw/FirefoxLite/issues/3300#issue-420301393)
