### ISSUE TITLE
[life feed][news] some news item has no thumbnail icon

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3302]
**Describe the bug**
[life feed][news] some news item has no thumbnail icon

**Steps To Reproduce**
1. Select news source to be Newspoint
2. Relaunch Lite and bring up the life feed
3. Scroll down to navigate through the news list

**Expected behavior**
All items have corresponding thumbnail

**Actual behavior**
Some don't.

**Screenshots/videos**
![Screenshot_20190313-114159](https://user-images.githubusercontent.com/9859809/54252582-5f668800-4586-11e9-87c5-a1ccad5ca190.png)

**Device info (please complete the following information):**

 - Version 1.1.4(10676).nightly

**Reproduce rate**
2/2

**Comment by chianger** [comment]
S2: visual improvement.

**Comment by TLHuang** [comment]
If the thumbnail not showing, shows the placeholder instead.
![Content Portal - News](https://user-images.githubusercontent.com/4092794/54598784-3eb19d00-4a74-11e9-981c-eb0f08af0dd4.jpg)
[Asset link](https://drive.google.com/open?id=11ELBwhTOHCbhBfjD2NrMHop1_UnY_qbq&authuser=hhuang@mozilla.com)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.2.1(10927).nightly
Test case:
1. launch app
2. swipe up to see news 
3. check placeholder when thumbnail is not showing

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test case: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3302#issuecomment-476064961)
