### ISSUE TITLE
Home is shown for a brief while every time we switch from another App

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#332]

**Comment by Conjuror** [comment]
P0 for investigating the root cause and efforts we need to work on it.

**Comment by Conjuror** [comment]
You can also see home after visiting a web page, leaving zerda app, and coming back to zerda.

STR:
1. Launch Zerda and visit a website
2. Press system home
3. Press Zerda app

Expected Result:

1. Zerda is launched, skip Home and website is display

Actual Result:
1. Zerda is launched and Home will be there at a glance

**Comment by dakaizou** [comment]
Looks good in build 623
DuT: Samsung J7 Prime, Advan, Lenovo

**Comment by mTwTm** [comment]
I believe it's still there but it's not 100% reproducible with the STR.

**Comment by mTwTm** [comment]
The webview creation is very slow after the App is killed and recreated on low end devices.

**Comment by mTwTm** [comment]
No longer relevant due to architecture change.
