### ISSUE TITLE
User feedback: reCAPTCHA doesn't work with tracking protection on

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3320]

**Comment by Daisy-pliu** [comment]
Test case : 
1. launch app
2. go to [settings]-> turn on [turbo mode]
3. tap back
4. search and go to[https://www.google.com/recapthcha/api2/demo]
5. tap [I'm not a robot ] to begin identify journey

Test result:
it can start recapthcha identify journey correctly

**Comment by chianger** [comment]
no actionable item so close it.
