### ISSUE TITLE
Layout adjustment of content portal news - Shadow

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3329]
.Each news' left and right spacing is not qual
.The outline of each news is using a little heavy shadow

**Comment by cnevinc** [comment]
see #2712 or spec

**Comment by chianger** [comment]
S1: to make this feature more complete.

**Comment by Daisy-pliu** [comment]
Verify:✅
Device : redmi 5x (7.0)
Test result:
![Screenshot_2019-03-25-13-59-44-961_gro allizom zelda beta](https://user-images.githubusercontent.com/44990878/54898255-7b631580-4f06-11e9-8b92-e23541885c80.png)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: remote life_feed feature and url is ON and mobile with India SIM
Test case : 
1. launch app
2. swipe up to see news
