### ISSUE TITLE
 Layout adjustment of content portal news - Padding (Ref #3329) 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3334]

**Comment by chianger** [comment]
Break down of original #3329

**Comment by Daisy-pliu** [comment]
Verify:✅
Device : redmi 5x (7.0)
Test result:
![Screenshot_2019-03-25-13-59-44-961_gro allizom zelda beta](https://user-images.githubusercontent.com/44990878/54898255-7b631580-4f06-11e9-8b92-e23541885c80.png)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: remote life_feed feature and url is on and mobile with India SIM 
Test step:
1. launch app
2. swipe up  to see news
