### ISSUE TITLE
Be clear about "Top Trending News" or "Latest News" offering

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3338]
As a user, I want to know whether the news I'm reading is Top Trending or Personalized.

**Comment by chianger** [comment]
scope: rename the "news" to be a more clear string.

**Comment by joechengla** [comment]
Let's go with "Latest & Top Trending News"

**Comment by chianger** [comment]
string is defined.

**Comment by Daisy-pliu** [comment]
verify:✅
Test version : 1.2.1 (11037).nightly
Test steps:
1. launch app 
2. swipe up 

test result:
see "Latest & Top Trending New" as title

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: remote life_feed feature and url is on and mobile with India SIM 
Test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3338#issuecomment-477535867)
