### ISSUE TITLE
Offer news in different categories and languages

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3339]
As a user, I'd like to view top news from different categories

**Comment by chianger** [comment]
see also #3192

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1F4yXQb4WQtuIQyPzTHngQ5kZa0_B_rYz/view?usp=sharing

**Comment by TLHuang** [comment]
Visual spec: https://zpl.io/aX3eGYM

**Comment by Daisy-pliu** [comment]
Test case for news category and languages is ready, which refactors TC0198 with more on [TC0234 -TC0236.](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D304)  

Note: Detailed verification on dynamic category for individual language will be conducted in this sprint only.

**Comment by elin-moco** [comment]
@cnevinc , as per discussion with @lanyliu , here are the suggested ping definition
1. Open lifefeed news
  method=open, object=home, value=lifefeed_news, extra={category=top-news|india|world, feed=Newspoint, position=[0-9]}
2. Change news setting (Fire only when there’s change on exiting news settings)
  method=change, object=setting, value=pref_news, extra={language=english|hindi, category=[top-news, india, world, ...]}

**Comment by cnevinc** [comment]
something missing
[] unit tests
[] timeout? for no network in setting page
[] new lang set to app lang (eng, hindi)
[] auto refresh news-cat after setting
[] loading animation when changing lang

**Comment by cnevinc** [comment]
> @cnevinc , as per discussion with @lanyliu , here are the suggested ping definition
> 
> 1. Open lifefeed news
>    method=open, object=home, value=lifefeed_news, extra={category=top-news|india|world, feed=Newspoint, position=[0-9]}
To do this, we need to remember the selected tab. But in UX design, we need to reset the selected tab. ( clicking the news item, history, clicking anything in TabTray....etc)

> 2. Change news setting (Fire only when there’s change on exiting news settings)
>    method=change, object=setting, value=pref_news, extra={language=english|hindi, category=[top-news, india, world, ...]}

> 3. Click lifefeed settings
>    method=click, object=lifefeed, value=settings

**Comment by elin-moco** [comment]
@cnevinc, thank you for pointing out, just updated as follows:
1. Open lifefeed news
  method=open, object=**panel**, value=lifefeed_news, extra={category=top-news|india|world, feed=Newspoint, position=[0-9]}
2. Change news setting (Fire only when there’s change on exiting news settings)
  method=change, object=setting, value=pref_news, extra={language=english|hindi, category=[top-news, india, world, ...]}
3. Click news lifefeed settings
    method=click, object=**lifefeed_news**, value=settings

**Comment by cnevinc** [comment]
@elin-moco  Per discussion, please give me the short version of categories so it can fit in 100 characters limit. Thank you

**Comment by elin-moco** [comment]
@cnevinc Pardon me for the delayed reply,
we just decided to use number mapping for better maintenance.
Here they are:

- Top-news: 0
- India: 1
- World: 2
- Technology: 3
- Education: 4
- Politics: 5
- Career: 6
- Cricket: 7
- Sports: 8
- Entertainment: 9
- Business: 10
- Health: 11
- Movie-reviews: 12
- Automobile: 13
- Regional: 14
- Travel: 15
- Lifestyle: 16
- Food: 17
- Video: 18
- City: 19
- Events: 20 
- Religion: 21
- Crime: 22
- Astrology: 23
- Science: 24
- Jokes: 25

**Comment by Daisy-pliu** [comment]
verify: ❌
version: 1.8.0 (12867)
device: Redmi 4X (7.1.2)
Related issue are listed here: 
1. #3706
2. #3705
3. #3703 
4. #3702

**Comment by Daisy-pliu** [comment]
The critical one #3702 is resolved so that this ticket will mark as verified success with minor issue.
