### ISSUE TITLE
Add remaining time left in download Bar

### ISSUE THREAD

**Issue by manddy** [mozilla-tw/FirefoxLite#3344]
**User story**
As a user while downloading a file if we are able to see the time remaining along with progres update , this will lead to better user experience and keep the users more engaged

**Acceptance Criteria ** 
1.When there is timer text view added along side the progress percentage
2.The timer keeps on updating the remaining time left for the download

**Additional context**
![timer](https://user-images.githubusercontent.com/22556185/54629065-cd3a1480-4a9c-11e9-80f8-1863c4401b0e.png)

**Comment by manddy** [comment]
@mTwTm @chianger @cnevinc I would like to work on this feature .If possible is there any chat channel for  this project ,so that I can get in suggestions from the developers of this project in order to contribute more.

**Comment by mTwTm** [comment]
@Jacklin-ux Can you take a look at if this is what we want?

**Comment by Jacklin-ux** [comment]
This is a good suggestion. If possible, I expect to show not only "remaining time left", but also "current download size/file size" instead of "percentage". Any suggestions?

**Comment by manddy** [comment]
@Jacklin-ux I can definitely make that change as well but I think showing percentage instead of a fraction would not be  such a good idea. @mTwTm any idea on this ?

**Comment by Jacklin-ux** [comment]
I suggest this because lots of Lite's users gave us feedback that they want to see download file size when downloading, and I also agree this because for the user in expensive data plan envirenment, they really care about the file size (=money). So how do you think?

**Comment by manddy** [comment]
@Jacklin-ux  thanks for telling me this use case and I would try to send across a pr with the above features mentioned soon, just kindly help me out by reviewing it.

**Comment by manddy** [comment]
@Jacklin-ux Should I send across different pull request for remaining time left and currentdownload size/total size?

**Comment by Jacklin-ux** [comment]
For me, these two functions are important for users. If you want me to prioritize, I prefer to have "currentdownload size/total size" first. But I think it depends on your time, we are willing to see both and integrate into Lite. Thank you :)

**Comment by manddy** [comment]
@mTwTm @cnevinc  @Jacklin-ux  I have send a pull request for this feature can you review it .

**Comment by mTwTm** [comment]
Just asked @Jacklin-ux and he said yes this is better.

**Comment by chianger** [comment]
add QAWanted to test this.

**Comment by Daisy-pliu** [comment]
@Jacklin-ux could you suggest if below behavior is in your expectation ?

Test case TC0172 :
1. fresh install to launch rocket
2. go to [my google drive] 
3. click [5MB] on browser page
4. switch to home page
5. long click on [Menu] button
6.  click any where

Expect result :
3.1 show [downloading] toast message
3.2 show [download (↓) ] indicator next to menu button
3.3 then show context message [long press to open downloads]
4. show [download indicator (↓) ] next to menu button
5.1 no show context message [long press to open downloads]
5.2 show [download panel], [file name]
5.3 while downloading, it shows [remaining time left], [progress bar],[file size],[file type icon],[cancel], button near file name (no percentage progress)
5.3. once downloaded, it shows,[file size, date] ,[file type] icon, [more] button near file name
6. back to home page

**Comment by Daisy-pliu** [comment]
verify ❌
**version :** 1.4.0 (11444) nightly
**test case:** [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3344#issuecomment-484362790)
**Actual  result:**
5.3 while downloading, it shows [progress bar],[current file size/file size],[file type icon],[cancel]
**Expect result:**
5.3 while downloading, it shows [remaining time left], [progress bar],[current file size/file size],[file type icon],[cancel]

![Screenshot_20190419-113834_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/56404307-80627d00-6298-11e9-8237-3238267c35b1.jpg)

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 1.5.0 (11653)
test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3344#issuecomment-
Device info: sony xperia (5.0.1), webview: 73.0.3683.90
