### ISSUE TITLE
Remote configurable Life feed URL

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3350]
**User story**
As life feed service provider, I would like to be able to use Firebase as remote config backend to configure service URL (API)

** acceptance criteria **
1. Supports versioning of the API URL to map to corresponding client app

**Comment by chianger** [comment]
see also #3289

**Comment by Daisy-pliu** [comment]
verify: ✅
Test case:
**SC1 Set wrong url in Newspoint** ❓
1. set "life_feed_providers= [{"name":"Newspoint","type":"news","url":"http://partnersnp123.indiatimes.com/feed/fx/atp?channel=*&section=top-news&lang=english&curpg=%d&pp=%d&v=v1&fromtime=1551267146210","enable":true},{"name":"DainikBhaskar.com","type":"news","url":"http://appfeed.bhaskar.com/webfeed/apidata/firefox?pageSize=%d&channel_slno=%d&pageNumber=%d","enable":true}]" in Firebase
2. clear app data 
3. launch app
4. go to [settings] to change source to [news point]->see [make sure you are connected to the internet] with [try again] button
5. back to home page 
6. swipe up
7. go to [settings] to change source to [DainikBhaskar.com]
8. back to home page 
9. swipe up -> see [DainikBhaskar.com] news displayed
Note:  in step 4 , not sure it is expected when a news source service is unavailable? @Jacklin-ux 

**SC2: Set Newspoint url to correct link:** ✅
1. set "life_feed_providers= 
[{"name":"Newspoint","type":"news","url":"http://partnersnp.indiatimes.com/feed/fx/atp?channel=*&section=top-news&lang=english&curpg=%d&pp=%d&v=v1&fromtime=1551267146210","enable":true},{"name":"DainikBhaskar.com","type":"news","url":"http://appfeed.bhaskar.com/webfeed/apidata/firefox?pageSize=%d&channel_slno=%d&pageNumber=%d","enable":true}]" in Firebase
4. go to [settings] to change source to [news point]
5. back to home page 
6. swipe up ->see [news point] news displayed



**SC3 Set wrong url in DainikBhaskar.com:**❓
1. set "life_feed_providers= [{"name":"Newspoint","type":"news","url":"http://partnersnp.indiatimes.com/feed/fx/atp?channel=*&section=top-news&lang=english&curpg=%d&pp=%d&v=v1&fromtime=1551267146210","enable":true},{"name":"DainikBhaskar.com","type":"news","url":"http://appfeed.bhaskar.com123/webfeed/apidata/firefox?pageSize=%d&channel_slno=%d&pageNumber=%d","enable":true}]" in Firebase
2. clear app data 
3. launch app
4. go to [settings] to change source to [DainikBhaskar.com]->see [make sure you are connected to the internet] with [try again] button
5. back to home page 
6. swipe up
7. go to [settings] to change source to [News point]
8. back to home page 
9. swipe up -> see [News point] news displayed
Note:  in step 4 , not sure it is expected when a news source service is unavailable? @Jacklin-ux 

**SC3 Set correct url in DainikBhaskar.com:**✅ 
1. set "life_feed_providers= [{"name":"Newspoint","type":"news","url":"http://partnersnp.indiatimes.com/feed/fx/atp?channel=*&section=top-news&lang=english&curpg=%d&pp=%d&v=v1&fromtime=1551267146210","enable":true},{"name":"DainikBhaskar.com","type":"news","url":"http://appfeed.bhaskar.com/webfeed/apidata/firefox?pageSize=%d&channel_slno=%d&pageNumber=%d","enable":true}]" in Firebase
2. clear app data 
3. launch app
4. go to [settings] to change source to [DainikBhaskar.com]
5. back to home page 
6. swipe up ->see [DainikBhaskar.com] news displayed
