### ISSUE TITLE
pinned topsite onboarding

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3351]
for #2263, once done existing users may be confused. 
We would like to provide onboarding to let users know that they can recover their previous topsites.

**Comment by cnevinc** [comment]
I think #2263 need to depend on this. So I assume #2263 can at most land in sprint Q and ship in sprint R.

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1QM2CwPAu_sm_sWzv64YOQMCS_qY_cv7v/view?usp=sharing
