### ISSUE TITLE
Options between sd card and downloads

### ISSUE THREAD

**Issue by manddy** [mozilla-tw/FirefoxLite#3356]
User story
As a user I would like to have an option to select the location for my download.Some user want to have their downloads in sd card(removable) whereas others would prefer the standard downloads in the storage(This is already in firefox lite).

Acceptance Criteria 
1.Ui additions for  the option for user to select the download location(sd card or storage)
2 Implementation of sd card storage if the user selects this option.

Additional context
This is picture from chrome which currently supports this feature
![first](https://user-images.githubusercontent.com/22556185/54724891-f937c180-4b92-11e9-95bd-a9a5c038a626.jpeg)
![second](https://user-images.githubusercontent.com/22556185/54724893-fb9a1b80-4b92-11e9-80be-2b3447f0c774.jpg)

**Comment by mTwTm** [comment]
I think we already have this i our setting!

**Comment by manddy** [comment]
@mTwTm I don't have an external sd card so in my settings its not showing up .In  the project proposed there was mentioned that user should be able to download directly to removable sd card can you clarify on this whether we need this feature or need?

**Comment by mTwTm** [comment]
See: https://github.com/mozilla-tw/FirefoxLite/blob/master/app/src/main/java/org/mozilla/focus/components/RelocateService.java We relocate after downloading with Android Download Manager.
