### ISSUE TITLE
Affilated Sites Section

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3359]
// TBD

**Comment by Jacklin-ux** [comment]
Proposal: https://drive.google.com/file/d/1Dp1rQ9XyZ0DDOnAY806v8ONXgdKY8-xG/view?usp=sharing

**Comment by chianger** [comment]
Requirement: remote configurable to switch on/off per region.

**Comment by TLHuang** [comment]
Visual spec please refer to https://zpl.io/aMWZzPr

**Comment by chianger** [comment]
Will be replaced by new home design
