### ISSUE TITLE
Add more Indian locales

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3373]

**Comment by iamVP7** [comment]
If its related to l10n of browser menus, I can organize the sprint along with contributors for Tamil.

**Comment by luntik2012** [comment]
please no. let him learn english

**Comment by gkeegan** [comment]
@luntik2012 You're clearly either trolling or too bigoted to participate in civil discussion. Please stop posting telling people to just remove features in order to fix problems or suggest that people should be forced to learn new languages.

**Comment by gkeegan** [comment]
@luntik2012 Please stop trolling. It's quite obvious based on your profile here that you just seek attention. Get a life.

**Comment by chianger** [comment]
Candidate as below:
1. Tamil (ta)
2. Kannada (kn)
3. Malayalam (ml)
4. Marathi (mr)
5. Gujarati (gu-IN)
6. Telugu (te) 

Perhaps given the apk size limit we can't include all these. Will discuss in the planning meeting.

**Comment by weslyhuang** [comment]
moved it to the next Sprint per @chianger's comment on slack.

**Comment by chianger** [comment]
Let's add these 3 locales to production:
Tamil (ta)
Kannada (kn)
Malayalam (ml)

**Comment by cnevinc** [comment]
I'm waiting for delphin or Sebastian to advise what's the meaning of`local_name` and `plural_rule` and `team` fields

**Comment by Delphine** [comment]
Tamil:
local name: தமிழ்
Plural form: one, other
Plural rule: (n != 1)
-----
Kannada:
local name:  ಕನ್ನಡ
Plural form: one, other
Plural rule: (n != 1)
-----
Malayalam:
local name: മലയാളം
Plural form: one, other
Plural rule: (n != 1)

I'm not sure how you need to reflect these plural rules on your side. As I mentioned on Slack, I believe that for Focus Android, you only had to call this information out if the languages were not natively supported by Android - and these 3 locales should be supported. So might be something to double check.

@pocmo or @boek used to take care of this for Focus Android, so may have some knowledge to share too.

**Comment by pocmo** [comment]
* `local_name`: That's the name of the language in this language (and with that how it will show up in the UI). We usually asked the L10N team to provide this value for Focus.
* `plural_rule`: Since a2po/babble doesn't know which plural rule to apply we used a language with the same plural rules that it knows about and provided that locale. I did this by looking at the `po` files in the repo, looking at the "Plural-Form", e.g.: https://github.com/mozilla-l10n/focus-android-l10n/blob/master/locales/am/app.po#L19
then providing a locale (a popular language; that the tooling will know about) that has the same rule
* `team`: Not important, just copy the other value.

**Comment by chianger** [comment]
@pocmo well how do we know what locale the tooling will know about?

**Comment by chianger** [comment]
Oh. Just found the WIKI saying about this https://wiki.mozilla.org/L10n_Android_Unsupported_Locales
 
to test what locales are supported by Bebel, one can run `pybabel --list-locales` 

not sure of this help.

**Comment by pocmo** [comment]
> @pocmo well how do we know what locale the tooling will know about?

Try languages that are spoken by a lot of people - or look at the other po files that are already in the L10N repo and do not require to be listed in env.py ... if you can find one with the same plural rule then take that one :)

**Comment by Daisy-pliu** [comment]
verify :✅
test devcie : vivo  1606 (6.1.1), samsung 8.0
test version : 1.7.0 (12623)
![Screenshot_20190603-183228_Firefox Lite](https://user-images.githubusercontent.com/44990878/58795741-0448ac80-862e-11e9-8db9-169272e0c2b4.jpg)
