### ISSUE TITLE
Simple e-commerce portal in life feed

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3380]
This is a simple version given #1999 is to big. 
Story: As ID users, I would like to have the category URLs provided by e-commerce site.
AC1: onboarding is given, per ID MNC.

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1qGuGcZK4VM6qD8klaf-xfMFLeLvQhbT3/view?usp=sharing

**Comment by TLHuang** [comment]
Update visual spec accordingly https://drive.google.com/open?id=1uVpAp7RC3Je9lZ5-Zo2dYKnCjsbV_TrX

**Comment by chianger** [comment]
onboarding to leverage the exiting one from life feed

**Comment by cnevinc** [comment]
May I know where can I get the category name and the URLs?

**Comment by Jacklin-ux** [comment]
@cnevinc Indonesian category name as below,
1.Pulsa
2.Paket Data
3.Voucher Game
4.Tiket Kereta
5.Tiket Pesawat
6.Event

(Refer to https://www.bukalapak.com/pulsa?from=landing_page&source=train)

**Comment by Daisy-pliu** [comment]
Test case for [E-commerce portal ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B322)  is ready. Please let me know if you have any feedback

**Comment by Daisy-pliu** [comment]
Verify: ✅ with minor failure
version : nightly 1.3.1 (10250)
Test scenarios:[ test cases for e-commerce ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D321)
It has minor test failed so opened with several tickets
UI failed: #3442, #3441, #3439, #3437, #3438, #3435
Minor functionality failed: #3440, #3444

**Comment by Daisy-pliu** [comment]
Verify: ✅ 
version : nightly 1.3.1 (11298)
Test scenarios: test cases for e-commerce

**Comment by chianger** [comment]
data review request to @cnevinc  :

1. What questions will you answer with this data?
    We want to know how user interacts with the "life feed" (a.k.a content portal) function. (see
    https://bugzilla.mozilla.org/show_bug.cgi?id=1529868 ) This is also a follow up feature after #2712 

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
    We need more information from the user so we can enhance the user experience on the "life feed" feature and also further make plan for new features

3.   What alternative methods did you consider to answer these questions? Why were they not sufficient?
    We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
    No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
    Category 2 “Interaction data”

6. How long will this data be collected? Choose one of the following:
    We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

7. What populations will you measure?
    Users in targets markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)

8.  If this data collection is default on, what is the opt-out mechanism for users?
    The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
    We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and the usage over time.

10. Where do you intend to share the results of your analysis?
    N/A. Data is for internal feature planning evaluation only
