### ISSUE TITLE
Remove Yahoo from Search options

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3392]

**Comment by gkeegan** [comment]
Why should Yahoo be removed?

**Comment by luntik2012** [comment]
remove yandex also

**Comment by Daisy-pliu** [comment]
**Verify**✅
**Test version :** 
1.3.1 (11298) nightly 
**Test step:**
1. launch app
2. tap menu -> setting -> default search engine

**actual /expect**
1. show [google] and [DuckDuckGo] 

**test device**
samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify**: ✅
**Test version :** 
1.4.0 (11307) RC, webview : 74.0.3729.77
**Test step:**
refer [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3392#issuecomment-482011139)
