### ISSUE TITLE
The filename of a downloaded file is sometimes wrong, and can not be opened because of a wrong file extension

### ISSUE THREAD

**Issue by mossroy** [mozilla-tw/FirefoxLite#3394]
**Describe the bug**
Some websites make browsers download a file through a response header "Content-Disposition: inline;filename=..."
In this case, Firefox Lite seems to ignore the filename, and use the last part of the URL instead.
The downloaded file does not have the right file extension, and can not be opened.

**Steps To Reproduce**
1. Go to http://mossroy.free.fr/testcases-firefoxlite/download-pdf.php
2. A file named "download-pdf.php" is downloaded with some PDF content
3. This file can not be opened as its extension is .php instead of .pdf

**Expected behavior**
When the filename is set in this kind of Content-Disposition header, it should be used to name the downloaded file.

**Actual behavior**
The downloaded file content is correct, but it does not have the right name.
A workaround is to rename it.

**Device info (please complete the following information):**
 - Device: ZTE Open C
 - OS: LineageOS 14.1
 - Webview : 71.0.3578.99
 - Version : 1.1.3

**Reproduce rate**
Every time

**Additional context**
I faced this issue in a real-world use-case, but I can not easily share a test-case on it. It's an online shop, and the issue occurs when trying to download the invoice (in PDF format), from a .aspx URL

**Comment by mTwTm** [comment]
Duplicate to #1201
