### ISSUE TITLE
Youtube video can not enter fullscreen mode

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3399]
**Build**
1.3.0(11073)
**Steps To Reproduce**
1.  launch app 
2.  go to Youtube
3.  tap any [video]
4. tap [full screen mode] on the video

**Expected behavior**
enter full screen mode

**Actual behavior**
do nothing 

**Device info (please complete the following information):**
 - Device: Oppo (7.1.1) webview: 73.0.3683.90
 - Device :Samsung (8.0 )webview: 73.0.3683.90

**Reproduce rate**
5/5

**Note**
it is not happening on 1.2.1 (10858) , 1.0.6 (9033)
This issue happened on only in normal mode (not in private mode)

**Comment by cnevinc** [comment]
I've tested with 1.2 on my device (emulator and Asus).
https://vimeo.com/82567495 works and Youtube didn't.
I think we should have a static page for testing JavaScript APIs instead of relying on external websites to determine regression.

**Comment by chianger** [comment]
Still clarifying the ticket but we would tag the sprint Q release anyway.

**Comment by Daisy-pliu** [comment]
retested on 1.2.1 on device, the revised reproduce step is below: 

**Build**
1.3.0(11073), 1.2.1 (10858)

**Steps To Reproduce**
1.  fresh install app
2.  go to Youtube
3.  tap any [video]
4. tap [full screen mode] on the video -> it show [full screen mode] successfully
5. kill to relaunch app
6. tap [full screen mode] on the video


**Expected behavior**
enter full screen mode

**Actual behavior**
do nothing

**Note**
it is not happening on https://vimeo.com/82567495  on both  1.3.0(11073), 1.2.1 (10858).
more likely Youtube javascript call change.

**Comment by chianger** [comment]
According to the latest clarification above, this isn't a code regression. Let's not block v1.3 with this. Retag to sprint R.

**Comment by cnevinc** [comment]
I think this is because Youtube has different implementation now.
See the log when requesting fullscreen

`
I/chromium: [INFO:CONSOLE(0)] "Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.", source: https://m.youtube.com/watch?v=tWNVL7NF47w (0)
`

https://github.com/chromium/chromium/blob/685a1df9a3a27a8f806675400402d737d1539a24/third_party/blink/renderer/core/fullscreen/fullscreen.cc#L241

**Comment by mxlius** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=945287

Chrome/Webview bug. The interesting part is, our private mode can enter fullscreen, while normal browsing failed.

**Comment by chianger** [comment]
this is external bug and we don't really have work around. Leaving this in the sprint just to keep monitoring this and see what we can do.

**Comment by Daisy-pliu** [comment]
Test verify : ✅
1.4.0 (11307)
Test stesp: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3399#issue-427492752)
Test device: 
pixel xl (9.0),webview74.0.3729.77
samsung (8.0),webview 74.0.3729.77

**Comment by Daisy-pliu** [comment]
Set up sample test site on https://downloadfiletest-eab8a.firebaseapp.com/ to test video player. However it is the webview issue so still can not full screen in webview 73.

**Comment by elin-moco** [comment]
This can help if we want to notify affected users by targeting their webview version
https://github.com/mozilla-tw/FirefoxLite/issues/3272

**Comment by chianger** [comment]
> This can help if we want to notify affected users by targeting their webview version
> #3272
I'm requesting SUMO team to write an article for better communication.
https://bugzilla.mozilla.org/show_bug.cgi?id=1546573

**Comment by chianger** [comment]
Up and running; Chrome has webview 74 as stable now.
https://support.mozilla.org/en-US/kb/cant-watch-youtube-videos-fullscreen-firefox-lite
