### ISSUE TITLE
Language support for new Life Feed

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3407]
// TBD

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1F4yXQb4WQtuIQyPzTHngQ5kZa0_B_rYz/view?usp=sharing

**Comment by TLHuang** [comment]
Visual spec: https://zpl.io/aX3eGYM

**Comment by chianger** [comment]
covered by #3339
