### ISSUE TITLE
License link isn't correctly displayed (Javanese only)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3409]
**Describe the bug**
License link isn't correctly displayed, due to a typo on Pontoon

See: 
https://pontoon.mozilla.org/jv/firefox-rocket/app.po/?search=your_rights_content4&string=174040
There should be "a href"  instead of "href"

**Steps To Reproduce**
1. Go to Settings and switch the locale to Basa Jawa
2. Go to About page, and then Your rights and license
3. See the error display
![Screenshot_20190402-104712_Firefox Lite Nightly](https://user-images.githubusercontent.com/9859809/55378061-116fef00-554a-11e9-970c-425aa48cda67.jpg)

**Comment by chianger** [comment]
Al had made the suggestion on Pontoon to fix this.

**Comment by Delphine** [comment]
I've updated this in Pontoon. Correction should be available at the next Pontoon sync, within the next 15min.

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version : 1.4.0 (11337)
refer[ privacy screenshot ](https://drive.google.com/drive/u/0/folders/1oN21pFIkNmh765VTdZ9w9iRgFbCDUcyo)

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version : 1.5.0 (11653)
Device info:  sony xperia (5.0.1), webview: 73.0.3683.90
![Screen Shot 2019-04-26 at 2 00 19 PM](https://user-images.githubusercontent.com/44990878/56786479-b0c39180-682b-11e9-8ae9-5c7496bf653e.png)
