### ISSUE TITLE
APK files in latest versions are missing

### ISSUE THREAD

**Issue by ghost** [mozilla-tw/FirefoxLite#3411]
**Describe the bug**
APK files in latest versions are missing.
No APK files for 1.2.0, 1.2.1, 1.3.0, 1.3.1.

**Steps To Reproduce**
1. Go to https://github.com/mozilla-tw/FirefoxLite/releases
2. Click on "Show 4 newer tags" at the top.

**Expected behavior**
There have to be APK file to download and install for testing proposes.

**Actual behavior**
There is not any APK file available to download and install for testing proposes.

**Screenshots/videos**
Irrelevant.

**Device info (please complete the following information):**
Irrelevant.

**Reproduce rate**
Always.

**Additional context**
None.

**Comment by mTwTm** [comment]
AFAIK our current policy is to only publish when a release is safe and stable, cc @chianger to confirm.

**Comment by chianger** [comment]
Yes that is correct. Now we have 1.2.1 and 1.3.1 on GIthub.
