### ISSUE TITLE
Tabbed life feed

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3426]
Part of #1999
To make current life feed richer with switchable tabs.

**Comment by chianger** [comment]
size XL for this takes about two sprints.

**Comment by chianger** [comment]
this taken into sprint but would be cross-sprint issue.

**Comment by elin-moco** [comment]
After discussed with @lanyliu, here is the suggested event ping:

 - Click on Lifefeed Arrow
    method=click, object=home, value=lifefeed, extra={default_tab=promo|ec|news|..., tabs=[0-9]+}

Note that this includes "swipe". (no need to distinguish swipe/click)

**Comment by elin-moco** [comment]
Copy @lanyliu 
As per discussion with @cnevinc, this build will only have hard-coded tab default to coupons.
To make it easier to instrument tracking, we decided not to use "Click on Lifefeed Arrow.
Just use an extra to identify where users come from (tab or arrow)
 method=click, object=home, value=lifefeed_(news|ec|promo), extra={from=arrow|tab}

**Comment by Daisy-pliu** [comment]
Verify :❌
TC0223 :✅
version: 1.6.0 (12035) nightly
Note : The tabbed life feed is working however we can not see contextual life feed on boarding for Indo any more which is feature #3402 (while we can see such onboarding in India) after this PR landed.

**Comment by Daisy-pliu** [comment]
per discussion we will not nee A/B testing on  single tab anymore so  I am going to mark it as PASS.

**Comment by Daisy-pliu** [comment]
Verify: ✅
@elin-moco  please noted we will not have single tab anymore so we can only turn both ticket and coupon to ON or both OFF for Indonesian afterwards.
