### ISSUE TITLE
Life feed coupon

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3427]
part of #1999 and enhancement on #3380
For E-commerce Life Feed, I would like to have a tab listing coupons. 

Prerequisite: #3426 and #3428

**Comment by chianger** [comment]
data review request to @cnevinc :

1. What questions will you answer with this data?
    We want to know how user interacts with the "life feed" (a.k.a content portal) function. (see
    https://bugzilla.mozilla.org/show_bug.cgi?id=1529868 ) This is also a follow up feature after #2712 and #3380 . More details of the feature can be found in #1999 

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
    We need more information from the user so we can enhance the user experience on the "life feed" feature and also further make plan for new features

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
    We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
    No.

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
    Category 2 “Interaction data”

6. How long will this data be collected? Choose one of the following:
    We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.
7. What populations will you measure?
    Users in targets markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)
8. If this data collection is default on, what is the opt-out mechanism for users?
    The user can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
    We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and the usage over time.

10. Where do you intend to share the results of your analysis?
    N/A. Data is for internal feature planning evaluation only

**Comment by Daisy-pliu** [comment]
This ticket manly focus on coupon UI.
**Version :** Nightly 1.4.0 (11590)
**Verify :** ✅
**Test case in full run:** TC0220, TC0222,TC0224,   (TC0225 not ship)

**Verify :** ❌
**Test case in details:** backward compatibility
1. Current version:  nightly1.4.0 (11590) 
    1. VPN in Indo
    - Ticket, Coupon  (00) -> nothing
    - Ticket, Coupon  (01) -> nothing  -> which should be coupon ([fix PR](https://github.com/mozilla-tw/FirefoxLite/pull/3513) is on the way)
    - Ticket, Coupon (10) -> ticket
    - Ticket, Coupon (11) -> coupon


    2. VPN in India
    - News, (1)-> news
    - News, (0)-> nothing

2. Last release version: nighlty 1.4.0 (11336) 
    1.  VPN in Indo
    - Ticket, Coupon  (00) -> nothing
    - Ticket, Coupon (01)-> nothing
    - Ticket, Coupon (10)-> ticket
    - Ticket, Coupon (11)-> ticket


    2.  VPN in India
    - News, (1)-> news
    - News, (0)-> nothing

**Note:** 
In this sprint, we split out Coupon validation when no network but has cache to next sprint, #3523 is opened to track this sub-feature

**Comment by Daisy-pliu** [comment]
**Verify:**✅
**Device**: Pixel XL (9.0)
**Version :** Nightly 1.4.0(11618) 
**UI enhancement:** #3516 ✅ cc: @Jacklin-ux  please double check the UI.
**Backward compatibility:** ✅
