### ISSUE TITLE
life feed -  banner

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3429]
part of #1999 and enhancement on #3380
For E-commerce Life Feed, I would like to have the banner area .See #1999 for spec

**Comment by Daisy-pliu** [comment]
[coupon & banner test case ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D328) (TC0220~TC0225)  is ready

**Comment by Daisy-pliu** [comment]
Verify: ❎
Test case: [Indonesia coupon & banner test case ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=D328) (TC0220~TC0225) 
version: 1.5.0 (11680) nightly
Device info: sony xperia (5.0.1), webview: 73.0.3683.90
Note: found unexpected isssue #3544

**Comment by Daisy-pliu** [comment]
Verify: ❎ but not a blocker
Test case: Indonesia coupon & banner test case (TC0221~TC0222)
version: 1.5.0 (11682) release
Device info: sony xperia (5.0.1), webview: 74.3729.112
Note: found unexpected isssue #3544
