### ISSUE TITLE
For development settings is mafunctioning

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#3434]
I'm still seeing Content Portal when the setting is off.

**Comment by cnevinc** [comment]
now content portal is controlled by remote config, which will override the setting. I 'll suggest removing the development setting. Or make them "News" and "E-Commerce". I'd prefer the former.

**Comment by chianger** [comment]
no need to track in sprint planning

**Comment by cnevinc** [comment]
removed and done
