### ISSUE TITLE
For e-commerce portal, change title's string to "E-Voucher & Tiket" 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3435]
Current title is "E-voucher & Tiket"

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 

**Test step:**
1. set remote config str_e_commerce_shoppinglinks ={hasData for Indo && empty for default}
2. launch app 
3. swipe up 

**actual /expect**
![Screenshot_20190411-164607_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/55944298-e8064000-5c7a-11e9-8f2d-bf2a2d2859e1.jpg)

**Test device**
 samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 

**Test step:**
[steps](https://github.com/mozilla-tw/FirefoxLite/issues/3435#issuecomment-482031159)
**Test device**
pixle xl 9.0
