### ISSUE TITLE
Life feed (E-Commerce) non-localized string (Indonesian)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3436]
**Describe the bug**
"Service provided by" is not localized to Indonesian

**Steps To Reproduce**
1. Change UI locale to Indonesia
2. Click on Life feed to see E-Voucher and Tiket
3. Check the bottom "Service provided by ..." It's not localized.
![Screenshot_20190410-105748](https://user-images.githubusercontent.com/9859809/55848953-6979a780-5b81-11e9-8efc-7dc109713f19.png)

**Comment by cnevinc** [comment]
I think l10n import(01:03) after the nightly build(01:01) ?

**Comment by chianger** [comment]
S1 but non blocking

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 

**Test step:**
1. set remote config str_e_commerce_shoppinglinks ={hasData for Indo && empty for default}
2. launch app 
3. swipe up 

**actual /expect**
![Screenshot_20190411-164641_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/55945515-8abfbe00-5c7d-11e9-8373-a1f189aef9b8.jpg)

**Test device**
 samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.4.0 (11307) 
**Nightly  precondition**  
VPN in Indonesia 
**Test step:**
[steps ](https://github.com/mozilla-tw/FirefoxLite/issues/3436#issuecomment-482036294)
**device**
pixel xl 9.0
