### ISSUE TITLE
Life feed (E-Commerce)  string truncate   [Pixel XL]

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3437]
**Describe the bug**
 The "y" of "Service provided by" is truncated  

**Steps To Reproduce**

1.    Click on Life feed to see E-Voucher and Tiket
2.   Check the bottom "Service provided by ...",  the "y" is truncated
![Screenshot_20190410-105748](https://user-images.githubusercontent.com/9859809/55849059-e3aa2c00-5b81-11e9-8e10-49663cfa6b9d.png)

**Device info (please complete the following information):**
 - Device: [Pixel XL]
 - OS: [Android 8.1.0]

**Comment by chianger** [comment]
Obvious UI flaw. Will fix

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 

**Test step:**
1. set remote config str_e_commerce_shoppinglinks ={hasData for Indo && empty for default}
2. launch app 
3. swipe up 

**actual /expect**
![Screenshot_20190411-164607_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/55944298-e8064000-5c7a-11e9-8f2d-bf2a2d2859e1.jpg)

**Test device**
Pixel XL

**Comment by Daisy-pliu** [comment]
@Jacklin-ux  will help the verification.

**Comment by Daisy-pliu** [comment]
Verify:✅
version: 1.4.0 (11337 ) RC
teststep:  [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3438#issue-431284874)
device: pixel xl 9.0 webview: 74.0.3729.77
screenshot: 
![Screenshot_20190412-184008](https://user-images.githubusercontent.com/44990878/56032189-0db34800-5d54-11e9-878a-b399019cb741.png)
