### ISSUE TITLE
For e-commerce portal, "Event" button overlaps BUKALAPAK logo

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3438]
![Screenshot_20190410-110938](https://user-images.githubusercontent.com/22672569/55849015-b493ba80-5b81-11e9-81c0-9a14758ad738.png)

**Comment by chianger** [comment]
Obvious UI flaw. Will fix

**Comment by Daisy-pliu** [comment]
@Jacklin-ux  will help the verification.

**Comment by Daisy-pliu** [comment]
Verify:✅
version: 1.4.0 (11337 ) RC
teststep:  [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3438#issue-431284874)
device: pixel xl 9.0 webview: 74.0.3729.77
screenshot: 
![Screenshot_20190412-184008](https://user-images.githubusercontent.com/44990878/56032189-0db34800-5d54-11e9-878a-b399019cb741.png)

**Comment by Daisy-pliu** [comment]
Verify:✅
version: 1.4.0 (11337 ) RC
teststep: steps
device: advan 5 (small screen), webview: 72.0.3626.121
screenshot:
![Screenshot_2019-04-12-19-01-05](https://user-images.githubusercontent.com/44990878/56032856-c0d07100-5d55-11e9-8ab1-12af5991b902.png)
