### ISSUE TITLE
The round corners of categories background are blurry

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#3439]
The round corners of categories background are blurry, and shadow style is missing.

![Screenshot_20190410-110944](https://user-images.githubusercontent.com/4092794/55849404-0b4dc400-5b83-11e9-8ac4-800952d9699c.png)

**Comment by chianger** [comment]
Obvious UI flaw. Will fix

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**nightly precondition:** 
VPN in Indonesia 
**Test step:**
1. set remote config str_e_commerce_shoppinglinks ={hasData for Indo && empty for default}
2. launch app 
3. swipe up 

**actual /expect**
![Screenshot_20190411-164607_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/55944298-e8064000-5c7a-11e9-8f2d-bf2a2d2859e1.jpg)

**Test device**
 samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify:** ✅ 
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 
**Test step:**
[steps](https://github.com/mozilla-tw/FirefoxLite/issues/3439#issuecomment-482029918)**
**Test device**
 pixel xl 9.0
