### ISSUE TITLE
No onboarding for E-commerce 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3440]
**Version**
nightly 1.3.1 (11250)

**Steps To Reproduce**
1. Remote config nightly with  correct "str_e_commerce_shoppinglinks" value
2. Fresh install app with indo sim
3. launch app

**Expected behavior**
see original onboarding + new life feed page

**Actual behavior**
no onboarding 

**Device info (please complete the following information):**
all device 
**Reproduce rate**
5/5

**Comment by cnevinc** [comment]
Remote config comes later than onboarding. So seeing nothing is expected.
If we want to see onboarding, we must use mcc.

Currently, if the user opens the app next time (after Remote Config has fetched), he'll see upgrade onboarding.

**Comment by Daisy-pliu** [comment]
After offline discussion, it will enhance by even user seeing 4 original onboarding and skip them,  user will see life feed on boarding after relaunch.

**Comment by Daisy-pliu** [comment]
**Verify**: ✅
**Test version :** 
1.3.1 (11298) nightly 
**precondition:** 
VPN in Indonesia
**Test step:**
1. set remote config  str_e_commerce_shoppinglinks ={hasData for Indo && empty for default} 
2. wait 3 min
3. fresh install app to skip original 4 onboarding pages
4. relaunch app

**actual /expect**
1. see life feed onboarding page

**test device**
samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify**: ✅
**Test version :** 
1.4.0 (11307) RC
**precondition:** 
VPN in Indonesia
**Test step:**
[steps](https://github.com/mozilla-tw/FirefoxLite/issues/3440#issuecomment-482022178)
**Test device**
pixel xl 9.0, webview: 74.0.3729.77
