### ISSUE TITLE
For e-commerce portal, adjust BUKALAPAK logo's location 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3441]
Currently, BUKALAPAK logo a little overlaps the string "Service provided by"

**Comment by Daisy-pliu** [comment]
**Verify:** ? @Jacklin-ux  please advise
**Test version** : 1.3.1 (11298) 
**Nightly  precondition**  
VPN in Indonesia 

**Test step:**
1. set remote config str_e_commerce_shoppinglinks ={hasData for Indo && empty for default}
2. launch app 
3. swipe up 

**actual /expect**
![Screenshot_20190411-164641_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/55945515-8abfbe00-5c7d-11e9-8373-a1f189aef9b8.jpg)

**Test device**
 samsung 8.0

**Comment by Daisy-pliu** [comment]
@Jacklin-ux  will help the verification.

**Comment by Daisy-pliu** [comment]
Verify:✅
version: 1.4.0 (11337 ) RC
teststep:  [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3438#issue-431284874)
device: pixel xl 9.0 webview: 74.0.3729.77
screenshot: 
![Screenshot_20190412-184008](https://user-images.githubusercontent.com/44990878/56032189-0db34800-5d54-11e9-878a-b399019cb741.png)
