### ISSUE TITLE
Update tokopedia preset icon

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3443]
Choose from https://www.tokopedia.com/brand-asset/ rather than the favicon

**Comment by TLHuang** [comment]
Resizing Tokopedia icons for topsites and quick search, please help to update them.

For topsite
![ic_tokopedia](https://user-images.githubusercontent.com/4092794/55858877-5aa3ec80-5ba3-11e9-8c9b-c51b2f4687b5.png)

For quick search
![tokopedia](https://user-images.githubusercontent.com/4092794/55858900-68f20880-5ba3-11e9-8e5f-6299c212cd53.png)

**Comment by cnevinc** [comment]
done in #3465

**Comment by Daisy-pliu** [comment]
verify: ❓
@Jacklin-ux  could you check it displays right? 
test version : 1.4.0 (11444) nightly
1. topsite
![Screenshot_20190419-111016_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/56403928-5019df00-6296-11e9-90d8-8582ee859c18.jpg)

2. quick search 
![Screenshot_20190419-111030_Firefox Lite Nightly](https://user-images.githubusercontent.com/44990878/56403920-47290d80-6296-11e9-89d2-174b92d04df0.jpg)

**Comment by Jacklin-ux** [comment]
Looks good. Thank you

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 1.5.0 (11653)
Device info: sony xperia (5.0.1), webview: 73.0.3683.90
