### ISSUE TITLE
Indo user see India news in older build 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3444]
**Steps To Reproduce**
1. set nightly remote config 
 -> "enable_life_feed" ={ TRUE for indonesia &&  FALSE for default}
 -> "str_e_commerce_shoppinglinks" ={ hasdata for indonesia &&  FALSE for default }
-> "life_feed_providers"={ hasdata for india &&  FALSE for default }
2. install nightly 1.3.1 (11228) with indo sim 
3. launch

**Expected behavior**
should not see arrow or swipe up to see portal news 

**Actual behavior**
after swipe up user see content news portal "Latest& Top trending news"

**Device info (please complete the following information):**
all

**Reproduce rate**
8/8

**Note**
version nightly 1.3.1 (11228) should not see content portal in Indonesia as this version only has the feature for India.

**Comment by benjamin-cheng** [comment]
We may add app version constraint in remote config ex:
-> "enable_life_feed" ={TRUE for (country is indonesia && app version > 1.3.1) ; FALSE for default}

**Comment by Daisy-pliu** [comment]
I can not set condition by app version 
<img width="829" alt="Screen Shot 2019-04-10 at 5 11 36 PM" src="https://user-images.githubusercontent.com/44990878/55866871-d7d75d80-5bb3-11e9-973a-f5b485282e2b.png">
not sure if it is permission issue ?

**Comment by benjamin-cheng** [comment]
You need to add the App with our package name first, then specify the version.

**Comment by Daisy-pliu** [comment]
good to know. I set the app but I can not find config that larger than certain version ? 
<img width="846" alt="Screen Shot 2019-04-10 at 6 11 17 PM" src="https://user-images.githubusercontent.com/44990878/55870915-2688f580-5bbc-11e9-8b79-df0abac25888.png">

**Comment by Daisy-pliu** [comment]
**Verify**: ✅
**Test version :** 
1.3.1 (11298) nightly 
**Verify steps**
1. set nightly remote config 
 -> "enable_life_feed" ={ TRUE for india &&  FALSE for default}
 -> "str_e_commerce_shoppinglinks" ={ hasdata for indonesia &&  empty for default }
-> "life_feed_providers"={ hasdata for india &&  empty for default }
2. install nightly 1.3.1 (11298) with vpn in indo
3. launch

**Expected/Actual behavior**
indo users not see any portal on home page

**test device**
samsung 8.0

**Comment by Daisy-pliu** [comment]
**Verify**: ✅
**Test version :** 
1.3.1 (11115) RC
**precondition:**
 VPN in Indonesia
**Verify steps**
[steps](https://github.com/mozilla-tw/FirefoxLite/issues/3444#issuecomment-482024453)
**test device**
pixel xl (9.0)
