### ISSUE TITLE
Keyboard won't dismiss while attemping to close FInd in Page mode

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#3464]
**Describe the bug**
Tapping "x" on the input field doesn't dismiss keyboard correctly

**Steps To Reproduce**
1. Launch Firefox Lite and open a web page
2. Tap on menu
3. Tap on Find in Page
4. Tap on "x" on input field

**Expected behavior**
4. Find in page input field and keyboard are both dismissed

**Actual behavior**
4. Find in page input field is dismissed but keyboard isn't 

**Screenshots/videos**

**Device info (please complete the following information):**
 - Device: Pixel
 - OS: Android 9.0
 - Webview 74.0.3729.77
 - Version 1.4.0 (11337)

**Reproduce rate**
50%

**Additional context**

**Comment by chianger** [comment]
dup of #2657 ?

**Comment by Conjuror** [comment]
Yes. Let's track with #2657
