### ISSUE TITLE
Change Youtube to YouTube on Top Sites

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3477]
**Describe the bug**
Currently the preloaded top sites spell "Youtube" where it should be "YouTube"

**Comment by iadeelzafar** [comment]
Hey @joechengla @cnevinc  @mTwTm  , I'm trying to set up this project but I'm getting this build error. Could you please help me with this?
![image](https://user-images.githubusercontent.com/36811908/56471940-be66c900-6471-11e9-836d-f7899c8fe990.png)

**Comment by mTwTm** [comment]
@iadeelzafar You'll need to run `git submodule init update` as described in the readme. Let me know if this works. Also, to discuss the technical items you're welcomed utilize this public mail list: https://groups.google.com/forum/#!forum/mozilla-asia-products

**Comment by iadeelzafar** [comment]
@mTwTm ```git submodule update``` didn't worked.

![image](https://user-images.githubusercontent.com/36811908/56473535-f1b35300-6485-11e9-85da-a260aeb94414.png)

Hence, the problem persists in android studio.

**Comment by mTwTm** [comment]
Let's move this to: https://groups.google.com/forum/#!topic/mozilla-asia-products/RuzOailLtF4

**Comment by mTwTm** [comment]
@iadeelzafar I totally missed the possibility that you might want to fix this issue? I'll leave it to you if you're happy to do so?

**Comment by abhi211199** [comment]
@mTwTm the bug lies in `topsites.json` file.
`{
    "id": -1,
    "url": "https://m.youtube.com/",
    "title": "Youtube",
    "favicon": "ic_youtube.png",
    "viewCount": 20
  },
` 
here, `Youtube` is to be changed to `YouTube`.
![DeepinScreenshot_20190422095354](https://user-images.githubusercontent.com/36303692/56483106-623d8c80-64e5-11e9-97e4-40ea8688ce5b.png)

I am facing problem in building the project, once I fix the build error, I can make a PR.

**Comment by mTwTm** [comment]
@abhi211199 Yes exactly, thanks for the update. However, if @iadeelzafar is already working on that let's not have some duplicate work. I've just tagged a lot `good first issue` bugs that you might also be interested!

**Comment by iadeelzafar** [comment]
Hi @abhi211199 you can work on this. @mTwTm I'll start with the night mode one once the repo buids successfully. And yeah, I'll surely checkout more issues to work on too. Thanks a lot!

**Comment by mTwTm** [comment]
Fixed in #3508
