### ISSUE TITLE
News source random percentage unbalanced

### ISSUE THREAD

**Issue by lanyliu** [mozilla-tw/FirefoxLite#3492]
**Describe the bug**
Data shows 80/20 start from April instead of expected 50/50

**Steps To Reproduce**
NA

**Expected behavior**
50/50

**Actual behavior**
80/20

**Screenshots/videos**
![newplot](https://user-images.githubusercontent.com/49740335/56403272-17c4d180-6293-11e9-818d-58dfe3165f77.png)

**Comment by mTwTm** [comment]
What event is this?

**Comment by lanyliu** [comment]
count uu by events.extra['feed']

with condition: 
events.method = 'click' and events.value = 'lifefeed_news'

**Comment by mTwTm** [comment]
Could it be that users are changing favoring one source over another? Or I just heard from Eddy that the users that have changed the source are relatively small?

**Comment by mTwTm** [comment]
From the code, I didn't see anything that is fishy including the Random Generator. @cnevinc maybe you can help?

**Comment by lanyliu** [comment]
I've check whether it comes from user's intention, for those client_id having more then one status on settings will be identified as user's intend. However, there's no trending on DB news source.

**Comment by mTwTm** [comment]
Thanks! Let's see if @cnevinc has some magic that can save us then.

**Comment by chianger** [comment]
Let's use remote config to make it balanced through backend.

**Comment by mTwTm** [comment]
`if (new Random().nextInt(1) % 2 == 0)` should be `if (new Random().nextInt(2) % 2 == 0)` since boundary is exclusive.

**Comment by mTwTm** [comment]
Let's fix it in the code rather than do some cumbersome remote configuration now that we have a fix.

**Comment by chianger** [comment]
see also #3549 since now we're transitioning it to one source.

**Comment by chianger** [comment]
we no longer need this.
