### ISSUE TITLE
Cannot see share_app_dialog after relaunch 8 times on Nightly

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3495]
**Steps To Reproduce**
1. given share_app_dialog_threshold is "10" on nightly
2. user reset app (clear app data on system)
3. user relaunch app for 10 times

**Version**
Nightly 1.4.0 (11479)

**Expected behavior**
see share_app_dialog

**Actual behavior**
not see share_app_dialog

**Device info (please complete the following information):**
samsung 8.0

**Reproduce rate**
5/5

**Additional context**
it happens on production Lite 1.4.0 (11337) app as well

**Comment by elin-moco** [comment]
I can also reproduce this bug on my HTC U-Ultra.

**Comment by elin-moco** [comment]
Very weird, we are still getting share dialog pings,
but the active % dropped gradually since Aug 2018.
https://analytics.amplitude.com/share/f9bfeca99edf4026806f389691216eb3
Note that the share dialog experiment is performed on July 2018.

**Comment by Daisy-pliu** [comment]
Confirmed with dev that the behavior should be as below which is correct so that I close the ticket

**Steps To Reproduce**
1. given share_app_dialog_threshold is "10" on nightly
2. user reset app (clear app data on system)
3. user relaunch app for 6th times to see rate_app_dialog
4. tap [X] on dialog
5. user relaunch app for 12th times to see rate_app_notification
6. tap [rate us] on dialog
7. user relaunch app for 16th times to see share_app_dialog

**Steps To Reproduce**
1. given share_app_dialog_threshold is "10" on nightly
2. user reset app (clear app data on system)
3. user relaunch app for 6th times to see rate_app_dialog
4. tap [rate us] on dialog
5. user relaunch app for 10th times to see share_app_dialog
