### ISSUE TITLE
Remove enable_private_mode remote config feature

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3521]
**User story**
Per discussion, better to remove enable_private_mode remote config feature from code as it is not used any more, which will reduce technical debt and have clean code base.

**Acceptance Criteria (how do I know when I’m done?)** 
1. enable_private_mode on remote config should not work any more

**Comment by chianger** [comment]
Dup of #3490 ?

**Comment by chianger** [comment]
No user impact but for code maintenability, devs might want to take it.

**Comment by benjamin-cheng** [comment]
The remote config can be safely removed by #3491. I've already removed the config from dev console.

**Comment by benjamin-cheng** [comment]
FYI. The commit was tagged by release 1.5.0. However, the private mode is default enable started from v3.1.0. So, removing the remote config from production console might impact those users stick to the older versions before v3.1.0.

**Comment by Daisy-pliu** [comment]
QA will verify on release APK 3.1.0, 3.3.0, 1.0.0, 1.0.6,1.2.1,1.6.2 to ensure backward compatibility.

**Comment by Daisy-pliu** [comment]
Should we support private mode for apk version under v3.1.0 ? @weslyhuang 

**Test verify :** ✅
**Test step:**
1.  production remote config remove {enable_private_mode}
2. download v3.1.0/v1.5.0/v1.8.0 
3 launch app
4. search and open WIKI page
5. tap [tab tray]

**Test result:**
see [private mode] icon

**Test device:**
Oppo 7.1.1

**Comment by Daisy-pliu** [comment]
Based on [discussion](https://mozilla.slack.com/archives/G5QBPEK4J/p1561972787078900) in slack , we will remove  enable_private_mode from Firebase remote config as the impact is low in terms of the number of users with < v3.1.0 build on private mode activity.

**Comment by Daisy-pliu** [comment]
Reminder : when release this build, we need to remove enable_private_mode from Firebase.

**Comment by Daisy-pliu** [comment]
not add to full run as it is a configuration clean up.

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.0(13268)
Test step:
1. production remote config remove {enable_private_mode}
2. download RC v1.5.0/01.9.0
3. launch app
4. search and open [WIKI page]
5. tap [tab tray]

**Test result:**
see [private mode] icon

**Test device:**
Samsung 8.0
