### ISSUE TITLE
SUMO didn't show for setting default browser

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#3529]
**Describe the bug**
This issue failed TC0063.

**Steps To Reproduce**
"1. Launch Rocket 
2. Press settings 2ed time
3. Close Rocket
4. Tap Make default browser notification
5. ReLaunch Rocket 
6. Press settings 2ed time"

**Expected behavior**
4. There might be browser option menu and a user should be able to open SUMO page via Firefox Lite.

**Actual behavior**
4. nothing happen

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: Advan i5C
 - OS: Android 5.0
 - Webview 73.0.3683.90
 - Version 1.4.0(11624)

**Reproduce rate**
5 out of 5

**Additional context**

**Comment by chianger** [comment]
QAWanted that we probably need to update the test case.

**Comment by Conjuror** [comment]
Close it as test case is updated.
