### ISSUE TITLE
Give user a way to share us the id for user testing

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#3530]
Per discussion with Yvonne, we'd like to give users a way to share us their ids.

I think it's possible via `TelemetryHolder.get().getClientId()` but we'd need to verify it's the correct id. (the formats are the same per what I see.)

**Comment by chianger** [comment]
trigger: bring up dialog of "share with friends" 19 times
action: show firebase user id and telemetry ID.

**Comment by Daisy-pliu** [comment]
TC 0028 in full run : 
Version: 1.5.1 (11790) 
Device: pixel 2(9.0) 
Test step: 
1. tap [settings]
2. tap [share with friends] for 19 times

result:
![Screenshot_20190510-110857](https://user-images.githubusercontent.com/44990878/57500081-8a662180-7314-11e9-9cf5-4a4181c7a8b6.png)

**Comment by Daisy-pliu** [comment]
TC0028 Share user id will perform on full run.
Verify: ✅
Version: 1.6.1 (12105)
Device: vivo 6.0.1
Test step: [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3530#issuecomment-491140327)
