### ISSUE TITLE
Current version not available in F-Droid

### ISSUE THREAD

**Issue by Krawei** [mozilla-tw/FirefoxLite#3533]
**Describe the bug**
Dear team,

when I take a look in the play store the current version is 1.4.0, in tbe F-Droid store the current version is 1.3.0. 

What's the reason for this gap? Is there a bug in thr build process?

Please fix this.

Kind Regards,

Krawei

**Steps To Reproduce**
1. Search Firefox Lite in Playstore
2. Search Firefox Litein F-Droid
3. Compare version numbers

**Expected behavior**
There shouldn't be a gap regarding Firefox Lite's  version number between playstore and f-droid.

**Actual behavior**
See bug description

**Device info (please complete the following information):**
 - Device: BQ Aquaris X Pro
 - OS: Android 8.1.0
 - Webview 73.0.3683.90
 - Version 1.3.0

**Reproduce rate**
100%

**Comment by mTwTm** [comment]
I'm uncertain but I guess fdroid has their only release cadence. Mozilla doesn't actively distribute to fdroid at this moment.

**Comment by chianger** [comment]
Correct. There's actually no action from Mozilla side.

**Comment by Krawei** [comment]
Well if there's no action from mozilla to F-Droid, who built that app there?
Currently the F-Droid-Version stucks on 1.4.0, wäre the Google Play store Version is 1.9.x.

Whom I need to ask to solve this issue?

**Comment by Rudloff** [comment]
The issue is tracked on the F-Droid side here: https://gitlab.com/fdroid/fdroiddata/issues/1668

The main reason we don't build this app anymore is because https://github.com/mozilla-tw/FirefoxLite/commit/ffe5c1e473e48993f0e92f6a55fb12390b683fd2 removed the ability to build it without Firebase (and we don't accept proprietary libraries).
