### ISSUE TITLE
Change logo to adaptive icon for Android 8 & up 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3535]
Currently more than 40% of users are using Android 8 & up, we also received user feedback of 3 stars rating due to logo is too small. So I suggest we do change our logo to adaptive icon.

**Comment by TLHuang** [comment]
Assets are ready! I exported a SVG file, also a XML file just in case. Let me know if any questions!
[adaptive_icon.zip](https://github.com/mozilla-tw/FirefoxLite/files/3116458/adaptive_icon.zip)

**Comment by TLHuang** [comment]
The visual is updated, spec please refer to https://zpl.io/29wLlBA

**Comment by Daisy-pliu** [comment]
QA will verify with designer on launcher icons in shortcuts, the Settings app, sharing dialogs, and the overview screen across Pixel 2 , Samsung 8.0, redmi 7.0 for this sprint.

Note : this feature will not have test case in full run.

**Comment by Daisy-pliu** [comment]
verify: ✅
Test device: Samsung 8.0 ,Pixel 9.0
Below is Samsung icons on settings, sharing dialog, overview,launcher icon.
![Screenshot_20190527-175413_Android System](https://user-images.githubusercontent.com/44990878/58412841-e1f0e500-80a9-11e9-8ab3-f05ffb0c9542.jpg)
![Screenshot_20190527-175321_Samsung Experience Home](https://user-images.githubusercontent.com/44990878/58412843-e1f0e500-80a9-11e9-9ffb-2c2f3d9b112e.jpg)
![Screenshot_20190527-175304_Settings](https://user-images.githubusercontent.com/44990878/58412844-e1f0e500-80a9-11e9-9249-c1525d35a32d.jpg)
![Screenshot_20190527-180534_Samsung Experience Home](https://user-images.githubusercontent.com/44990878/58413071-79563800-80aa-11e9-8535-21b2e1c454b7.jpg)

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**version:** 1.7.0(12623) 
**device:** google pixel 9.0, samsung 8.0
