### ISSUE TITLE
Can not see banner when back

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3544]
**Steps To Reproduce**
1. vpn in indo
2. swipe up 
3. tap [banner]
4. tap [back]

**Expected behavior**
see [banner] on life feed

**Actual behavior**
not see [banner] on life feed

**Version**
1.5.0 (11680) nightly

**Device info**
 sony xperia (5.0.1), webview: 74.3729.112
**Reproduce rate**
10/10

**Comment by Daisy-pliu** [comment]
verify: ✅
version: release 1.5.0 (11682)
Device info: sony xperia (5.0.1),  webview: 74.3729.112

**Comment by chianger** [comment]
QAWanted to reproduce again. If can't reproduce let's close it.

**Comment by chianger** [comment]
No one can reproduce at this moment.
