### ISSUE TITLE
Should be no life-feed onboaring when upgrade from 1.4.0 to 1.5.0

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3545]
Below I conclude life-feed on boarding case for indonesia.

**Life feed onboarding TC 1** ❌
1. vpn in indonesia
2. fresh install 1.5.0
3. skip all onboarding  (original 3 onboarding )
4. kill to relaunch 

**Expected behavior**
see no [life feed onboarding]

**Actual behavior**
see  [life feed onboarding]

**Test version:** 
1.5.0

**Reproduce rate**
3/3

**Note:**
this issue does not happen on india

If we do below steps we wont see onboarding in 1.5.0
**Life feed onboarding TC 2** ✅
1. vpn in indonesia
2. install 1.4.0 
3. skip all onboarding  (original 3 onboarding )
4. kill to relaunch & skip life-feed onboading
4. upgrade to 1.5.0

**Expected behavior same as actual behavior**
see no [life feed onboarding]

**Comment by chianger** [comment]
no longer happening in 1.6.2.

**Comment by chianger** [comment]
Close as v1.5.0 is history now.
