### ISSUE TITLE
Transition life feed newsource to single source 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3549]
Areas to cover:
1. remote config
2. setting UI (Eng wanted)
https://github.com/mozilla-tw/FirefoxLite/blob/12125ca9ec8f22374fb9db1d089f68fd6d9e0e5a/app/src/main/java/org/mozilla/rocket/widget/NewsSourcePreference.java#L49
This hardcoded options should be only newspoint. 

3. sumo page update  (Bug 1547652 - [SUMO] Removing DainikBhaskar.com)
4. product communication (through push notification, etc)

**Comment by Daisy-pliu** [comment]
test case 1 - upgrade : user change settings:
1. launch app 1.5.0 
2. swipe up 
3. change setting to [DB]
4. upgrade to 1.5.1
5. launch app
6. swipe up 
7. go to [setttings] -> [news source]

Expect result:
6. see [DB] news
7. see [source] only has [news point] 

test case 2 - upgrade : default setting:
1. launch app 1.5.0 
2. swipe up to see news
3. upgrade to 1.5.1
4. launch app
5. swipe up 
6. go to [setttings] -> [news source]

Expect result:
2. see [DB] news
6. see [source] only has [news point] 


Test case 3 - fresh install:
1. fresh install to 1.5.1
2. launch app
3. swipe up 
4. go to [setttings] -> [news source]

Expect result:
3. see [news point] news
4. see [news point]

**Comment by benjamin-cheng** [comment]
@Daisy-pliu regarding your test cases, according to the discussion with UX @Jacklin-ux ,  there is no "news source" preference in the settings page anymore.

**Comment by Daisy-pliu** [comment]
thanks for letting me know.  I am planning to change the test case

**Comment by Daisy-pliu** [comment]
**test version:**
Release 1.5.1 (11790)

**Test case**
test case 1 : ✅
test case 2 : ✅
test case 3: ✅

**Note:**
only take case 3 in full run by refactoring TC0198 , and remove  TC0205
