### ISSUE TITLE
Support in-app updates

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3585]
https://developer.android.com/guide/app-bundle/in-app-updates

**Comment by Jacklin-ux** [comment]
UX spec (version 1): https://drive.google.com/file/d/1I902a4ZzXeCkIAhjp8pvBiQFySSY2Mgb/view?usp=sharing

**Comment by pharspher** [comment]
- Dialogs popup logic control (i.e. Strategy when multiple dialogs are to be shown at the same time)
- Firebase remote config
  - target version
  - prompt type (optional|force)
  - prompt ui (title/description/button text, etc)
- Download progress/complete notification
- Download progress toast/snackbar
- Overall flow implementation

**Comment by chianger** [comment]
Open question to follow up: possible to make A/B testing for a: skiping step1 dialog; b: two dialogues exisit

**Comment by pharspher** [comment]
@Jacklin-ux 
Needed L10N strings

Toast msg indicating download is started

Snackbar msg indicating download complete
Snackbar install button text

Notification title for download progress
Notification content for download progress (if any)

Notification title for download complete
Notification content for download complete (if any)
Notification install action button text

**Comment by pharspher** [comment]
> Open question to follow up: possible to make A/B testing for a: skiping step1 dialog; b: two dialogues exisit

After further looking into the overall flow, I think this can be included in this sprint

**Comment by pharspher** [comment]
@chianger The strings on the first dialog is provided by the remote config. So there should be some other L10N process for these strings instead of Pontoon?

**Comment by pharspher** [comment]
@Jacklin-ux The in-app update API does not provide download progress information, so you might need to redesign the content of downloading notification.

**Comment by elin-moco** [comment]
Here are the suggested event probe:

- Prompt for update: method=show, object=update, value=, extra={from_build=[0-9]+, to_build=[0-9]+}
- Click on Update Prompt: method=click, object=update, value=positive|negative, extra={from_build=[0-9]+, to_build=[0-9]+}
- Show Apply Update: method=show, object=update, value=downloaded, extra={from_build=[0-9]+, to_build=[0-9]+}
- Apply Update: method=click, object=update, value=apply, extra={from_build=[0-9]+, to_build=[0-9]+, source=notificaiton|snackbar}

**Comment by chianger** [comment]
strings in #3722

**Comment by elin-moco** [comment]
Also note that, users who didn't install from Google Play won't be able to receive in-app update.
So we'll need to record INSTALL_REFERRER.
So we know who aren't able to get in-app update.

**Comment by Daisy-pliu** [comment]
Test case is created for in-app update: [TC00239~TC00241](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B352)

**Comment by Daisy-pliu** [comment]
We won't test the feature this time on production as production version now is 1.8.0 which has no in-app notification feature. Instead we will test it on production when version is newer than 1.9.0.

**verify:** ✅
**Test build:**
Nightly 1.8.0 (13128)

**Test step:**
[TC0239 ~TC0240](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B353)
**Test result:**
![Screenshot_20190711-143610](https://user-images.githubusercontent.com/44990878/61027823-bc196880-a3e9-11e9-89d9-576128fc3fb0.png)

**Test device:**
Samsung 6.0.1 S6 edge
