### ISSUE TITLE
Multi-tab life feed not back to the last location 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3594]
**Steps To Reproduce**
1. vpn in indo
2. swipe [up]
3. tap [ticket] tab
4. tap any ticket
5. tap system back 

**Expected behavior**
see [disabled coupon] tab and  [enabled ticket] tab 

**Actual behavior**
see [enabled coupon] tab and  [disabled ticket] tab 

**Version**
1.6.0 (12105)

**Device info (please complete the following information):**
 - vivo 6.0.1
- samsung 8.0

**Reproduce rate**
5/5

**Comment by chianger** [comment]
UX enhancement: S2.

**Comment by chianger** [comment]
Plan to be fixed while #3339 lands, so adding to sprint U for verifying.

**Comment by chianger** [comment]
looks it's fixed. tag @Daisy-pliu to verify.

**Comment by Daisy-pliu** [comment]
verify: ✅
test step: [step](https://github.com/mozilla-tw/FirefoxLite/issues/3594#issue-444226530)
version: 1.8.0 (12867)
device: redmi 4X
