### ISSUE TITLE
[top crash] ContentPortalView.kt line 111 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3620]
Happens since v1.6.0, see:

https://console.firebase.google.com/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5cdccb32f8b88c296308a719?time=last-ninety-days&sessionId=5CE3ACCC015C0001650C0E4F0D1C6AD6_DNE_0_v2

**Comment by chianger** [comment]
close as #3620 landed.

**Comment by Daisy-pliu** [comment]
This crash not happened on 1.6.2 so verify ✅
