### ISSUE TITLE
Enhance dialog to adding private browsing shortcut

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3638]
Visual improvement of the dialog, and shorten the description.  follow up of #3184

**Comment by Jacklin-ux** [comment]
![Add Privacy Browsing Shortcut](https://user-images.githubusercontent.com/22672569/58533717-d32a3f80-821b-11e9-816e-3d447fc1983e.png)

**Comment by Daisy-pliu** [comment]
@Jacklin-ux  if user select [X] (close button) will the result same as user tap [No, thanks] button ?

**Comment by Daisy-pliu** [comment]
private browsing shortcut test case are refactored on  TC0231 ~TC0232

**Comment by Jacklin-ux** [comment]
> @Jacklin-ux if user tap [X] (close button) will the result same as user tap [No, thanks] button ?
Yes. 

Thank you

**Comment by Daisy-pliu** [comment]
verify: ✅
Device: samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Device: redmi4X
Test Build : RC 1.8.0(12867) webview: 75.0.3770.89
