### ISSUE TITLE
Configurable bottom bar items in private mode

### ISSUE THREAD

**Issue by proevan** [mozilla-tw/FirefoxLite#3647]
Since I'm doing the code base structure refactoring, also issue a PR to apply the dynamic bottom bar to private mode pages to make it configurable.

The configuration document is on the [wiki](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config)

**Comment by proevan** [comment]
Two PRs to solve this issue
#3633
#3642

**Comment by Daisy-pliu** [comment]
Test case : 
1. remote nightly config to [{"type":10},{"type":9},{"type":11},{"type":3},{"type":5}]
2 launch app
3. see [private icon] [forward][trash][search] [pin shortcut]
This test will not on full run as this is not a requirement

**Comment by Daisy-pliu** [comment]
Verify: ✅
version :
1.7.0 (12606)
Device:
Samsung 8.0
Test case : [steps](https://github.com/mozilla-tw/FirefoxLite/issues/3647#issuecomment-496866920)
