### ISSUE TITLE
News can not display

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3665]
**Describe the bug**
User in India can not see news as it is  loading forever

**Steps To Reproduce**
1. vpn in India
2. fresh install  NIghtly 1.6.2 (12538)
3. skip onboarding 
4. swipe [up] to see [news]

**Expected behavior**
see [lastest news]

**Actual behavior**
whole page is loading forever

**Screenshots/videos**
![Screenshot_20190531-173040](https://user-images.githubusercontent.com/44990878/58696528-59848400-83ca-11e9-8835-6e1ad9171cab.png)

**Device info (please complete the following information):**
 - Device: pixel 2 (9.0) webview beta:  75.0.3770.40
 - Device: oppo (7.1.1) webview stable: 73.0.3683.90

**Reproduce rate**
6/6

**Additional context**
This issue not happen on release version 1.6.2 (12322)

**Comment by benjamin-cheng** [comment]
I've updated the remote config on Firebase nightly that should resolve this issue.

**Comment by chianger** [comment]
Closed and to be verified.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 1.7.0(12623) RC
test device: samsung 8.0 webview : 74.0.3729.157 and webview beta: 75.0.3770.67
test case: TC0198~TC0202
Note: Test on 1.6.2 (12322) RC as well good to go.
