### ISSUE TITLE
Configurable menu grid items

### ISSUE THREAD

**Issue by proevan** [mozilla-tw/FirefoxLite#3676]
Since I'm doing the code base clean-up. I want to isolate the Menu feature from the MainActivity in following steps:
1. Isolate the code that relates to Menu out from MainActivity
2. Make the Menu items configurable

**Comment by proevan** [comment]
PR #3652

**Comment by chianger** [comment]
#3682

**Comment by Daisy-pliu** [comment]
Verify: ❌
Test steps:
1. remote config on nightly as [{"type":0},{"type":2},{"type":1},{"type":3},{"type":4},{"type":5},{"type":6},{"type":7},{"type":8},{"type":9},{"type":10},{"type":11}]
2. fresh install nightly
3. launch app
4. skip onboarding 
4. tap [menu]

Test version: 1.8.0 (13041)
Test result: crash
Test device: Oppo 7.1.1
Note: crash happens after  fresh install. if user continue use app and tap [menu] it is fine.

**Comment by proevan** [comment]
> Verify: ❌
> Test steps:
> 
>     1. remote config on nightly as [{"type":0},{"type":2},{"type":1},{"type":3},{"type":4},{"type":5},{"type":6},{"type":7},{"type":8},{"type":9},{"type":10},{"type":11}]
> 
>     2. fresh install nightly
> 
>     3. launch app
> 
>     4. skip onboarding
> 
>     5. tap [menu]
> 
> 
> Test version: 1.8.0 (13041)
> Test result: crash
> Test device: Oppo 7.1.1
> Crash report : [crash LiveDataExtension.kt line 18 ](https://console.firebase.google.com/u/0/project/rocketnightly/crashlytics/app/android:gro.allizom.zelda.beta/issues/f61909231b35b4769258de83da933440?time=last-seven-days&sessionId=5D19842C036D0001555AD438E2856CEB_DNE_0_v2)
> 
> Note: crash happens after fresh install. if user continue use app and tap [menu] it is fine and the grid setting are good as exepected.

fixed in #3745

**Comment by Daisy-pliu** [comment]
refer :https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_menu_items
verify: ✅
Test step:[step](https://github.com/mozilla-tw/FirefoxLite/issues/3676#issuecomment-507107809)
Test version: 1.8.0 (13607)
Test result:  see correct menu grid
Test device: Oppo 7.1.1

**Comment by Daisy-pliu** [comment]
add to full run as test case TC0238

**Comment by Daisy-pliu** [comment]
verify: ✅
Test step:[step](https://github.com/mozilla-tw/FirefoxLite/issues/3676#issuecomment-507107809)
Test version: 1.9.0 (13287) nightly
Test result: see correct menu grid
Test device: samsung 8.0
This feature won't need test on production as in this sprint we wont need it releases on production
