### ISSUE TITLE
Release tags are out of order

### ISSUE THREAD

**Issue by mTwTm** [mozilla-tw/FirefoxLite#3685]
Visit https://github.com/mozilla-tw/FirefoxLite/releases and release 1.2.1 comes after 1.4.0

Root cause:

these tags are order by the creation time of tags themselves rather than the creation time of the corresponding commit.

With proper permission, one may want to re-create these tags to reorder them. See:
https://stackoverflow.com/questions/21738647/change-date-of-git-tag-or-github-release-based-on-it

**Comment by chianger** [comment]
@Daisy-pliu   thank you @mTwTm for reporting

**Comment by Daisy-pliu** [comment]
fixed by changing the tag date.
