### ISSUE TITLE
language text not aligned

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3704]
**Describe the bug**

**Steps To Reproduce**
1. fresh install
2.  skip onboarding
3 swipe [up]
4. tap [setting] -> [new language]

**Expected behavior**
see listed lang aligned
**Actual behavior**
see listed lang not aligned

**Screenshots/videos**
![Screenshot_2019-06-19-04-11-50-457_org mozilla rocket](https://user-images.githubusercontent.com/44990878/59716576-d0ce6a80-9248-11e9-96ca-d61d89350bde.png)

**Device info (please complete the following information):**
Redmi 4X (7.12.)
**Version **
RC 1.8.0 (12867)

**Reproduce rate**
10/10

**Additional context**

**Comment by mxlius** [comment]
This language is اُردُو(Urdū), which is written as a right-to-left language. So in Android system, this language alignment to the right is correct.
