### ISSUE TITLE
[Top crash] EnqueueDownloadTask.java line 153 

### ISSUE THREAD

**Issue by benjamin-cheng** [mozilla-tw/FirefoxLite#3723]
Caused by java.lang.IllegalArgumentException
Unknown package: com.android.providers.downloads
android.os.Parcel.readException (Parcel.java:1550)
android.app.ApplicationPackageManager.getApplicationEnabledSetting (ApplicationPackageManager.java:1530)
org.mozilla.focus.download.EnqueueDownloadTask.isDownloadManagerEnabled (EnqueueDownloadTask.java:153)
org.mozilla.focus.download.EnqueueDownloadTask.doInBackground (EnqueueDownloadTask.java:70)
org.mozilla.focus.download.EnqueueDownloadTask.doInBackground (EnqueueDownloadTask.java:26)
android.os.AsyncTask$2.call (AsyncTask.java:292)

https://console.firebase.google.com/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5c28790ff8b88c2963a60ddf?time=last-seven-days&sessionId=5D13C4B1031900013B36070FE3E8CE57_DNE_0_v2

**Comment by Daisy-pliu** [comment]
will keep monitoring this issue on 1.9.0 (13268)
