### ISSUE TITLE
Text too long in the bubble of news category

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3734]
**Describe the bug**
When text is too long (ex: technology) in the bubble of news category, we want to use "…" instead of multiple lines.

**Steps To Reproduce**
1. Swipe up Life feed to see news
2. Press top-right News settings to see news bubble

**Comment by Conjuror** [comment]
Detail will be offline discussion. Prefer to use "..."

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**Test version :** 1.9.0(13268)

**Test step:**
1. launch app
2. vpn in India
3. set font size to big in system
3. swipe [up]
4. tap [life feed setting]

**Test result:**
![Screenshot_20190711-133916_Firefox Lite](https://user-images.githubusercontent.com/44990878/61025113-3f36c080-a3e2-11e9-9973-be40b593f449.jpg)


**Test device:**
Samsung 8.0

**Comment by Daisy-pliu** [comment]
add to test case [TC0242](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B318)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : RC 1.9.1(13361)
Test device:
Samsung 8.0
