### ISSUE TITLE
Network pic is wrong

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#3735]
The illustration should be an outline one, please refer to the spec.
![Spec_firefox lite_content portal_06](https://user-images.githubusercontent.com/4092794/60316330-a09b7000-999c-11e9-99b1-c3df329093bf.jpg)

Asset link: https://drive.google.com/open?id=1-0OzuRPZIkn63c0xrwWt0D5Jgp6bW4S0

**Comment by chianger** [comment]
fixed by #3749 and to be verified

**Comment by chianger** [comment]
to be verified

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**Test version** : 1.9.0(13268)
**Test step:**
1. launch app
2. vpn in India
3. cut off network

**Test result:**
![Screenshot_20190711-134148_Firefox Lite](https://user-images.githubusercontent.com/44990878/61024962-bae43d80-a3e1-11e9-8c96-348e7e24bf47.jpg)

**Test device:**
Samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : RC 1.9.1(13361)
Test device:
Samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : RC 1.9.1(13361)
Test device:
Samsung 8.0
