### ISSUE TITLE
The titles in News content are misalignment

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#3737]
As screenshot below, "Interests" should be left align with "News language"
![Screenshot_20190628-113608](https://user-images.githubusercontent.com/4092794/60316903-3e903a00-999f-11e9-8bd2-56d5aad6bbf6.png)

**Comment by mxlius** [comment]
@TLHuang Where's the spec, please?

**Comment by TLHuang** [comment]
Visual spec link: https://zpl.io/aRznGe0

**Comment by chianger** [comment]
looks fixed to me. to be verified

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.0(13268)
**Test result:**
seems aligned to me
![Screenshot_20190711-133916_Firefox Lite](https://user-images.githubusercontent.com/44990878/61024855-82dcfa80-a3e1-11e9-9595-aa938e8fd0a3.jpg)

**Test device:**
Samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : RC 1.9.1(13361)
Test device:
Samsung 8.0
