### ISSUE TITLE
Text color is not aligned in menu

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#3744]
**Describe the bug**
As title, text color of "MyShots" and "Private tab" is lighter than others.

1.8.0(13041) Nightly

![Screenshot_2019-07-01-11-12-21-037_gro allizom zelda beta](https://user-images.githubusercontent.com/1625148/60408545-f2890380-9bf1-11e9-814f-32e05b681164.png)

**Comment by chianger** [comment]
#3760 merged

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.0(13268)

**Test step:**
1. launch app
2. tap [menu]

**screenshot**
![Screenshot_20190711-132945_Firefox Lite](https://user-images.githubusercontent.com/44990878/61024417-1ca3a800-a3e0-11e9-8e4a-1621d97c48d7.jpg)

**Test device:**
Samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.1(13361)
Test device:
Samsung 8.0
