### ISSUE TITLE
Turbo mode doesn't sync in Settings page and menu

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#3762]
**Describe the bug**
When a user turns off Turbo mode, the Turbo mode icon in menu is still on. Vice versa.

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on Menu
3. Tap on Settings
4. Disable Turbo mode
5. Tap back and trigger menu again

**Expected behavior**
5. Turbo mode is disabled

**Actual behavior**
5. Turbo mode is disabled but the icon is still in blue (on)

**Screenshots/videos**
N/A

**Device info (please complete the following information):**
 - Device: Redmi 5 plus
 - OS: Android 8.1.0
 - Webview 75.0.3770.101
 - Version 1.8.0 (13143)

**Reproduce rate**
5/5

**Additional context**
This is regresison which is not there in 1.8.0 (13128)

**Comment by Daisy-pliu** [comment]
add this scenario to [TC0042](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=H77)

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.0(13268)
**Test Step:**
[step](https://github.com/mozilla-tw/FirefoxLite/issues/3762#issue-464116605)
**Test device:**
Samsung 8.0

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version : 1.9.1(13361)
