### ISSUE TITLE
Ensure Firefox Lite still works when bn locales merge 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3773]
Context: https://github.com/mozilla-l10n/pm-projects/issues/168#issuecomment-509796317

We might want to make sure that Nightly still builds alright, and the auto-import works too.

**Comment by Conjuror** [comment]
Currently impact:
*l10n-repo/bn-ID* to clarify who will make the change. I am expecting l10n to do the merge work.
*app/src/main/res/values-bn-rIN* to modify to *values-bn*. If l10n-repo modified as expected. We should be good at merge it. There's no impacts for working scripts.

**Comment by Conjuror** [comment]
label L10N wanted to keep it tracked
