### ISSUE TITLE
On some devices, the glasses of Logo man will become a box

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#3777]
**Describe the bug**
As title

**Steps To Reproduce**
1. Launch Firefox lite
2. Tap menu and switch to Private mode

**Expected behavior**
An animation of logo man is displayed correctly

**Actual behavior**
Logo man is carrying a box instead of a glasses

**Screenshots/videos**

**Device info (please complete the following information):**
 - Device: Samsung
 - OS: Android 8.0
 - Webview 75.0.3770.101 (Stable)
 - Version 1.9.0

**Reproduce rate**
On specific devices, 5/5

**Additional context**

**Comment by Conjuror** [comment]
![Screenshot_20190712-135413_Firefox Lite Nightly](https://user-images.githubusercontent.com/1625148/61105513-a7ea6f80-a4ac-11e9-94f3-777b65891458.jpg)

Screenshot!!

**Comment by Daisy-pliu** [comment]
verify: ✅
Verison: 1.9.1 (13459) nightly
Test step: [step](https://github.com/mozilla-tw/FirefoxLite/issues/3777#issue-467234734)
Test device: samsung 8.0
