### ISSUE TITLE
use Android Component's System Engine in private Mode

### ISSUE THREAD

**Issue by proevan** [mozilla-tw/FirefoxLite#3782]
In order to have the ability to use GeckoView in the future. We're trying to integrate `System Engine` in private mode as an experimental feature.

**Comment by proevan** [comment]
have to increase the apk size limit from 6.0MB to 6.2MB

**Comment by proevan** [comment]
needs to fix fullscreen bug after migrating to AC interface

**Comment by chianger** [comment]
meta bug.

**Comment by chianger** [comment]
delay merging to after 2.1.17 RC

**Comment by chianger** [comment]
removed from 4-6 backlog and back to ready-for-development
