### ISSUE TITLE
Firefox Lite is Geo-Restricted

### ISSUE THREAD

**Issue by ozbargainq** [mozilla-tw/FirefoxLite#3837]
**Describe the bug**
Firefox lite is limited to certain markets in Google Play.

**Steps To Reproduce**
1. Live in Thailand
2. Have access to Firefox Lite
3. Move to Australia
4. Cannot find Firefox Lite on Google Play

**Expected behavior**
I can find Firefox Lite on Google Play

**Actual behavior**
I cannot find Firefox lite on Google Play.

**Additional context**
How does this align with the [Mozilla Manifesto](https://www.mozilla.org/en-US/about/manifesto/)?

>We are committed to an internet that includes all the peoples of the earth — where a person’s demographic characteristics do not determine their online access, opportunities, or quality of experience.

**Comment by chianger** [comment]
Given limited resource we are not able to expand too quickly. Will definitely expand to more countries soon, but gradually.

**Comment by ozbargainq** [comment]
This is not obvious to me. What effort is required?

Are there non free components to Firefox Lite that are restricted?
