### ISSUE TITLE
Fix the menu bar disappearing in landscape mode

### ISSUE THREAD

**Issue by thequilava** [mozilla-tw/FirefoxLite#3841]
The menu bar at the bottom disappears as I switch to landscape mode on my Lenovo tab410

Landscape Mode
![Screenshot_2019-11-15-15-19-11-187](https://user-images.githubusercontent.com/49340559/68933741-571cb780-07bb-11ea-8043-9ff0f3c262c3.jpeg)
Portrait Mode
![Screenshot_2019-11-15-15-18-57-872](https://user-images.githubusercontent.com/49340559/68933796-7287c280-07bb-11ea-9dcd-00c1d2abfef4.jpeg)

**Comment by chianger** [comment]
This is by design

**Comment by chianger** [comment]
Will fw to UX/PM to consider
