### ISSUE TITLE
Add Top-news category to the first tab (Outside of IN/ID)

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3842]
Please refer to the [spreadsheet](https://docs.google.com/spreadsheets/d/1dxh0HDGwoGqaCGtHvM5eHB0uQ0OT9u-YxgX5wW9bAJ0/edit#gid=0) to add the rss to "Top-news" category (for the countries using google news rss)

**Comment by Jacklin-ux** [comment]
Talked to BI team, following current telemetry.

**Comment by chianger** [comment]
metrics review needed

**Comment by cnevinc** [comment]
working on it

**Comment by Conjuror** [comment]
build 17478
