### ISSUE TITLE
Data review

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3844]
Dependency of mozilla-tw/mango#87  , we will need to have data steward reviewing FxLite 2.0 changes:
1. Batch review of new pings across verticals
2. Update the telemetry wiki
https://github.com/mozilla-tw/FirefoxLite/wiki/Telemetry#install-campaign-tracking

**Comment by chianger** [comment]
Per grooming meeting, let's do it into small batches so that sprint by sprint we can finish some.

Side note: this task needs BI team support to file the questionnaire

**Comment by chianger** [comment]
It's in progress in current sprint

**Comment by weslyhuang** [comment]
Data review request for verticals (News, Game, Shopping, Travel) is tracked in #4564

**Comment by chianger** [comment]
MSRP in #4589

**Comment by chianger** [comment]
platform in https://github.com/mozilla-tw/FirefoxLite/issues/4576

**Comment by chianger** [comment]
I'm closing this since #4564 #4589 and #4576 are all closed.
