### ISSUE TITLE
[US-GAME-009] (context-menu) know how I can share games and create shotcuts of games

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3855]
As an end user,
I would like to know how I can share games and create shortcuts of games.

https://mozilla.invisionapp.com/share/32TCHJV7BGJ#/screens/377829706  
see p.14 contexual hint

AC: show the hint if the user plays the same game over 3 times.

**Comment by weslyhuang** [comment]
closed by #4374
