### ISSUE TITLE
MSRP Rewards font seems inconsistent with fonts used elsewhere in the app

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3861]
https://drive.google.com/file/d/1xZKA3RN2t_meFddZ-_sPxYDWGFj4s9gB/view?usp=sharing

**Comment by Daisy-pliu** [comment]
verify: ✅
version :  17368 prod
![Screenshot_20191206-101241](https://user-images.githubusercontent.com/44990878/70289908-3fac7980-1811-11ea-95c8-91eb1c74e7c2.png)
