### ISSUE TITLE
Forcing app version update - MSRP

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3864]

**Comment by Jacklin-ux** [comment]
UX spec link: https://mozilla.invisionapp.com/share/YAUWB72PRQU

**Comment by joechengla** [comment]
Telemetry https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947

**Comment by cnevinc** [comment]
Telemetry is not ready since BI team has not added the actual event that we need.
PM still wants this to be done in this sprint.
Without a clear Telemetry definition, this task is still at risk.

**Comment by Daisy-pliu** [comment]
**Scenario:**
1. If user's app version higher than min_version it should not show popup 
2. If user's app version lower than min_version it should not show popup  
3. When user tap update and user has Playstore app, it should bring user to Playstore 
4. When user tap update and user has Playstore app, it should bring user to link from remote config.
 
We can Set up target version in Admin Page
1. min_version 
2. Min Version Dialog Image   
3. Min Version Dialog Title 
4. Min Version Dialog Message

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version : 17290 Nightly
**step:**
1. create mission with min_version 17314
2. launch app with older version 17290
3. tap [gift] -> [mission]-> [i'm join]
4. tap [X]
5. tap [gift] -> [mission]-> [i'm join]

**Result:**
3.5. see update popup 

<img src="https://user-images.githubusercontent.com/44990878/70136351-cc96ec00-16c6-11ea-809e-8c2708c35538.png" width="200" /> <img src="https://user-images.githubusercontent.com/44990878/70136352-cc96ec00-16c6-11ea-9ff8-bfdf87103570.png" width="200" />



**Scenario**
1. If user's app version higher than min_version it should not show popup ✅
2. If user's app version lower than min_version it should not show popup  ✅
3. When user tap update and user has enabled Playstore app, it should bring user to Playstore ✅  
4. When user tap update and user disable Playstore app, it should bring user to link from remote config. ✅ 
4.1  after user tap [gift] -> [mission], see pic as below
<img src="https://user-images.githubusercontent.com/44990878/70137131-4085c400-16c8-11ea-8f53-98377e47f351.png" width="200" />

**Comment by Daisy-pliu** [comment]
**Note:** 
this feature can directly benefit user with app version higher than 17290 to join old mission by updating old mission's database.

Add new Test case to MSRP : MSRP039- MSRP040

**Comment by Daisy-pliu** [comment]
production remote config is setup for Force update
{str_apk_download_link= "https://mozilla-next.com/eng/firefox_lite"}

**Comment by elin-moco** [comment]
Also Telemetry verifyed on Firebase

**Comment by Daisy-pliu** [comment]
can not test on production as it will not turned on for this release so tested on nighlty only.
