### ISSUE TITLE
Travel content uploading - PM side

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#3865]
Three related tasks, this issue is used to track (1)

(#3865) 1. Travel PM needs to know how to manually upload curated travel content if there is any.
(#3860) 2. Dev needs to set up a way for PM to upload (e.g., web page for upload) 
(#3862) 3. Dev needs to implement the backend API for travel front end to fetch content.

**Comment by tinahsieh** [comment]
Please see the draft spec and content sheet here: https://docs.google.com/spreadsheets/d/1SqGftat12-haRWb_6js_dnJ_LnyLiFWAu93MNSRhUfs/edit?usp=sharing

**Comment by weslyhuang** [comment]
Tina has done the upload practice to nightly
