### ISSUE TITLE
Expand to more countries (wave2)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3866]
Scope: to be defined

**Comment by chianger** [comment]
Country list planning in doc https://docs.google.com/spreadsheets/d/158cUp0L1YhsNQkwdKcG8HBlqsb6Y9r9Gc9ZtjBDlqTw/edit#gid=650097059 (permission required)

**Comment by chianger** [comment]
RelMan efforts as well for store listing and config.

**Comment by weslyhuang** [comment]
for wave#2 (English only), all vertical config will simply follow the setting of wave#1 RoW except Game, which is still to be confirmed. @Mozillove

**Comment by weslyhuang** [comment]
add RM as assignee since we expect RelMan efforts for store listing and config.

**Comment by Mozillove** [comment]
After confirming with Charles, we are allowed to use all the HTML5 games from our 4 partners (Gamezop/Gameloft/Atmegame/FRVR) in all countries. Thanks.

**Comment by weslyhuang** [comment]
per talk with Joe, the latest plan is to open those countries in batches, and @joechengla is working with with Marketing team to decide the countries for each phase. will be updated here (permission needed):

https://docs.google.com/spreadsheets/d/158cUp0L1YhsNQkwdKcG8HBlqsb6Y9r9Gc9ZtjBDlqTw/edit#gid=650097059

**Comment by weslyhuang** [comment]
@joechengla pls help confirm the list is finalized by 2pm today, tks

**Comment by chianger** [comment]
It was done
