### ISSUE TITLE
Upload images

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#3867]
**User story**
As a content editor, I would like to upload images and generate URLs for putting on the backend sheet so that the image can be presented on Firefox Lite.

**Additional context**
Use case 1:  Cities on travel home
Image library: https://drive.google.com/drive/folders/1DfEnMiENImyw3Xf2hfoj7QYzUan65hmt?usp=sharing

**Comment by tinahsieh** [comment]
Thank you Linear for the big support on this!
I can upload the image now.

One more question: In which stage will the image be downsized for mobile phones? Currently, the largest image can be around 6mb.

**Comment by niyali** [comment]
> Thank you Linear for the big support on this!
> I can upload the image now.
> 
> One more question: In which stage will the image be downsized for mobile phones? Currently, the largest image can be around 6mb.

offline discussion result: Tina will downsize the pictures then upload. 

Thanks Tina.

**Comment by weslyhuang** [comment]
closed per the conclusion above.
