### ISSUE TITLE
Support Deeplinks 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3871]
https://docs.google.com/spreadsheets/d/1YIjtAFvDqBTbMTE-TFdeHWxxi-ur5_tQJe2X5KIE5_E/edit#gid=0

User Story
---
As Mozilla, I want to support deeplinks so that users can click a link then direct them to a specific page in browser. (See excel for use cases)

Metrics
---
- CTR (from "display of message" to "user taking action to tap on msg" to "interact with the deeplink"

**Comment by chianger** [comment]
Scope for this ticket: P1 CTAs in the sheet https://docs.google.com/spreadsheets/d/1YIjtAFvDqBTbMTE-TFdeHWxxi-ur5_tQJe2X5KIE5_E/edit#gid=0

**Comment by joechengla** [comment]
Telemetry https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947

**Comment by Jacklin-ux** [comment]
No UI request. UX has been defined in the telemetry.

**Comment by chianger** [comment]
still need metrics review

**Comment by Jacklin-ux** [comment]
I added UX flow here for using deeplink to vertical tab.
- "Open (URL) in specific vertical's Content Tab, tap system back key then direct to its vertical hub"

**Comment by chianger** [comment]
Can we create multiple tickets for different use cases so that this won't be a too big scope bug.
Use case means: Trigger/ Deeplink combination#1, #2, ...etc.

**Comment by chianger** [comment]
this is meta bug and since we have separate issues to track individually, we can close it.
