### ISSUE TITLE
Logoman banner remote config

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3873]
https://docs.google.com/spreadsheets/d/1YIjtAFvDqBTbMTE-TFdeHWxxi-ur5_tQJe2X5KIE5_E/edit#gid=0

User Story
---
As Mozilla, we would like to be able to remote config logoman "icon, title, description, call to action links (deeplink or URL)" so we can drive "specific" users to take specific action we want.

Metrics
--- 
- CTR (from "display of message" to "user taking action to tap on banner" to "interact with the deeplink/URL"

**Comment by joechengla** [comment]
Telemetry https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947

**Comment by Jacklin-ux** [comment]
For UI design, please see [the link](https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e?seid=5d5f4df62ffb679bba9a4f6e)

**Comment by chianger** [comment]
Scope, (Use cases) to be defined.

**Comment by lanyliu** [comment]
telemetry spec 
please refer to [spec](https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947) row 20-27

**Comment by lanyliu** [comment]
detail tasks
https://github.com/mozilla-tw/FirefoxLite/issues/4445
https://github.com/mozilla-tw/FirefoxLite/issues/4447
https://github.com/mozilla-tw/FirefoxLite/issues/4448

**Comment by chianger** [comment]
> Scope, (Use cases) to be defined.

Use cases defined in the sheet (P1s):
https://docs.google.com/spreadsheets/d/1YIjtAFvDqBTbMTE-TFdeHWxxi-ur5_tQJe2X5KIE5_E/edit#gid=0

**Comment by shsu571** [comment]
@Jacklin-ux  will put all UI spec here and confirm with @proevan

**Comment by Jacklin-ux** [comment]
For UI design, please see the link

**Comment by proevan** [comment]
only needs to make imageUrl as an optional parameter

**Comment by Conjuror** [comment]
18876
