### ISSUE TITLE
(Travel) city search redesign

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3874]
Some obligation alignment. Not sure what the scope is yet.

**Comment by tinahsieh** [comment]
Updated design in the spec: https://mozilla.invisionapp.com/share/EWSX97EB69J#/374206200_1-2_Search_for_a_city

We'll got a final confirmation from legal by tomorrow to see if we're allowed to replace "enter" by "done".

**Comment by Conjuror** [comment]
When tapping a unexist city, there will have no search suggestion.

At least, search the unexist city from Google should be suggested.
