### ISSUE TITLE
[US-Platform-022] Remote Config: enable Firebase in-app message

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3875]
As Mozilla, 
I would like to enable Firebase in-app message,
so that i can create more contexual msgs with flexibility

Acceptance criteria:

    support followup actions to deeplinks mozilla-tw/mango#63 and mozilla-tw/mango#82

**Comment by joechengla** [comment]
Telemetry https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947

**Comment by joechengla** [comment]
use Firebase default UX/UI

**Comment by chianger** [comment]
> As Mozilla,
> I would like to enable Firebase in-app message,
> so that i can create more contexual msgs with flexibility
> 
> Acceptance criteria:
> 
> ```
> support followup actions to deeplinks mozilla-tw/mango#63 and mozilla-tw/mango#82
> ```

Elaboration on the scope:
1. Deep link to MSRP home
2. Deep link to verticals (news, shopping, games)

**Comment by joechengla** [comment]
refer to Column G "P1" for deekplinks for the initial implementation
https://docs.google.com/spreadsheets/d/1YIjtAFvDqBTbMTE-TFdeHWxxi-ur5_tQJe2X5KIE5_E/edit#gid=0

**Comment by proevan** [comment]
Since every user will only receive one in app message per day.
Please also help to test if it works fine for mutable days

**Comment by proevan** [comment]
note: in app message will be postpone when home page onboarding is showing
