### ISSUE TITLE
Telemetry for travel 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3876]
https://docs.google.com/spreadsheets/d/1UinEVG2trRLeUoHtB-5lvLtUr3oFWCWT8Wh_osSAGmM/edit#gid=888392947

**Comment by elin-moco** [comment]
@benjamin-cheng @chianger @lanyliu 
Please remember to include travel vertical when sending these events to adjust:

 - StartContentTab vi0mil
 - StartVerticalProcess sg1h39

**Comment by benjamin-cheng** [comment]
@elin-moco yes, these two are shared events along with other verticals, confirmed it will also send to Adjust.
