### ISSUE TITLE
Offer personalized news

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3899]

**Comment by weslyhuang** [comment]
still in UX design, add the "feature" label so be excluded from daily launch-blocker(P0) scanning.

**Comment by Jacklin-ux** [comment]
Telemetry Spec: https://docs.google.com/spreadsheets/d/1NJ-EwtMq3pmSisk6ZCLHH8u1kHQVHHVGu6qfvXOtS7I/edit#gid=888392947

**Comment by Jacklin-ux** [comment]
UX spec: https://mozilla.invisionapp.com/share/NKVBXOSTD4G#/398463806_0-0_Cover
Visual design: 
https://sketch.cloud/s/15xy8/a/oExmGQ
https://sketch.cloud/s/15xy8/a/RrqJ0Z

**Comment by chianger** [comment]
size XL; this is 2-sprint efforts

**Comment by FinnickC** [comment]
And here is the Language entry page with no internet scenario.
UI Spec
https://zpl.io/blAGKX5

**Comment by Jacklin-ux** [comment]
Dailyhunt logo.svg (shared from partner): https://drive.google.com/file/d/11BZHFj2FxJl6rh8ThVCDBvHr4PT5tTaE/view?usp=sharing

**Comment by chianger** [comment]
Carried over to next sprint per discussion.
This is XL which we expected as 2-sprint task

**Comment by Daisy-pliu** [comment]
based on [Slack msg](https://mozilla.slack.com/archives/G5QBPEK4J/p1579256633013500?thread_ts=1579251909.007500&cid=G5QBPEK4J) it is being tested on Nighlty
