### ISSUE TITLE
Open banners in different modes: Game mode, Content tab, Play store

### ISSUE THREAD

**Issue by Mozillove** [mozilla-tw/FirefoxLite#3905]
**User story**
As a user, after tapping on the banner, I would like to open a game in the Content Tab for a better gaming experience (Full screen mode, recently played list, etc), and open a website in a normal browser tab. 

**Acceptance Criteria (how do I know when I’m done?)** 
1. If it's a game, open it in the Content Tab (All the features and interactions should be exactly the same as how you play other games from cards.)
2. If it's a website, open it in a normal browser tab

**Additional context**
It may require some works in the backend, and also extra data in JSON files.

**Comment by Mozillove** [comment]
Set this feature request as P0 and update the UX Spec here:
https://mozilla.invisionapp.com/share/32TCHJV7BGJ#/395135634_5-0_Banner
Thank you!

**Comment by weslyhuang** [comment]
need to confirm metrics design (with BI) and feasibility (with Dev) before moving to "Ready for Dev"

**Comment by Mozillove** [comment]
Metrics checked! Waiting for comments from Dev team. Thanks.

**Comment by chianger** [comment]
backend input needed

**Comment by weslyhuang** [comment]
still in UX design, add the "feature" label so be excluded from daily launch-blocker(P0) scanning.

**Comment by chianger** [comment]
dup of #4483
