### ISSUE TITLE
If a shopping site have a bottom navigation bar, it will be blocked by the Shopping Search prompt

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#3907]
1. Go to 露天, momo, pchome websites
2. All those websites have bottom navigation bar
3. See the Shopping search prompt blocking the navigation bar

![image](https://user-images.githubusercontent.com/8919308/67657233-26521b00-f991-11e9-93aa-13a55c60891e.png)
![image](https://user-images.githubusercontent.com/8919308/67657242-294d0b80-f991-11e9-90eb-8bd44e41e70f.png)
![image](https://user-images.githubusercontent.com/8919308/67657246-2c47fc00-f991-11e9-9cdf-f7e825dfae90.png)

**Comment by weslyhuang** [comment]
still in UX design, add the "feature" label so be excluded from daily launch-blocker(P0) scanning.

**Comment by youwenliang** [comment]
here's the updated spec -> https://mozilla.invisionapp.com/share/DQV8E0SFWS9#/377799453_1-3_Shopping_Search_Prompt_Message

@benjamin-cheng let me know which part you have concerns and we can discuss further, thanks!

**Comment by shsu571** [comment]
**Prompt Appear**
First  5 times to get into certain website -> will show the prompt
Depends on engineer effort

**Prompt disappear**
User closed -> will not show again
Clicked the “search” button -> -> will not show again
User left certain website -> will disappear automatically ( current)

**Telemetry**
Click Tab Swipe drawer
Add event: 
Show Tab Swipe drawer

**Comment by elin-moco** [comment]
The Telemetry spec for Show Tab Swipe Drawer is here:
https://docs.google.com/spreadsheets/d/1YcDo5jViGpwrrR1e1akHpkAXzXsGaN92DVqP9T3QMhE/edit#gid=888392947&range=F10

**Comment by chianger** [comment]
adding back the need metrics label. once dev confirm the telemetry can be implemented, please go ahead and remove it and move the ticket tor ready for development

**Comment by benjamin-cheng** [comment]
@elin-moco could you help to confirm that the feed value is the same as `Click Tab Swipe Drawer` event? which is the shopping site title

**Comment by elin-moco** [comment]
@benjamin-cheng we confirm that the feed value is the same as ```Click Tab Swipe Drawer```
Thank you!

**Comment by Daisy-pliu** [comment]
QA team has developed test case : SHOP019, SHOP37

**Comment by yshlin** [comment]
Show Tab Swipe Drawer is verified correct on Firebase DebugView

**Comment by Daisy-pliu** [comment]
verify:✅
version: 2.1.8 (18628)
Test case: [SHOP037](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C213). [SHOP019 ](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C212)

**Comment by Daisy-pliu** [comment]
verify:✅
version: 2.1.9 (18628) release
Test case: SHOP037. SHOP019
