### ISSUE TITLE
Back Up User Data on a Daily Basis - MSRP

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3909]
We need to back up our database on a daily basis.
Otherwise, we are exposed to the risk of
1. Lose our customer data if DB is compromised.
2. Can't track the user behavior if the log didn't provide enough information.
3. Can't rollback to a certain date if there's a bug/logic error that breaks the user data.

**Comment by chianger** [comment]
Linear working on: Firebase -> Google cloud storage  @niyali can confirm if this is done?
Wendy working on: Google cloud storage -> bigquery (need to do by manual everyday, bg transfer doesn’t support this kind of data dump )

**Comment by Daisy-pliu** [comment]
same as #4418
