### ISSUE TITLE
Add a link and web page for the voucher terms of use 

### ISSUE THREAD

**Issue by Mozillove** [mozilla-tw/FirefoxLite#3912]
**User story**
As a users, I would like know the policy of using the voucher.

Zeplin (UI): zpl://screen?pid=5d3e6ee752e9500d60e1f07e&sid=5d64cfbadd6f4cb2bf6b8f50
Spec (UX): https://mozilla.invisionapp.com/share/UJTEW95EZVF#/screens/392556719

Thank you!

**Comment by chianger** [comment]
https://github.com/mozilla/legal-docs/pull/1383  PR for legal doc in position to be reviewd

**Comment by Daisy-pliu** [comment]
slack discussion in : https://mozilla.slack.com/archives/CKBBTTUAD/p1574147903021700
Since this workaround will affect test case MSRP034, this test case is changed accordingly.

**Comment by chianger** [comment]
> [mozilla/legal-docs#1383](https://github.com/mozilla/legal-docs/pull/1383) PR for legal doc in position to be reviewd

merged. now i'm requesting localization

**Comment by chianger** [comment]
Link change so new PR here https://github.com/mozilla/legal-docs/pull/1385
It was merged, but I have to update all localized files once we have those translated.

**Comment by chianger** [comment]
Still need this https://github.com/mozilla/bedrock/pull/8229 to make the website publish

**Comment by chianger** [comment]
merged
