### ISSUE TITLE
Setting up probes & alarm for backend

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3913]
**User story**
As a system admin, I'd like to know if the design work as expected. For example
1. There are too many users been suspended
2. There are too many users fail to redeem
3. There are too many users fail to join missions
4. There are too many users fail to bind their firefox account
5. There are too many users fail to get the mission list
6. News data never refresh ( News sources are down?)
7. Users always get empty vertical data ( either shopping/games/news)
8. It took too long to join a mission
9. It took too long to redeem a reward.
10. It took too long to fetch the content.......

**Acceptance Criteria (how do I know when I’m done?)** 
1. When any of the above happened, the project owner will get an email notification.
2. The project owner can get a weekly report about the trend above

**Additional context**
The product team needs to decide the priority of above. So engineers can prioritize and set them up.

**Comment by weslyhuang** [comment]
need https://github.com/mozilla-tw/FirefoxLite/issues/4362 first
