### ISSUE TITLE
Re-test MSRP after we have multiple instances

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#3917]
**Describe the bug**
We have 8 GAE instances by default.
Need to re-test MSRP flow to make sure all APIs are stateless and will work as expected.

**Additional context**
I believe this should not be a problem. But it's better we double-check it again.

**Comment by Daisy-pliu** [comment]
Can only test admin page on prod as MSRP not release on prod yet.
verify: ✅
Frontend version: 17097
Backend version: prod 0.16
Test: 
1.use can log into MSRP Admin Page
