### ISSUE TITLE
Create Indonesia for MSRP in Firebase

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#3922]
Firebase Production needs to create Indonesia in Firestore
Group: Indonesian users

**Comment by Daisy-pliu** [comment]
@shsu571 @ChenMorpheus @Mozillove 
just let you know today I checked this "groupIndo" is not there anymore as Firestore does not accept empty collection.
So please remember to add this collection when you have missions in hand and add the missions under this collection.
