### ISSUE TITLE
Remove JD from product

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3923]
Scope:
1. in product default: top sites 
2. in product default: shopping search

And remote config for above two. 

@Jacklin-ux @joechengla we need updated topsite list and shopping search list accordingly.
https://docs.google.com/spreadsheets/d/1p52CgIdA9PMNGY4X0keLVq21AzNOg_yo2Qk-_ULVAtM/edit?ts=5d410e53#gid=1225379349

**Comment by Daisy-pliu** [comment]
verify:✅
version: 17097 release 
Confirmed Jd.ID is removed on Production.

**Comment by Conjuror** [comment]
confirmed
