### ISSUE TITLE
Smart Shopping Search - support market detection by SIM

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3924]
so the experience across various features will be market consistent before the first app re-launch.

**Comment by Daisy-pliu** [comment]
Need Testing with Indo and India SIM on Nighlty and Prod.

**Comment by Daisy-pliu** [comment]
This ticket is not using SIM anymore as we decide to use remote config only, in other words it is  descoped.
PMs @shsu571 @youwenliang  please check the scope of this ticket and make sure the purpose matched the title and the scope is documented after eng and PM reach consensus, thank you.

**Comment by Daisy-pliu** [comment]
verify:✅
version:2.0.3(17079) nighlty
Use remote config to see Indo ,India shopping search sites.

**Comment by Daisy-pliu** [comment]
verify:✅
version: 2.0.3(17097) release
Use remote config to see Indo ,India shopping search sites.
