### ISSUE TITLE
Refine strings

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3937]
The english translation here is a little awkward. Would suggest something like:

“Remain Fast and Lightweight”
^ This isn’t a sentence and fast and lightweight don’t need to be capitalized unless it’s a headline. 

Maybe something like:
“Lite is still just as fast and lightweight!”

“We added smart shopping search”
Think this needs a “we have added…”

<img width="212" alt="Screenshot 2019-10-23 at 4 11 45 PM" src="https://user-images.githubusercontent.com/22672569/67372183-11037800-f5b0-11e9-8bb9-d67b6fad4753.png">

**Comment by chianger** [comment]
to be verified
