### ISSUE TITLE
Push notification support image push

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#3938]
We are planning pushing news notification to India users, but currently can push just text but can't push text with image.

**Comment by chianger** [comment]
scope to be defined since it varies on efforts: whether support cases when app isn't in "recent apps"

**Comment by chianger** [comment]
scope clarified: we can live with this to work only when app is in recent apps.

**Comment by lanyliu** [comment]
For the purpose of this feature, no extra definition for telemetry.

Please note that we'll need metrics when we run experiment different types of display on message (with image vs. w/o image), and will according to the purpose define telemetry spec at that moment.

**Comment by weslyhuang** [comment]
expect to get the outsourcing team's help with this.

**Comment by weslyhuang** [comment]
will rely on @benjamin-cheng to decide to priority for outsourcing to work on.

**Comment by weslyhuang** [comment]
firebase related, may not suitable for outsourcing.

**Comment by chianger** [comment]
Per discussion with @Jacklin-ux , he understands that we have limited bandwidth. Ok to defer to next sprint.

**Comment by benjamin-cheng** [comment]
@shsu571 , @Jacklin-ux FCM has supported the push notification with image. Could you help to check if it's already fulfilled what you requested? Thank you!

<img width="789" alt="截圖 2020-02-11 下午12 03 38" src="https://user-images.githubusercontent.com/7045016/74210515-038d0d80-4cc7-11ea-9f8c-ff9ae53e0f40.png">

![device-2020-02-11-120303](https://user-images.githubusercontent.com/7045016/74210525-10a9fc80-4cc7-11ea-8198-d5f496d1b99c.png)

**Comment by shsu571** [comment]
I think this is already okay! (confirmed with Cynthia and Jack)
But I can't find the document in the firebase about image restriction, do you have related document? I tried 1:1 and 16:9 are all work! Thx!

**Comment by shsu571** [comment]
@benjamin-cheng  provided : https://documentation.onesignal.com/docs/android-customizations#section-big-picture
need to recode on the notification doc

**Comment by benjamin-cheng** [comment]
Thanks @proevan reminding, we still need to do extra work to correctly show the image push notification when app is in the foreground. I just add a PR #4702 for that.

**Comment by Conjuror** [comment]
18628
