### ISSUE TITLE
Youtube video playing feature in private mode is abnormal.

### ISSUE THREAD

**Issue by Jack-king-1** [mozilla-tw/FirefoxLite#3940]
**Describe the bug**
Youtube video playing feature in private mode is abnormal.

**Steps To Reproduce**
1. Go to private mode and open youtube.
2. Click on any video and full screen.
3. Tap full screen again.
4. The video shows black screen.

**Screenshots/videos**
![20191007_132502](https://user-images.githubusercontent.com/56010545/66286955-49475d00-e906-11e9-91d7-592ca96c1817.gif)

**Device info (please complete the following information):**
 - Device: OPPO R11s Plus
 - OS: Android 7.1.1
 - Webview 78.0.3904.43 beta
 - Version 2.0.0(16164).beta

**Reproduce rate**
5/5

**Additional context**
1. Android 6~9 all have this issue.
2. In Android 6 , both private and normal mode have this issue.

**Comment by Jacklin-ux** [comment]
The situation in my device looks fixed.

2.0.2(16855)
Android 10
Pixel3

**Comment by joechengla** [comment]
same for me 
QAwanted!

**Comment by joechengla** [comment]
moving to p2 as we can't reproduce

**Comment by Jack-king-1** [comment]
Verify pass.
Samsung Galaxy S6 , Android 6.0.1 , 2.0.2(16977)
OPPO R11s Plus , Android 7.1.1 , 2.0.2(17050)
Samsung Galaxy S7 , Android 8.0.0 , 2.0.2(17050)
Pixel XL , Android 9 , 2.0.2(17045)
