### ISSUE TITLE
[US-MSRP-007] notification: Be able to notify users about an ongoing challenge	

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#3965]
as a: Player
I want to: Be able to notify users about an ongoing challenge
so that I can: avoid becoming unqualify for the challenge

Per ENG breakdown this item is categorized as pure UI work (backend part to be implemented by other tasks), which will be done by outsourcing team.

**Comment by weslyhuang** [comment]
reopened thus remove P0 for PM to triage

**Comment by Daisy-pliu** [comment]
This feature needs staging 0.16 in place.

**Step**
1. enable Debug mission reminder notification  
2. Join mission 
3. wait 15min 
4. tap notification

**Test/Actual result:**
3. see notification
4. see home page


**version :** 
BE: Nighlty0.16 
FE: 17079

![Screenshot_20191120-174610](https://user-images.githubusercontent.com/44990878/69227956-b153b900-0bbd-11ea-98da-373810f926af.png)
