### ISSUE TITLE
Add description on Shopping Search (price comparison)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3977]
To make it clear to users that using such search is user's choice.
Dependency: asset and l10n

**Comment by weslyhuang** [comment]
expect to get the outsourcing team's help with this.

**Comment by weslyhuang** [comment]
will rely on @benjamin-cheng to decide to priority for outsourcing to work on.

**Comment by benjamin-cheng** [comment]
Confirm with @youwenliang, we need to keep the onboarding message on the top (won't disappear after the second-time visit). Need @youwenliang to confirm the string modification part.

**Comment by youwenliang** [comment]
@benjamin-cheng Confirm with Wendy, we will keep the string as it is now, so we only need to keep the onboarding message even after the second-time visit. Thanks!

**Comment by Daisy-pliu** [comment]
verify:✅
version: 17545
steps:
1. launch app 
2. tap [shopping search icon]
3. search [bag] -> tap [enter]
4. tap [shopping search icon]

**Result:**
2. see [find great prices]
4. still see [find great prices]

Modify Test case : SHOP017

**Comment by Daisy-pliu** [comment]
verify:✅
version: 2.1.0 releas(17658)
