### ISSUE TITLE
Update Google Developer API for Nightly

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4348]
**Describe the bug**
From December 1 2019, versions 1 and 2 of this API will no longer be available, and any calls to these versions will fail. Update to version 3 before this date. 

**Actions**
1. Check with Bitrise if they update to API version 3

**Risk**
If Bitirse failed to do it , our Nightly could not auto publish on Playstore

<img width="1373" alt="Screen Shot 2019-11-20 at 10 04 55 AM" src="https://user-images.githubusercontent.com/44990878/69204442-e0e4d000-0b81-11ea-82e1-abfa352b3260.png">

**Additional context**

**Comment by Daisy-pliu** [comment]
RE has updated version 3.0.0 in "Deploy to Google Play" CI step so now it is using latest API to upload app on Play Store Console. 
Need to monitor if the PlayStore console keeps alerting.

**Comment by Conjuror** [comment]
According to the code base, it's using publish API v3 now. But we still have the alert in the banner of Play Console. Let's wait one more day to observe it.
https://github.com/bitrise-steplib/steps-google-play-deploy/blob/master/publish.go#L12

**Comment by Conjuror** [comment]
The banner is removed now on Play Console. I think we are good with it. :)
