### ISSUE TITLE
Update link inside PN to the proper Sumo Page

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#4357]
https://www.mozilla.org/en-US/privacy/firefox-lite/

Content & Services: The Firefox Lite Content & Services is non-personalized localized news, games, deals and more offered by our partners in certain countries. In some cases, when you click on suggested content, we will notify the third-party content owner their content was found on Firefox Lite, but not who found it. See "HERE" for more details.

HERE should be updated to https://support.mozilla.org/en-US/kb/firefox-lite-content-and-services

**Comment by chianger** [comment]
https://github.com/mozilla/legal-docs/pull/1385 PR in legal repo now.

**Comment by chianger** [comment]
ready to be verified
