### ISSUE TITLE
Add Youtube server key and client key to Firestore

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4358]
**Describe the bug**
travel needs to access Youtube API so we need 2 keys,
1 key to communicate with Youtube server from our backend.
1 key for client side communicates with our backend.

**Steps To Config**
1. Enable Youtube API 
2. add server key to Firestore
3. add android key to Firestore

**Env info**
Backend version: nightly 0.16
 
**Additional context**

**Comment by weslyhuang** [comment]
P0 as this is for Travel, and done already by Daisy.

**Comment by Daisy-pliu** [comment]
Release team has added the key into Firestore, but need testing

**Comment by Daisy-pliu** [comment]
verify:✅
version : 0.17 nightly
test step: admin UI is good
