### ISSUE TITLE
Need a confirmation dialog that asks users to confirm before leaving missions

### ISSUE THREAD

**Issue by Mozillove** [mozilla-tw/FirefoxLite#4361]
**User story**
As a user, I would like to know the consequence of leaving a mission.

**Acceptance Criteria (how do I know when I’m done?)** 
Follow the UX spec:
https://mozilla.invisionapp.com/share/UJTEW95EZVF#/screens/378556608

Add the dialog:
All your progress will be deleted? Are you sure?
[Cancel] [Leave]

**Comment by weslyhuang** [comment]
@Mozillove I assume you wanna bring this to grooming?

**Comment by Mozillove** [comment]
Yes. Sorry that I forgot to add this to the project. Thank you again!

**Comment by weslyhuang** [comment]
need to confirm metrics design (with BI) and its feasibility (with Dev) before moving to "Ready for Dev"

**Comment by Mozillove** [comment]
Already confirmed with BI and Dev team. Should be ready to be moved to "Ready for Dev". Thank you!

**Comment by Daisy-pliu** [comment]
verify:✅
version: 17545
steps:
1. launch app 
2. tap [gift]
3. tap [mission] -> [join] 
4. tap [leave mission] to see dialog popup
5. tap [quit] to back mission list page

Note : Modify test case MSRP012
![Screenshot_20191217-135547](https://user-images.githubusercontent.com/44990878/70968913-7cac2200-20d5-11ea-86a2-0bf0e114f843.png)

**Comment by Daisy-pliu** [comment]
verify:✅
Version: nighlty (17646 )
![Screenshot_20191220-120342](https://user-images.githubusercontent.com/44990878/71229679-790cdb00-2321-11ea-93c9-028564a8da02.png)
