### ISSUE TITLE
Backend Metrics Refinement

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#4362]
The backend also needs a mechanism like "telemetry-wanted" in the Android app.

The current design can poorly support the log-based metrics [needs](https://docs.google.com/document/d/1z-jRBZbxhKicAWaOEPdnHcqZHdDCVTDKOe2EOG6LmXo/edit). But it is super time-consuming. 
Because we'll need to match the log message scattered in the codebase. 

Adding something like error/reason code like this will help
https://github.com/mozilla-tw/mango_backend/pull/130/files

**Comment by weslyhuang** [comment]
need to do this before https://github.com/mozilla-tw/FirefoxLite/issues/3913
