### ISSUE TITLE
Wave2 cross functional tasks: SUMO, PN, ...etc

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4363]
Meta bug for wave2/travel

**Comment by tinahsieh** [comment]
Need to update:
1. SUMO
2. Privacy Notice
3. Terms

**Comment by weslyhuang** [comment]
per the discussion in grooming, we don't plan to initiate another round of SecReview given the scope of backend change for wave#2.

**Comment by tinahsieh** [comment]
Please see the updated privacy notice here: https://docs.google.com/document/d/1SzE6XLWr10g6GGhjceSMftYJv5PH7k7byWT-2-BUg3c/edit

**Comment by weslyhuang** [comment]
PN is update and l10n-ed here: https://github.com/mozilla/legal-docs/tree/master/firefox_lite_privacy_notice

**Comment by chianger** [comment]
SUMO in progress https://bugzilla.mozilla.org/show_bug.cgi?id=1603381

**Comment by chianger** [comment]
Both sumo and PN are up and running
