### ISSUE TITLE
Update URL link of "Copy voucher & Go shopping"

### ISSUE THREAD

**Issue by ChenMorpheus** [mozilla-tw/FirefoxLite#4364]
**Acceptance Criteria (how do I know when I’m done?)** 
"Copy voucher & Go shopping" directs users to a web page hosting in Next website

**Additional context**
Since Shopee only allows users to use the voucher via the app, we need to direct the user to a web page with voucher instruction instead of Shopee website. 

UX spec
<img width="2240" alt="image" src="https://user-images.githubusercontent.com/18019946/69299728-3e455380-0c4c-11ea-8f0a-75ad3bfbe3c3.png">

https://mozilla.invisionapp.com/share/UJTEW95EZVF#/394043983_4-3_Use_The_Voucher

**The URL link will be provided here once done:**

**Comment by chianger** [comment]
PM config efforts, not dev task

**Comment by ChenMorpheus** [comment]
The [URL link](https://mozilla-next.com/voucher/index.html) had been updated. Find the attached screenshots below.

![Screenshot_2019-11-28 Firefox Lite - How to use the voucher ](https://user-images.githubusercontent.com/18019946/69782771-f0e95900-11ec-11ea-9d12-946a89b7bef7.png)

**Comment by Daisy-pliu** [comment]
verify:✅
version: 2.0.2(17045) Nightly
step:
1. user has a coupon
2. user tap [gift]-> [Gift] -> [voucher]-> [copy voucher and go shopping]
3. tap [google play] 
4. tap back
5. tap [condition & terms ] (in Indo lang)
6. tap [shop now] (in Indo lang)

Result
2. see directed page opened in content tab
<img src="https://user-images.githubusercontent.com/44990878/70118469-0524ce80-16a3-11ea-866a-f71b0f3f6428.png" width="200" /> <img src="https://user-images.githubusercontent.com/44990878/70118968-3baf1900-16a4-11ea-8576-21111af66aae.png" width="200" />


3. see shopee app in play store 
4. back to directed page 
5. see shopee terms& condition
<img src="https://user-images.githubusercontent.com/44990878/70118881-0dc9d480-16a4-11ea-990f-730d3132a7f5.png" width="200" /> <img src="https://user-images.githubusercontent.com/44990878/70119324-ff2fed00-16a4-11ea-90ed-4dba592e097e.png" width="200" />

6. see shopee home in content hub
<img src="https://user-images.githubusercontent.com/44990878/70118467-0524ce80-16a3-11ea-962e-93baa69fcd22.png" width="200" />

**Comment by Daisy-pliu** [comment]
can not test on production as it will not turned on for this release so tested on nighlty only.
