### ISSUE TITLE
"More" button in detail page for visiting Booking.com's booking sites.

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4366]
**User story**
As a user, I'd like to visit booking.com's booking site for seeing more hotel options.

**UX spec**
https://mozilla.invisionapp.com/share/EWSX97EB69J#/374278129_1-3_Search_for_a_city_2

**Comment by lanyliu** [comment]
Travel telemetry [spec](https://docs.google.com/spreadsheets/d/1UinEVG2trRLeUoHtB-5lvLtUr3oFWCWT8Wh_osSAGmM/edit?usp=sharing)

1. define ping for "more"
please refer to row 18

2. define value format for "city"
refer to row 18, open, detail_page, more, extra: item_name
refer to row 24, click, content_home, item, extra: item_name
format example:
- item_name: "vn-ho chi minh" (2 digit country code + '-' + city name, in lower case)

note:
please make sure it should be the same definition for "city" in backend

**Comment by Conjuror** [comment]
17478
