### ISSUE TITLE
Spike-Firebase in-app msg

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4371]
spike for #3875

**Comment by chianger** [comment]
Scope:
1. in-app message demo 
2. CTA => deep link to vertical home

**Comment by Conjuror** [comment]
I noticed that there's some limitation (bug!?) on server side, and it seems we have nothing to do unless Google starts to fix it. Team needs to be careful before trigger in-app messaging.

**Comment by elin-moco** [comment]
Also Verified event data on telemtry, looks OK.
But can't get it work when targeting foreground/show__home.
