### ISSUE TITLE
[News Backend Enhacement] Add Setting for ID

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#4372]
to support #3901, #3842

**Comment by chianger** [comment]
#3842 will be covered with this backend enhancement

**Comment by cnevinc** [comment]
This is pure fontend work.
Not working on it. 
Please feel free to take it

**Comment by weslyhuang** [comment]
add the "feature" label so be excluded from daily launch-blocker(P0) scanning.

**Comment by chianger** [comment]
no longer needed
