### ISSUE TITLE
The pattern of loading page is different with UI spec.

### ISSUE THREAD

**Issue by Jack-king-1** [mozilla-tw/FirefoxLite#4373]
**Describe the bug**
The pattern of loading page is different with UI spec.

**Expected behavior**
<img width="365" alt="螢幕快照 2019-11-22 下午2 17 50" src="https://user-images.githubusercontent.com/56010545/69409922-e0e0fd80-0d44-11ea-8c3d-7318e7d4e5d4.png">

**Actual behavior**
![Screenshot_20191122-131336_Firefox Lite Preview](https://user-images.githubusercontent.com/56010545/69409931-e50d1b00-0d44-11ea-9007-768960ee08f8.jpg)

**Device info (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0
 - Webview 78.0.3904.108
 - Version 2.0.2(17050)

**Reproduce rate**
5/5

**Additional context**
Only Samsung Galaxy S7 have this issue.

**Comment by Jacklin-ux** [comment]
Is loading UI different in other verticals in Samsung S7? If different, this is a bug. Otherwise, it's expected.

**Comment by Jacklin-ux** [comment]
Is loading UI different in other verticals in Samsung S7? If different, this is a bug. Otherwise, it's expected.

**Comment by Jack-king-1** [comment]
It's same as other verticals , I think it is expected  behavior.
So , closed.
