### ISSUE TITLE
Use Mission Name instead of translated title in Telemertry

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#4375]
open on-behalf of Lany
We now use Mission Title. which is translated. (need confirm with Evan)
It's better we use an identifier. 
mid is not readable. Maybe we can use "Mission Name" from the backend 
![image](https://user-images.githubusercontent.com/1287363/69417552-daa64d80-0d53-11ea-8ef0-3863ba60b781.png)

OR. we can use mid, and let BI team query the Mission collection :P

**Comment by lanyliu** [comment]
related https://github.com/mozilla-tw/FirefoxLite/issues/3864

As we need challenge_name from backend, missionName is a better identifier comparing to l10n title and non-human readable mission_id.

**Comment by weslyhuang** [comment]
is this something urgent to be done in this Sprint (like #3864), or a P0 issue to be fixed soon? @harly21 would you help confirm? tks.

**Comment by cnevinc** [comment]
I think @proevan has done it?

**Comment by proevan** [comment]
yes it's done
