### ISSUE TITLE
Grant Tina publish permission on preview and production

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/FirefoxLite#4381]
Tina is the travel vertical owner and will need the admin publish permission

**Comment by niyali** [comment]
publish admin permission granted to Tina on both preview and production. 
@tinahsieh, could you give it a try when you can, please?

**Comment by tinahsieh** [comment]
I can access preview but not production.

**Comment by niyali** [comment]
> I can access preview but not production.

Had Tina opened a private window and login again and it works now.

**Comment by tinahsieh** [comment]
Thank you. Linear! <3
