### ISSUE TITLE
Please grant me triage permission for this repo so I can grab requests relating to GCP/firebase permission 

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/FirefoxLite#4382]
As I've been currently in charge of granting GCP/firebase permission. 
I would like to have triage permission for this repo so I can grab requests related. 

Thank you very much.

**Comment by niyali** [comment]
ex: https://github.com/mozilla-tw/FirefoxLite/issues/4381

**Comment by niyali** [comment]
to be clear - what I need is simply to be able to add myself to assignees.

**Comment by Conjuror** [comment]
done
