### ISSUE TITLE
Experiment - Add red dot to vertical button to increase vertical's CTR 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4383]

**Comment by Jacklin-ux** [comment]
![4 Vertical without name](https://user-images.githubusercontent.com/22672569/69614774-a80b9600-106e-11ea-95d0-8f3e109e9f80.jpg)

**Comment by Jacklin-ux** [comment]
Discussion with data team: https://trello.com/c/0uwTEiGX

**Comment by chianger** [comment]
need dev to confirm design and metrics

**Comment by chianger** [comment]
action: to put concluded metrics here on the bug, and also UX scope (red dot behavior and remote config timing)

**Comment by lanyliu** [comment]
will go through data spec with RD

https://docs.google.com/spreadsheets/d/11J7Bxmpi9WThQrpxd0fA9rQaddSti6VEg27vZlgtii8/edit?usp=sharing

**Comment by FinnickC** [comment]
https://zpl.io/bA5DGw8
Please reference this page.
