### ISSUE TITLE
Experiment - Add vertical name to increase vertical's CTR 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4384]

**Comment by Jacklin-ux** [comment]
![4 Vertical without note](https://user-images.githubusercontent.com/22672569/69614794-b78adf00-106e-11ea-84e9-310ffd994306.jpg)

**Comment by Jacklin-ux** [comment]
Discussion with data team: https://trello.com/c/wLafOw5G

**Comment by chianger** [comment]
need dev to confirm design and metrics

**Comment by lanyliu** [comment]
will go through data spec with RD
https://docs.google.com/spreadsheets/d/134F9H6U2aoxSnWdHeqj1hCDfYIrT6WdkAV2jNCR5RO4/edit?usp=sharing

**Comment by FinnickC** [comment]
Please reference this page.
https://zpl.io/beeOgGm
