### ISSUE TITLE
l10n issue

### ISSUE THREAD

**Issue by proevan** [mozilla-tw/FirefoxLite#4390]
Following string resource should have 1 parameter in `ru/string.xml`

`<string name="msrp_challenge_details_body_2">Чтобы начать введите свой адрес электронной почты. Убедитесь, что вы вошли в аккаунт, который хотите использовать, до получения вознаграждения.</string>`
`<string name="msrp_challenge_tou">Нажимая «Я участвую», вы соглашаетесь с нашими Условиями использования.</string>`

**Comment by weslyhuang** [comment]
not severe and will be fixed by the coming l10n merge back, so P1.

**Comment by Conjuror** [comment]
We'll wait for https://github.com/mozilla-l10n/zerda-android-l10n/pull/59 to land and come back to the issue.

**Comment by Conjuror** [comment]
> We'll wait for [mozilla-l10n/zerda-android-l10n#59](https://github.com/mozilla-l10n/zerda-android-l10n/pull/59) to land and come back to the issue.

The l10n patch is landed already. #4410 should fix the issue.
