### ISSUE TITLE
Need to check if we use the correct Affiliated ID for partners

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4391]
**Describe the bug**

We'll need to make sure if we are using the correct Affiliated ID

HOTEL URL from Hotels API
City URL from autocomplete API

For details, please look for Charles' comment in #firefoxlite-travel in Slack

**Comment by cnevinc** [comment]
Also need to check the latest affiliate ID

**Comment by chianger** [comment]
check point: by Dec-10 we should have conclusion on how to do it.

**Comment by weslyhuang** [comment]
still pending on partner's confirmation. bix impact instead of user impact, non-blocking.

**Comment by tinahsieh** [comment]
Just got the reply from Booking.com:
"You will just have to add the new AID to the url all , API call are done on a partner and not AID level "

@benjamin-cheng Seems like it requires some engineering efforts from our side?

**Comment by weslyhuang** [comment]
need @benjamin-cheng 's support here.

**Comment by benjamin-cheng** [comment]
@tinahsieh we are still waiting for the exact the affiliate id parameter format from Booking.com, please help to follow with partner. In the mean time, I've made the affiliate id remote configurable, once we get the format, we can update it on the Firebase, so it should not block the release.

**Comment by benjamin-cheng** [comment]
I found partner has replied the format. This issue can be closed by #4502

**Comment by weslyhuang** [comment]
@benjamin-cheng even with the correct format confirmed now, we;ll still implement the affiliate id as remote configurale so get the flexibility in the future, right?

**Comment by weslyhuang** [comment]
closed per comment above (closed by #4502)
