### ISSUE TITLE
[Travel] Page loading mechanism in detail page

### ISSUE THREAD

**Issue by benjamin-cheng** [mozilla-tw/FirefoxLite#4397]
UX SPEC:
https://mozilla.invisionapp.com/share/EWSX97EB69J#/screens/381122626

Visual SPEC:
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5dd75dab586be49438ac9168
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5dd75da9d5d3739492dd0a65

**Comment by Conjuror** [comment]
17478
