### ISSUE TITLE
Create firestore indexing for travel vertical

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4403]
**User story**
Release team needs to help Travel Discovery to add indexing to publish collection before backend deploys to Nightly or Production.

**Comment by Daisy-pliu** [comment]
related to PR [Add tag for content](https://github.com/mozilla-tw/mango_backend/pull/187#issuecomment-559323308)

**Comment by weslyhuang** [comment]
P0 as needed before Travel is launched.

**Comment by Daisy-pliu** [comment]
done on production and Nightly.

**Comment by Daisy-pliu** [comment]
verify:✅
