### ISSUE TITLE
Reduce the min GAE instance count 

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#4405]
Per discussion with Vance, we don't need that many instances(according to the stress test, we set it to 4) for now.
See the history since Nov 21nd
![image](https://user-images.githubusercontent.com/1287363/69894266-560d8d80-1358-11ea-8b63-0d3fae664a36.png)

Consider making the min instance count 2 to save money

**Comment by weslyhuang** [comment]
per traige discussion in the morning, let's revisit the status and make the decision AFTER the 1st MSRP campaign coming this week.

**Comment by weslyhuang** [comment]
per last week's MSRP stats we'll reduce the number of instances to 2.

**Comment by chianger** [comment]
Done.
