### ISSUE TITLE
Set up MSRP alerting for Nightly and Prod 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4409]
**User story**
Release team set up alerting matrix for MSRP  on Nightly and production.
It will help 
1. send alerting when MSRP API consumption is abnormal 
2. PM can do API data analysis on a daily basis 

**Acceptance Criteria (how do I know when I’m done?)** 
Refer Spec : [MSRP alert](https://docs.google.com/spreadsheets/d/1jA-TGV4QEP8oO3sYxM0SiLg0C_PQRAQH5VJ7UT205FQ/edit#gid=0)
1. set up matrix 
2. set up alerting so alert sending from email/Slack
3. set up exports to Big Query

**Additional context**
so far system sends email alert to @shsu571 @cnevinc @Daisy-pliu 
please let me know if any more people need to receive alerts.

**Comment by Daisy-pliu** [comment]
since sending slack GCP alert needs US slack manager approval, we will initially sending via email. Once permission approved , we will config Slack to send message.

**Comment by Daisy-pliu** [comment]
sent request to slack manager 
<img width="586" alt="Screen Shot 2019-12-02 at 4 44 25 PM" src="https://user-images.githubusercontent.com/44990878/69945045-b6045f80-1523-11ea-8db6-410956464687.png">

**Comment by weslyhuang** [comment]
I think this is something we need before the formal MSRP campaign this week? so set P0 first

**Comment by Daisy-pliu** [comment]
verify : ✅
1. Deploy prod-0.16.1 which cherry pick MSRP-alerting PR onto 0.16.1
2. setup alerting matrix on Nightly and Prod

**Comment by Daisy-pliu** [comment]
3. slack alert is configured . Once there is matrix violation,  GCP alert will send to msrp-alert Slack channel.
