### ISSUE TITLE
[Travel] Youtube card UI enhancement

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4429]
**Describe the bug**
1. The thumbnails are blurry. 
2. There are some black areas in the thumbnails.

**Actions**
1. Replace default size thumbnails by **medium size** thumbnails
2. Scale the thumbnails to **fit the image height**

**Expected results**
1.  Better image quality of the thumbnails
2. No black areas but the edge of the thumbnail is cut

**Comment by weslyhuang** [comment]
suggest to separate this into 2 tickets.

**Comment by tinahsieh** [comment]
Separated! by listing some easy fix actions to this card.
I'll add another card as P1 for making the thumbnail as 16:9.

@benjamin-cheng Please let me know if the actions are not clear for you.

**Comment by Conjuror** [comment]
17478
