### ISSUE TITLE
[Travel] $0 hotels on the detail page

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4431]
**Describe the bug**
$0 hotels can be found on the detail page.

**Steps To Reproduce**
1. Go to 'Travel vertical'
2. Click on 'Budapest'
3. Scroll down to 'Top hotels'
4. Found a hotel with $0 as following

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/17559807/70132697-ae79bd80-16bf-11ea-9a10-377e8c4e1552.png)

**Device info (please complete the following information):**
 - Device: [e.g. Samsung A50]
 - Webview [e.g. 78.0.3904.108]
 - Version [e.g. 2.0.3(17314).beta]

**Reproduce rate**
every time

**Comment by Conjuror** [comment]
When the hotel rooms are sold out, it will display 0 on the price. Suggest to P0 it to reduce misunderstanding.
![Screen Shot 2019-12-05 at 2 41 36 PM](https://user-images.githubusercontent.com/1625148/70210382-73ce5e80-176d-11ea-93fc-6d61665e826e.png)

**Comment by benjamin-cheng** [comment]
@tinahsieh Just double confirmed, if the all of its hotel room is `0` we should hide the entire price information, right?

**Comment by tinahsieh** [comment]
I'd like to know the reason behind the API showing "$0" before making the decision since we can either hide the entire hotel card or just simply replace the price by "Find Price".

@Conjuror Thanks for the investigation!

**Comment by benjamin-cheng** [comment]
It may not be the "sold out" case since we do not provide the check-in & check-out date information. @tinahsieh Could you help to ask booking.com contact why all the room type in the hotel with zero price? Thank you!

**Comment by tinahsieh** [comment]
Asked! let's wait for the answer.

**Comment by weslyhuang** [comment]
confirm to hide those with $0.

**Comment by Conjuror** [comment]
build 17478
