### ISSUE TITLE
L10n follow up

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4435]
**Describe the bug**
As #4410 landed, we are still waiting for force-updated to land on our l10n-repo.

Before it happens, we need to merge l10n strings manually. and bring the localized strings to the local builds. Manually update are required for following files after #4410 landed:
- app/src/main/res/values-hi-rIN/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-su/strings.xml
- app/src/main/res/values-th/strings.xml

**Comment by weslyhuang** [comment]
need to handle this every Sprint until we got 100% l10n back.
