### ISSUE TITLE
Spike for partner news source API investigation

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4436]

**Comment by Jacklin-ux** [comment]
API from Dailyhunt: https://drive.google.com/file/d/1xm4ZSnOuA1i9ws1pMGq_oThmIBSTMWwF/view?usp=sharing

**Comment by Jacklin-ux** [comment]
DH_API_Keys_for_Mozilla-Stage: https://drive.google.com/file/d/1daaFkQLKq5eHVWul5l-IEObvvKBGdijZ/view?usp=sharing
Password: 72@JpNiqnzm7

**Comment by Jacklin-ux** [comment]
API reference: https://docs.google.com/document/d/1LPpSnFwKgIs5TorfsWMzLYSO6fZgtkVwtmxutLSXwxE/edit?usp=sharing

**Comment by chianger** [comment]
Scope for the spike: dev build showcase

**Comment by cnevinc** [comment]
email and asked about "Signature Base String"

**Comment by weslyhuang** [comment]
done thus close.
