### ISSUE TITLE
spike for #3871 deep link. scope = push -> specific game (content tab), back can direct to game home

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4440]
for #3871

**Comment by elin-moco** [comment]
Just confirmed no telemetry needed for deep link.
So this is good to go from BI perspective.

**Comment by chianger** [comment]
scope: dev build to demo.

**Comment by weslyhuang** [comment]
done thus close.

**Comment by Daisy-pliu** [comment]
It is a spike to survey notification which not requires QA effort so labelled no-need-verification.
