### ISSUE TITLE
[Travel] Youtube card UI enhancement - 16:9 thumbnails

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4441]
**User story**
As a user, I'd like to see the full-sized thumbnails.

@FinnickC Please attach the UI spec link in this bug. Thank you!

**Comment by FinnickC** [comment]
https://zpl.io/bP1OLDl

**Comment by hartsu** [comment]
@FinnickC According to the UI Spec, the thumbnail ratio is not 16:9. It's more like 16:9.56 (width:164dp, height:98dp). Should we follow the issue description or the UI spec?

**Comment by FinnickC** [comment]
yeah, please follow the UI spec, I resize to this size on our layout which should use a consistent grid to make two columns.
