### ISSUE TITLE
Open vetical home/ MSRP challenge list from Logoman banner

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4445]
Use deeplink to open below,
News Home opens
Shopping Home opens
Game Home opens
Travel Home opens
MSRP Challenge List opens

For UI design, please see the [link](https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e?seid=5d5f4df62ffb679bba9a4f6e)

**Comment by lanyliu** [comment]
telemetry spec 
please refer to [spec](https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947) row 20-27

to be checked:
**click_logoman** event will also send **start_process_vertical**
