### ISSUE TITLE
Change Instagram logo and copy "Instagram"

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4446]
**Describe the bug**
1. The Instagram logo isn't consistent with the logo we use in quick search.
2. We should replace the copy "IG" with the full name "Instagram"

**Comment by benjamin-cheng** [comment]
@tinahsieh please help to update the copy to `<string name="travel_content_ig_link">#%1$s on Instagram</string>`

**Comment by benjamin-cheng** [comment]
@hartsu  please help to apply the same icon from UrlInputFragment to the travel city detail page.
![device-2019-12-06-084814](https://user-images.githubusercontent.com/7045016/70305653-39180500-1805-11ea-8879-49e9729b4482.png)

**Comment by Conjuror** [comment]
build 17478
