### ISSUE TITLE
Open content tab from Logoman

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4448]
Users can tap logoman and directed to a specific vertical's content tab.
*Open (URL) in specific vertical's Content Tab, tap system back key then direct to its vertical hub.

**Comment by Jacklin-ux** [comment]
First use case:
deep link. scope = logoman -> specific game (content tab), back can direct to game home

**Comment by lanyliu** [comment]
telemetry spec 
please refer to [spec](https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947) row 20-27

to be checked:
**click_logoman** event will also send **start_process_vertical** & **start_content_tab**
