### ISSUE TITLE
%1$s should be replaced by the search context in travel

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4451]
**Describe the bug**
As title

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [Search bar] to search city
4. Type a name of a city, i.e. "Taipei"

**Expected behavior**
4. In the second part, "See results in Taipei"

**Actual behavior**
4. "See results in %1$s"

**Comment by weslyhuang** [comment]
need to align w/ MKT message @tinahsieh

**Comment by StellaTseng** [comment]
Test

**Comment by StellaTseng** [comment]
The draft copy for travel would be

**Comment by StellaTseng** [comment]
The travel related copy was confirmed now. 
 Headline : Travel Discovery
圖 Subhead: Discover and plan your next adventure文字 description:
Travel Discovery 
Discover and plan your next adventure. Explore new cities, find hidden gems, get deals on hotels, and create a bucket list of all your top destinations.

**Comment by weslyhuang** [comment]
note: need a new string id to avoid potential l10n confict. @tinahsieh

**Comment by tinahsieh** [comment]
The new string is as following:
<string name=“travel_search_engine_fxlite”>See results in %1$s Travel Discovery</string>
