### ISSUE TITLE
Youtube search results enhancement

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4454]
**Describe the bug**
The current search results are sorted by `viewCount` as what the design spec defined, but the results are not relevant and some of them are not appropriate to be shown on Firefox Lite.

**Action**
Replace the order parameter `viewCount` by the default value `relevance` for getting better search results. (The quality of the search results have been checked by PM)

**Comment by tinahsieh** [comment]
Need to check again on the real API implementation

**Comment by weslyhuang** [comment]
pure backend config, independent of client APP release.

**Comment by Conjuror** [comment]
build 17478
