### ISSUE TITLE
Language in Travel content tab are different

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4455]
**Describe the bug**
If a user's system default language is not English and the user attempts to visit travel content, leave, and visit travel content again. The user sees text display in different languages

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on Travel content
3. Tap on back key
4. Tap on Travel content

**Expected behavior**
The language displays in step 2 and step 4 are the same

**Actual behavior**
The language displays in step 2 and step 4 are not the same

**Screenshots/videos**
https://drive.google.com/file/d/1Pc5vEZhbFr2sZThmP60SXTpODnrWw5Mk/view?usp=sharing

**Comment by chianger** [comment]
Works for me as it's not able to reproduce
