### ISSUE TITLE
Thumbnails of cities need to have 4dp radius corner

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4464]
**Describe the bug**
According to [Spec](https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5d720d33d230f41869cd7439), the pictures should have 4dp radius, which is not there.

![Screenshot_20191210-163001](https://user-images.githubusercontent.com/1625148/70511049-68fb3b80-1b6a-11ea-8e66-5592276f4e76.png)

**Comment by chianger** [comment]
tag to current sprint for QA verification
