### ISSUE TITLE
Decode the titles in Youtube cards 

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4465]
**Describe the bug**
The titles in Youtube cards contain some strings which are not readable for users.

**Screenshots/videos**
![Screenshot_20191210-165651_Firefox Lite Preview](https://user-images.githubusercontent.com/17559807/70514248-3b17f600-1b6e-11ea-926a-7ac0513912bc.jpg)

**Comment by Conjuror** [comment]
build 17478
