### ISSUE TITLE
voucher introduction page shuold not show "Exit app and open Firefox Lite again to find challenges"

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4468]
**Steps To Reproduce**
given user has coupon
1. launch app
2. tap [gift] -> [reward] -> [coupon]
3. tap [copy code and shopping] 

**Expected behavior**
User see voucher_usage_intro_site: voucher can be only used in Shopee application
<img width="300" alt="Screen Shot 2019-12-10 at 5 59 43 PM" src="https://user-images.githubusercontent.com/44990878/70519443-e462ea00-1b76-11ea-8fab-7d8584e9c09a.png">

**Actual behavior**
User see voucher _usage_intro_site : Exit app and open Firefox Lite again to find challenges.
<img width="200" alt="Screen Shot 2019-12-10 at 5 54 11 PM" src="https://user-images.githubusercontent.com/44990878/70519248-98b04080-1b76-11ea-8811-a898e30591cf.png">

**Reproduce rate**
all

**Additional context**
since PM has communication gap with support team, voucher _usage_intro_site has been accidentally changed to wrong one on production since 12/06, which will mislead Indo user when they want to use voucher.

**Lesson Learn**
1. Please create git ticket for the team to check and consolidate requirement 
 
**Device**
All

**version**
All , nightly and production

**Comment by niyali** [comment]
The page has been reverted. 
Moving forward only valid git ticket will initiate the change of voucher page.

**Comment by niyali** [comment]
Had a meeting with Morpheus, Mark and Wendy, @swlibi  and I will be the only two to upload files needed for the time being.

**Comment by shsu571** [comment]
Need to be done by next campaign (est: 2020/2)

**Comment by weslyhuang** [comment]
assigned P1 thus remove "need triage"

**Comment by weslyhuang** [comment]
deferred to the next sprint as no urgent now. (before 2020 Feb.)

**Comment by niyali** [comment]
Considered this is done and per offline discussion, whoever wants to make the change need to open a github ticket for review.
