### ISSUE TITLE
Enhance (or clarify) Location/Storage permission 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4471]
Android OS on devices for review: Pixel 3, 9.0
Reviewed app Version Name: 2.0.4 (17368)  Version Code: 17368 PRODUCTION

- Many users are sensitive to what sort of information is requested by the apps they install. Limiting the amount of private information the app gathers from users by only requesting the absolute minimum number of permissions that it needs to support core functionality can help to draw in new users and keep them coming back to the app in the future. While reviewing the app, the following sensitive permissions found in the app's manifest don't seem necessary to support user-facing features and they we not even prompted during my interaction with the app.

• ACCESS_FINE_LOCATION
• ACCESS_COARSE_LOCATION
• READ_EXTERNAL_STORAGE
• WRITE_EXTERNAL_STORAGE

Please remove any unnecessary permissions and/or explain how the permissions are being used. Additionally, make sure that when making use of these permissions, prompts follow the proper flow at run time.

For more info:
http://developer.android.com/distribute/essentials/quality/core.html#fn
https://developer.android.com/training/permissions/usage-notes.html

**Comment by cnevinc** [comment]
I'm not sure where this request comes from.
AFAIK,  `ACCESS_COARSE_LOCATION`/`ACCESS_FINE_LOCATION` is needed when the website asks for permission. See the [API document](https://developer.android.com/reference/android/webkit/WebChromeClient). Sites like `google.com` will ask for it.

`READ_EXTERNAL_STORAGE` is needed for viewing screenshot files, file chooser ( upload content in web pages) `WRITE_EXTERNAL_STORAGE ` for saving screenshots, and downloading files.

If other devs had better answers, please feel free to correct me or add comments.

**Comment by joechengla** [comment]
Thanks for providing a detailed explanation for the permissions being used. Having said that, it is ok to use the current permissions.
