### ISSUE TITLE
Add touch feedback to improve user experience (exclu. MSRP)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4472]
- Not all users have powerful devices or fast internet connections, therefore it is important to provide some form of touch feedback on all interactive elements within the app. Providing feedback on user input lets the user know which element is reacting to input and that the app has taken their action even if the activity can't react or load instantaneously due to lack of processing power or limited bandwidth. Note that the screenshots provided below are just some of the screens with missing touch feedback, please ensure to check for missing touch feedback throughout the app.

 
![image](https://user-images.githubusercontent.com/9859809/70590737-939ed000-1c0e-11ea-8e24-8822ef76ec00.png)

![image](https://user-images.githubusercontent.com/9859809/70590802-c47f0500-1c0e-11ea-9f1d-fc11bddde426.png)

For more info:
https://developer.android.com/training/material/animations.html#Touch
https://material.io/guidelines/motion/material-motion.html#material-motion-how-does-material-move

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/a7x88K8

**Comment by weslyhuang** [comment]
MSRP part on Evan, others may get support from outsourcing.

**Comment by chianger** [comment]
Once this is merged, we can push a hotifix to get this build reviewed by play store to get it featured.

**Comment by chianger** [comment]
due date for having this build in place is Jan-02.

**Comment by chianger** [comment]
per discussion, let's skip MSRP for this UI enhancement

**Comment by Conjuror** [comment]
Most of the event effects are not aligned to spec. Reopen the issue and wait for fixes.

**Comment by Conjuror** [comment]
Currently, most of the events are not aligned to spec. The missing parts can be divided into three types:

- Effect area is over the item. i.e., icon, search bar, images with rounded corners
- Effect speed is too fast to be observed. i.e., coupons, cards, pictures of city in bucket list
- Effect is hard to observe. i.e., pictures of city in bucket list, coupons

**Comment by FinnickC** [comment]
In visual opinion, these events need to fix. we may decide after discuss.
