### ISSUE TITLE
Shopping Home: no conversion data on partner platform ( only can get clicks) 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4480]
Partner: Flipkart, Bukalapak

Current Statue:
https://docs.google.com/document/d/11snEPN2mygVm9o_XmloIwOmZigDYs1ozAG_a6txdfmw/edit
Already mailed partner to confirm the order condition, but haven't got replied yet.
Test we did: purchase item link from shopping mode (only can get clicks but no conversions)

Need engineering team to help to confirm the content tab have data missing or not.
Purchase on Content Tab vs Purchase on Normal Tab(could use topsite flow to check)
 
PM will keep following up the partners' reply about this issue.

**Comment by Daisy-pliu** [comment]
Hi PMs,
For Bukalapak I could see conversion on 11/27 please help verify if this is the item you purchased.
<img width="1680" alt="Screen Shot 2019-12-26 at 6 04 17 PM" src="https://user-images.githubusercontent.com/44990878/71471340-2728f100-280a-11ea-852f-fc38f50dc985.png">

**Comment by chianger** [comment]
decided not to take further actions at this momen
