### ISSUE TITLE
Content Home : open in different modes 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4483]
**User story**
As a  user, after tapping any items on content Home in every category, 
I would like to open in the different type of tab by providing best browsing experience

**Acceptance Criteria (how do I know when I’m done?)** 
1. Decide how to open "destination" by  new column destination_type
2.destination_type ( Type name -> open way)
(1)full_content_tab: Full screen content tab
(2)content_tab: content tab
(3)google_play: Google Play Store
3.Back-end needs to add new column on the upload files.

**Additional context**
The request if from Game vertical but after discussion this might be applied to all vertical in the future.
https://github.com/mozilla-tw/FirefoxLite/issues/3905

**Metrics and reasons for feature request**
- Different type of destination conversion rate -> new model to works with partner
ex. installs or partner's app new users acquisition 
- Partner provides different type of destination (partner request)
**Telemetry**
The uploading data will not need to do telemetry update.

**Comment by shsu571** [comment]
The uploading data will not need to do telemetry.

**Comment by cnevinc** [comment]
@shsu571 Please check with @benjamin-cheng about the implementation so it can be placed in the next sprint

I also need the filed name (e.g. open_mode )in the backend so this can be "backend-ready"

**Comment by benjamin-cheng** [comment]
@shsu571 It's ready for app front-end development.

**Comment by cnevinc** [comment]
backend development completed
https://github.com/mozilla-tw/mango_backend/pull/213

**Comment by shsu571** [comment]
Test dataset (uploaded to dev)
https://docs.google.com/spreadsheets/d/1YEYH7fwWiWJjrSQwBiPul-e0N9B7j0QbemvBtJxmgN8/edit#gid=0
PM needs to upload new csv files after finish production.

**Comment by Daisy-pliu** [comment]
verify :✅
version : 2.1.9 (18655)
**Test step:**
1.  login Nightly Admin page
2. Upload banner , browser games based on [ Game_20191210_List Optimization_destination_type sheet ](https://docs.google.com/spreadsheets/d/1YEYH7fwWiWJjrSQwBiPul-e0N9B7j0QbemvBtJxmgN8/edit#gid=916540177)
3. launch app
4. tap [games]
5. tab each game banner 

**Expect result:**
each game banner will open different content tab type based on admin console input data. 

**Refer**
[Verticals upload Process on wiki ](https://github.com/mozilla-tw/FirefoxLite/wiki/Verticals-Data-Upload)

**Comment by Daisy-pliu** [comment]
We wont have data upload demand on Prod this sprint.  Instead, it will happen when PM receives partner request . During that time , release team & PM team will upload data for verticals on Nightly and Production.
