### ISSUE TITLE
Add a prompt when users visit the Google search result page

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4484]
**User story**

- [x] As a product manager, I'd like to see the portion of users who go to Google search result page by tapping "enter" when searching for cities.

- [x] As a product manager, I want to guide users to visit Firefox Lite Travel Discovery.

**Comment by elin-moco** [comment]
Booking.com vs Google travel search:
 - users: google is 2.5x of booking.com
 - events: google is 2.2x of booking.com
https://sql.telemetry.mozilla.org/queries/67317/source

**Comment by shsu571** [comment]
UX spec: https://mozilla.invisionapp.com/share/EWSX97EB69J#/screens/374278126

**Comment by tinahsieh** [comment]
@FinnickC , could you please provide the UI spec for the prompt with a check box? It's a new component that we never have before.

**Comment by chianger** [comment]
Target build time for the RC is Jan-13 by noon.

**Comment by FinnickC** [comment]
UI Spec
zpl.io/VQnAxqP
zpl.io/aBpkeq0
zpl.io/amwXzOA

**Comment by shsu571** [comment]
teletmetry: https://docs.google.com/spreadsheets/d/1goBvD5Q6hHNcNK0xB9MgNN7JbpWQ8sMr59jGal4DF44/edit#gid=0

**Comment by Conjuror** [comment]
Test cases are added:

TRAVEL018
TRAVEL019
TRAVEL020

**Comment by elin-moco** [comment]
Verified new Telemetry events w/t Firebase DebugView
