### ISSUE TITLE
We need e2e test for verticals... to prevent regression for backend data

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#4491]
We are changing  / will change the backend data sooner or later.

We must make sure that all API changes are covered by either automation or manual testing.

We already have e2e test for MSRP.

We now need e2e test for verticals.

**Comment by weslyhuang** [comment]
need to decide the overall priority accordingly.

**Comment by weslyhuang** [comment]
i.e., Backend API test.

**Comment by weslyhuang** [comment]
to catch the sprint deadline we do it manually this time, but need to automate it asap. (#4493 )

**Comment by cnevinc** [comment]
We can run this script manually now. It'll be great if we can make this automated (target Nightly and production)

[api_data_regression_vertical.zip](https://github.com/mozilla-tw/FirefoxLite/files/3967423/api_data_regression_vertical.zip)

**Comment by Conjuror** [comment]
https://github.com/mozilla-tw/mango_backend/pull/205
