### ISSUE TITLE
Automated backend API test

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#4493]
We did it manually in #4491 but need to automate it asap so not to get the debt bigger with time.

**Comment by weslyhuang** [comment]
per discussion, important as P0.

**Comment by Daisy-pliu** [comment]
Can refer this #437. It will auto trigger verticals API test when every backend deployment.

**Comment by cnevinc** [comment]
See https://github.com/mozilla-tw/FirefoxLite/issues/4491#issuecomment-565993824

**Comment by Conjuror** [comment]
https://github.com/mozilla-tw/mango_backend/pull/205 is landed. so close it.

**Comment by Daisy-pliu** [comment]
verify:✅
backend version : v0.22
<img width="933" alt="Screen Shot 2019-12-30 at 10 46 41 AM" src="https://user-images.githubusercontent.com/44990878/71566332-b88db100-2af1-11ea-9810-90168ce8709e.png">
