### ISSUE TITLE
Support Traditional Chinese for Booking.com hotel cards 

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4494]
**Describe the bug**
The current hotel cards only support Simplified Chinese.

**Information from Booking.com API specialist**
"We have 3 that can be done via api, zh-yu, zh-ch, zh-tw"

**Actions**
- [ ] Tina to ask more details about how Booking.com supports the API languages
- [ ] Benjamin to help implementation

**Comment by benjamin-cheng** [comment]
It would show Traditional Chinese with language `zh-tw`
https://distribution-xml.booking.com/2.5/json/hotels?city_ids=-553173&language=**zh-tw**&extras=room_info,%20payment_details,%20hotel_info,%20hotel_photos,%20hotel_facilities,%20hotel_description&rows=1

However, it would show Simplified Chinese with language `zh-hant-tw`
https://distribution-xml.booking.com/2.5/json/hotels?city_ids=-553173&language=**zh-hant-tw**&extras=room_info,%20payment_details,%20hotel_info,%20hotel_photos,%20hotel_facilities,%20hotel_description&rows=1

So, we should force the `zh-hant-tw` to `zh-tw` in booking.com APIs

**Comment by Conjuror** [comment]
17646
