### ISSUE TITLE
when typing Chinese in travel search, no suggested result

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4499]
**Describe the bug**
As title, when typing Chinese in travel search, no result is shown.

Build 17478

**Comment by Conjuror** [comment]
#4426

**Comment by weslyhuang** [comment]
triage to decide if this is a launch blocker.

**Comment by weslyhuang** [comment]
blocker for Chinese markets.

**Comment by benjamin-cheng** [comment]
@Conjuror could you provide detail reproduce steps along with your device language settings? Thanks!

**Comment by Conjuror** [comment]
After more investigation, I just realized that it won't show the search result if I only entered one Chinese character.

**Comment by Conjuror** [comment]
**STR:**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [Search bar]
4. Type "台"
5. Type "北"

**Actual Result:**
4. No search result is shown
5. Search result of "台北" is shown

I suggest to push back to PM to decide if we need to consider it as an issue.

**Comment by tinahsieh** [comment]
I see. It's a constraint that Booking.com's API can only provide suggestions when a user types a second Alphabet.
I'd say it's not a bug but we can definitely have some UX improvement on this so that we won't confuse users
