### ISSUE TITLE
Open content tab from D1 push notification

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4506]

**Comment by lanyliu** [comment]
Telemetry [spec](https://docs.google.com/spreadsheets/d/1-FIXLsci0kt4ZJoCuD3N17cmy1rYs1R82l6xhjoJS_o/edit?usp=sharing)

related ticket: https://github.com/mozilla-tw/FirefoxLite/issues/1788

already exist, need modified:
- get, firstrun_push, null {delay: , message: , link: url|deeplink|null}
- show, firstrun_push, null {delay: , message: , link: url|deeplink|null}

add ping:
- open, firstrun_push, null {message: , link: url|deeplink|null}
- swipe, firstrun_push, dismiss {message: , link: url|deeplink|null}


to be checked:
**open_firstrun_push** event will also send **start_process_vertical** & **start_content_tab**

**Comment by shsu571** [comment]
confirmed with @proevan 
appearing rule: first launch + internet check
