### ISSUE TITLE
Open Open vetical home/ MSRP challenge list from D1 push notification

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4507]

**Comment by lanyliu** [comment]
Waiting for PM to provide data request form.

related ticket: https://github.com/mozilla-tw/FirefoxLite/issues/1788

already exist:
- get, firstrun_push, null {delay: , message: }
- show, firstrun_push, null {delay: , message: }

add ping:
- open, firstrun_push, null {message: , link: url|deeplink|null}
