### ISSUE TITLE
Open shopping search through deeplink 

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4508]
Open shopping search from notification/D1 push notification/Logoman banner/In-app message

**Comment by elin-moco** [comment]
Telemetry Spec for Logoman/Push/In-App Message
https://docs.google.com/spreadsheets/d/18ate-F2ZrmjOsYXfZSeA7rqdFrrJ6ekIbP4hiV8T8eU/edit#gid=888392947

Telemetry Spec for D1 push
https://docs.google.com/spreadsheets/d/1-FIXLsci0kt4ZJoCuD3N17cmy1rYs1R82l6xhjoJS_o/edit#gid=0

**Comment by weslyhuang** [comment]
still clarifying scope, add all need-X labels first.

**Comment by chianger** [comment]
leave the labels for now, and let's make sure the re-org task transition covers it.

**Comment by shsu571** [comment]
back -> back to last step

**Comment by elin-moco** [comment]
We discussed with Evan to confirm the extra definition of Show/Click/Swipe logoman:

 - type: comes from Remote config (except type: rewards is hardcoded)
 - message_id: comes from Remote config
 - link: the actual URL

Also updated notes in the spec

**Comment by Conjuror** [comment]
sample:
`rocket://content/shopping/item?url=https%3A%2F%2Fwww.yahoo.com&feed=yahoo&source=yahoo`

**Comment by Conjuror** [comment]
18655
