### ISSUE TITLE
UI enhancement for travel search

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4510]
**Describe the bug**
The line-height for the title should be flexible if the copy becomes 2 rows.

**Comment by tinahsieh** [comment]
@FinnickC Could you please provide UI spec for this? Thanks!

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/VxrJKQJ

**Comment by cnevinc** [comment]
@youwenliang @tinahsieh can you please let any engineer check if this is ready for development before the sprint planning?

**Comment by tinahsieh** [comment]
Have checked with @benjamin-cheng.

**Comment by Conjuror** [comment]
18642
