### ISSUE TITLE
Behavior of refresh button in travel vertical is inconsistent

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4515]
**Describe the bug**
There are some behaviors by current testing.

- Multiple "#xxxtravel on IG"
- Unfinished Hotel searching
- No Wikipedia
- No "IG hastag" and No Youtube videos

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Select a city or search a city
4. Tap on [Refresh] (or Tap on [Refresh] twice quickly)

**Comment by weslyhuang** [comment]
could be multiple/mixed root causes. @benjamin-cheng to help investigate first.

**Comment by Conjuror** [comment]
17646
