### ISSUE TITLE
Run out of Youtube query points

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#4519]

**Comment by weslyhuang** [comment]
need to contact Youtube for this. PM is on it.

**Comment by tinahsieh** [comment]
**City scope**
Youtube content priority as below:
1.  Recommended cities on Travel Home (10*4 versions <40 cities)
2. 100 Popular cities (defined in[ this sheet](https://docs.google.com/spreadsheets/d/1SqGftat12-haRWb_6js_dnJ_LnyLiFWAu93MNSRhUfs/edit#gid=1337450899))
3. All cities in IN & ID
4. Others cities & regions defined in Booking.com's API

**Comment by tinahsieh** [comment]
@tina to help find the expire time in Youtube term.

**Comment by cnevinc** [comment]
Per discussion with PM. We'll use Memorystore(Redis) for shared cached.
This will add ~50 USD per environment (DEV/STABLE/NIGHTLY/PROD)

**Comment by Daisy-pliu** [comment]
@Conjuror  will help deploy "Youtube API cache information feature" on backend Staging/Production on Thursday before the end of milestone.

Please help check travel feature is good condition after deploy to Staging or Prod, make sure the feature is not risky and wont affect the other piece. Then on Monday more cached related testing (eg. different city, locale ) in details will be done on my side. thank you !

**Comment by chianger** [comment]
Backend v0.23 deployed to Nightly. 
- Youtube API enhancement  (Quota/shared cache)

**Comment by Daisy-pliu** [comment]
We will test the major scenarios and supported combination: 

**Given we have valid Youtube video data ** 
1. when user location from TW , system should cache 10 cities ( 沖繩, 澳門,布拉格,布達佩斯,胡志明市,峇里島,曼谷,東京,里斯本,伊斯坦堡) on Travel explore page and Destination list page. 
2. when user location from Indonesia , system should cache 10 cities (Yogyakarta, Bandung,Malang,Gili Trawangan,Surabaya,Bali,Bangkok,Kuala Lumpur,Singapura,Ho Chi Minh) on Travel explore page and Destination list page. 
3. when user location not from TW or Indo, it falls into "global default", system should cache 100 cities.

**Given we have expired Youtube video data**
1. when user visit, it pulls latest data -> QA check the data and timestamp updated on database.

**Given we have empty Youtube video data for certain country **
1. when user visit , it pulls latest data -> QA can check the data and timestamp updated on database.

**Comment by Daisy-pliu** [comment]
verify: ✅ 
version: Debug build on stable dev env since we run out of Staging Youtube API quota.

**Comment by Daisy-pliu** [comment]
verify:✅
Backend version : 0.24 on Production  
Frontend version: 2.1.4(17907)
We had prefilled 122 videos cached on database. it works on production.
