### ISSUE TITLE
AB test: Put Vertical Icons into Top Site - UI only(1/4)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4522]
**User story**
As a user, I would like to know how to explore vertical content.
Assumption: Users don't know we have content and how to get to explore content.

**Acceptance Criteria (how do I know when I’m done?)** 
***New Users****

 vertical icon replace partner topsite area

***Design***
Remove vertical put into topsite
Logman Banner ->  visual balance

**Additional context**
Apply on Indoensia and India New Users

**Metrics**
Vertical CTR
Side effect
Top Site long press -> remove (REMOVED; for latest version of UI 2019/12/30)
Experiment group uninstall rate
Setting menu usage
User feedback
Pin website related question

https://docs.google.com/document/d/1klSKuaArAhS0O-HcwM6qYd9xt3jx8uWAPXhqaD96vxI/edit?usp=sharing

**Comment by chianger** [comment]
@shsu571 this actually still needs design. moving back to design phase.

**Comment by cnevinc** [comment]
@shsu571 
I'm sure there'll be a different version in the Telemetry. But you can decide. 
Please have an engineer confirm the T-shirt size be for the sprint planning

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1fKvY_XMuPUUoOsKQGTIWmO0AHl-XZdHg/view?usp=sharing (Will update to Invision link later)

@FinnickC Please provide the visual design, thank you.

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/VQn3Yx9

**Comment by lanyliu** [comment]
Just verify experiment logic with PM, we don't need new defined telemetry for this experiment.

**Comment by chianger** [comment]
red dot , on boarding not included in this . follow up bugs : #4592 #4593

**Comment by TLHuang** [comment]
Since the vertical shopping will be closed, update visual for showing 3 vertical icons.
Visual spec update here https://zpl.io/VQn3Yx9

**Comment by tinahsieh** [comment]
> UX spec: https://drive.google.com/file/d/1fKvY_XMuPUUoOsKQGTIWmO0AHl-XZdHg/view?usp=sharing (Will update to Invision link later)

Updated this UX spec to align with the new visual: https://drive.google.com/drive/folders/1JuJPzNsMJWoCVPAU0EK7zYYtsctcQQU6

Also, upload this file to Invision as we put all specs on Invision: https://mozilla.invisionapp.com/share/45VYCL4MUHV#/404738745_0-0_Cover_-_Home_-

**Comment by TLHuang** [comment]
Update onboarding for vertical icons on topsites, let me know if any questions.
Visual spec here https://zpl.io/V0wXXpO

**Comment by Daisy-pliu** [comment]
verify: ✅
Version: 2.1.9 (18655)
refer : #4592 
test case: [TCP040](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C46)
