### ISSUE TITLE
Estimate the Youtube API query times in Travel

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4527]
Per #4519, we'll need to increase the API quota from the GCP platform. For increasing the quota, we need more information for submitting the ticket to Youtube Help.

@lanyliu @elin-moco: Could you please estimate the times that Firefox Lite users will visit the travel detail page?

@benjamin-cheng: Can you calculate the units that a search query costs? [Calculator](https://developers.google.com/youtube/v3/determine_quota_cost)

@niyali @chianger Let's fill the form by the end of this week :)

**Comment by lanyliu** [comment]
We don't have much data to estimate currently. According to accumulated event count from 1 day bases, we got shopping, news, and game number per vertical: 
- shopping: 180 times per day
- game and news: 1400 times per day

So we might roughly guess the range will between 180 to 1400 per day.

**Comment by tinahsieh** [comment]
From @benjamin-cheng 's information, it costs 125 units for a query.

**Comment by tinahsieh** [comment]
CC @chianger

**Comment by niyali** [comment]
Application filled. 
I am the main contact for the request and will keep you all posted. 

Thanks.

**Comment by niyali** [comment]
Received the review result, will loop team for further discussion.

**Comment by niyali** [comment]
Addressed two issues raise by Youtube API team and replied the solutions.

Waiting for the revised result.

**Comment by tinahsieh** [comment]
Summarize the conclusion we had this morning:
1. The hotfix will be push to 2.1.1
2. Update with Youtube that the new icon will be landed in the versions starting from 2.1.1, and also attach an APK for them to review.

**Comment by Conjuror** [comment]
v2.1.2 (17721)

**Comment by tinahsieh** [comment]
Close this bug and track the status in #4590
