### ISSUE TITLE
D1 push notification regression

### ISSUE THREAD

**Issue by Jacklin-ux** [mozilla-tw/FirefoxLite#4530]

**Comment by elin-moco** [comment]
Telemetry [spec](https://docs.google.com/spreadsheets/d/1-FIXLsci0kt4ZJoCuD3N17cmy1rYs1R82l6xhjoJS_o/edit?usp=sharing)

related ticket: https://github.com/mozilla-tw/FirefoxLite/issues/1788

already exist, need modified:
- get, firstrun_push, null {delay: , message: , link: url|deeplink|null}
- show, firstrun_push, null {delay: , message: , link: url|deeplink|null}

add ping:
- open, firstrun_push, null {message: , link: url|deeplink|null}
- swipe, firstrun_push, dismiss {message: , link: url|deeplink|null}


to be checked:
**open_firstrun_push** event will also send **start_process_vertical** & **start_content_tab**

**Comment by Daisy-pliu** [comment]
Refer older ticket, Day1 Push notification ticket #1788 for test case. 
Since this ticket will have enhancement for deeplink which will expand the test scenario .
