### ISSUE TITLE
Risk of losing Amplitude data for travel ( and any new events added after 2019 Oct 31)

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#4534]
**Need to use a new approach for "Telemetry -> Amplitude"** 

**Risk:** 
we'll lose amplitude data for new events (Travel mainly) until we got this fixed.

**Cause:**
After the data team moved the pipeline from AWS to GCP, the previous approach(json+scala) won't work.

**Solution 1:**
The new mapping script is here: https://github.com/mozilla/bigquery-etl/blob/master/templates/telemetry/rocket_android_events_v1/view.sql#L29-L198
If we want to add new events, we can update the above SQL script manually.

**Solution 2:**
But the data team suggest a different approach: https://github.com/mozilla/bigquery-etl/pull/625
That way the newly added events will go to Amplitude automatically.
The Devtools and ios teams are already doing it like here: https://github.com/mozilla/bigquery-etl/pull/619/files

**Verification:**
We need someone from the data team to help us.
It'll be great if the BI team can take ownership of this new pipeline.
The backend team(me) can help. But I'm not sure it works best if I still own this pipeline since I need to take care of the backend service development as well.

**Est effort**
- If owned by the backend team
  -  0 to 2 days for the script, 1~2 weeks to work with the BI team to verify the result.
- If owned by the BI team
  - need @elin-moco / @lanyliu 's input

**Comment by weslyhuang** [comment]
per Dec. 23 5pm discussion, this is not blocking Travel release and go with the solution below:
====================
Hi Wesly,
We will go with 1. Pause the " Telemetry-> Amplitude pipeline" from 12/26 till we fix the issue    
Pros: No data loss    
Cons: We won't have any amplitude data update during that time. But we can backfill them later.
=====================
and still need a follow-up meeting for the way going forward with Nevin (and maybe AL).

**Comment by weslyhuang** [comment]
and 2 actions:
1. @cnevinc to help stop the pipeline asap.
2. a follow-up meeting for the way going forward with BI, Nevin (and maybe AL, too).

**Comment by chianger** [comment]
Forgot to mention that we no longer need to stop the pipeline since data team has approach to backfill selected pings.

**Comment by lanyliu** [comment]
thx! BI will verify the mapping logic.
