### ISSUE TITLE
Microcopy error

### ISSUE THREAD

**Issue by iprithvitharun** [mozilla-tw/FirefoxLite#4535]
**Describe the bug**
Microcopy message which appears after closing the Private Tab uses present perfect passive. Here, present tense can be used for clear and concise message.

**Steps To Reproduce**

1. Open a private tab.
2. Go to any URL.
3. Hit delete icon at the bottom.
4. See the message. 

**Expected behavior**
Your private browser history is deleted.

**Actual behavior**
Your private browser history has been deleted.

**Screenshots/videos**
Screenshot link - https://imgur.com/a/otOOkGt

**Device info (please complete the following information):**
 - Device: [Redmi Note 7]
 - OS: [e.g. Android 9]

**Reproduce rate**
Every time

**Comment by Conjuror** [comment]
Thank you for the valuable inputs.

**Comment by weslyhuang** [comment]
per discussion, works for us.

**Comment by iprithvitharun** [comment]
Hi,

Can you review the request and approve it?

Prithvi
LinkedIn <https://www.linkedin.com/in/prithvi-tharun/> | Twitter
<https://twitter.com/iprithvitharun>

**Comment by joechengla** [comment]
see https://github.com/mozilla-tw/FirefoxLite/pull/4536
