### ISSUE TITLE
Need telemetry for travel - removing like from content home

### ISSUE THREAD

**Issue by lanyliu** [mozilla-tw/FirefoxLite#4537]
**Describe the bug**
Found a missing data point for removing like

**Steps To Reproduce**
1. Click travel content hub
2. Switch to bucket list
3. Remove like directly 
4. Non of pings on firebase debug view

**Expected behavior**
see [spec](https://docs.google.com/spreadsheets/d/1UinEVG2trRLeUoHtB-5lvLtUr3oFWCWT8Wh_osSAGmM/edit#gid=888392947&range=F41) row 41

method: change, 
object: setting, 
value: content_home
extra:
- vertical=(shopping|game|travel|lifestyle|rewards)
- category: explore|bucket_list
- item_name: "vn-ho chi minh" (2 digit country code + '-' + city name, in lower case)
- item_id: from backend
- subcategory id (pre-defined for detail page)
- version id (current timestamp when loading)
- action: save|remove

**Device info (please complete the following information):**
 - Version 2.1.0(17658)

**Comment by benjamin-cheng** [comment]
As PM request, remove the unlike feature in travel bucket listing. So, it's an invalid issue now.
