### ISSUE TITLE
[Travel Backend] Monitor if the Youtube API exceed the quota

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4538]
**User story**
We need an alert for monitoring if we're going to exceed **60%** and **80%** of the Youtube API quota within a day.

**Comment by tinahsieh** [comment]
Need a further discussion for how we want to handle the issue once the alert triggered.

**Comment by cnevinc** [comment]
Please help add Logging for below keywords in the log-based metrics

1. cache_missed
```
resource.type="gae_app"
resource.labels.module_id="default"
logName="projects/zerda-dcf76/logs/appengine.googleapis.com%2Frequest_log"
protoPayload.resource:"/api/v1/video"
"cache_missed"
```

2. cache_expired
```
resource.type="gae_app"
resource.labels.module_id="default"
logName="projects/zerda-dcf76/logs/appengine.googleapis.com%2Frequest_log"
protoPayload.resource:"/api/v1/video"
"cache_expired"
```

3. cache_exception
```
resource.type="gae_app"
resource.labels.module_id="default"
logName="projects/zerda-dcf76/logs/appengine.googleapis.com%2Frequest_log"
protoPayload.resource:"/api/v1/video"
"cache_exception"
```

4. Youtube Quota
```
resource.type="gae_app"
resource.labels.module_id="default"
logName="projects/zerda-dcf76/logs/appengine.googleapis.com%2Frequest_log"
protoPayload.resource:"/api/v1/video"
"quotaExceeded"
```

**Comment by chianger** [comment]
One of the follow up of #4519

**Comment by chianger** [comment]
Nevin working on it and need daisy to configure once done

**Comment by Daisy-pliu** [comment]
verify:✅
Env: google cloud build production 
logging matrix and sink are added so target logging mesaage are able to auto sync on BigQuery.
![Screen Shot 2020-01-16 at 11 48 57 AM](https://user-images.githubusercontent.com/44990878/72491824-3540bf00-3856-11ea-81e3-87fd1bb9f520.png)
