### ISSUE TITLE
[Travel] Replace the background color for Youtube topsite

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4539]
**Describe the bug**
Per the request from #4519, let's change the bg color of the Youtube topsite icon.

@FinnickC Could you please define a background color here? Thanks!
@proevan Can you share the screenshot after it's done?
CC @Jacklin-ux

**Comment by FinnickC** [comment]
UI Spec
https://zpl.io/adN66KR

**Comment by weslyhuang** [comment]
per Dec. 23 5pm discussion, this is not blocking Travel release. (need to fix this asap, though)

**Comment by Conjuror** [comment]
Verified on v2.1.2 and current nightly build
