### ISSUE TITLE
sync failed firefox 2.0.5 (release version .zip)

### ISSUE THREAD

**Issue by rahuldeshwal21** [mozilla-tw/FirefoxLite#4545]
gradle version 6.0.1
android studio 3.5 
**Describe the bug**
ERROR: Unable to resolve dependency for ':app@previewWebkitRelease/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@previewWebkitReleaseUnitTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitCoverage/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitCoverageUnitTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitDebug/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitDebugAndroidTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitDebugUnitTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitRelease/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitReleaseUnitTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitFirebase/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@focusWebkitFirebaseUnitTest/compileClasspath': Could not resolve project :permissionhandler.
Show Details
Affected Modules: app

**Comment by Conjuror** [comment]
@rahuldeshwal21 Can you check if you walk through https://github.com/mozilla-tw/FirefoxLite#build-instructions steps? Thank you.
