### ISSUE TITLE
Data review request: verticals (News, Game, Shopping, Travel)

### ISSUE THREAD

**Issue by weslyhuang** [mozilla-tw/FirefoxLite#4564]
1. What questions will you answer with this data?

- We want to understand deeper about how our users interact with the new vertical features we delivered with the launch of Firefox Lite 2.0 wave#1 (News, Game, Shopping) and wave#2 (Travel).

 
2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

- We’d like to get product insights to enhance the user experience from different perspectives (UI design, feature roadmap planning & prioritization, …) and increase user engagement and retention that benefit Mozilla’s 2019 goal of Reach and Resilience.

 
3. What alternative methods did you consider to answer these questions? Why were they not sufficient?

- We don't have any other than user survey and user research, but that is not enough to get granular detailed data.

 
4. Can current instrumentation answer these questions?

- No.

 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.

- All the 23 pings here for review (listed below) are Category 2 “Interaction data”.

 
6. How long will this data be collected? Choose one of the following:

- We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

 
7. What populations will you measure?

- Users in targeting markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)

 
8. If this data collection is default on, what is the opt-out mechanism for users?

- The user can disable "Send usage data" in settings to opt-out.

 
9. Please provide a general description of how you will analyze this data.

- We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and usage over time.

 
10. Where do you intend to share the results of your analysis?

- N/A. Data is for internal feature planning evaluation only

11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

- Yes, Firebase.

**Comment by weslyhuang** [comment]
| No | Event | category | method | object | value | extra |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- |
|V01|Show Logoman|action|show|logoman|""|"type=shopping,game,travel,lifestyle,rewards,weather,null,link=url,deeplink,null,"
|V02|Click Logoman|action|click|logoman|""|"type=shopping,game,travel,lifestyle,rewards,weather,null,link=url,deeplink,null,"
|V03|Click Logoman|action|swipe|logoman|""|"type=shopping,game,travel,lifestyle,rewards,weather,null,link=url,deeplink,null,"
|V04|Click Content Hub|action|click|content_hub|""|"vertical=shopping,game,travel,lifestyle,"
|V05|Reload Content Home|action|reload|content_home|""|"vertical=shopping,game,travel,lifestyle,category=category,"
|V06|Open Category|action|open|category|""|"vertical=shopping,game,travel,lifestyle,category=category,"
|V07|Start Content Tab|action|start|content_tab|""|"vertical=shopping,game,travel,lifestyle,feed=feed,source=source,category=category,component_id=component id,subcategory_id=subcategory id,version_id=version id,"
|V08|End Content Tab|action|end|content_tab|""|"vertical=shopping,game,travel,lifestyle,feed=feed,source=source,category=category,component_id=component id,subcategory_id=subcategory id,version_id=version,session_time=time duration from entering component,url_counts=url counts duration from entering component,app_link=open|install|null,show_keyboard=true|false,"
|V09|Category Impression|action|impression|category|""|"version_id=version id,category=category,impression={subcategory id1: max index, subcategory id2: max index...},"
|V10|Start Vertical Process|action|start|process|"vertical"|"vertical=shopping,game,travel,lifestyle,all,"
|V11|End Vertical Process|action|end|process|"vertical"|"vertical=shopping,game,travel,lifestyle,all,loadtime=[0-9]+,"
|V12|Start Tab Swipe Process|action|start|process|"tab_swipe"|"vertical=shopping,game,travel,lifestyle,all,"
|V13|End Tab Swipe Process|action|end|process|"tab_swipe"|"vertical=shopping,game,travel,lifestyle,all,loadtime=[0-9]+,"
|V14|Start Tab Swipe|action|start|tab_swipe|""|"vertical=shopping,game,travel,lifestyle,feed=feed,source=source,"
|V15|End Tab Swipe|action|end|tab_swipe|""|"vertical=shopping,game,travel,lifestyle,feed=feed,source=source,session_time=time duration from entering component,url_counts=url counts duration from entering component,app_link=open|install|null,show_keyboard=true|false,"
|V16|Click Toolbar - Share/Reload/Back|action|click|toolbar|"share|OPEN_IN_BROWSER|reload|back"|"mode=webview,position=[0-9],vertical=shopping,game,travel,lifestyle,feed=feed,source=source,category=category,component_id=component id,subcategory_id=subcategory id,version_id=version id,"
|V17|Click Toolbar - Tab Swipe|action|click|toolbar|"tab_swipe"|"vertical=shopping,game,travel,lifestyle,rewards,from=home,tab_swipe,"
|V18|Click Tab Swipe Drawer|action|click|drawer|"tab_swipe"|"vertical=shopping,game,travel,lifestyle,rewards,feed=feed,"
|V19|Add Tab Swipe Tab|action|add|tab|"tab_swipe"|"vertical=shopping,game,travel,lifestyle,rewards,"
|V20|Change Tab Swipe Settings|action|change|setting|"tab_swipe"|"feed=feed,"
|V21|Long Press Content Home Item|action|long_press|content_home|"item"|"vertical=shopping|game|travel|lifestyle|rewards,category=browser game|premium game,"
|V22|Click Content Home Contextmenu|action|click|content_home|"contextmenu"|"action=create_game_shortcut|share_game,category=browser game|premium game,"
|V23|App is launched by Game Shortcut|action|launch|app|"game_shortcut"|""

**Comment by weslyhuang** [comment]
@cnevinc would you kind help review it? thank you.

**Comment by cnevinc** [comment]
> 1. What populations will you measure?
> 
> * Users in targeting markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)
1. How about travel and games?
2. If I remember correctly, News is a global feature, not just India.

**Comment by weslyhuang** [comment]
Thanks for the check @cnevinc , the latest status of verticals is recorded in the sheet ["Verticals per Market"](https://docs.google.com/spreadsheets/d/1p52CgIdA9PMNGY4X0keLVq21AzNOg_yo2Qk-_ULVAtM/edit?ts=5d410e53#gid=1071467479), and in short:

1. Shopping is only for Indonesia & India
2. News, Game, Travel are for global.

feel free to let me know if you have any questions. tks.

**Comment by cnevinc** [comment]
The link you provide is not public. So I suggest you remove it. Since all questions are anwsered, I'll give it a R+

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?  
yes

2) Is there a control mechanism that allows the user to turn the data collection on and off? 
yes. There's a "Send usage data " option in the settings page.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
@joechengla @elin-moco @lanyliu 

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice? 
yes

8) Does there need to be a check-in in the future to determine whether to renew the data? 
Yes. https://github.com/mozilla-tw/FirefoxLite/issues/4588

9) Does the data collection use a third-party collection tool? 
Yes(Firebase). But this is covered in the Privacy Notice

**Comment by weslyhuang** [comment]
thanks for the suggestion, updated the comments.
