### ISSUE TITLE
Ship side load APK to partners

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4566]
**User story**
Ship side-load apk to partners for 3 different countries. 

Spec: 
   | Country | Adjust Tracking Name | Adjust Tracker Token | Google Play Tracking Link|
1 | India | 2019_GP_IN_1 | m5p9g0t | https://app.adjust.com/m5p9g0t
2 | Bangladesh | 2019_GP_BD_1 | z6j5pin | https://app.adjust.com/z6j5pin
3 | Thailand | 2019_GP_TH_1 | joyv8c9 | https://app.adjust.com/joyv8c9

**Acceptance Criteria (how do I know when I’m done?)** 
Install customized side-load APK to verify Adjust tracker is embedded in app. 
1. Check APK1 shows India tracker on Adjust console.
2. Check APK2 shows Bangladesh tracker on Adjust console.
3. Check APK3 shows Thailand tracker on Adjust console.

**Additional context**

**Comment by Daisy-pliu** [comment]
verify:✅
India Version: 17781 
<img width="790" alt="Screen Shot 2019-12-26 at 4 11 24 PM" src="https://user-images.githubusercontent.com/44990878/71466951-238e6d80-27fc-11ea-899c-f2c73ea5b49a.png">

Thailand Version: 17784
<img width="796" alt="Screen Shot 2019-12-26 at 4 12 35 PM" src="https://user-images.githubusercontent.com/44990878/71466942-1ec9b980-27fc-11ea-94af-8716b1da7d90.png">

Bangladesh Version: 17783
<img width="835" alt="Screen Shot 2019-12-26 at 4 13 44 PM" src="https://user-images.githubusercontent.com/44990878/71466937-1b363280-27fc-11ea-97c9-e27b28ed8a1d.png">

**Comment by Daisy-pliu** [comment]
Already email to BD team with the Google drive link so that they can send APKs to partners.

**Comment by Daisy-pliu** [comment]
Should be these as below.
 - India (2019Dec_IN_1) : https://app.adjust.com/u9efrhh
 - Bangladesh (2019Dec_BD_1) : https://app.adjust.com/ryba7dp
 - Thailand (2019Dec_TH_1) : https://app.adjust.com/j588882

**Comment by StellaTseng** [comment]
India Version: 17976
<img width="825" alt="image" src="https://user-images.githubusercontent.com/34704183/71891967-c347e600-3182-11ea-9dfb-2999ac0a4ccd.png">

**Comment by Daisy-pliu** [comment]
TH: 17978
<img width="786" alt="Screen Shot 2020-01-07 at 7 22 09 PM" src="https://user-images.githubusercontent.com/44990878/71892088-0c983580-3183-11ea-9ec1-3cd3ffb3a253.png">

BD 17977:
<img width="781" alt="Screen Shot 2020-01-07 at 7 20 46 PM" src="https://user-images.githubusercontent.com/44990878/71892089-0c983580-3183-11ea-8d48-6f85dda3391d.png">
TBC:17979
<img width="804" alt="Screen Shot 2020-01-07 at 7 19 11 PM" src="https://user-images.githubusercontent.com/44990878/71892090-0d30cc00-3183-11ea-90d4-0a4335bfddd9.png">
