### ISSUE TITLE
Add touch feedback to menu button and url bar

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4570]
This is related to #4472 
We are still missing a few touch feedback, as shown below:

![Screenshot_2019-12-27-11-01-20-787_org mozilla rocket](https://user-images.githubusercontent.com/8919308/71499683-9a7b4300-289c-11ea-8d6c-c76a8b721b82.jpg)
![Screenshot_2019-12-27-11-01-22-997_org mozilla rocket](https://user-images.githubusercontent.com/8919308/71499684-9a7b4300-289c-11ea-9803-91b16cc4ed71.jpg)
![Screenshot_2019-12-27-11-01-24-977_org mozilla rocket](https://user-images.githubusercontent.com/8919308/71499685-9a7b4300-289c-11ea-929a-69b65f1f0524.jpg)
![Screenshot_2019-12-27-11-02-16-954_org mozilla rocket](https://user-images.githubusercontent.com/8919308/71499686-9b13d980-289c-11ea-958e-120cc25ccac0.jpg)

Let's prioritize this for the next sprints.

**Comment by youwenliang** [comment]
@FinnickC let me know if there's anything missing, and please provide zeplin spec for these, thanks!

**Comment by FinnickC** [comment]
UI spec
**Bookmark**
https://zpl.io/bLnJZQG
**Download**
https://zpl.io/bJ0LXRx
**History**
https://zpl.io/bLnJZl6
**My Shot**
https://zpl.io/259jXDr

**Comment by chianger** [comment]
As spec provided in above comment

**Comment by Conjuror** [comment]
Most of the issues are fixed. We are waiting URL bar to have touch feedback to close the issue.
