### ISSUE TITLE
Distribute APK to Xiaomi & Samsung Store v2.1.2

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4573]
**User story**
Distribute v2.1.2 to Xiaomi and Samsung Store with specified Adjust tracker

**Acceptance Criteria (how do I know when I’m done?)** 
1. customized APK1 shows correct Samsung tracker
2. customized APK2 shows correct Xiaomi tracker

**Additional context**
Need US team upload APK so tracking from Bugzilla 
Samsung https://bugzilla.mozilla.org/show_bug.cgi?id=1606064
Xiaomi https://bugzilla.mozilla.org/show_bug.cgi?id=1606065

**Comment by Daisy-pliu** [comment]
Adjust verify :✅
version: 17809 Samsung store
Adjust verify :✅
version: 17810 Xiaomi store

Uploaded 2 APKs to Bugzilla.
Slack discussion : [distrubution info and Adjust tracker](https://mozilla.slack.com/archives/CMP856PSM/p1577436634040900?thread_ts=1577432544.037100&cid=CMP856PSM)

**Comment by chianger** [comment]
I saw this was closed but actually not yet shipped to both stores. We will keep track this on bugzilla. 
Samsung https://bugzilla.mozilla.org/show_bug.cgi?id=1606064
Xiaomi https://bugzilla.mozilla.org/show_bug.cgi?id=1606065
