### ISSUE TITLE
Data Review Request - Platform Data Review

### ISSUE THREAD

**Issue by vanceyen** [mozilla-tw/FirefoxLite#4576]
- What questions will you answer with this data?

    We want to understand deeper about how our users interact with the new general browser UI designed/features we delivered with the launch of Firefox Lite 2.0 wave#1 (News, Game, Shopping) and wave#2 (Travel).

- Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?

    We’d like to get product insights to enhance the user experience from different perspectives (UI design, feature roadmap planning & prioritization, …) and increase user engagement and retention that benefit Mozilla’s 2019 goal of Reach and Resilience.
 - What alternative methods did you consider to answer these questions? Why were they not sufficient?
    
    We don't have any other than user survey and user research, but that is not enough to get granular detailed data.
- Can current instrumentation answer these questions?
    
    No.
- List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
    
    All the 41 pings here for review (listed below) are Category 2 “Interaction data”.
- How long will this data be collected? Choose one of the following:

    We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.
- What populations will you measure?

    Users in targeting markets. Including Indonesia (for e-commerce life feed) and India (for news life feed)
- If this data collection is default on, what is the opt-out mechanism for users?

    The user can disable "Send usage data" in settings to opt-out.
- Please provide a general description of how you will analyze this data.

    We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate, CTR and usage over time.
- Where do you intend to share the results of your analysis?

    N/A. Data is for internal feature planning evaluation only
- Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?

    Yes, Firebase.

**Comment by vanceyen** [comment]
The following are the 41 pings that belong to general browser features/UI designs from [the list of wave#1 + wave#2 pings that need data review](https://docs.google.com/spreadsheets/d/1D0Xle8EKOm7x_DM9oHzbuG4RNCVUOSQaWpOuRgxAkDA/edit#gid=0).

| No | Event | category | method | object | value | extra |
| ---- | ---- | ---- | ---- | ---- | ---- | ---- |
|V01|App is launched from Private Shortcut|action|launch|app|"private_mode"|"from=[launcher|external_app],"
|V02|Show private shortcut prompt|action|show|private_shortcut|""|"mode=private_mode,"
|V03|Click private shortcut prompt|action|click|private_shortcut|"[positive|negative|dismiss]"|"mode=private_mode,"
|V04|Users clicked on a Setting|action|click|setting|"pref_private_shortcut"|"
|V05|Exit private mode|action|click|private_mode|"exit"|"from=[system_back],mode=private_mode,"
|V06|Private shortcut created|action|pin_shortcut|private_shortcut|""|"mode=private_mode,"
|V07|Kill app|action|kill|app|""|"mode=private_mode,"
|V08|Show TabTray from Toolbar|action|show|tab_tray|"toolbar"|"version=2,mode=[webview|menu],position=[0-4],"
|V09|Show Menu from Toolbar|action|show|menu|"toolbar"|"version=2,mode=[webview|menu],position=[0-4],"
|V10|Click Toolbar - Forward|action|click|toolbar|"forward"|"version=2,mode=[webview|menu],position=[0-4],"
|V11|Click Toolbar - Reload|action|click|toolbar|"reload"|"version=2,mode=[webview|menu],position=[0-4],"
|V12|Click Toolbar - Share Link|action|share|toolbar|"link"|"version=2,mode=[webview|menu],position=[0-4],"
|V13|Click Toolbar - Add bookmark|action|share|toolbar|"bookmark"|"version=2,to=true,false,mode=[webview|menu],position=[0-4],"
|V14|Click Toolbar - Pin shortcut|action|pin_shortcut|toolbar|"link"|"version=2,mode=[webview|menu],position=[0-4],"
|V15|Click Toolbar - Take Screenshot|action|click|toolbar|"capture"|"version=4,category=category name,category_versio=category version,mode=[webview|menu],position=0-4,"
|V16|Click Top Site|action|open|home|"link"|"on=Top Site Position,source=Preset Top Site like **,version=2,"
|V17|Show SearchBar by clicking SEARCH_BUTTON|action|show|search_bar|"search_btn"|"version=2,mode=[webview|menu],position=[0-4],"
|V18|Add Tab from Toolbar|action|add|tab|"toolbar"|"version=2,mode=[webview|menu],position=[0-4],"
|V19|Enter Landscape Mode|enter landscape mode|change|landscape_mode|"enter"|"
|V20||Exit Landscape Mode|enter landscape mode|change|landscape_mode|"exit"|"duration=duration in ms,"
|V21|Show in-app update intro dialog|action|show|update_msg|""|"from_build=old version,to_build=new version,"
|V22|Show google play's in-app update dialog|action|show|update|""|"from_build=old version,to_build=new version,"
|V23|Click in-app update intro dialog|action|click|update_msg|"positive,negative"|"from_build=old version,to_build=new version,action=dismiss,force_close,"
|V24|Show google play's in-app update dialog|action|show|update|""|"from_build=old version,to_build=new version,"
|V25|Show in-app update install prompt|action|show|update|"downloaded"|"from_build=old version,to_build=new version,type=new,reminder,"
|V26|Click in-app update install prompt|action|click|update|"apply"|"from_build=old version,to_build=new version,source=notification,snackbar,type=new,reminder,"
|V27|Show Firstrun Onboarding|action|show|onboarding|"firstrun"|"
|V28|Show Whatsnew Onboarding|action|show|onboarding|"whatsnew"|"
|V29|Click Firstrun Onboarding|action|click|onboarding|"firstrun"|"on=time spent on page,page=[0-9],finish=true,false,"
|V30||Click Whatsnew Onboarding|action|click|onboarding|"whatsnew"|"on=time spent on page,page=[0-9],finish=true,false,"
|V31|Show Firstrun Contextual Hint|action|show|contextual_hint|"firstrun"|"message_id=message id,"
|V32|Show Whatsnew Contextual Hint|action|show|contextual_hint|"whatsnew"|"message_id=message id,"
|V33|Click Firstrun Contextual Hint|action|click|contextual_hint|"firstrun"|"message_id=message id,on=time spent on page,page=[0-9],finish=true,false,"
|V34|Click Whatsnew Contextual Hint|action|click|contextual_hint|"whatsnew"|"message_id=message id,on=time spent on page,page=[0-9],finish=true,false,"
|V35|Get Notification|action|get|notification|""|"link=url,deeplink,null,message_id=messageId,"
|V36|Show Notification|action|show|notification|""|"link=url,deeplink,null,message_id=messageId,"
|V37|Dismiss Notification|action|swipe|notification|"dismiss"|"link=url,deeplink,null,message_id=messageId,"
|V38|Open Notification|action|open|notification|""|"link=url,deeplink,null,message_id=messageId,background=true|false,"
|V39|Show In-App Message|action|show|message|"in_app_message"|"link=url,deeplink,null,message_id=messageId,"
|V40|Click In-App Message|action|click|message|"in_app_message"|"link=url,deeplink,null,message_id=messageId,primary=true,false,"
|V41|Pin Topsite|action|pin|home|"link"|"source=buka|toko...|null,position=[0-9],"

**Comment by cnevinc** [comment]
1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?  
yes

2) Is there a control mechanism that allows the user to turn the data collection on and off? 
yes. There's a "Send usage data " option in the settings page.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
@joechengla @elin-moco @lanyliu 

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice? 
yes
8) Does there need to be a check-in in the future to determine whether to renew the data? 
Yes. https://github.com/mozilla-tw/FirefoxLite/issues/4588

9) Does the data collection use a third-party collection tool? 
Yes(Firebase). But this is covered in the Privacy Notice
