### ISSUE TITLE
AB test red dot apply for all (target jan-6)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4580]
https://github.com/mozilla-tw/FirefoxLite/issues/4383
AB test result: https://docs.google.com/spreadsheets/d/1lo2BQ0jF4VNPQdR1eWjz2J0kkrMSga4QBJgmdWhQf1g/edit#gid=1747086063

ID : success ; IN: no significant different but still okay.
No negative effect (cause only show once)

Conclusion: 
- Release on next version after Friday(1/3). 
- App version after: 2.1.2(17721)
- All red dots version ; apply for all 

Metric:
New users CTR for verticals from content home after release. 
https://analytics.amplitude.com/mozilla-corp/chart/oam2krb

**Comment by chianger** [comment]
Confirmed this is a pure remote config effort.

**Comment by chianger** [comment]
Per discussion let's do it on Jan-6, Monday.

**Comment by Daisy-pliu** [comment]
verify:✅
version : Firefox Lite 2.1.4(17907)
Remote config for "str_content_hub_unread_enabled_items" is completed. 
A. Indonesia & India: all vertical
B. Other countries : travel , news ,games
