### ISSUE TITLE
Cannot remove cities from bucket list in Travel directly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4587]
**Describe the bug**
As title

**Steps To Reproduce**
Prerequisite:
1. Cities in bucket list
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [Bucket List]
4. Tap on [heart icon] to remove city

**Expected behavior**
Selected City is removed

**Actual behavior**
Visit City detail page

**Device info (please complete the following information):**
 2.1.3 (17894)

**Reproduce rate**
5/5

**Additional context**

**Comment by Conjuror** [comment]
This is a feature change in offline discussion.

**Comment by benjamin-cheng** [comment]
Related to #4537
