### ISSUE TITLE
Raise YouTube data api quota

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4590]
Follow up of #4519

**Comment by niyali** [comment]
Good news!
Our application has been approved and the quota is now 175,000 units / day.
Confirmed on GCP API portal. 

<img width="893" alt="Screen Shot 2020-01-04 at 2 01 45 PM" src="https://user-images.githubusercontent.com/1436482/71760574-ccbf1d00-2efa-11ea-8a4f-ad8e6f1df8ad.png">

Thank you team!

**Comment by chianger** [comment]
awesome!
