### ISSUE TITLE
 AB test: Put Vertical Icons into Top Site - onboarding display area(2/4)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4592]

**Comment by shsu571** [comment]
https://github.com/mozilla-tw/FirefoxLite/issues/4522

**Comment by shsu571** [comment]
Current: onboarding vertical icons -> locked the display area
Expect: display area to change with the vertical icons (flexible)

**Comment by TLHuang** [comment]
Update onboarding for vertical icons on topsites, let me know if any questions.
Visual spec here https://zpl.io/V0wXXpO

**Comment by Daisy-pliu** [comment]
**verify:** ❌
**version:**
2.1. 9(18655)
**test step:**
**SC1: Content hub in top site**
1. insert indo SIM
2. launch nightly
**result:**
2.1 see wrong text on boarding message
2.2  wrong onbaording UI layout
2.3 see 4 verticals
**expect:**
2.1 see on boarding message without shopping deals promotion
2.2 see correct UI layout
2.2 see 3 verticals

**screenshot :**
2. ![Screenshot_20200221-172409_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/75026995-d1ef2000-54d8-11ea-812f-18e8240d68c1.jpg)


**Note:** 
After launch again it shows correct 3 verticals. 

**SC2: Content hub as original**
1. insert indo SIM
2. launch nightly
3. kill app and relaunch 
3. long tap [Tokopedia] on default top site
4. long tap [Youtube] on remote config topsite
**result:**
4.1. no action menu 
4.2. Action menu is placed next to [Tokopedia] 
**expect:**
4.1. no action menu 
4.1 action menu should be placed next to [Youtube]

**Comment by Daisy-pliu** [comment]
verify: ✅
verison: 2.1.9 (81705) release
