### ISSUE TITLE
AB test: Put Vertical Icons into Top Site - AB test group method(3/4)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4593]

**Comment by shsu571** [comment]
https://github.com/mozilla-tw/FirefoxLite/issues/4522
Needs to discuss with @lanyliu  and  @mxlius

**Comment by shsu571** [comment]
current:
- telemetry client id -> hash  put into bucket
- 1-20 bucket (last time -> Evan)

**Comment by shsu571** [comment]
confirm with @proevan  : @shsu571 will confirm with BI bucket and provide by 2/14

**Comment by shsu571** [comment]
Spec check notes:
- New grouping: control vs test (2 groups) ; both have onboarding and red dot!
- BI wiill provide Bucket group allocation and data needs to send to telemtry 

doc: https://docs.google.com/document/d/1klSKuaArAhS0O-HcwM6qYd9xt3jx8uWAPXhqaD96vxI/edit

**Comment by lanyliu** [comment]
**分組方式**
A group: 控制組
experiment_bucket: 1-9
experiment_name: content_position_control

B group: 實驗組
experiment_bucket: 10-18
experiment_name: content_position_topsite

AA group: AA test用
experiment_bucket: 19-20
experiment_name: (null)

**分析Note**
鎖版本&鎖國家（IN,ID）

**Comment by shsu571** [comment]
This ticket need to do more telemtry checking. Please @Daisy-pliu  and @Conjuror tag @shsu571 , @lanyliu and @elin-moco after you finished testing!

**Comment by Daisy-pliu** [comment]
verify: ✅
Version: 2.1.9 (18655)
refer : #4592 
test case: [TCP042](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C46)

**Comment by Conjuror** [comment]
There's no easy way to verify the grouping mechanism. According to the code review, it shoud work as the code. Mark as verified

**Comment by Daisy-pliu** [comment]
since it has dependency with #4592 and it verified failed. Data team need to wait until issue fixes to verify telemetry.
