### ISSUE TITLE
AB test: Put Vertical Icons into Top Site - red dot on the icon(4/4)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4594]

**Comment by shsu571** [comment]
https://github.com/mozilla-tw/FirefoxLite/issues/4522

**Comment by shsu571** [comment]
Need to also apply the red dot on the vertical item

**Comment by shsu571** [comment]
Note: https://github.com/mozilla-tw/FirefoxLite/issues/4522
BI for red dot release and the experiement set needs to have red dot too

**Comment by Daisy-pliu** [comment]
verify: ✅
Version: 2.1.9 (18655)
refer : #4592 
test case: [TCP042](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C46)
