### ISSUE TITLE
Could not determine the dependencies of task ':app:compileFocusWebkitDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by gh-debug** [mozilla-tw/FirefoxLite#4600]
FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':app:compileFocusWebkitDebugJavaWithJavac'.
Could not resolve all task dependencies for configuration ':app:focusWebkitDebugCompileClasspath'.
Could not resolve project :permissionhandler.
Required by:
project :app
> Unable to find a matching configuration of project :permissionhandler: None of the consumable configurations have attributes.

**Comment by mxlius** [comment]
We put this module as a git submodule, so you need to update/sync after checkout/clone the source.
```
git submodule update
git submodule sync
```
We will update the README for this detail. Thanks!
