### ISSUE TITLE
Firebase notifciation audience amount vs sending amount - data checking

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4602]
Data checking:
Format: push notification
- Confirm audience amount
- Send notification amount

If possible, would also like to know sending time.

**Comment by elin-moco** [comment]
Take the rewards push in Indonesia for example,
the Audience size is 78K, but sends only 26K (33% of audience),
on the first day 14K received (54% total sends), 
on the 2nd day 1.7K received (60% total sends)
