### ISSUE TITLE
Can not update Lang immediately on India News after user change lang preference

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4607]
**Steps To Reproduce**
1. vpn in India
2. launch app
3. tap [news]
4. tap [preference settings]
4. select[language : india]
5. tap [back] on top left side

**Expected behavior**
it should change news with Indian lang immediately which is expected in 1.9 X build

**Actual behavior**
It does not change lang to Indian immediately. 

**Device info (please complete the following information):**
 - Device: Pixel 8.1.0
- version : 2.1.4 (17907)

**Reproduce rate**
10/10

**Additional context**
After making cahnge, user should go out to revisit news or tap [refresh] button to see lang change.

**Comment by youwenliang** [comment]
This issue is non-blocking since users can still see the lang changes if they reopen News or click refresh. I'll mark this as P1 but should be fixed in the future sprint.

**Comment by chianger** [comment]
Putting this to next sprint so that we don;t forget to discuss it.
