### ISSUE TITLE
Crash when a not encoded HTTP url opened by our App

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4609]
**Describe the bug**
Crash report
https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/aaac019907809a095b592b47279e0b47?time=last-seven-days

**Test steps**
When user long click a not encoded url and open it in our Firefox Lite browser,  It will crash.

**Cause**
it is a regression as we did not happened before.
Ideally, deep link and http url handing should be separate, and not affecting each other.
However, we use the same function to handle. So After the deep link is implemented it does not handle a link correctly, which affecting our normal url handling.

**Comment by chianger** [comment]
see also #4604

**Comment by shsu571** [comment]
Confirm with Release manager @Daisy-pliu  and Engineer @proevan 
This is needed for hotfilx event the crash rate is not high at moment 

<img width="1023" alt="螢幕快照 2020-01-08 上午11 22 13" src="https://user-images.githubusercontent.com/52307187/71947865-241a0180-3209-11ea-91b9-617f4fdb9aad.png">

<img width="1276" alt="螢幕快照 2020-01-08 上午11 17 02" src="https://user-images.githubusercontent.com/52307187/71947736-c2f22e00-3208-11ea-94f7-f075a294f6da.png">

Bug fix deadline 1/9 12:00
QA 1/9 afternoon
Release on 1/9 

current action: keep current adoption rate wait for hotfix to raise the adoption rate @Daisy-pliu

**Comment by Daisy-pliu** [comment]
2.1.4 50% production has been halted rolling out and we are targeting to generate hot-fix build tomorrow.
