### ISSUE TITLE
Increase Youtube API query times in Preview

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4611]
As mentioned in the standup meeting, we'll also need to increase Youtube API query for Preview version to insure our dogfooding process won't be blocked.

Will need to follow the same procedure here #4527
@niyali will you be able to help with this? 
Let me know if you need any support or have any questions, thanks!

**Comment by niyali** [comment]
Application filed and got response from Youtube team.
Our youtube icon broke their branding guideline. 
Forwarding the email to Mark and Tina. 
IIRC, we've fixed it while we applied for more quota for production version. 

@youwenliang  @tinahsieh idea?

**Comment by youwenliang** [comment]
@tinahsieh  I thought we already fixed the branding guideline issue?
@niyali Did they mention any specific reason?

**Comment by niyali** [comment]
@youwenliang email forwarded. 
screenshot attached. 
![violated-youtube](https://user-images.githubusercontent.com/1436482/73439378-cbdda780-434f-11ea-8c41-01d3c1cabd0c.png)

**Comment by niyali** [comment]
Thanks @tinahsieh nailing the issue. 
The icon caption should be "You**T**ube". 
Issue #4680 filed and temporarily assigned to Max for now. 

Thanks.

**Comment by niyali** [comment]
Sorry for the late reply. 
The quotation has been raised at March 27 to 100,000 units/day
