### ISSUE TITLE
As a user, if no result for Travel Discovery search, no response on search button

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4617]
**Describe the bug**
As title, if Travel discovery is set as default, users cannot user Google to search cities.

**Reproduce steps**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [search bar] and search for a city
4. Tap on a city to detail view
5. Tap on [Back key] to exit detail view
6. Tap on [Set as default]
7. Search a city name which has no response from search API, i.e. "大鵬灣"

Expected Result:
7. Search by Google

Actual result:
7. No response

**Comment by Conjuror** [comment]
Related to #4484

**Comment by Conjuror** [comment]
Concluded, we need a page for no search result.

Here's another reproduce steps
**Reproduce Steps**
1. Launch Firefox Lite
2. Tap on [Travel]
3. Tap on [Search bar]
4. Type "大鵬灣"
5. Press [Search/Enter]

Expected Result:
5. Search with Google

Actual Result:
5. No response and no information

**Comment by tinahsieh** [comment]
UX spec: https://mozilla.invisionapp.com/share/EWSX97EB69J#/404999237_6-1_No_Search_Results

The copy string is still under review. I'll be updated on both spec and .xml when it's ready.

**Comment by TLHuang** [comment]
The visual spec is ready, please find it here https://zpl.io/bejMG0p

**Comment by Conjuror** [comment]
18889
