### ISSUE TITLE
Reserve "Travel Discovery" as a term that doesn't need to translate on pontoon

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4620]
As title.
Per our discussion we need to keep "Travel Discovery" as a feature name for all countries so don't need to translate it on pontoon.
Add this ticket for tracking.

**Comment by benjamin-cheng** [comment]
@youwenliang @Conjuror 

We should follow the procedure to safely update the string in the existing code

- [ ] PM adds the new strings with new string ids (Don't override the existing strings)
- [ ] Engineer modify the code to reference the new string ids
- [ ] PM removes those strings which have been replaced and no longer used
- [ ] EPM team files l10n PR

**Comment by tinahsieh** [comment]
Hey @benjamin-cheng, no prob, I'll work on it :)

**Comment by Conjuror** [comment]
https://github.com/mozilla-l10n/zerda-android-l10n/pull/63

**Comment by Conjuror** [comment]
18876

**Comment by benjamin-cheng** [comment]
Checked with @tinahsieh, the whole requirement is `Travel Discovery` should not be translated from Protoon, however, let marketing team decide the localized translation instead. Refer to the issue #4812.
