### ISSUE TITLE
Need to have a better error handle for incoming deeplink

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4621]
**Describe the bug**
We need a better deeplink error handling
#4604 

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on [search bar] and type "rocket://content/hihi"
3. Tap on Enter/Search
4. Tap [open once]
5. Tap [always open with Firefox Lite]

**Expected behavior**
4. 5. Have error handling for it

**Actual behavior**
4. 5. Loop to open an invalid deeplink

**Comment by chianger** [comment]
Non blocking to current sprint but let's discuss in next sprint.

**Comment by chianger** [comment]
non-blocking to travel vertical announcement but blocking deep link relevant campaign. Tagging current sprint to track.

**Comment by shsu571** [comment]
wrong deeplink error handle
expect behavior: when open wrong deeplink -> we need to have error handle behavior
Wendy will discuss with ux to decise what if deeplink is not correct, what is the behavior we would like to have

To do:

    UX spec of error handling
    discuss with engineer and releasing manger and about release schedule

**Comment by shsu571** [comment]
![Screenshot_20200113-102651](https://user-images.githubusercontent.com/52307187/72232471-527a5100-35fc-11ea-8b96-cef8463b8c12.png

**Comment by shsu571** [comment]
![Screenshot_20200113-102651](https://user-images.githubusercontent.com/52307187/72232480-5f974000-35fc-11ea-935a-b6ce96b4a792.png)

**Comment by proevan** [comment]
I will suggest that we can just ignore any unsupported deep link. I'll ignore them for now.
