### ISSUE TITLE
Blank page when Deep link with utm parameter

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4625]
**Describe the bug**
When a Deeplink with utm parameter it will direct user to blank page.  

**Steps To Reproduce**
1. launch app
2. tap [search]
3. insert `rocket://content/news/item?url=https%3A%2F%2Fwww.newspointapp.com%2Fenglish-news%2Fpublisher-lifeberry%2Ftravel%2F5-most-oldest-yet-alive-cities-india%2Farticleshow%2F145048206a7957e25ac294e41dfde4dadf90310d%3Futm_source%3Dmozilla_notification%26utm_medium%3Dreferral%26utm_campaign%3Dnp&feed=newspoint&source=newspoint`

**Expected behavior**
see certain news page

**Actual behavior**
see blank content tab page

**Screenshots/videos**

**Device info (please complete the following information):**
all
version: 2.1.5 (18027)
**Reproduce rate**
10/10

**Additional context**
Note if remove `utm` related parameter by inserting `rocket://content/news/item?url=https%3A%2F%2Fwww.newspointapp.com%2Fenglish-news%2Fpublisher-lifeberry%2Ftravel%2F5-most-oldest-yet-alive-cities-india%2Farticleshow%2F145048206a7957e25ac294e41dfde4dadf90310d&feed=newspoint&source=newspoint` it will open the news correctly

**Comment by elin-moco** [comment]
This will block D1 push experiment scheduled next week since partners need the utm parameters to be able to track our traffic.

**Comment by chianger** [comment]
non-blocking to travel vertical announcement but blocking deep link relevant campaign. Tagging current sprint to track.
