### ISSUE TITLE
Infinite tab open when wrong deep link path specified (if Lite is set as default)

### ISSUE THREAD

**Issue by elin-moco** [mozilla-tw/FirefoxLite#4626]
Describe the bug
If Firefox Lite is set as default browser, 
and when a deeplink with wrong path specified
it will keep open new tabs infinitely.

Steps To Reproduce
Prerequisites:
   Firefox Lite is set as default browser

    launch app
    tap [search]
    insert rocket://content/lifestyle

Expected behavior
see certain news page

Actual behavior
if set to default browser: infinite loop

Screenshots/videos

Device info (please complete the following information):
all
version: 2.1.5 (18027)
Reproduce rate
10/10

**Comment by elin-moco** [comment]
This is up to PM to determine it's priority.

**Comment by elin-moco** [comment]
Close due to duplication of https://github.com/mozilla-tw/FirefoxLite/issues/4621

**Comment by shsu571** [comment]
wrong deeplink error handle
expect behavior: when open wrong deeplink -> we need to have error handle behavior 
Wendy will discuss with ux to decise what if deeplink is not correct, what is the behavior we would like to have

To do: 
- UX spec of error handling
- discuss with engineer and releasing manger and  about release schedule
