### ISSUE TITLE
Day 1 Notification format - notifcation needs to be expandable 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4636]
**Describe the bug**
Day 1 notification in the prview mode from device -> can't open the notification to see the whole message.

**Steps To Reproduce**
1. Reset and clean data
2. Open App
3. Get Day 1 notification on the device
4. Notification show

**Expected behavior**
With the button and click the butoon to see more detail message

**Actual behavior**
NO button to extend the notification detail

**Screenshots/videos**
![Screenshot_20200114_133923_org mozilla rocket beta](https://user-images.githubusercontent.com/52307187/72317564-a8bac300-36d4-11ea-8b9f-2b977229fbd5.jpg)
![Screenshot_20200114_133923_org mozilla rocket beta](https://user-images.githubusercontent.com/52307187/72317573-af493a80-36d4-11ea-8c92-da7b0493266a.jpg)

**Reproduce rate**
100%

**Comment by chianger** [comment]
need @proevan to assess how dev can do this.

**Comment by shsu571** [comment]
spec change: 
Current 
{
  "message": "I'm Message",
  "push_deep_link": "rocket://content/reward"
}

Add new column: 
- messageId 
- title
{
"messageId ": "testMessageId",
"title" : "test"  
"message": "I'm Message",
 "push_deep_link": "rocket://content/reward",
}
expect result: If we don't fill title, the message will get the position of title.

**Comment by shsu571** [comment]
I will confirm the Telemetry chagne with BI and confirm the spec and update here latter

**Comment by Conjuror** [comment]
@proevan  Format in documentation is wrong

{"messageId":"12345",
"title":"tittttttle",
"message":"Test First Launch Notification ",
"push_deep_link":"rocket://content/reward"}

**Comment by Conjuror** [comment]
![Screenshot_20200305-155744](https://user-images.githubusercontent.com/1625148/75960073-622a5d80-5efa-11ea-8ad4-6a0a2898beec.png)

**Comment by proevan** [comment]
> @proevan Format in documentation is wrong
> 
> {"messageId":"12345",
> "title":"tittttttle",
> "message":"Test First Launch Notification ",
> "push_deep_link":"rocket://content/reward"}

fixed, thanks!
