### ISSUE TITLE
Top-news not translated in Chinese

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#4639]
https://drive.google.com/file/d/1cQrJDhNYh4j4F4TqDUdRD-C0vYkb-psG/view?usp=sharing

**Comment by chianger** [comment]
We actually had the string localized https://pontoon.mozilla.org/zh-TW/firefox-rocket/app.po/?search=top-news&string=199023

**Comment by Conjuror** [comment]
https://github.com/mozilla-tw/FirefoxLite/blob/master/app/src/main/res/values-zh-rTW/strings.xml#L250

**Comment by chianger** [comment]
being work on together with news enhancement.

**Comment by Conjuror** [comment]
build v2.1.7 18148
