### ISSUE TITLE
News shows blank page after change system text font

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4642]
**Steps To Reproduce**
1. VPN in India & launch app
2. tap list of [news]
3. go to [system home] -> tap [system setting] -> [display] -> change font size to [large]
4. tap [recent app]
5. select [Lite preview]app

**Expected behavior**
see list of news

**Actual behavior**
see blank page 

**Screenshots/videos**
![Screenshot_20200115-155413](https://user-images.githubusercontent.com/44990878/72415536-9497c400-37af-11ea-89aa-bd921487e36a.png)

**Device info (please complete the following information):**
 - Device:  Pixel2 (9.0)
 - Veriosn: 2.1.6(18105) nightly
 
**Reproduce rate**
10/10

**Additional context**
the issue is there since 2.0 release as lifestyle becomes a separated activity which is different from 1.9

**Comment by Conjuror** [comment]
18542
