### ISSUE TITLE
Partner's name is partially masked on onboarding messages

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4643]
**Describe the bug**

**Steps To Reproduce**
1. fresh launch app
2. tap [games]
3. tap [any games]
4. tap system back

**Expected behavior**
see onboarding message with full games information 

**Actual behavior**
see onboarding message with partially masked "XRVR"partner's name 

**Screenshots/videos**
![Screenshot_20200115-162816](https://user-images.githubusercontent.com/44990878/72417775-90ba7080-37b4-11ea-9db1-ac67984d1418.png)

**Device info (please complete the following information):**
 - Device: pixel 9.0

**Reproduce rate**
10/10

**Additional context**

**Comment by youwenliang** [comment]
Visual spec here: https://zpl.io/VkW6e3L

**Comment by Conjuror** [comment]
18876

**Comment by youwenliang** [comment]
An extra issue -> https://github.com/mozilla-tw/FirefoxLite/issues/4791
Will fix this next sprint.
