### ISSUE TITLE
[Telemetry] Shopping Search detect text input

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4650]
We would like to collect data regarding the text input behavior in Shopping search to determine how we can optimize the performance & ux in Shopping Search.

In short, we want to know if a user has performed "text input" when seeing the Shopping Search (search UI) before doing the next actions.

Data requested here:
https://trello.com/c/Ut0dRDQg/263-shopping-check-typing-or-not-in-shopping-search

**Comment by youwenliang** [comment]
Will need input from @elin-moco and @benjamin-cheng thanks!

**Comment by lanyliu** [comment]
google doc for data review
https://docs.google.com/document/d/1pCtOtlOHwFTlQYqkoxeSvP22QKITD5w0DasyewxQLGs/edit

telemetry spec
https://docs.google.com/spreadsheets/d/1B4PEDo7XHaAzx21F_QOCeVZH0Dk3NONwzYkMlVJd704/edit#gid=888392947&range=F11

**Comment by benjamin-cheng** [comment]
BI updated `search suggestion` event in the telemetry document. Close by #4776

**Comment by Conjuror** [comment]
Amplitude PR
https://github.com/mozilla/bigquery-etl/pull/781

**Comment by Conjuror** [comment]
Confirmed by BI
