### ISSUE TITLE
Add Dailyhunt logo to Recommended News homepage

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4655]
There should be a Dailyhunt logo on top of the Recommended News page. (as partner requested)
Need UX/VD to update the visual spec and its behavior.

Something like this:
![image](https://user-images.githubusercontent.com/8919308/72589634-c5563580-3936-11ea-840a-0a0d5ee4df35.png)

**Comment by TLHuang** [comment]
The visual is updated, please find it here https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5d70c626caa10e18f37b3ce6

**Comment by chianger** [comment]
HOTFIX for 2.1.8
