### ISSUE TITLE
Not able to be fully recorded news setting status in extra

### ISSUE THREAD

**Issue by lanyliu** [mozilla-tw/FirefoxLite#4657]
**Describe the bug**
As discussed with RD, the original spec for category setting change is not able to exceed 100 chars.
change, setting, lifestyle
extra
- category=[xxx,xxx,xxx,...]

**So we made a change to this spec. Split ping in two parts:**

For category changing
- timing: every clicks
- method/ object/ value: change, setting, category
- extra
  - vertical=lifestyle
  - category=xxx
  - to=true|false
  - personalization=true|false

For settings change (remove category)
- timing: when exit setting
- method/ object/ value: change, setting, lifestyle
- extra
  - vertical=lifestyle
  - personalization=true|false
  - language=xxx

Update telemetry spec here
https://docs.google.com/spreadsheets/d/1NJ-EwtMq3pmSisk6ZCLHH8u1kHQVHHVGu6qfvXOtS7I/edit#gid=888392947

**Device info (please complete the following information):**
 - Version: 2.1.7 (18160) nightly

**Comment by chianger** [comment]
HOTFIX for 2.1.8
