### ISSUE TITLE
Backend tasks (Push server)

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4659]
Backend tasks tracked in https://github.com/mozilla-tw/mango_backend/projects/2

**Comment by chianger** [comment]
This is a multi-sprint task

**Comment by cnevinc** [comment]
This is the APK for dev-testing per our conversation last Friday.
Please note this APK is for pre-UAT testing. Not for test automation.
It's built with a self-signed key and connect to rocket-dev01
[app-focus-webkit-release.apk.zip](https://github.com/mozilla-tw/FirefoxLite/files/4466817/app-focus-webkit-release.apk.zip)

**Comment by chianger** [comment]
Looks like we can close it as per standup note today.

**Comment by Daisy-pliu** [comment]
Please check test report : [push server test report:  UAT Test on Stable-Dev & UAT Test on Staging](https://docs.google.com/document/d/1cWcx2JgW8IIeSy8n3XRTDYLMpT-IoXM3otkPI9il3ds/edit?usp=sharing)

**Comment by chianger** [comment]
So since this is a meta bug, shall we take it as a tracking ticket for "pref on" push services on client side?

**Comment by chianger** [comment]
plan to pref on together with sprint 4-6.

**Comment by Daisy-pliu** [comment]
deployed  0-31 on production.

**Comment by Daisy-pliu** [comment]
Turned on Fireabse remote config setup [bool_is_server_push_enabled = true ]on Prod

**Comment by Daisy-pliu** [comment]
Add push notification service config to [Firefox Lite2.0 Remote config](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1047128443&range=A55)
