### ISSUE TITLE
Redesign search entry page in Shopping Search

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4674]
**User story**
As a visitor/shopper, I want to be able to better understand what Shopping Search is and its benefits before starting to search, so that I can be more confident about trying the Shopping Search feature.

Acceptance Criteria:
- Copywriting describing the introduction of Shopping Search
- Illustration/animation demonstrating what Shopping Search is
- Add trending products as search suggestions
- An onboarding process introducing the updated version of Shopping Search (optional)

**Proposal**
Improve the Shopping Search’s Search UI page by providing a clear message about the benefits and outcomes of using Shopping Search, and use "trending search terms" as suggestions for users to search with one click.

**Comment by youwenliang** [comment]
Will provide detail UX spec this week.

**Comment by tinahsieh** [comment]
Please see the UX spec here: https://mozilla.invisionapp.com/share/WHW18MMQPAX#/405549568_1-1_Smart_Shopping_Search_UI_Flow

Copy strings aren't the final version. They'll be updated on both the UX spec and .xml when they're confirmed.

**Comment by lanyliu** [comment]
done telemetry spec
we extend extra definition for searching from search suggestion

Spec
https://docs.google.com/spreadsheets/d/1u0E87x-Ua5vewbhImb4QfHpJhIKAkXMw00czVMysguM/edit?usp=sharing

Data review
https://docs.google.com/document/d/144QZJGybJFzh4JGUczIhhY4w-OW37SEJI4s63GUBI-c/edit?usp=sharing

**Comment by TLHuang** [comment]
The visual spec is updated https://zpl.io/29RXMJd

**Comment by benjamin-cheng** [comment]
@shsu571 @youwenliang 
I think the issue size should be XL. Suggest to split this issue to three separate issues according to the acceptance criteria (item 1&2 could merge to be one issue).

Acceptance Criteria:
- Copywriting describing the introduction of Shopping Search
- Illustration/animation demonstrating what Shopping Search is
- Add trending products as search suggestions
- An onboarding process introducing the updated version of Shopping Search (optional)

**Comment by youwenliang** [comment]
Thanks for the comment @benjamin-cheng , will seperate this issue into two (we will ignore the optional one for now)

**Comment by chianger** [comment]
Dup of #4788 #4787
