### ISSUE TITLE
Is there a simplified Chinese version of Firefox Lite?

### ISSUE THREAD

**Issue by gh-debug** [mozilla-tw/FirefoxLite#4676]
Is there a simplified Chinese version of Firefox Lite?

**Comment by rxumoz** [comment]
Hi, Beijing Office have maintained a Chinese version of Firefox Lite, you can download it from https://www.firefox.com.cn/mobile/
However we do not always update with the original version at the same time, there might be some delay, just let you know.

**Comment by Conjuror** [comment]
I'll close the issue since @rxumoz has commented on it. Thanks, @rxumoz
