### ISSUE TITLE
Whenever I click on download on a website, the Download starts but my page turns to webpage not available...check your connection.... Etc

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#4677]
https://play.google.com/apps/publish?account=7083182635971239206#BetaFeedbackDetailsPlace:p=org.mozilla.rocket&feedbackid=gp:AOqpTOHl0EG5pBZ45JHwcskUkXU0Gb_ezgCjJNlW5FDLZyGgxlSklFQ2TYE0LJtM2eoZLpiJI5cryPvVJWLSb7wgMQ

**Comment by Conjuror** [comment]
I think this is the correct behavior since the page is unavailable. We might need to discuss if we need to avoid the redirection. For now, I suggest to keep it as is. My two cents.

**Comment by chianger** [comment]
This is current spec. 
We'll revisit it when we plan download manager enhancement.
