### ISSUE TITLE
The app firefox lite  (process org.mozilla.rocket.coverage) has violated its self-enforced Strict Mode policy.

### ISSUE THREAD

**Issue by gh-debug** [mozilla-tw/FirefoxLite#4678]
When I open firefox lite, the pop-up error is as follows. How to fix it?
The app firefox lite  (process org.mozilla.rocket.coverage) has violated its self-enforced Strict Mode policy.

==================
The error message is in：
Android/Sdk/platforms/android-28/data/res/values-en-rAU/strings.xml。

 <string name="smv_application" msgid="3307209192155442829">"The app <xliff:g id="APPLICATION">%1$s</xliff:g> (process <xliff:g id="PROCESS">%2$s</xliff:g>) has violated its self-enforced Strict Mode policy."</string>

**Comment by Conjuror** [comment]
Close the issue since it's not related to Firefox Lite.

For the development issue, you can start with [Strict Mode](https://developer.android.com/reference/android/os/StrictMode) and how to solve it.
