### ISSUE TITLE
How to see Firefox Lite App page on the Xiaomi store?

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4684]
FxLite is now officially on Xiaomi store (regions outside China) https://bugzilla.mozilla.org/show_bug.cgi?id=1606065#c16

**Comment by chianger** [comment]
Reaching out to overseas-dev at xiaomi.com
Let's see how they reply.

**Comment by chianger** [comment]
We know how to verify now. will keep updating https://docs.google.com/spreadsheets/d/1xDUOrHawAVcv41gGGKe5eSBdOq9s6q-ltqLfDteGYP0/edit#gid=151219566
