### ISSUE TITLE
Samsung store 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4685]
Need to track sumsang galaxy store too.
current version 1.2.1
![Screenshot_20200204-133832_Galaxy Store](https://user-images.githubusercontent.com/52307187/73721002-33d02b80-475e-11ea-8ca9-301f6a86ebae.jpg)

**Comment by chianger** [comment]
It's now verified with 2.1.8 up there.
Will keep updating the live doc.
https://docs.google.com/spreadsheets/d/1xDUOrHawAVcv41gGGKe5eSBdOq9s6q-ltqLfDteGYP0/edit#gid=1976875092
