### ISSUE TITLE
Downloading an file from the forum does not work 

### ISSUE THREAD

**Issue by USB3-2-10Gbit** [mozilla-tw/FirefoxLite#4687]
**Describe the bug**
When I download a file with Firefox Lite in MIUI forum it does not work.

## Steps to reproduce

1. Go to https://c.mi.com/thread-2831947-1-0.html and register in this forum.

2. Click on 'Mi Calculator.apk' to download.

3. Downloading an file from this forum does not work.

### Device information

* Android device: Redmi Note 8 (Android 9)
* Firefox Lite version: 2.1.8
https://github.com/mozilla-tw/FirefoxLite/releases/tag/v2.1.8

**Reproduce rate**
Always

**Comment by Conjuror** [comment]
For a large file, it requires more time to accomplish the hand shaking mechanism. From the result of testing on my side, the download works. Please help to provide more information so we can have a deep dive on it. Thank you.
