### ISSUE TITLE
[Remote Config] Switch off Shopping Vertical

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4692]
The decision is to switch off Shopping Vertical due to its performance and will re-evaluate this feature later this year.

Task: Remove Shopping Vertical through Remote Config
Locale: IN & ID
Schedule: End of this week (2/15)
Request owner: Mark
Execution owner: Daisy

Marketing team & Comms team will adjust on their end for this change.

**Comment by Daisy-pliu** [comment]
Env :
1. Nightly 2.1.8(18482) :  ✅
2. Production 2.1.8(18211): ✅
Verify by : PM & Release 
Summary: India & Indo shopping verticals are officially turned off on release build.
