### ISSUE TITLE
Wrong category data in event extra from daily hunt

### ISSUE THREAD

**Issue by yshlin** [mozilla-tw/FirefoxLite#4700]
**Describe the bug**
We just found that in both start__content_tab and open__category events,
the category data in event extra from daily hunt are numbers, which should be strings (like newspoint)

**Steps To Reproduce**

**Expected behavior**
String representation of category

**Actual behavior**
Numbers

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
100%

**Additional context**
Here are the numbers we get when click on the category
- News: 1
- India: 3
- Sports: 5
- Entertainment: 2
- Technology: 6
- Lifestyle: 8
- Business: 7
- World: 4
- Bollywood: 4143
- Hollywood: 4144
- Celebrities: 4145
- Movies: 4148
- Mobiles & Gadgets: 4149
- Science: 4142
- Travel: 4140
- Education and Employment: 4139
- Employment: 4138
- Relationship: 4134
- Recipes: 4133
- Food: 4132
- Gossip: 4131
- Magazing & Articles: 4150
- Relegion & Spirituality: 4130
- Beauty: 4128

**Comment by benjamin-cheng** [comment]
@elin-moco It is the conclusion discussed with @lanyliu to use DailyHunt category id instead of its name since the category name would be localized when user switches to different news languages.

**Comment by yshlin** [comment]
Just confirmed that this behavior is consistent, closing it now.
