### ISSUE TITLE
[Remote Config] Remove Shopping deal related message

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4701]
Currently the "Share with Friends" prompt still mentioned "shopping deals" in IN & ID.
Will need to remove them.

1. Indonesia English
2. Indonesia Bahasa
3. India English

See the image below:

![image](https://user-images.githubusercontent.com/8919308/74318208-c18fc480-4db7-11ea-804e-6a94abf17bbc.png)

**Comment by Conjuror** [comment]
indo english -> 拿掉 shopping deals
indo bahasa -> 拿掉 penawaran belanja
india english -> 拿掉 shopping deals

**Comment by Conjuror** [comment]
done
