### ISSUE TITLE
Pop up : give us feedback wording change

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4704]
**User story**
As a user, I would like to get the popup : give us feedback (add wording give us 5-star! )

**Acceptance Criteria (how do I know when I’m done?)** 
Popup setting: add give us 5-star

**Additional context**
For raising our rating!
12/10 for making Google featuring app -> Google regulation: remove suggestive wording
But we didn't get featuring -> we can move back to " give us 5-star" wording

**Comment by yshlin** [comment]
Here are the previous (before 2019/12/10) translations and configs FYR
https://docs.google.com/spreadsheets/d/1qa4-jpzirHr8oD56LF6UekaFio-4duO4_l4hQe25EEA/edit#gid=2060514788

**Comment by shsu571** [comment]
Need to confirm with @joechengla  Google Policy again before publish

**Comment by shsu571** [comment]
https://play.google.com/about/storelisting-promotional/ratings-reviews-installs/

**Comment by shsu571** [comment]
Preview confirm
![Screenshot_20200217-114421](https://user-images.githubusercontent.com/52307187/74622731-e2bc3080-517c-11ea-848f-2eaa3636ce91.png)

![Uploading Screenshot_20200217-114809.p
![Screenshot_20200217-115001](https://user-images.githubusercontent.com/52307187/74622729-e059d680-517c-11ea-99c5-92a2708a33ad.png)
![Screenshot_20200217-115331](https://user-images.githubusercontent.com/52307187/74622730-e18b0380-517c-11ea-8a4c-c92397acf14c.png)



![Screenshot_20200217-114608](https://user-images.githubusercontent.com/52307187/74622717-da63f580-517c-11ea-8e92-c7f3f0b8fbb3.png)

**Comment by shsu571** [comment]
@Conjuror  published on the production! (2020/2/17 12:00 TPE)

**Comment by Conjuror** [comment]
Close the issue since it's published.
