### ISSUE TITLE
Add Shopee logo for top site uploading preparation

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4707]
For uploading the Shopee logo into production. 
@TLHuang  to help confirm the shopee logo image
@proevan  to transfer file 
![Shopee-72p](https://user-images.githubusercontent.com/52307187/74636384-d0ed8400-51a2-11ea-8776-74de8ba2bf7b.jpg)

Need to upload to this week's release!

**Comment by proevan** [comment]
@shsu571 there's already a shopee icon in the project, are we going to replace it with this new icon?

**Comment by shsu571** [comment]
[Shopee-72p-1-01.svg.zip](https://github.com/mozilla-tw/FirefoxLite/files/4223439/Shopee-72p-1-01.svg.zip)

**Comment by shsu571** [comment]
Could we try this one @proevan ? i will print screen and show  BD

**Comment by shsu571** [comment]
the image name should be the same as previous one(replace pervious image)

**Comment by shsu571** [comment]
Confirm with BD the image is okay! Please build in release version! Thx

**Comment by Conjuror** [comment]
verified in preview build. Icon displays correctly.
