### ISSUE TITLE
[Server Notification] data confirm - export push notification to Bigquery

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4708]
Export push notification to Bigquery
https://firebase.google.com/docs/cloud-messaging/understand-delivery#bigquery-data-export

Purpose: BI data verification ( real cloud msg )

**Comment by cnevinc** [comment]
For @elin-moco  and @lanyliu 
These are the query you can get from the data set:

https://firebase.google.com/docs/cloud-messaging/understand-delivery#what-can-you-do-with-the-exported-data

**Comment by Daisy-pliu** [comment]
Hi all,
release team has setup Firebase cloud messaging integrated with Big Query on Nighly.
Once Bi team finish confirming the data structure in big query matched their expectation ,we will move on to Production.

**Comment by cnevinc** [comment]
Please help enable int in BQ

**Comment by Daisy-pliu** [comment]
Firebase Production integrated with BigQuery is enabled. 
No one's fault here. I think we can have a process by going though all open tickets before we go live.
