### ISSUE TITLE
[Shopping Search] Spike for Flipkart API for search terms

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4709]
**Describe the bug**
We would like to collect terms that are product related so that we can provide better shopping search suggestions. Currently, we might be able to use Flipkart's API to get various product names to populate on our search suggestion field, will need some time to study.

From the initial study, we should be able to use this: https://affiliate.flipkart.com/api-docs/af_prod_ref.html#search-query-based-on-keywords-api

With "search query based on keywords" we can grab a number of product details based on the keywords and display the product titles as our search suggestions.

**Comment by benjamin-cheng** [comment]
@youwenliang List some sample results for reference:


![device-2020-03-02-171720](https://user-images.githubusercontent.com/7045016/75662426-0b2e4980-5caa-11ea-800b-32a8ad2b716f.png)


![device-2020-03-02-171745](https://user-images.githubusercontent.com/7045016/75662553-403a9c00-5caa-11ea-9698-8afc59150e54.png)


![device-2020-03-02-171800](https://user-images.githubusercontent.com/7045016/75662626-5d6f6a80-5caa-11ea-9ab4-80c3cdb823b9.png)


![device-2020-03-02-171856](https://user-images.githubusercontent.com/7045016/75662675-70823a80-5caa-11ea-91d4-bed4538333e7.png)


![device-2020-03-02-171911](https://user-images.githubusercontent.com/7045016/75662699-7c6dfc80-5caa-11ea-9db9-18e7a48d175c.png)

**Comment by youwenliang** [comment]
As discussed yesterday, here are some suggestions:
1. Remove the detail spec (anything in the brackets), and avoid duplicates.
2. Show 3 results from the product api and 2 results from google autocomplete.

**Comment by chianger** [comment]
confirmed with Mark that we consider this spike is done
