### ISSUE TITLE
[News] Feature adjustment based on Dailyhunt's feedback

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4710]
**Describe the bug**
1. change scroll to next page mechanism
2. change "For You" timestamp
3. change Urdu language display
4. Adjust tracking and API response with ComScore attribute

Will describe the above list in more detail later.

**Comment by youwenliang** [comment]
This is the meta bug for 
#4712 
#4713 
#4714 
#4715

**Comment by Conjuror** [comment]
We'll track the issues separately. There's no limitation to have all the issues fixed in the same sprint.
