### ISSUE TITLE
New remote-config on production - logo man banner

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4711]
**Remote config name**
New Remote-config test -> Logoman Banner 
name in preview "str_logo_man_notification"

**Audience setting**
Region: Taiwan 
Language: Tradition Chinese
Excluded: New Users

**Parameter + Audience **
for Taiwan
{"messageId":"try_games__43879",
"title":"免費遊戲，盡情玩",
"subtitle":"不用安裝遊戲程式也能盡情享受超過一百種熱門遊戲, 快來試試！",
"imageUrl":"https://drive.google.com/file/d/11PSi1ICZaXl21JpD_CHX6ifebpIaGuCV/view",
"action":"rocket://content/gmae","type":"game"}

**Expected Online Time**
2/18 after test on preview -> online

**Additional context**
This is for new remote-config test!

**Comment by Conjuror** [comment]
Cannot display full texts. Also, specifying language for Chinese doesn't work
![Screenshot_20200218-150821](https://user-images.githubusercontent.com/1625148/74712168-a2ce7980-5260-11ea-9f48-4c2da8097c6a.png)

**Comment by shsu571** [comment]
changed the photo link
![Screenshot_20200218-152156](https://user-images.githubusercontent.com/52307187/74712959-859aaa80-5262-11ea-9f61-9af630aee035.png)

**Comment by Conjuror** [comment]
bool_msrp_enabled needs to be true to enable logo_man. @proevan is tracking the issue.
