### ISSUE TITLE
[News] Dailyhunt - change next page mechanism

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4712]
**Describe the bug**
Based on Dailyhunt's feedback on next page mechanism:
“For populating the next page, you should use the nextPageUrl fetched as a part of the current response. NextPageUrl contains parameters to take care of the content user has already seen and the same will not be repeated. I suppose currently, you are just updating the pageNumber to fetch new content. This is resulting in repetition of items in the same feed.”

We should change the "scroll to next page" mechanism to avoid repetition.

**Comment by proevan** [comment]
document https://api-syndication.dailyhunt.in/?version=c80c7774-8ab0-4c38-8a30-1a9c760b9817#intro
