### ISSUE TITLE
[News] Dailyhunt - adjust tracking and API response

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4715]
**Describe the bug**
Based on Dailyhunt's feedback: "For ComScore attribution, there is a small update. Now you can fetch the Url from the API dynamically as a part of items API response.
Refer documentation"

Let's see if we can use the updated API response for the tracking mechanism.

**Comment by Daisy-pliu** [comment]
verify : ✅
version Release build 19400 preview
