### ISSUE TITLE
[News] KLY RSS link update

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4717]
**Describe the bug**
The original RSS links for Indonesia is here: https://docs.google.com/spreadsheets/d/1dxh0HDGwoGqaCGtHvM5eHB0uQ0OT9u-YxgX5wW9bAJ0/edit#gid=1978563959

And here are the new ones based on our partner's request: (KLY)

Liputan6.com:
News https://feed.liputan6.com/new/mozilla-news
Technology https://feed.liputan6.com/new/mozilla-technology
International https://feed.liputan6.com/new/mozilla-international
Health https://feed.liputan6.com/new/mozilla-health
Soccer https://feed.liputan6.com/new/mozilla-soccer
Showbiz https://feed.liputan6.com/new/mozilla-showbiz

Bola.com:
E-sport https://feed.bola.com/new/mozilla-esport
Sports https://feed.bola.com/new/mozilla-sports
Indonesian league https://feed.bola.com/new/mozilla-indonesia

Fimela.com:
Fashion https://feed.fimela.com/new/mozilla-fashion
Parenting https://feed.fimela.com/new/mozilla-parenting
Lifestyle https://feed.fimela.com/new/mozilla-lifestyle

**Comment by youwenliang** [comment]
Partner said the old links will be deactivated on March 1.

**Comment by cnevinc** [comment]
> News https://feed.liputan6.com/new/mozilla-news
> Technology https://feed.liputan6.com/new/mozilla-technology
> International https://feed.liputan6.com/new/mozilla-international
> Health https://feed.liputan6.com/new/mozilla-health
> Soccer https://feed.liputan6.com/new/mozilla-soccer

Are International, Soccer new categories?


> Showbiz https://feed.liputan6.com/new/mozilla-showbiz
> 
> Bola.com:
> E-sport https://feed.bola.com/new/mozilla-esport
> Sports https://feed.bola.com/new/mozilla-sports
> Indonesian league https://feed.bola.com/new/mozilla-indonesia
> 

what's the difference between E-sport and Sports?
Is Indonesian league a new category?

> Fimela.com:
> Fashion https://feed.fimela.com/new/mozilla-fashion
> Parenting https://feed.fimela.com/new/mozilla-parenting
> Lifestyle https://feed.fimela.com/new/mozilla-lifestyle

**Comment by youwenliang** [comment]
> > News https://feed.liputan6.com/new/mozilla-news
> > Technology https://feed.liputan6.com/new/mozilla-technology
> > International https://feed.liputan6.com/new/mozilla-international
> > Health https://feed.liputan6.com/new/mozilla-health
> > Soccer https://feed.liputan6.com/new/mozilla-soccer
> 
> Are International, Soccer new categories?
Yes

> 
> > Showbiz https://feed.liputan6.com/new/mozilla-showbiz
> > Bola.com:
> > E-sport https://feed.bola.com/new/mozilla-esport
> > Sports https://feed.bola.com/new/mozilla-sports
> > Indonesian league https://feed.bola.com/new/mozilla-indonesia
> 
> what's the difference between E-sport and Sports?
E-sport is related to gaming (PC & Mobile)
> Is Indonesian league a new category?
Yes
> 
> > Fimela.com:
> > Fashion https://feed.fimela.com/new/mozilla-fashion
> > Parenting https://feed.fimela.com/new/mozilla-parenting
> > Lifestyle https://feed.fimela.com/new/mozilla-lifestyle

**Comment by cnevinc** [comment]
PR: https://github.com/mozilla-tw/mango_backend/pull/235

@youwenliang Could you please update the document? Thank you!

**Comment by youwenliang** [comment]
OK will do, thanks @cnevinc

**Comment by Daisy-pliu** [comment]
> Build `6f28c1ff-c9de-43b5-b025-cf658307c0ba`
<sub>[View in Slack](https://mozilla.slack.com/archives/CJ0LPE7FC/p1584586979000200)</sub>

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.11 (18890) Prod
Device: Redmi 7

1. Deployed to Prod
2. check News in Indo are loaded successfully

**Comment by yshlin** [comment]
Verified receiving start content tab event with source correctly.

**Comment by Daisy-pliu** [comment]
seems good to me on 2.1.12(19131)
