### ISSUE TITLE
Games display incorrectly

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4718]
**Describe the bug**
Games displayed incorrectly

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on game vertical

**Expected behavior**
1. Games show

**Actual behavior**
1. Only category title displays

**Screenshots/videos**
![Screenshot_20200218-160015](https://user-images.githubusercontent.com/1625148/74715804-35bee200-5268-11ea-82c1-d1a99d1f6735.png)

**Device info (please complete the following information):**
 - 2.1.8 (18587)

**Reproduce rate**
5/5

**Additional context**

**Comment by benjamin-cheng** [comment]
Fixed by #4716

**Comment by Conjuror** [comment]
18542
