### ISSUE TITLE
Logoman Banner and MSRP remote config dependency

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4719]
**User story**
As a user, I would like to see Logoman banner even the MSRP feature (bool_msrp_enabled) didn't turn on . Ideally in the implementation, we hope it has no dependency on MSRP.

**Acceptance Criteria (how do I know when I’m done?)** 
UI only shows logoman banner based on (str_logo_man_notification) , but don't show MSRP icon

**Comment by Conjuror** [comment]
18642
