### ISSUE TITLE
Add round corners to the search suggestion buttons in General Search

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4721]
**User story**
Since we'll have a minor visual refresh for the Smart Shopping Search, we'd like to make the search suggestion buttons in General Search to be aligned with the new visual design.

@TLHuang Please update the visual spec here when it's ready, thanks!!!
CC @youwenliang

**Comment by tinahsieh** [comment]
Related to #4674

**Comment by TLHuang** [comment]
Visual spec is ready https://zpl.io/bApEMAn
Let me know if any questions.

**Comment by Daisy-pliu** [comment]
verify:✅
version : 2.1.11(19098) nightly
Device: samsung S6
![Screenshot_20200318-144146](https://user-images.githubusercontent.com/44990878/76932926-fb0f9e80-6926-11ea-91bc-cb6ca00422a8.png)

**Comment by Daisy-pliu** [comment]
verified, refer #4787
