### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by fliteuser** [mozilla-tw/FirefoxLite#4723]
Hi,

I'm new to Android Studio, and try to build Firefox Lite from source into an apk to make some changes for myself.

I'm trying to follow the Readme instructions on github. Installed Android Studio, checked out the Firefox Lite repository, ran "git submodule init" and "git submodule update", and opened the project in Android Studio. The next step would be "select build variant focusWebkitDebug", but for me the menu item "Select Build Variant" is grayed out, and opening the "Build variants" tab in the left bottom corner doesn't show any options. How could I continue to build Firefox Lite?

Thanks.

**Comment by benjamin-cheng** [comment]
Could you help to double check if there is any error messages after the project is imported?(perhaps in the Build tab)

If possible, could you also take a screenshot of your Android studio showing the "Project" and "Build Variants" tabs?

**Comment by Conjuror** [comment]
I'll close the issue since there's no update about it.
