### ISSUE TITLE
Shopee Top Site Update

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4725]
**Title **
Shopee Top Site Update

**Description**
Top Site tracking link renew:
https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0

Add new countries ( Yellow part of the spreadsheet)

**Release Time**
After the test and confirm, we can publish this setting!
Please announce on slack and note in this issue and the spreadsheet when this setting is published!

**Additional context**
Partner data confirm : Shopee data access -> https://docs.google.com/document/d/1VGqum9hQ2ya_1WvLe2RReVTsi-sUy5N7-O3OeqGvAyg/edit

**Comment by shsu571** [comment]
need to wait for next release (new icon) for publish
https://github.com/mozilla-tw/FirefoxLite/issues/4707

**Comment by youwenliang** [comment]
I think the icon is ready, should we put this to this sprint? @shsu571

**Comment by shsu571** [comment]
This will launch with @youwenliang 's shopping search remote confit https://github.com/mozilla-tw/FirefoxLite/issues/4758

**Comment by shsu571** [comment]
Updated new tracking link @Conjuror

**Comment by shsu571** [comment]
@Conjuror  2.1.10 Adoption Rate is 44% and Production 99%. Could you publish on production? Thank you!

**Comment by Conjuror** [comment]
Top Sites configuration is on live now

**Comment by Conjuror** [comment]
Reopen the ticket due to issues on Shopee website. TopSites list is temporarily updated

**Comment by shsu571** [comment]
Click button -> can't go to Google Play Store
Already change to weblink!
