### ISSUE TITLE
Logoman Banner format renew

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4731]
Banner character size is too small. 
UI already renew the font size and color.
https://zpl.io/VxwOJ1k

**Comment by shsu571** [comment]
![Screenshot_20200305-115925](https://user-images.githubusercontent.com/52307187/75946826-2206b300-5ed9-11ea-82fa-ace7b48381ee.png)

**Comment by shsu571** [comment]
![Screenshot_20200305-120732](https://user-images.githubusercontent.com/52307187/75947408-3fd51780-5edb-11ea-8c1e-5971e27414dd.png)

**Comment by Conjuror** [comment]
18876
