### ISSUE TITLE
Can not play certain Gamezop HTML game 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4734]
**Steps To Reproduce**
1. upload game_banner_destination_type in [sheet ](https://docs.google.com/spreadsheets/d/1YEYH7fwWiWJjrSQwBiPul-e0N9B7j0QbemvBtJxmgN8/edit#gid=916540177) Admin console in Nightly
2. launch app 
3.  tap [game ]
4.  tap [banner's gamezop game] 
5.  tap [login]

**Expected behavior**

**Actual behavior**

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds

**Additional context**

**Comment by youwenliang** [comment]
this is dup of #4735
