### ISSUE TITLE
[News] Dailyhunt - update article links with deepLinkUrl + Puid

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4738]
For partner's tracking purpose we need to change the link to: deepLinkUrl+Puid

For example:
http://mozilla.dailyhunt.in/news/india/english/news+nation-epaper-newnatn/samsung+galaxy+z+flip+goes+official+in+india+at+rs+109999+specifications+features+here-newsid-166823716?mode=pwa&s=Mozilla&ss=Browser-Feed&utm_source=Mozilla&utm_medium=Browser-Feed&utm_campaign=Mozilla-Browser-Feed&lite=true&prevRef=mozilla1**&puid=<puid_value>**

**Comment by Conjuror** [comment]
Confirmed that PUID is attached correctly. 2.1.10(18876)
