### ISSUE TITLE
Wrong notification icon in certain device

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4743]
**Steps To Reproduce**
1. launch app
2. relaunch 6 times to see "give feedback" dialog 
3. tap [close]
4. relaunch 6 times to see "give feedback" notification 

**Expected behavior**
see wrong icon

**Actual behavior**
see correct icon

**Screenshots/videos**

![Screenshot_20200224-110558](https://user-images.githubusercontent.com/44990878/75126824-a8abdb00-56f6-11ea-9169-47b4c171711f.png)

**Device info (please complete the following information):**
 - Device: Sumsung S6 edge 
-  Device version: 2.1.9 (18652)
-  App verion: 6.0.1

**Reproduce rate**
10/10

**Additional context**
This happened on since 1.8.1
this issue not on Pixel 9.0 , need to check if it happen on other 6 device.
not happen on VIvio 6.

**Comment by shsu571** [comment]
My Android 10 has this too.
I think this is about language setting? @Conjuror

**Comment by shsu571** [comment]
This is device issue so i think we should not spend effort to fix this.

**Comment by Daisy-pliu** [comment]
Let's close it as the impact and severity is extremely minor.
