### ISSUE TITLE
Adjust SDK update by 3/1

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4748]
**Description**
https://github.com/adjust/android_sdk#qs-install-referrer
In preparation for this change, make sure you have updated your Adjust SDK to version 4.20 AND updated to Google Play Install Referrer API v1.0 or higher.
SDK 4.12 is the lowest version that supports the Install Play Referrer API.

Adjsut sdk update
Need to update by 3/1 -> We will not get data if we don't update.

**Additional context**
Why is this important? (from Adjust)
Adjust attributes Android users using the Google Play Store referrer. This is captured via the Play Referrer API or install_referrer intent broadcast (no longer recommended). After March 1st, the latest Google Play Store app will not broadcast the referrer when a new app is installed. This means the install_referrer will not be able to capture it. In this scenario, Adjust must rely on the device's advertising ID (which is accurate but only available on selected inventories) or on device fingerprinting. Consequently, it is crucial that all apps published on the Google Play Store support the Play Referrer API.

**Comment by shsu571** [comment]
<img width="535" alt="螢幕快照 2020-02-25 下午12 01 19" src="https://user-images.githubusercontent.com/52307187/75213886-8f725f80-57c6-11ea-984a-d1c0da74d084.png">

**Comment by proevan** [comment]
fixed in #4750

**Comment by Daisy-pliu** [comment]
Need data team verify if Adjust is able to get data after 3/1

**Comment by Daisy-pliu** [comment]
> adjust data checked!
2.1.10 vs. 2.1.8 channel % for new user looks similar to each other
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1583380674211500)</sub>
