### ISSUE TITLE
Shopee Shopping Search Update

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4758]
**Remote config name**
str_shopping_search_sites

**Audience setting**
Indonesia, Malaysia, Philippines, Singapore, Taiwan, Thailand, Vietnam

**Parameter + Audience**
The above 7 audiences will need to change Shopee's searchUrl and order.
Change Shopee site's order to No.2, next to Google (No.1)

And change Shopee site's links to tracking links:
See detail in this document(https://docs.google.com/document/d/1EOk8LOmsyD9HhvAUseVIvwl2TD6qaNTvpT-u4oPkceg/edit?usp=sharing)

**Expected Online Time**
Next week (week of 3/2)

**Comment by youwenliang** [comment]
Checked on Preview, all tracking links worked! @Daisy-pliu

**Comment by Daisy-pliu** [comment]
release team updated on Production
