### ISSUE TITLE
Modify the smart shopping search icon to be more recognizable

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#4762]
Based on the quick research around smart shopping search, some users get confused about the relationship between smart shopping search and browsing search through the current icon.

Proposal: emphasizing the shopping bag or shopping-related element, and avoid using the magnifier to distinguish with the browsing search.

cc @youwenliang could you help on the label for this issue, thanks?

**Comment by TLHuang** [comment]
The change will be replace all the shopping search icon with the new one, including:
- Home
- Tab tray
- Prompt in shopping sites
- Shopping search UI input field
- Shopping search switch UI redo search
- Shopping search onboarding

**Comment by youwenliang** [comment]
@benjamin-cheng There are 6 places with shopping search icons that needed to replace.
Helen will provide the new icon this week.
You can start to tag size first.

**Comment by TLHuang** [comment]
The visuals are updated https://zpl.io/2pAMj1y
Let me know if any questions.

**Comment by Daisy-pliu** [comment]
## Test Report
Verify: ✅
Version: 2.1.13(19230)
Looks good to me.

@TLHuang could you help double check the shopping search icons . Thank you!

## Screenshots
### Tab tray
![Screenshot_20200407-142943_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78643365-bdc77c80-78e6-11ea-87de-e0dd793e1617.jpg)
### EC site
![Screenshot_20200407-144337_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78643368-be601300-78e6-11ea-9c04-fa49e0050334.jpg)

### Home page
![Screenshot_20200407-143014_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78643359-bb652280-78e6-11ea-9e85-f2a8fdf0ecd8.jpg)

### Shopping search onboarding 
![Screenshot_20200407-143008_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78643364-bd2ee600-78e6-11ea-8f35-9c95d083d507.jpg)

**Comment by Daisy-pliu** [comment]
Will verify in Release build

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.1.4(19257)
