### ISSUE TITLE
Warning about PhoneStatusPermission on Playstore console

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4763]
**Describe the bug**
[issue in slack ](https://mozilla.slack.com/archives/CS7KS9DT6/p1582698997045200)

**Issue:**
Playstore console warns  android.permission.READ_PHONE_STATE permission  is required to be accepted by user to upgrade

**Risk/Impact :** 
if user dont accept the permission, they can't upgrage to 2.1.10.

**Version**
2.1.9 (18705)

**Action Required** 
Need Dev check where the issue from and let us know if we can fix it or not?

**Comment by Daisy-pliu** [comment]
verify:✅
test case:
verify adjust tracker and version is displayed correctly after user install app.

**Comment by benjamin-cheng** [comment]
Fix by #4761
