### ISSUE TITLE
Spike for Appier API & Integration documents

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4771]
For Game home we will integrate Appier's promotional contents in banner and will need to study the documents Appier provided.

Here are the detail information partner provided:
https://docs.google.com/document/d/1nwCWV7_UJ4zgxrHF5kQCKuf2621HnLk81mHeKjJHWSc/edit#heading=h.sp6f2c91hupm

**Comment by youwenliang** [comment]
Appier's game ads will place in the banner section:
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5d48f49b110df6132bacf24b
Our current banner ratio is 2:1, so we should be able to use the "1200x627" size Appier provides.

**Comment by proevan** [comment]
understood how to compose the API call and the click url.
