### ISSUE TITLE
[Firebase: Push Notification] Logo Renew

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4778]
**User story**
As a user, I would like see the new Firefox Lite logo on push notification/D1 push notification
![IMG_20200303_164313_2](https://user-images.githubusercontent.com/52307187/75759298-47c47880-5d70-11ea-8151-4e15980fba3b.jpg)
The fox and color are not fit for new logo design

**Acceptance Criteria (how do I know when I’m done?)** 
Change the new logo

**Additional context**
Still confirm with US design team about small size log design

**Comment by tinahsieh** [comment]
Please use the new logo:
[logo-flat.svg.zip](https://github.com/mozilla-tw/FirefoxLite/files/4290845/logo-flat.svg.zip)

And the color code defined as below (the logo should be replaced by the new logo):
<img width="490" alt="Screen Shot 2020-03-03 at 5 14 53 PM" src="https://user-images.githubusercontent.com/17559807/75945541-81fb5a80-5ed5-11ea-98e4-7320fac650c7.png">

**Comment by TLHuang** [comment]
Sorry for providing a wrong one... Please help to update the icon again! 
[logo-flat.svg.zip](https://github.com/mozilla-tw/FirefoxLite/files/4352601/logo-flat.svg.zip)

**Comment by tinahsieh** [comment]
Verified OK!
![Screenshot_20200320-110223_Slack](https://user-images.githubusercontent.com/17559807/77132428-6b8afc80-6a9a-11ea-922f-8195030fc5b8.jpg)
