### ISSUE TITLE
Firefox Lite Preview Firebase Permissions: Cynthia & Helen

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4781]
For msg design testing, need Firefox Lite Preview permission: Editor
-Helen, hhuang@mozilla.com
-Cynthia, cywang@mozilla.com

**Comment by Daisy-pliu** [comment]
these 2 member are added to Editors. Please try to login to the console. Thanks.
<img width="1302" alt="Screen Shot 2020-03-04 at 11 20 59 AM" src="https://user-images.githubusercontent.com/44990878/75842081-6414f380-5e0a-11ea-8229-e80a8818a1cd.png">
<img width="1305" alt="Screen Shot 2020-03-04 at 11 20 44 AM" src="https://user-images.githubusercontent.com/44990878/75842084-670fe400-5e0a-11ea-8b35-95b97a724237.png">

**Comment by Daisy-pliu** [comment]
From now on @niyali will take over permission related request. cc: @shsu571 @youwenliang
