### ISSUE TITLE
[Shopping Search] Search UI information update

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4787]
Add different copy strings & illustration for the search UI in Shopping Search
visual spec: https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/dashboard?tag=4674

Meta bug: #4674

**Comment by tinahsieh** [comment]
Add "need metrics" for copy string A/B testing and remote config-able illustration.

**Comment by lanyliu** [comment]
Copy strings
**Copy A**: Compare prices easily on popular shopping sites.
**Copy B**: Start saving today. Search and compare prices on popular sites.

分組方式
A group: **Copy A**
experiment_bucket: 1-7
experiment_name: smart_shopping_copy_a

B group: **Copy B**
experiment_bucket: 8-14
experiment_name: smart_shopping_copy_b

AA group: **Copy A**
experiment_bucket: 15-20
experiment_name: smart_shopping_copy_aa

分析Note
鎖版本&鎖國家（IN,ID）

**Comment by tinahsieh** [comment]
featured website logos on the illustration:
ID：shopee, google, tokopedia, bukalapak
IN：snapdeal, google, flipkart, club factory
Global: shopee, google, amazon, lazada

**Comment by yshlin** [comment]
Verified receiving Variant B when bucket=9, and others are control.

**Comment by benjamin-cheng** [comment]
@Daisy-pliu 
Please use the remote config to have different shopping search logo man for different countries -`str_shopping_search_logo_man_image_url`

**Comment by Daisy-pliu** [comment]
> <https://rocketnightly.firebaseapp.com/SSS_ID.png>
<sub>[View in Slack](https://mozilla.slack.com/archives/DE75J16SD/p1584677047000200)</sub>

**Comment by Daisy-pliu** [comment]
UX slack me privately to add pics below on Nightly.
**Indo** 
https://rocketnightly.firebaseapp.com/SSS_ID.png
**India**
https://rocketnightly.firebaseapp.com/SSS_IN.png

verify:✅
version : 2.1.12(19119)
device: Samsung S6 
**India**
![Screenshot_20200320-134904](https://user-images.githubusercontent.com/44990878/77139759-3b4f5800-6ab2-11ea-95b1-21f1ebaa43dc.png)
**Indo**
![Screenshot_20200320-134925](https://user-images.githubusercontent.com/44990878/77139764-3ee2df00-6ab2-11ea-8d3d-447e30d0aad0.png)

**Comment by Daisy-pliu** [comment]
Added new remote config parameter `str_shopping_search_logo_man_image_url` on [FxLite2.0_RemoteConfig](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=A31:K31)

**Comment by niyali** [comment]
Deployed to Prod.

**Comment by Daisy-pliu** [comment]
Thank you. Will config &  verify on Production once Release build v2.1.12 comes out.

**Comment by tinahsieh** [comment]
> The website logos on the illustration:
> ID：shopee, google, tokopedia, bukalapak
> 
>     * **Nightly** https://rocketnightly.firebaseapp.com/SSS_ID.png
> 
>     * **Production** https://zerda-dcf76.firebaseapp.com/SSS_ID.png
> 
> 
> IN：snapdeal, google, flipkart, club factory
> 
>     * **Nightly** https://rocketnightly.firebaseapp.com/SSS_IN.png
> 
>     * **Production** https://zerda-dcf76.firebaseapp.com/SSS_IN.png
> 
> 
> Global: shopee, google, amazon, lazada
> 
> CC @Daisy-pliu

Thanks @Daisy-pliu and @niyali ! I collected the links for the illustrations in the previous comment, and in case people can't find it, it's going to be noted on my UX spec as well. 

Feel free to let me know if there's anything missed.

**Comment by Daisy-pliu** [comment]
verify:  ✅
version: 2.1.12(19131)
**Default** 
![Screenshot_20200323-090508_Firefox Lite](https://user-images.githubusercontent.com/44990878/77273536-cc127780-6cee-11ea-816c-6afb06370df4.jpg)
**India**
![Screenshot_20200323-090731_Firefox Lite](https://user-images.githubusercontent.com/44990878/77273539-cd43a480-6cee-11ea-8e3c-b9a17d2a3be6.jpg)
**Indo**
![Screenshot_20200323-090925_Firefox Lite](https://user-images.githubusercontent.com/44990878/77273540-cddc3b00-6cee-11ea-991d-25c9a4824e1e.jpg)
