### ISSUE TITLE
[Shopping Search] Search UI trending search suggestion

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4788]
Adjust search suggestion layout and add trending search suggestion before users start typing
visual spec: https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/dashboard?tag=4674

Meta bug: #4674 

This feature should be able to turn on/off with remote config(?) so that we can tested in one country first (such as India).

**Comment by youwenliang** [comment]
We will provide 5 trending keywords for IN, ID and global.
Will need to discuss how PM can provide the keywords with Remote Config.

**Comment by tinahsieh** [comment]
As per the offline discussion with Helen and Benjamin, we'll add another rule "limit to 2 rows" for the search suggestions. I've opened issue #4833 for this.

**Comment by yshlin** [comment]
Verified receiving default=true and keyword after clicking default suggestion
default=false and null keyword after clicking user suggestion
