### ISSUE TITLE
Picture cannot display correct on survey

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4801]
**Describe the bug**
This is not an in-app issue. We'll need PM to coordinate with the correct team.

**Steps To Reproduce**
1. Launch Firefox Lite
2. Tap on Settings
3. Tap on "Give Feedback"
4. Tap on "Leave comments"

**Expected behavior**
Survey work as expected

**Actual behavior**
an image is broken

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.
![Screenshot_2020-03-09-15-23-50-95](https://user-images.githubusercontent.com/1625148/76192254-57ced300-621c-11ea-8e79-ecdf4ff02740.png)

**Device info (please complete the following information):**
 - Device: [e.g. Pixel2]
 - OS: [e.g. Android 8.1.0]
 - Webview 80
 - Version 2.1.11(18890)

**Reproduce rate**
5/5
**Additional context**

**Comment by shsu571** [comment]
Do we try in other browser? Only happend on Firefox Lite?

**Comment by Conjuror** [comment]
It doesn't happen on other browser (Firefox Preview/Chrome).
![Screenshot_20200310-101459](https://user-images.githubusercontent.com/1625148/76273220-5226cb00-62b8-11ea-80bd-43445e5746b2.png)

Also, this issue can be reproduced on English version only.

**Comment by chianger** [comment]
Need more info: 
1. check more locales to see if this issue still reproduces.
2. check with vendor (qsurvey)

**Comment by Conjuror** [comment]
Tested on the following languages, and only English displays incorrectly.
- English
- Traditional Chinese
- Thai
- Vietnamese
- Hindi
- Indonesian

**Comment by Conjuror** [comment]
Close the issue since it's fixed on partner side.
