### ISSUE TITLE
[Remote Config] Add trending search terms for #4788

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4807]
**Remote config name**
new remote config
str_shopping_search_trending_terms

**Audience setting**
Audience group will be:
1. India
2. Indonesia
3. Default

**Parameter + Audience**
This is work in progress, will need to discuss with @benjamin-cheng how we should format this.

1. India
trending search terms:
["redmi 8", "adidas", "oppo", "face wash", "realme c2"]

2. Indonesia
trending search terms:
["case iphone", "kemeja pria", "masker sensi", "samsung note 8", "hand sanitizer"]

3. Default
trending search terms:
["mobiles", "shoes", "t shirts", "laptops", "watches"]

**Expected Online Time**
End of this week or early next week.

**Additional context**
This is for #4788

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version : 2.1.1
![Screenshot_20200319-155032](https://user-images.githubusercontent.com/44990878/77044262-10093200-69fa-11ea-996f-763af8851467.png)
![Screenshot_20200319-155209](https://user-images.githubusercontent.com/44990878/77044264-10a1c880-69fa-11ea-9034-1d35d3eb3865.png)

1 (19111)
Device: Samsung S6 (6.0)

![Screenshot_20200319-155149](https://user-images.githubusercontent.com/44990878/77044189-ee0faf80-69f9-11ea-8817-f3ffd81166e3.png)
![Screenshot_20200319-155032](https://user-images.githubusercontent.com/44990878/77044192-efd97300-69f9-11ea-85bc-8bf693167092.png)
![Screenshot_20200319-155209](https://user-images.githubusercontent.com/44990878/77044264-10a1c880-69fa-11ea-9034-1d35d3eb3865.png)
