### ISSUE TITLE
George needs remoteconfig permission on Nightly 

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/FirefoxLite#4808]
George needs remoteconfig permission on Nightly. 
@swlibi correct?

Thanks.

**Comment by swlibi** [comment]
Yes, please!

**Comment by niyali** [comment]
![Screen Shot 2020-03-10 at 5 52 28 PM](https://user-images.githubusercontent.com/1436482/76300640-072ca800-62f8-11ea-85cc-ea4682e91177.png)

Access granted. 
Please logout and login back if needed. 

Thanks.
