### ISSUE TITLE
Firebase - Can't get in app message (top banner)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4809]
**Describe the bug**
Send the  in app message -top banner

**Steps To Reproduce**
1. Go to Firebase
2. Make in app message -top banner
3. send (Firebase Id)

**Expected behavior**
Test user will see the in app message -top banner when they open Firefox Lite

**Actual behavior**
Can't recieve (but we do receive Mold and Card)

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Reproduce rate**
2 /2

<img width="921" alt="螢幕快照 2020-03-10 下午6 25 32" src="https://user-images.githubusercontent.com/52307187/76303548-e31f9580-62fc-11ea-937d-2fa7251553ff.png">

**Comment by proevan** [comment]
it was a  issue from firebase side, and it seems worked for now after tested.
