### ISSUE TITLE
[Remote Config] Update Shopping Search sites in India

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4813]
**Remote config name**
str_shopping_search_sites

**Audience setting**
India

**Parameter + Audience**
Change the India audience's shopping sites to:

[
  {
    "title": "Google",
    "searchUrl": "https://www.google.com/search?q=",
    "displayUrl": "google.com",
    "showPrompt": false
  },
  {
    "title": "Flipkart",
    "searchUrl": "https://www.flipkart.com/search?affid=fxlite&affExtParam1=shopping&affExtParam2=search&q=",
    "displayUrl": "flipkart.com"
  },
  {
    "title": "Snapdeal",
    "searchUrl": "https://www.snapdeal.com/search?keyword=",
    "displayUrl": "snapdeal.com"
  },
  {
    "title": "Club Factory",
    "searchUrl": "https://www.clubfactory.com/search?q=",
    "displayUrl": "clubfactory.com"
  },
  {
    "title": "Paytm",
    "searchUrl": "https://paytm.com/shop/search?q=",
    "displayUrl": "paytm.com"
  }
]

**Expected Online Time**
Early next week

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.8(18628)
![Screenshot_20200316-150406_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/76735437-e1901a80-679f-11ea-8860-de1a4ed4860c.jpg)
I just verified. If you are good it is ready for production. Thanks !

**Comment by Daisy-pliu** [comment]
verify :✅
version: 2.1.11(18974)
