### ISSUE TITLE
Update l10n strings for Travel

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4817]
**Describe the bug**
Need to update l10n strings according to two sheets:

https://docs.google.com/spreadsheets/d/1cHMs6bWXPNDwiGe6zlMEn_yKepxnqOS_9hKpR1ehZ08/edit#gid=0

https://docs.google.com/spreadsheets/d/1Rb7DK7nOSNmwQJf3IHpJ_QWqFPHhFLm9Dn_LLSWwM0E/edit#gid=0

**Comment by Conjuror** [comment]
Not sure if we need to be blocked by the issue, suggest to P1

**Comment by Conjuror** [comment]
Please move to S4-2 if we need to get it land in the sprint. Thanks

**Comment by Conjuror** [comment]
Update according to PM's comment on Slack

**Comment by weslyhuang** [comment]
need it this Sprint (S4-2) so I marked it P0.
