### ISSUE TITLE
Shopping Search Crash on Nightly 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4819]
**Steps To Reproduce**
1. launch app
2. tap [shopping search]
3. input [nike]
4. tap shopping suggestion e.g. [nike air..]

**Expected behavior**
4. see [nike air..] shopping search result

**Actual behavior**
4. Firebase crash https://console.firebase.google.com/u/0/project/rocketnightly/crashlytics/app/android:org.mozilla.rocket.beta/issues/09c9856e7eb3a7413e33ca9724d75faa?time=last-seven-days&sessionId=5E69B53702B0000167A8C197B5910357_DNE_0_v2

**Screenshots/videos**
[slack link ](https://mozilla.slack.com/archives/CS7KS9DT6/p1584346991399300)

**Device info (please complete the following information):**
 - Device: Redmi Note 7
 - Webview [e.g. 69.0.3497.100]
 - Version [e.g. 3.3.0(7183).nightly]

**Reproduce rate**
can always reproduce on Mark's Phone

**Additional context**
No happen on my testing phone  Redme 7

**Comment by shsu571** [comment]
my pixel 3a is crash too

**Comment by benjamin-cheng** [comment]
Fix in Preview build#19077

**Comment by Daisy-pliu** [comment]
> I am okay with new version now
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1584588611473600)</sub>

**Comment by Daisy-pliu** [comment]
> work for me
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1584588682474200)</sub>
