### ISSUE TITLE
[Telemetry] error in url_counts 

### ISSUE THREAD

**Issue by lanyliu** [mozilla-tw/FirefoxLite#4824]
**Describe the bug**

event method: end  
event object: tab_swipe
event extra: url_counts

error:
url_counts should = 0

**Steps To Reproduce**
1. Go to 'shopping search'
2. see Google tab
3. switch to second tab
4. will receive url_counts=0

**Expected behavior**
url_counts should >= 1

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/49740335/76929866-2b077380-6920-11ea-9acb-402429f9725c.png)

**Comment by chianger** [comment]
Looks like we're gonna block this for 2.1.12

**Comment by shsu571** [comment]
Mark already confirmed yesterday. This is not block, but should be fixed on next sprint.

**Comment by yshlin** [comment]
Verified seeing url_counts=1
