### ISSUE TITLE
[Shopping Search] Change Switch UI toolbar search icon

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4825]
Change the shopping search icon in the toolbar to normal search icon.
Meta bug: #4675

**Comment by youwenliang** [comment]
UX Spec: https://mozilla.invisionapp.com/share/WHW18MMQPAX#/screens/409727579

**Comment by youwenliang** [comment]
Metric Request: https://trello.com/c/7lIEcJkR/341-product-add-event-for-shopping-search-switch-ui-redo-search

**Comment by chianger** [comment]
per discussion we'll have the metric design coming during sprint.

**Comment by lanyliu** [comment]
already exist
spec
https://docs.google.com/spreadsheets/d/1YcDo5jViGpwrrR1e1akHpkAXzXsGaN92DVqP9T3QMhE/edit#gid=888392947&range=F10


method = click
object = toolbar
value = tab_swipe
extra 
- vertical = shopping
- from = tab_swipe
https://github.com/mozilla-tw/FirefoxLite/blob/master/docs/events.md

**Comment by Daisy-pliu** [comment]
verify: ✅
Version : Preview 2.1.13(19230)
Test step:
1. launch app
2. tap [shopping search icon]
3. search [shoes] -> [enter]
4. tap [search bar]
5. search [shoes] -> [enter]
6. tap [shopping search icon]

Result
4.  back to [shopping search home with "shoes"]
6. back to [shopping search home with "shoes"]

**Comment by Daisy-pliu** [comment]
Will check on Release build and modify test case accordingly

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.1.4(19257)
