### ISSUE TITLE
[Shopping Search] Update the miniURL bar's format & behavior

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4826]
Change the format of the miniURL bar in Shopping Search's Switch UI (with magnifying glass & keywords), and allow users to tap the miniURL bar to redo search.

Meta bug: #4675

**Comment by youwenliang** [comment]
UX Spec: https://mozilla.invisionapp.com/share/WHW18MMQPAX#/screens/409727579

**Comment by youwenliang** [comment]
Metric Request: https://trello.com/c/7lIEcJkR/341-product-add-event-for-shopping-search-switch-ui-redo-search

**Comment by chianger** [comment]
per discussion we'll have the metric design coming during sprint.

**Comment by lanyliu** [comment]
telemetry spec
https://docs.google.com/spreadsheets/d/1OoNnoqtsTlQPmf3NSnjaQZP4mXLVJCwQIKHKDA0hyiE/edit#gid=888392947

**Comment by TLHuang** [comment]
Visual spec is updated https://zpl.io/bl0KGvD

**Comment by Daisy-pliu** [comment]
verify: ✅
Version : Preview 2.1.13(19230)
Test step:
1. launch app
2. tap [shopping search icon]
3. search [shoes] -> [enter]
4. tap [search bar]
5. search [shoes] -> [enter]
6. tap [shopping search icon]

Result
4.  back to [shopping search home with "shoes"]
6. back to [shopping search home with "shoes"]

**Comment by Daisy-pliu** [comment]
Test case modified in SHOP36.

**Comment by yshlin** [comment]
Verified seeing it on Firebase, also the original event works properly.
<img width="352" alt="Screen Shot 2020-04-08 at 5 54 52 PM" src="https://user-images.githubusercontent.com/936571/78771163-4bc46580-79c2-11ea-8f62-723035848dd0.png">

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.1.4(19257)
Good on SHOP036.
