### ISSUE TITLE
[Shopping Search] Move the settings button in Switch UI to the end

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4827]
Currently, the settings button in Switch UI is fixed on the right side of the tab bar, will need to move it to the end of the tab bar, only accessible when users scroll till the end, and change the icon. (And also remove the overlay onboarding for the settings button)

Meta bug: #4675

**Comment by youwenliang** [comment]
UX Spec: https://mozilla.invisionapp.com/share/WHW18MMQPAX#/screens/409727580

**Comment by Daisy-pliu** [comment]
verify: ✅
version: Preview 2.1.12 (19230)
**Test step:**
1. launch app
2. tap [shopping search icon]
3. search [shoes] -> [enter]
4. swipe right to the end 

**Result**
3. see [no shopping search onboarding]
4. see [sites setting] button

## Question
@youwenliang @tinahsieh 
Just raise a minor concern , if user only compare between 2 sites they will see below. not sure if it is good from UX perspective. 
![Screenshot_20200407-141321_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78640518-78a14b80-78e2-11ea-92b9-97234b546003.jpg)

**Comment by youwenliang** [comment]
looks like a bug to me, shouldn't look like this.

**Comment by Daisy-pliu** [comment]
Will verify in Release build and modify test case accordingly.

**Comment by youwenliang** [comment]
There are some visual changes around the toolbar that we missed to mention:
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5e708f42ee9848144fa46a31

1. tab buttons that are not selected should have a white background
2. the divider line should be on the top of the tabbar instead of between the toolbar and tabbar

@benjamin-cheng Let me know if this is something you can work on within this sprint while fixing the bug daily mentioned, otherwise I'll open a new ticket for the visual fixes.

**Comment by benjamin-cheng** [comment]
@youwenliang OK, I'll made those minor UI changes along with the tab bar issue

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.14(19257)
Looks good when 2 sites, 3 sites, or more.

## 5 Sites selected
![Screenshot_20200410-082542_Firefox Lite](https://user-images.githubusercontent.com/44990878/78954553-137e6d80-7b0f-11ea-9f07-80c9364486df.jpg)

## 4 Sites selected
![Screenshot_20200410-083517_Firefox Lite](https://user-images.githubusercontent.com/44990878/78954557-15483100-7b0f-11ea-8531-453463b11eb0.jpg)

## 3 Sites selected
![Screenshot_20200410-083507_Firefox Lite](https://user-images.githubusercontent.com/44990878/78954564-16795e00-7b0f-11ea-9979-357a6900235c.jpg)

## 2 Sites selected
![Screenshot_20200410-083459_Firefox Lite](https://user-images.githubusercontent.com/44990878/78954566-1711f480-7b0f-11ea-9eba-4ae4eb3d77fa.jpg)
