### ISSUE TITLE
[Shopping Search] Make the miniURL bar and tool bar in Switch UI collapsible

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4828]
Allow the miniURL bar & tool bar in Switch UI to hide when users are scrolling down the page, and show them again when users scroll up.

Meta bug: #4675

**Comment by youwenliang** [comment]
UX Spec: https://mozilla.invisionapp.com/share/WHW18MMQPAX#/screens/409727577

**Comment by Daisy-pliu** [comment]
Hi @tinahsieh ,
could you let me is below case is an unexpected result or not , given it is not on spec.
## Step
1. launch app
2. tap [shopping search]
3. search [shoes] -> [enter]
4. scroll down 
5. tap [PChome]

## Result
4. the navigation is in smaller size and tool bar is hided.
5. use see tool bar shows and navigation bar is normal size

## Question
I am not sure if Step5 result is under UX expectation, could you let me know if it is good to go ? Thank you.

**Comment by tinahsieh** [comment]
Hey @Daisy-pliu, not sure if you're describing the behavior like this? If yes, then it's by design :)
https://mozilla.invisionapp.com/share/WHW18MMQPAX#/409727578_2-2_Switching_Tabs_In_The_Shrinking_State

**Comment by tinahsieh** [comment]
We found that the scrolling effect became a bit stuck for the first scroll...will post a video later!

**Comment by Daisy-pliu** [comment]
Thanks for the clarification @tinahsieh . I just realized we have this "shrinking state" spec. https://mozilla.invisionapp.com/share/WHW18MMQPAX#/screens/409727578.

**Comment by Daisy-pliu** [comment]
verify: ✅
Version : Preview 2.1.12 (19230)

**Comment by Daisy-pliu** [comment]
will verify on release build and modify test case.

**Comment by tinahsieh** [comment]
**Test Step:**
1. launch app
2. tap [shopping search]
3. search [shoes] -> [enter]
4. scroll down in the Google tab before loading completed for a while

**Result**
4. will be stuck for the first scroll, and need a second scroll for going further down.

CC @Daisy-pliu not sure if it's a bug? It seem like only happened in Google tab.

**Comment by Daisy-pliu** [comment]
Hey That's true. @tinahsieh .
It happens at the first scroll on Goolge site even the web page is fully loaded for a while.

**Comment by Daisy-pliu** [comment]
Test case modified in [SHOP023](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1456486403&range=C215).

**Comment by chianger** [comment]
Let's create a separate issue (non blocking) and this feature is considered as done.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.1.4(19257)
