### ISSUE TITLE
[Shopping Search] Limit the search suggestions to 2 rows

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4833]
The current implementation to provide 5 search suggestions, so there'll be some extreme cases like this:
![Screenshot_20200318-150651_Firefox Lite Preview](https://user-images.githubusercontent.com/17559807/77133109-d806fb00-6a9c-11ea-9a20-f15c4092a280.jpg)

To avoid this issue, we'll add another rule: "limit to 2 rows" for the search suggestions.
CC @youwenliang for labeling this bug.

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.12(19230)
![Screenshot_20200407-134033_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/78637828-c1a2d100-78dd-11ea-82ad-d1460833ef0f.jpg)

**Comment by Daisy-pliu** [comment]
Will verify in Release build and modify test case accordingly.

**Comment by Daisy-pliu** [comment]
Test case modified in SHOP17.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : Release 2.1.14(19257)
Good on SHOP017
