### ISSUE TITLE
Smart shopping search image upload to Production

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4835]
**User story**
Smart shopping search image upload to Production
1. Indo
https://rocketnightly.firebaseapp.com/SSS_ID.png
2. India
https://rocketnightly.firebaseapp.com/SSS_IN.png

**Acceptance Criteria (how do I know when I’m done?)** 
1. check it upload success on production
2.
3.

**Related to issue **
https://github.com/mozilla-tw/FirefoxLite/issues/4787

**Comment by niyali** [comment]
Deployed to Prod. (After validate on Preview) 

![Screen Shot 2020-03-20 at 2 03 20 PM](https://user-images.githubusercontent.com/1436482/77140141-a0577d80-6ab3-11ea-86df-42ed74b15230.png)

**Comment by Daisy-pliu** [comment]
Thank you. Will config&  verify on Production once Release build v2.1.12 comes out.

**Comment by Daisy-pliu** [comment]
refer #4787
