### ISSUE TITLE
Top Site for COVID-19

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4836]
**Remote config name**
_str_top_sites_fixed_items
str_top_sites_default_items

**Audience setting**
**Parameter + Audience**
https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0
2020/3/20 updated the change part (yellow highlight)

**Expected Online Time**
3/20 any time!

**Additional context**

**Comment by Conjuror** [comment]
configuration is on Preview and works for me.
![Screenshot_20200320-180924](https://user-images.githubusercontent.com/1625148/77154684-25a05980-6ad7-11ea-81ee-bac01b80bb7e.png)
![Screenshot_20200320-181445](https://user-images.githubusercontent.com/1625148/77154691-29cc7700-6ad7-11ea-8d2a-e91542887e54.png)
![Screenshot_20200320-181405](https://user-images.githubusercontent.com/1625148/77154696-2a650d80-6ad7-11ea-8b89-9351a0e48df4.png)

**Comment by Conjuror** [comment]
Production: Global/ID/IN
![Screenshot_20200320-183604](https://user-images.githubusercontent.com/1625148/77156436-533ad200-6ada-11ea-9ec7-3f146124d868.png)
![Screenshot_20200320-183921](https://user-images.githubusercontent.com/1625148/77156442-5766ef80-6ada-11ea-8daf-369e6dcd3462.png)
![Screenshot_20200320-183808](https://user-images.githubusercontent.com/1625148/77156443-58981c80-6ada-11ea-86f2-0805c9161a52.png)
