### ISSUE TITLE
Make browser toolbar collapsible

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4837]
In normal browsing mode and private browsing mode, make toolbar collapsible when users are scrolling the content.

UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/410131596_0-0_Cover

**Comment by shsu571** [comment]
Reason for this sprint:
Providing better users browsing experience.
Browsing related feature are highly correlated to retention and first day experience
