### ISSUE TITLE
Update amplitude SQL generator to moz-fx-data-shared-prod

### ISSUE THREAD

**Issue by Conjuror** [mozilla-tw/FirefoxLite#4844]
**User story**
We need to update current SQL query generator to align the change in [bug 1612543 - Moz confidential](https://bugzilla.mozilla.org/show_bug.cgi?id=1612543) .

Currently, we query from `moz-fx-data-derived-datasets` instead of `moz-fx-data-shared-prod`.  Since [the change](https://github.com/mozilla/bigquery-etl/commit/5ca696a6e19f9ead9b289ad55c5bc3ddfa8073f6) is made in bigquery-etl repo. We need to fix our query generator accordingly.

Suggest to P0 and put into S4-3. I can make the pull request to avoid to occupy dev resources.

**Comment by chianger** [comment]
per comment and there is PR in place, i’m adding this to current sprint as P0. Feel free to correct.

**Comment by chianger** [comment]
In this sprint 4-3 all telemetry changes are on "extra" so no impact to current sprint. We should fix in next sprint.
