### ISSUE TITLE
Top Site for Dailyhunt (switch Flipkart to Dailyhunt for India)

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#4846]
Remote config name
str_top_sites_default_items

Audience setting
Parameter + Audience
[https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0](url)
2020/3/25 updated the change part (yellow highlight)

Expected Online Time
3/25 or as soon as possible!

**Additional context**
Pls share screenshot of preview before going live.

**Comment by yowazzzup** [comment]
icon: 
[https://drive.google.com/file/d/1vvDhhATORwLOQ74R0wwbD0KWScKS0uaY/view?usp=sharing](url)

**Comment by shsu571** [comment]
link is not cilckable i paste again here : https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0

**Comment by shsu571** [comment]
@Conjuror daily hunt seem never upload logo before. could you check with @yowazzzup and @shsu571 the logo will look like when you publish? Thx

**Comment by Conjuror** [comment]
![Screenshot_20200326-102031](https://user-images.githubusercontent.com/1625148/77604362-43454700-6f4d-11ea-94f3-195fe8fc6b0c.png)
![Screenshot_20200326-103021](https://user-images.githubusercontent.com/1625148/77604368-4809fb00-6f4d-11ea-905a-2d792be03835.png)
