### ISSUE TITLE
Add Dailyhunt logo for top site uploading preparation

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#4847]
For uploading the Dailyhunt logo into production.

https://drive.google.com/file/d/1vvDhhATORwLOQ74R0wwbD0KWScKS0uaY/view?usp=sharing

**Comment by proevan** [comment]
@shsu571 currently we don't support svg for top site icon, we need a png or webp file instead.

**Comment by proevan** [comment]
I converted the svg file to a webp file for usage
[ic_dailyhunt.webp.zip](https://github.com/mozilla-tw/FirefoxLite/files/4384752/ic_dailyhunt.webp.zip)

**Comment by swlibi** [comment]
verified on 19258

**Comment by yowazzzup** [comment]
Tracking URL for Dailyhunt:
https://mozilla.dailyhunt.in/?mode=pwa&s=Mozilla&ss=Browser-Feed&&utm_source=Mozilla&utm_medium=Browser-Feed&utm_campaign=Mozilla-Browser-Top-Sites&partnerRef=%7B%22pid%22%3A%22mozilla1%22%7D&da=true&dpg=true
