### ISSUE TITLE
v2.1.12 crash on Andorid 5

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#4850]
**Describe the bug**
Crash
https://console.firebase.google.com/u/0/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/5b88267b6007d59fcd427e4b?time=last-seven-days&sessionId=

**Additional context**

**Comment by Daisy-pliu** [comment]
> Found the root cause =&gt; there is a bug in Google Appcompat library 1.1.0 which was recently updated in 2.1.12
<https://issuetracker.google.com/issues/141132133>
I'll try to either downgrade or upgrade the library to fix this issue.
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1585229872079100)</sub>

**Comment by Daisy-pliu** [comment]
> The crash happened when trying to load any web page on Android 5.x device. (100% reproduceable).
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1585227851068900)</sub>

**Comment by Daisy-pliu** [comment]
- [x]   Immediate Action: halted 2.1.12 release (3/26)
- [x]  Follow up Measurement : check how many user under Android 5 , how many users crashes  (3/27)
- [x]  Measurement leads to action: Hotfix  (3/27)
- [ ]  Hotfix Timeline
- [ ]  Hotfix verification
- [ ]  Discuss Long term solution

**Comment by shsu571** [comment]
Impact to users:
<img width="716" alt="螢幕快照 2020-03-27 上午10 54 05" src="https://user-images.githubusercontent.com/52307187/77716601-87058280-7019-11ea-847d-fb7ef59589d2.png">
- Yesterday Android 5 + App version 2.1.12: DAU 628 -> crashed users53 -> impact 8.4%
-  DAU of Android 5 :  8.3K

**Comment by Daisy-pliu** [comment]
verify: ✅
device :  Sony Android 5 
test on Sony Android 5 with commit 016426 on master branch

**Comment by Daisy-pliu** [comment]
> <!here>
crash free rate is 99.53%  seems pretty good , no new crashes and Android 5 crash is fixed. Lets roll out to Prod 99% ? let me know if you have any concerns,  thank you !
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1585709085066900)</sub>
