### ISSUE TITLE
COVID-19 logman banner in Taiwan

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4851]
Remote config name
str_logo_man_notification

Audience setting
Taiwan

Parameter + Audience
Region: Taiwan
Language: Traditional Chinese

Expected Online Time
3/27 Anytime

Additional context
Copy, image graphic, and URL: https://docs.google.com/spreadsheets/d/1JAoWNkksddU_-X4DlP29e4sle1VrwEcJ1QMY4rQK984/edit#gid=1182250926

**Comment by Conjuror** [comment]
![Screenshot_20200327-141422](https://user-images.githubusercontent.com/1625148/77727562-91ce1080-7035-11ea-87e6-3e1af1b532b5.png)
