### ISSUE TITLE
[Bug] Youtube view in fullscreen(landscape) mode issue

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4859]
**Describe the bug**
When viewing youtube in fullscreen mode, if you rotate the device the video position will move off screen.

**Steps To Reproduce**
1. Go to Youtube.com
2. Click on any video
3. Tap the fullscreen button in the video
4. Rotate your device to landscape and rotate back to portrait
5. See the issue.

**Expected behavior**
Video show in fullscreen

**Actual behavior**
Video cropped off screen

**Screenshots/videos**

Rotate to landscape:
![image](https://user-images.githubusercontent.com/8919308/78094507-45088200-7407-11ea-938e-d4713d27f2c7.png)

Rotate back to portrait:
![image](https://user-images.githubusercontent.com/8919308/78094502-433ebe80-7407-11ea-881e-96904affe229.png)

**Device info (please complete the following information):**
 - Device: Redmi Note 7
 - OS: Android 9
 - Version: 2.1.12(19131)

**Comment by shsu571** [comment]
Reason do add to sprint:
landscape( Video ) :
-important feature for first users
-event amounts is increasing during COVID-19 period
MAU and DUA are growing strongly recently, and we know that users will use this feature at first day, so we need to make it better!

**Comment by Daisy-pliu** [comment]
QA need to also verify on #4893

**Comment by Daisy-pliu** [comment]
QA need to also verify on #4891

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.15(19343) Preview
Device: Samsung (8.0) , Pixel 2(9.0)
webview: stable (81.0.4044.111) , beta (83.0.4103.14)

**Comment by Daisy-pliu** [comment]
> 發現一個bug…不確定是不是只有我會發生：
• 到 youtube
• 點開一個影片
• 點全螢幕
• 轉手機看全螢幕 landscape
• 轉回 portrait 看影片 (還是全螢幕)
• 按 system back -&gt; 畫面全黑 (應該要是在 youtube)
• 再按一次 system back -&gt; 回到首頁
• 然後 youtube 進去都會是黑畫面
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1587623286376500)</sub>

**Comment by Daisy-pliu** [comment]
Seems a side-effect and regression,

**version**
2.1.15(19343) 

**Device**
Samsung 8.0

**Test step:**
1. search [Youtube]
2. click [any video]
3. click [full screen]
4. rotate to  landscape
5. rotate to portrait
6. tap system back    按 system back -> 畫面全黑 (應該要是在 youtube)
7. tap system back   
8. tap [Youtube topsite]

**Expect result:**
6.  back to Youtube video page
7.   app home page
8. back to Youtube  page

**Actual result:**
6.  screen all back
7.  app home page
8.  screen all back

**Comment by Daisy-pliu** [comment]
verify ❌
version : 2.1.16 (19357)
Still see black screen from [test steps](https://github.com/mozilla-tw/FirefoxLite/issues/4859#issuecomment-618220634)

**Comment by Daisy-pliu** [comment]
verify ✅
version : 2.1.16 (19365)
works on both private and normal browsing
webview : Beta(83.0.4103.14) and stable (81.0.4044.111)
device: Samsung 8.0

**Comment by Daisy-pliu** [comment]
Need @youwenliang @tinahsieh also check on their Redmi , samsung phones.

**Comment by Daisy-pliu** [comment]
Need to test on Release build
