### ISSUE TITLE
[Feature] Landscape mode in Firefox Lite does not have toolbar or url bar

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4860]
The landscape mode hides toolbar and nav bar immediately without providing any hints, which might be confusing to many landscape mode users.

**Comment by shsu571** [comment]
Reason do add to sprint:
landscape( Video ) : 
-important feature for first users 
-event amounts is increasing during COVID-19 period
MAU and DUA are growing strongly recently, and we know that users will use this feature at first day, so we need to make it better!

**Comment by tinahsieh** [comment]
Need to understand: 
1. The user problem with use cases
2. The reason for the previous decision

**Comment by youwenliang** [comment]
1. In landscape mode user want to 
- refresh
- change tabs
- navigation-related actions
(based on google playstore reviews)

2. Ask jack~

**Comment by tinahsieh** [comment]
UX spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/414477340_3-0_Landscape_Mode

**Comment by youwenliang** [comment]
Data Review:
https://docs.google.com/document/d/1Vah_AD50XLAr1-viYFMtFxR8eIEiHOPmTqOvE2T8W-A/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

**Comment by lanyliu** [comment]
Goal metrics: landscape stickiness should be improved 
(as we observed landscape mode is correlated to retention)

telemetry spec
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

add extra:
- orientation: portrait|landscape

**Comment by TLHuang** [comment]
Visual spec is ready https://zpl.io/bzZgp9l

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.17 (19496) preview
test step:
1. launch app 
2. tap top site [Wikipedia]
3. rotate to landscape mode

actual result as expected :
3. see [home] [reload] [search icon] [tab tray] [share] 

![Screenshot_20200512-151440](https://user-images.githubusercontent.com/44990878/81649907-a2124180-9463-11ea-8f96-266faae99486.png)

**Comment by Daisy-pliu** [comment]
To be aware the miniUrl bar landscape mode is not implemented it as it will be tracked on https://github.com/mozilla-tw/FirefoxLite/issues/4914

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release
