### ISSUE TITLE
[Feature] Double confirm when users are exiting Firefox Lite

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4861]
Ask me if “I really want to exit Firefox Lite” to prevent the accidental exit by tapping “back” several times. Since we don't have a back button in browsing mode, users would tap system back key to navigate the browser and could potentially exit the browser by accident.

**Comment by shsu571** [comment]
Reason do add to sprint:
This is form design audit and after PM, UX and UI discuss. We think it's import to let users know that users will leave after they tap back.

**Comment by TLHuang** [comment]
Specs are ready, please let me know if any questions!
UX https://mozilla.invisionapp.com/share/WMWW54K93DT
Visual https://zpl.io/beJA1QP

**Comment by ariefbayu** [comment]
Can we add an option to "ask question before exit", while implementing it?

**Comment by youwenliang** [comment]
@ariefbayu Hi, can you explain more about what "ask question" means? thanks!

**Comment by ariefbayu** [comment]
an option in this screen that says: "add confirmation before exit (hit back button)" or something along the line

![photo_2020-04-21_14-43-08](https://user-images.githubusercontent.com/55084/79839325-8ffe2f80-83de-11ea-9eaf-ae90063422a3.jpg)

**Comment by ariefbayu** [comment]
The reason behind this is to support users who prefer original behaviour.

**Comment by youwenliang** [comment]
Data Review:
https://docs.google.com/document/d/1ohgkOdJy-TQWMpl8rs-6RgtTMMwQKBWuvjd6upT0iMQ/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1t2coNwv-UrhVBcjiYHJDLNsI-RhDG5IRw1Blu1wwJxQ/edit#gid=888392947

**Comment by lanyliu** [comment]
telemetry spec
https://docs.google.com/spreadsheets/d/1t2coNwv-UrhVBcjiYHJDLNsI-RhDG5IRw1Blu1wwJxQ/edit#gid=888392947


Amplitude: Show Exit Warning Toast 
Telemetry: show, toast, exit_warning

**Comment by Daisy-pliu** [comment]
Verify:  ✅
Version : 2.1.17 (19526) preview
Test step:
1. launch app
2. tap top site
3. tap sys back
4. tap sys back
5. tap sys back

Result
4. see [Press back again to exit]
5. exit app successfully

**Comment by Daisy-pliu** [comment]
will add test case in Fxlite exit browsing scenarios in test case sheet.
This feature will test on release build

**Comment by Daisy-pliu** [comment]
Added only positive case as TC0223 in test case sheet

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release
