### ISSUE TITLE
[Feature] Popup keyboard automatically when a user adds a new tab

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4862]
The “+” in tab tray should go back to the home UI with the keyboard opened. We assume that when a user wants to add a new tab they would want to do a search query so having the keyboard up would be easier for them to do so.

(But if a user taps "home" button then the keyboard won't be opened automatically)

**Comment by shsu571** [comment]
Reason do add to sprint:
This is form design audit and after PM, UX and UI discuss for let "+" has more clear next action.

**Comment by Daisy-pliu** [comment]
verify:✅
version : 2.1.16 (19360)Preview
test step:
1. launch app
2. tap any [topsite]
3. tap [tab tray] -> [+]

Actual Result:
see homepage with keyboard popup 
Expect Result: 
see homepage with keyboard popup

**Comment by Daisy-pliu** [comment]
Changed [+] behavior on test cases TC0087, TC0076, TC0197, SHOP019.

verify: ✅
version: 2.1.16 (19357)
