### ISSUE TITLE
Check copy string to see the rule of using all title case/ all cap

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4863]
Check copy string to see the rule of using all title case/ all cap to ensure UI consistency.
@TLHuang is working on this.

**Comment by TLHuang** [comment]
The first image shows the buttons need to be justified.
![Buttons UI consistency_Current](https://user-images.githubusercontent.com/4092794/78543582-6fa17300-782b-11ea-9b9e-57904ec56c1f.jpg)

The expected result as below, feel free to let me know if any question.
![Buttons UI consistency_Expected](https://user-images.githubusercontent.com/4092794/78543589-73cd9080-782b-11ea-9de3-263f0a34298d.jpg)

**Comment by chianger** [comment]
verification efforts will be more than S, considering localization.
