### ISSUE TITLE
[AB Test] Top Site, Group setting - Default Top Site Update 2/3

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4871]
Spec check notes:
doc:https://docs.google.com/document/d/1z9I9zlBM05OKwtALps4oYa96VPbYg4NZKTrLRQ0TApI/edit#
country - sim card ; new user- check from version

Group method:
https://docs.google.com/document/d/1z9I9zlBM05OKwtALps4oYa96VPbYg4NZKTrLRQ0TApI/edit#heading=h.g3d4s4ch64r2

Data of   str_top_sites_fixed_items ; str_top_sites_default_items 
https://docs.google.com/document/d/1z9I9zlBM05OKwtALps4oYa96VPbYg4NZKTrLRQ0TApI/edit#bookmark=id.zt707ssinou

Metrics: https://docs.google.com/spreadsheets/d/1T0d8HTCnhA495zsaszSAAAqz_PRISAtlyTBnOCfig2U/edit#gid=1007897701

Tracking even add two new parameter: source and position

Also need to do satisfaction survey for each group
Need to make sure: can send push notification for different group to do satisfaction survey

**Comment by lanyliu** [comment]
Two definitions to provide:
1. the logic for experiment grouping
2. telemetry for removing topsite

**Comment by lanyliu** [comment]
**Experiment Grouping**

spec
https://docs.google.com/spreadsheets/d/1T0d8HTCnhA495zsaszSAAAqz_PRISAtlyTBnOCfig2U/edit#gid=1007897701

- India, New User only (excl. update user)

Group desc | experiment_name | experiment_bucket
-- | -- | --
Control | in_topsite_rr_0429_control | 1
Control AA | in_topsite_rr_0429_aa | 2
Group 1: version 1.6 (New) | in_topsite_rr_0429_2pinned | 3
Group 2:  version 1.6 | in_topsite_rr_0429_2unpinable | 4
Group 3: version 1 | in_topsite_rr_0429_0pinned | 5
Group 4: Control (New) | in_topsite_rr_0429_4unpinable | 6

- Indonesia, New User only (excl. update user)

Group desc | experiment_name | experiment_bucket
-- | -- | --
Control | id_topsite_rr_0429_control | 1-4
Group 1: version 1.6 (New) | id_topsite_rr_0429_2pinned | 5-8
Group 2:  version 1.6 | id_topsite_rr_0429_2unpinable | 9-12
Group 3: version 1 | id_topsite_rr_0429_0pinned | 13-16
Group 4: Control (New) | id_topsite_rr_0429_4unpinable | 17-20

**Comment by lanyliu** [comment]
**Telemetry**

spec
https://docs.google.com/spreadsheets/d/1T0d8HTCnhA495zsaszSAAAqz_PRISAtlyTBnOCfig2U/edit#gid=888392947

modified in extra 
- on
- source

**Comment by Daisy-pliu** [comment]
## INDONESIA
Test with Indo SIM on version Nightly 2.1.15(19323)
### Group 1 :  2 fixed 6 user sites
#### 2 Fixed Shopee, Buka
1. Should not be remove or pin ✅
#### 6 user sites
1. Can be pinned .Once pinned it goes to the first order ✅
2. Can be removed ❌ [Bug, can not remove youtube]

### Group 2 :  2 default pin partner site, 6 user sites
#### 2 pinned sites: Shopee, Buka
1. Can not be pinned ✅
2. Can be removed ✅
#### 6 user sites : can be pinned and removed
1. Can be pinned .Once pinned it goes to the first order ✅
2. Can be removed ❌[Bug, can not remove e.g. Youtube]

### Group 3 :  8 user topsites
#### 8 user topsite
1. Can be pinned ✅
2. Can be removed ❌ [BUG-2]

### Group 4 :  4 default pin partner site,  4 user sites
#### 4 default pin partner sites 
1. Can not be pinned ✅
2. Can be removed ✅
#### 4 user sites
1. Can be removed ❌ [BUG -1 ]
2. Can be pinned ✅
### Control+AA : 4 fixed, 4 user default sites
#### 4 fixed
1. Can not be pinned nor removed ✅
#### 4 user default sites
1. Can be pinned .Once pinned it goes to the first order ✅
2. Can be removed ❌ [Bug, can not remove youtube]

## INDIA
Test with India SIM on version Nightly 2.1.15(19323).
### All groups
❌ All failed , when fresh launched app, it shows topsites in order : FRVR, booking.com, KKDay,Shopee, Youtube,Facebook,Twitter, Instagram which does not match spec , should be newspoint, Gamezop, dailyhuant...

**Comment by Daisy-pliu** [comment]
I assume the `remove topsite bug` are same issue that occurs on many scenarios in Indonesia.
So I list 2 bugs below first to better analysis and find root cause.

### BUG -1  [ Group 4 - 4 pinned sites and  4 user default sites ]
1. Launch app to see 4 pinned sites and  4 user default sites
2. Remove any 1  user default sites (e.g. Youtube)

#### Actual result 
2. see 4 pinned partner sites and 3 pinned sites  (they are Youtube, Facebook, Twitter) and more sites (Linkedin, eBay, Reddit)

#### Expect result
2.1 youtube site should be removed 
2.2 should not see  any more pinned sites (Youtube, Facebook, Twitter) to the user
2.3 the original user default sites are missing (Okezone,Tribunnews,Youtube, Derik)

###  BUG -2  [ Group 3 - 8 user default sites ]
1. Launch app to see 8 user default sites
2. Remove Youtube topsite
#### Actual result
1. correctly shows 8 sites (Shopee,Bukalapak, Gameloft, Okezone,Tribunnews,Youtube, Derik)
2.  It shows Youtube, Facebook, Twitter, Instagram,Reddit, eBay , which are all user default sites
#### Expect result
2.1 Youtube should be removed
2.2 The original unremoved user default sites should be displayed

**Comment by Daisy-pliu** [comment]
verify: ❌
## INDIA
Test with India SIM on version Nightly 2.1.16(19357).
###  Control+AA
Control+AA | 4 fixed | 0 | 4 | IN  1 - 2ID  17-20 | no one get into this group*
-- | -- | -- | -- | -- | --

**Expect:**
4 Fixed: newspoint, Gamezop, Dailyhunt, Covid-19
4 User default:  Youtube, FB, wikipedia, Indiatimes. 
<img width="300" alt="Screen Shot 2020-04-24 at 11 05 08 AM" src="https://user-images.githubusercontent.com/44990878/80171187-4438c980-861c-11ea-8ad6-f181d6e4d754.png">



**Actual:**
Fixed: newspoint, gamezop, flipkart, booking.com
User default: Youtube, FB, Reddit, Instagram, twitter, eBay, Twitch, Stackoverflow, Medium, Health 

First page topsites
<img src="https://user-images.githubusercontent.com/44990878/80171010-ec01c780-861b-11ea-8f60-10f433df55d1.jpg" width="300" height="500">
Second Page topsites
<img src="https://user-images.githubusercontent.com/44990878/80171009-ead09a80-861b-11ea-9599-c0faed40c5e8.jpg" width="300" height="500">

**Comment by shsu571** [comment]
top site sheet is being refreshed.  I will try to make it back to previous version.

**Comment by Daisy-pliu** [comment]
It is a misunderstanding, in India it is expected to have a "default group" that falls 7-20 bucket with 4 fixed sites and 12 user default sites. If we add this group in spec, I think it will look more clear for QA.

**Comment by Daisy-pliu** [comment]
## INDIA
Test with Indo SIM on version Release 2.1.16(19357)
### Group 1 :  2 fixed 6 user sites
#### 2 Fixed: Shopee, Buka
1. Can not remove or pin ✅
####  6 user sites
1. Can be pinned .Once pinned it goes to the first order ✅
2.Can be removed ✅

### Group 2 :  2 default pin partner site, 6 user sites
#### 2 pinned sites: Shopee, Buka
1. Can not be pinned ✅
2. Can be removed ✅
#### 6 user sites : can be pinned and removed
1. Can be pinned .Once pinned it goes to the first order  ✅
2. Can be removed ✅


### Group 3 :  8 user topsites
#### 8 user topsite
1. Can be pinned✅
2. Can be removed ✅

### Group 4 :  4 default pin partner site,  4 user sites
####  4 default pin partner sites 
1. Can not be pinned ✅
2. Can be removed ✅
#### 4 user sites
1. Can be removed ✅
2. Can be pinned ✅
###  Control+AA : 4 fixed, 4 user default sites
####  4 fixed
1. Can not be pinned nor removed ✅
#### 4 user default sites
1. Can be pinned .Once pinned it goes to the first order✅
2. Can be removed ✅

**Comment by Daisy-pliu** [comment]
given only QA has SIM card, we helped BI team to verify telemetry this time.

- India, New User only (excl. update user)

Group desc | experiment_name | experiment_bucket | verify
-- | -- | --| --
Control | in_topsite_rr_0429_control | 1 | ✅
Control AA | in_topsite_rr_0429_aa | 2 | ✅
Group 1: version 1.6 (New) | in_topsite_rr_0429_2pinned | 3 | ✅
Group 2:  version 1.6 | in_topsite_rr_0429_2unpinable | 4 | ✅
Group 3: version 1 | in_topsite_rr_0429_0pinned | 5 | ✅
Group 4: Control (New) | in_topsite_rr_0429_4unpinable | 6 | ✅

- Indonesia, New User only (excl. update user)

Group desc | experiment_name | experiment_bucket | verify
-- | -- | --| --
Control | id_topsite_rr_0429_control | 1-4 | ✅
Group 1: version 1.6 (New) | id_topsite_rr_0429_2pinned | 5-8 | ✅
Group 2:  version 1.6 | id_topsite_rr_0429_2unpinable | 9-12 | ✅
Group 3: version 1 | id_topsite_rr_0429_0pinned | 13-16 | ✅
Group 4: Control (New) | id_topsite_rr_0429_4unpinable | 17-20 | ✅

**Comment by Daisy-pliu** [comment]
> <@UE18AFUBX> topsite 測試步驟  <https://trello.com/c/8JlRy32U>
cc <@UKT9R3W8L>
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1587709952439200)</sub>
