### ISSUE TITLE
[AB Test] Top Site, AB test close 3/3

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4872]
Logic of order:
str_top_sites_fixed_items  
str_top_sites_default_items 
User recently use ( user opens for more than twice)

https://docs.google.com/document/d/1z9I9zlBM05OKwtALps4oYa96VPbYg4NZKTrLRQ0TApI/edit#
This the basic logic for all the group.
https://github.com/mozilla-tw/FirefoxLite/issues/4871

**Comment by shsu571** [comment]
Need to do Sprint 4-5

**Comment by Daisy-pliu** [comment]
verify :✅ on India SIM and Indo SIM
version : 2.1.17(19490) preview 
not see any A/B testing topsites with India or Indo sim as expected

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release
