### ISSUE TITLE
Firefox Lite resubmit 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4875]
After closed these two issues, please resubmit on the Google Play!
https://github.com/mozilla-tw/FirefoxLite/issues/4873
https://github.com/mozilla-tw/FirefoxLite/issues/4874

Will let @Daisy-pliu  know after all the remote config changed and ready to submit.

**Comment by Conjuror** [comment]
build 19244 is sent and pushed

**Comment by Daisy-pliu** [comment]
verify: ✅
verify on Preview.
