### ISSUE TITLE
[Shopping Search] MiniURL bar didn't collapse on scroll in the latest build

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4878]
**Describe the bug**
MiniURL bar didn't collapse on scroll in the latest build

**Steps To Reproduce**

1. Go to shopping search
2. Search a keyword and see the results
3. See Google tab
4. Scrolling in the Google tab or any tab

**Expected behavior**
MiniURL bar collapse to smaller version when scrolling

**Actual behavior**
MiniURL bar didn't change.

Version 2.1.12(19244)

This is related to #4828

**Comment by benjamin-cheng** [comment]
@proevan I found this issue only happened on the devices with display cutouts.
