### ISSUE TITLE
[Shopping Search] MiniURL bar should appear when users go to other URL in the same tab

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4885]
**Describe the bug**
MiniURL bar should appear when users go to other URL in the same tab for security reason. Users need to know they are not in the same URL.

**Steps To Reproduce**
1.  Go to shopping search
2.  Search a keyword and see the results
3.  See tab
4.  Click any link the tab
5.  Go to other link without seeing URL change

**Expected behavior**
Show URL bar when users click any link in one tab

**Actual behavior**
Hide URL bar when users click any link in the one tab

**Device info (please complete the following information):**
 2.1.14(19257)

**Comment by chianger** [comment]
as per discussion we would like to ship hot fix on this.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.15(19278) preview 
[Steps To Reproduce](https://github.com/mozilla-tw/FirefoxLite/issues/4885#issue-597649684)

**Comment by Daisy-pliu** [comment]
> <!here> We are good to roll out Hofix 2.1.15 on Beta 99%, please let me know if you have any concerns , thank you !
1. Adjust pass
2. Hotfix verified on  <https://github.com/mozilla-tw/FirefoxLite/issues/4885>
<sub>[View in Slack](https://mozilla.slack.com/archives/CS7KS9DT6/p1586767393172300)</sub>

**Comment by shsu571** [comment]
Some websites still not show url.
flipkart.com/
https://www.clubfactory.com/
Final confirm with @proevan
