### ISSUE TITLE
[Webpage] Video can not switch to landscape correctly on the Youtube website

### ISSUE THREAD

**Issue by swlibi** [mozilla-tw/FirefoxLite#4891]
**Describe the bug**
Video can not switch to landscape correctly on the Youtube website.

**Steps To Reproduce**
1. Launch firefox lite preview
2. click the Youtube shortcut on the homepage 
3. Play the video
4. Enter fullscreen mode
5. Put the device to landscape mode

**Expected behavior**
Switch mode correctly

**Screenshots/videos**
https://drive.google.com/file/d/1U6Kd9LtI5T2ASBllabRzhobdzeZw0JPx/view?usp=sharing

**Device info (please complete the following information):**
 - Device: ASUS_X01AD
 - OS:Android 9
 - Webview 81.0.4044.96
 - Version 2.1.15 19280

**Reproduce rate**
5/5

**Comment by swlibi** [comment]
I also can reproduce this issue on Samsung A50

**Comment by shsu571** [comment]
dup for #4859

**Comment by Daisy-pliu** [comment]
Let's trace in #4859 thanks !

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.15(19343) Preview
Device: Samsung (8.0) , Pixel 2(9.0)
webview: stable (81.0.4044.111) , beta (83.0.4103.14)
