### ISSUE TITLE
Top Site change 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4897]
**Remote config name**
str_top_sites_fixed_items

**Audience setting**
Parameter + Audience
https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0
2020/4/18 updated the change part (yellow highlight)

**Expected Online Time**
4/18 or as soon as possible!

**Additional context**
Pls share screenshot of preview before going live with Diane.

**Comment by Daisy-pliu** [comment]
Test env: Nightly 
Debug County : India
![Screenshot_20200416-155824](https://user-images.githubusercontent.com/44990878/79430317-581c7400-7ffb-11ea-9b48-ba29a0037869.png)

**Comment by shsu571** [comment]
favicon name :  ic_dailyhunt.webp

**Comment by Daisy-pliu** [comment]
Test : 2.1.15 (19278) Preview
![Screenshot_20200417-104119](https://user-images.githubusercontent.com/44990878/79526589-2c9b9700-8098-11ea-88d4-20cd2541c563.png)

**Comment by Daisy-pliu** [comment]
Test : 2.1.15 (19278) Preview
Partner name change
![Screenshot_20200417-142333](https://user-images.githubusercontent.com/44990878/79538528-1ea93e80-80b7-11ea-8d3d-989c1ebe9294.png)

**Comment by Daisy-pliu** [comment]
Verify :  2.1.15(19297) Prod
