### ISSUE TITLE
Add Amazon icon for top site uploading preparation (India)

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#4899]
For uploading the Amazon logo into production.
https://drive.google.com/file/d/1kwEeGAalkZW1cltQ7lu_NwY530CHReuE/view?usp=sharing

**Expected Online Time**
After Amazon IN resumes business.
(BD will notify the team once partner confirms can go live)

@youwenliang @shsu571

**Comment by shsu571** [comment]
Need to get 72*72
![amazon72](https://user-images.githubusercontent.com/52307187/80334246-3b95fc80-8883-11ea-8265-095df6d178ce.png)
Could @TLHuang  check this would be okay or not?

**Comment by shsu571** [comment]
Still need to confirm name of icon
We already have app/src/main/assets/topsites/icon/ic_amazon_in.png
@yowazzzup  Do you think we need to keep this one?

**Comment by yowazzzup** [comment]
@shsu571 Hi, suggest we don't need to keep the old icon, since new one is provided. Or if you like,  we can try both on preview and have partner decide which one looks better.

**Comment by TLHuang** [comment]
@shsu571 The icon looks okay and does follow the guideline, below is the guide for your reference. Please let me know if any future questions.
![Topsite Icon](https://user-images.githubusercontent.com/4092794/80342260-69387100-8896-11ea-897b-b1f1f6221115.jpg)

**Comment by proevan** [comment]
<img width="348" alt="Screen Shot 2020-04-27 at 3 09 04 PM" src="https://user-images.githubusercontent.com/5226898/80343770-0eecdf80-8899-11ea-985c-b085e7271214.png">

seems like there's a transparent border, is that ok? @shsu571 @TLHuang

**Comment by yowazzzup** [comment]
Oh wow I'm not sure that looks good >< I'm attaching a bigger file,
can you help transfer and resize the file to see if the transparent boarder can be adjusted?  thanks @proevan https://drive.google.com/file/d/1MJVd-HVr2h_78mxqceDMj9sPCP-A6F3d/view?usp=sharing

**Comment by shsu571** [comment]
I will confirm with @TLHuang  and update here latter

**Comment by TLHuang** [comment]
I've resized the image size to 72x72, and there should be no transparent area. 
![amazon](https://user-images.githubusercontent.com/4092794/80469681-7a0ae480-8973-11ea-99e8-612e442445cd.jpg)

**Comment by shsu571** [comment]
Thank you @TLHuang

**Comment by Daisy-pliu** [comment]
QA will test on another remote config ticket as it will be configured via Firebase remote config next week.
