### ISSUE TITLE
The Smart Shopping Search banner will be placed on a wrong position in landscape mode

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4903]
**Describe the bug**
The Smart Shopping Search banner will be placed on top of the screen in landscape mode. Since it was designed to be on the bottom, users have to swipe down on the banner to close it, which is unintuitive.

**Screenshots/videos**
![Screenshot_20200418-190440_Firefox Lite](https://user-images.githubusercontent.com/17559807/79710517-ca40d180-82f7-11ea-8229-c8cc287fcbe7.jpg)

**Reproduce rate**
100%

**Comment by benjamin-cheng** [comment]
It has been fixed in #4952

**Comment by Daisy-pliu** [comment]
verify ✅
version 2.1.18(19583) Release
![Screenshot_20200522-105656](https://user-images.githubusercontent.com/44990878/82626761-324a4680-9c1b-11ea-88e5-bd6911c3a6ea.png)
