### ISSUE TITLE
[Remote Config] Amazon India's Shopping Search tracking link

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#4907]
**Remote config name**
str_shopping_search_sites

**Audience setting**
India only.

**Parameter + Audience**
Need to add Amazon IN's searchUrl and order for India.
Have Amazon IN site's order to (No.2), next to Google (No.1)

Add Amazon IN's tracking URL for Smart Shopping Search:
See detail in this document: https://docs.google.com/document/d/1IJIQbnsGsMO9b3xBIOAFN9NySkXxoh0V9rNVZ9l2phk/edit?usp=sharing

**Expected Online Time**
As soon as possible. 

@youwenliang @shsu571

**Comment by youwenliang** [comment]
Search link for Amazon:
https://www.amazon.in/s?_encoding=UTF8&tag=smartshoppingsearch-21&linkCode=ur2&linkId=69eaba918d82ba6666a4a6a0185c0640&camp=3638&creative=24630&k=

**Comment by Daisy-pliu** [comment]
verify:✅ 
version : 2.1.17(19453) preview
finishes setup on Preview remote config on India of debug page
![Screenshot_20200512-134952](https://user-images.githubusercontent.com/44990878/81643200-ac2e4300-9457-11ea-8c1e-73ba1c2a4937.png)
Let me know it is good on Production.

**Comment by youwenliang** [comment]
Look good to me, but we will need a day to check Amazon's backend and see if the clicks are recorded. Will let you know tomorrow @Daisy-pliu

**Comment by youwenliang** [comment]
@Daisy-pliu the clicks are recorded! Good to go for production.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.17 (19437) Release
Finished config on Firebase remote config on Prod

**Comment by Daisy-pliu** [comment]
however the icon will show in the upcoming release build 2.1.18

**Comment by youwenliang** [comment]
@Daisy-pliu do you mean the top site icon?

**Comment by Daisy-pliu** [comment]
![Screenshot_20200522-112121](https://user-images.githubusercontent.com/44990878/82628124-91f62100-9c1e-11ea-9082-f9386c58e86c.png)
