### ISSUE TITLE
[Shopping Search] MiniURL bar should appear when users go to other URL of same website in the same tab 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4910]
**Describe the bug**
MiniURL bar should appear when users go to other URL in the same tab for security reason even in the **same website**.  Users need to know they are not in the same URL.

**Steps To Reproduce**
1.  Go to shopping search
2.  Search a keyword and see the results
3. See tab
4. Click any link with **same website** the tab
5. Go to other link without seeing URL change

**Expected behavior**
 Show URL bar when users click any link in same website in one tab

**Actual behavior**
 Hide URL bar when users click any link in the one tab

**Device info (please complete the following information):**
 - 2.1.15(19277)

**Comment by Daisy-pliu** [comment]
verify: ❓
version : 2.1.17(19526) preview
test scenario: landscape/scroll_tap - TC0216
test step
1. launch app
2. tap [wikipedia] topsite
3. rotate to landscape
4. scroll down 
5. scroll up
6. click any link

Expect result 
1. see [url bar] [tool bar ] from [UX spec](https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/414477343_3-3_Scrolling_In_Landscape_Mode)

Actual result
1. see [url bar] only 

please let me know if it is mandatory requirement, thanks.

**Comment by Daisy-pliu** [comment]
If it is not a hard requirement we can trace it in https://github.com/mozilla-tw/FirefoxLite/issues/4979 for the next sprint, otherwise it will be a blocker to the current release, thanks !

**Comment by Daisy-pliu** [comment]
Confirm with PM and UX it is not a blocker so we are going to pass this scenario and track the missing part in #4979.

**Comment by Daisy-pliu** [comment]
Verify: ✅
Version : 2.1.17(19529)
Test Steps :
 1.  Go to shopping search
 2. Search a keyword and see the results
 3.  Click any link with same website the tab
 4. Go to other link without seeing URL change

**Comment by Daisy-pliu** [comment]
This sceanrio adds to test case **SHOP023- scroll & tap & compare prices among sites.** 
Will test on Release build.

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.18(19583) Release
