### ISSUE TITLE
Custome Build confirm

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4911]
**Description**
We found that few countries have significant growth like Iran and Russia. We want to confirm their build number 

**The build we find on the forum or Meltwater** 

- https://phcorner.net/threads/853779/#post-15124061
APK:https://drive.google.com/file/d/1AdLEuZftMJdQI1zPvbdNvl8-m6NqP5FQ/view?usp=sharing
- postapk https://postapk.com/firefox-browser-fast-private-v68-7-0-mod-apk-latest/
APK: https://drive.google.com/open?id=1FsAtkC5mDE_vAQ44RTJ8eMkdrFYfnppl
- https://modapkpros.com/2020/04/firefox-lite-fast-and-lightweight-web-browser-2-1-1419257.html
APK: https://drive.google.com/open?id=1rqmZt0355zY92UjyofVRW81mXelaNbqj

**Additional context**
Need to confirm what is build number of each apk.
Please use test device to confirm!

**Comment by Daisy-pliu** [comment]
1. https://phcorner.net/threads/853779/#post-15124061 
    - The downloaded link is a link refer to itself, not a Firefox Lite apk file
    - It keeps spam with sexual ads
2. APK:https://drive.google.com/file/d/1AdLEuZftMJdQI1zPvbdNvl8-m6NqP5FQ/view?usp=sharing
    - It is required to send request to get permission
3. postapk https://postapk.com/firefox-browser-fast-private-v68-7-0-mod-apk-latest/
    - It is Firefox app, not Firefox Lite
4. APK: https://drive.google.com/open?id=1FsAtkC5mDE_vAQ44RTJ8eMkdrFYfnppl
    - It is required to send request to get permission
5. https://modapkpros.com/2020/04/firefox-lite-fast-and-lightweight-web-browser-2-1-1419257.html
   - Firefox Lite 2.1.14 (19257) However the topsites , shopping search look different from our global configuration
   - If PMs want to check and download this apk please reach me I will send you the Apk.

![Screenshot_20200504-142910](https://user-images.githubusercontent.com/44990878/80942140-a1036380-8e16-11ea-9cce-29c153ecc61b.png)
![Screenshot_20200504-142923](https://user-images.githubusercontent.com/44990878/80942151-a5c81780-8e16-11ea-9c0f-a5188b5898a1.png)


6. APK: https://drive.google.com/open?id=1rqmZt0355zY92UjyofVRW81mXelaNbqj
      - It is required to send request to get permission

**Comment by shsu571** [comment]
Could we have build @Daisy-pliu ?
