### ISSUE TITLE
[Feature] Landscape mode with search actions

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4914]
With the toolbar in landscape browsing mode, enable users to use search button and miniURL bar to start a search action.

This is related to #4860 

UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/414477341_3-1_Principle_And_Priority

**Comment by youwenliang** [comment]
Data request same as #4860 

Data Review:
https://docs.google.com/document/d/1Vah_AD50XLAr1-viYFMtFxR8eIEiHOPmTqOvE2T8W-A/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

**Comment by Daisy-pliu** [comment]
verify:  ✅
version : 2.1.17(19526)
Test scenario: landscape / mini url bar (or seach bar)
Test case: TC0220
Test step: 
1. launch app
2. search any webpage
3. rotate to landscape
4. tap [mini url bar] or [search icon]
5. search any word 
6. rotate 
7. enter

Test result as expected:
4. see search keyboard popup in landscape mode 
6. see word is still there
7 .see search results

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Releas
