### ISSUE TITLE
[Feature] Landscape mode with access to Tab Tray

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4915]
With the toolbar in landscape browsing mode, enable users to use tab tray to perform actions such as switching tabs, adding a new tab (back to home), closing tabs or all tabs, and visiting private mode.

This is related to #4860 

UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/414477342_3-2_Search_In_Landscape_Mode

**Comment by youwenliang** [comment]
Data request same as #4860 

Data Review:
https://docs.google.com/document/d/1Vah_AD50XLAr1-viYFMtFxR8eIEiHOPmTqOvE2T8W-A/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

**Comment by youwenliang** [comment]
Need some UI adjustments here. Will share more information after design audit.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.17 (19496 ) preview

✅ 1. [Test  scenario : shopping search tab exists-> enter shopping search ] 
1. shopping search results exists
2. tab tray has more than 1 tabs
3. rotate screen to landscape mode
4. tap [tab tray]
5. tap [shopping search] 

Result: 
5. see shopping search in portrait mode

✅ 2. [Test  scenario :  shopping search tab exists -> close all  ] 
1. shopping search results exists
2. tab tray has more than 1 tabs
3. rotate screen to landscape mode
4. tap [close all] in landscape mode
5. tap [yes] 

Result: 
4  see dialog in landscape mode
5. tabs closed successfully in landscape mode

✅ 3. [Test  scenario : shopping search tab exists -> close tabs -> close shopping search ]
1. shopping search results exists
2. tab tray has 1 tab
3. rotate screen to landscape mode
4. tap [close all ] on tab tray
5. tap [yes] 
6. tap [close ] on shopping search tab
7. tap [yes] 

Result: 
4. see dialog in landscape mode
5. see tab tray in landscape mode
6. see dialog in landscape mode
7.  see home in portrait mode

✅ 4. [Test  scenario : tap private mode ]
1. tab tray has more than 1 tabs
2. rotate screen to landscape mode
3. tap [private icon] in landscape mode 

Result: 
3.  see private browsing in portrait mode

✅ 5. [Test  scenario : add new tab  ]
1. tab tray has more than 1 tabs
2. rotate screen to landscape mode
3. tap [+] in landscape mode 

Result: 
3.  see a new tab in portrait mode


✅ 6. [Test  scenario : close all -> confirmation dialog ]
1. tab tray has more than 1 tabs
2. rotate screen to landscape mode
3. tap [close all ] in landscape mode
3. tap [yes ] in landscape mode

Result: 
3.  see home page in portrait mode

**Comment by TLHuang** [comment]
The padding of toolbar needs to be adjusted, currently it's too close to both sides of the screen.

![Screenshot_20200519-165433_Firefox Lite Preview](https://user-images.githubusercontent.com/4092794/82306635-e36d9880-99f1-11ea-9d6a-2b4c5d6add1a.jpg)

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Releas

**Comment by lanyliu** [comment]
remove "need BI audit" since #4860 finished
