### ISSUE TITLE
[Feature] Landscape mode with share link capability

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4916]
With the toolbar in landscape browsing mode, enable users to use share button to access system share panel to share links to others.

This is related to #4860 

UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/414477341_3-1_Principle_And_Priority

**Comment by youwenliang** [comment]
Data request same as #4860 

Data Review:
https://docs.google.com/document/d/1Vah_AD50XLAr1-viYFMtFxR8eIEiHOPmTqOvE2T8W-A/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.17(19496) preview
1. launch app in portrait mode
2. tap [any topsite] 
3. rotate to landscape mode
4. tap [share] -> [slack]

result is expected: 
successfully share message from slack

**Comment by Daisy-pliu** [comment]
QA will add test scenarios and test case on testcase sheet.
This ticket will be tested on release build.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release
