### ISSUE TITLE
[Feature] Landscape mode with collapsible toolbar & urlbar

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4917]
With the toolbar in landscape browsing mode, enable toolbar and urlbar to collapse (auto hide) when users are scrolling through contents. The behaviors will be the same in portrait mode, including showing toolbar back when visiting other urls.

This is related to #4860 

UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/414477343_3-3_Scrolling_In_Landscape_Mode

**Comment by youwenliang** [comment]
Data request same as #4860 

Data Review:
https://docs.google.com/document/d/1Vah_AD50XLAr1-viYFMtFxR8eIEiHOPmTqOvE2T8W-A/edit?usp=sharing

Data Spec:
https://docs.google.com/spreadsheets/d/1PNCfD3MUEZq-LAFAIz1SASIYBQdIh2D-sRmx5hL7WIY/edit#gid=888392947

**Comment by proevan** [comment]
@youwenliang if it's easier to also have collapsible toolbar and urlbar in portrait mode, should we have it?

**Comment by youwenliang** [comment]
Do you mean this #4837? @proevan 
Let's do both at the same time if it's easier for you!

**Comment by proevan** [comment]
> Do you mean this #4837? @proevan
> Let's do both at the same time if it's easier for you!

Yes, let's enable it on portrait mode as well and see if there are any extra problems

**Comment by youwenliang** [comment]
Got it, thanks @proevan

**Comment by Daisy-pliu** [comment]
verify : ❓
test step:
1. launch app
2. tap top site [Youtube]
3. scroll down to browse 

Actual result: 
3. Youtube search bar is hided

![Screenshot_20200512-141322](https://user-images.githubusercontent.com/44990878/81644817-0aa8f080-945b-11ea-8fcc-aaffe2b55395.png)


expect result:
3. see Youtube search bar when scrolling

![Screenshot_20200512-141327](https://user-images.githubusercontent.com/44990878/81644820-0bda1d80-945b-11ea-919b-5f6b4a209383.png)

@youwenliang  please let me know if it is an expected result, thank you !

**Comment by youwenliang** [comment]
I think this is Youtube's own behavior, so this should be expected.

**Comment by Daisy-pliu** [comment]
verify : ❌
test step:
1. launch app 
2.tap top site [Youtube]
3. rotate to landscape mode
4. tap [mini url bar ] or [search ]

Actual result:
4. search UI in protrait mode

Expected result:
4. search UI in landscape mode

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2/.1.17 (19496) preview
test step:
1. launch app 
2. tap top site [Wikipedia]
3. rotate to landscape mode
4. scroll down 
5. scroll up 

Actual result:
2. see Navbar and toolbar 
3. see  Navbar and toolbar 
4. not see Navbar and toolbar 
5. see  Navbar and toolbar 

Noted that  laoded new url to see Navbar and toolbar  will be tracked on https://github.com/mozilla-tw/FirefoxLite/issues/4910

**Comment by Daisy-pliu** [comment]
will add test scenario and test case in Test case sheet.
Target to test the functionality in release build.

**Comment by tinahsieh** [comment]
The toolbar remains hidding after scrolling in the page.

Steps:
1. View a website in landscape mode 
2. Scroll the page and hide the bars
3. Tap on any URL
4. It shows the website without the toolbar.

![Screenshot_20200519-164352_Firefox Lite Preview](https://user-images.githubusercontent.com/17559807/82305413-2cbce880-99f0-11ea-866d-1478f23cd7bb.jpg)

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release

**Comment by lanyliu** [comment]
remove "need bi audit" since #4860 finished
