### ISSUE TITLE
[D0] Default browser setting flow

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4936]
- Feasibility for opening an external link (`Flow #2`, Brave/ Opera) -> MUST
Doc: https://docs.google.com/document/d/1kZXiupZZr-D8a7xtEmgXipUtNV6R68XuRNYvOPwygqY/edit#
- Telemetry : current users already set default browser -> MUST
- pixel : prompt open link (`Flow #3`)

**Comment by chianger** [comment]
From weekly meeting, this ticket will be preempted and  replace other landscape related features in current sprint 4-5.

Actions:
1. PMs please define a scope for this spike, and with corresponding priorities for each objectives.
2. Devs to evaluate from above results, and propose what tickets (around landscape mode features) to postpone.

**Comment by shsu571** [comment]
Already check the feasibility with engineers. 
Telemetry : current users already set default browser -> will be another issue  https://github.com/mozilla-tw/FirefoxLite/issues/4951
