### ISSUE TITLE
 [D0] Default browser setting flow #4936 -Telemetry

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4951]
Telemetry Spec (Wendy will provide this week)

**Comment by shsu571** [comment]
spec: https://docs.google.com/spreadsheets/d/1krWyXZmLeWzMzdmshBvZZ8f0fKdJKsKMjFh_3JrzA-w/edit#gid=888392947

**Comment by shsu571** [comment]
data review: https://docs.google.com/document/d/1Ca99ARLzRN0BQgolnjk5Pt0nvQ4cklKz03rDUx6TOTk/edit#
@cnevinc

**Comment by lanyliu** [comment]
done

**Comment by yshlin** [comment]
Rename to pref_default_browser_name (add 'pref' prefix) after discussion.

**Comment by benjamin-cheng** [comment]
@yshlin I found the property name would be too long for telemetry if we add the `pref` prefix. So, we might have to keep the previous name.

``` Name is too long. Type, maximum supported length, name: user property, 24, pref_default_browser_name```
