### ISSUE TITLE
Update India Top Sites for Amazon & Flipkart 

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#4960]
**Title**
Amazon Top Site Update
Flipkart Top Site Update

**Description**
Top Site tracking link renew:
https://docs.google.com/spreadsheets/d/1FrmcM2Dzx2-_4uMCRdGiK0BmRUE9OoRLohYmPniGHdU/edit#gid=0

(Renewed place is highlighted in Yellow)

**Expected time**
May 20th or anytime possible!
After the test and confirm, we can publish this setting!
Please announce on slack and note in this issue and the spreadsheet when this setting is published.

**Additional context**
Partner data confirm : Amazon data access -> https://docs.google.com/document/d/1IJIQbnsGsMO9b3xBIOAFN9NySkXxoh0V9rNVZ9l2phk/edit?usp=sharing

@youwenliang @shsu571

**Comment by shsu571** [comment]
amazon icon : ic_amazon_in.png

**Comment by Daisy-pliu** [comment]
verify: ✅
version:  2.1.17 (199526) preview
country: India_debug
I just made changes on Nightly as below , please take a look and let me know if it is expected. Thanks !
![Screenshot_20200518-105232](https://user-images.githubusercontent.com/44990878/82169996-c05dbe80-98f5-11ea-9228-24b2e6249ac9.png)

**Comment by Daisy-pliu** [comment]
Please double confirm the icon part , thanks !
Added the FlipKart icon 
![Screenshot_20200519-142001](https://user-images.githubusercontent.com/44990878/82291609-e3629e00-99db-11ea-8cc8-e64aa362523a.png)

**Comment by yowazzzup** [comment]
@Daisy-pliu  Perfect, thank you! We can have both Amazon and Flipkart live anytime now :)

**Comment by Daisy-pliu** [comment]
It is live on Production now in India.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.18(19583) Release
![Screenshot_20200522-112121](https://user-images.githubusercontent.com/44990878/82628124-91f62100-9c1e-11ea-9082-f9386c58e86c.png)
