### ISSUE TITLE
[Feature] D0: Set default browser -Android >=7 1/4

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4964]
This enhancement aims to increase the number of users to set Firefox Lite as their default browser, and make users increase their engagement and continue using Firefox Lite as their main browser. 
Need to apply >= Andriod 7

Detail of Spec
Doc: https://docs.google.com/document/d/1kZXiupZZr-D8a7xtEmgXipUtNV6R68XuRNYvOPwygqY/edit#

UX Spec: https://mozilla.invisionapp.com/share/3EX875TVXCY#/screens/417096800
https://mozilla.invisionapp.com/share/3EX875TVXCY#/screens/417096801

Full UX spec :https://mozilla.invisionapp.com/share/3EX875TVXCY
UI Spec: https://zpl.io/VYg1vRJ

Metrics
https://docs.google.com/spreadsheets/d/15Pqqx1J4HovyYdf_xncsPApucqZFvMJALTvVOGkBTyo/edit#gid=888392947

Data Review
https://docs.google.com/document/d/1A8wNPWw8SHReH7U0sBilBmfKvRFTBQjo0M6ITVBolyU/edit#

**Comment by benjamin-cheng** [comment]
Assume the t-shirt size would be `L` with typical telemetry requirement. I may update the size when the data spec is ready.

**Comment by yshlin** [comment]
Data spec done:
https://docs.google.com/spreadsheets/d/15Pqqx1J4HovyYdf_xncsPApucqZFvMJALTvVOGkBTyo/edit#gid=888392947

**Comment by Daisy-pliu** [comment]
### [TC0098] Make default browser - given no default user and then user set Lite as default
**Test case** 
1. given no default browser
2. go to settings
3.Tap [set as default browser]
4. Tap [go to settings]
5. Back to Lite

**Test result**
3. seet dialog [set lite as default in 30 sec] with [cacnel] and [go to settings]
4. See Firefox Lite settings page
5. see [thanks for choosing lite]


### [TC0099] Make default browser - given chrome is default user set Lite as default 
**Test case** 
1. given no default browser
2. go to settings
3. Tap [set as default browser]
4. Tap [ok, got it]

**Test result**
2. See Firefox Lite settings page
3. See dialog [select Firefox Lite, always ] with [ok] [cancel]
4. See toast [thanks for choosing lite]


### [TC00100] Failed to make default browser - given no default 
**Test Case**
1. given no default browser
2. go to settings
3. Tap [set as default browser]
4. Tap [ok, got it]
5. set chrome as default

**Test result**
2. See Firefox Lite settings page
3. See dialog [select Firefox Lite, always ] with [ok] [cancel]
4. See Firefox open external link 
5. see [wanna finished setting lite as yout default?]

**Comment by Daisy-pliu** [comment]
Noted: it will not dismiss snack bar [wanna finish setting LIte as default ?] [yes] after 8 sec, as it is still under fixing.

**Comment by Daisy-pliu** [comment]
> Noted: it should dismiss snack bar [wanna finish setting LIte as default ?] [yes] after 8 sec in our final decision
This behavior is correct on 2.1.19 (19732)

**Comment by yshlin** [comment]
Telemetry Verifyed

**Comment by Daisy-pliu** [comment]
will test on Release build

**Comment by Daisy-pliu** [comment]
Since the tutorial to set default browser is controlled by remote config we add remote config parameter in [FirefoxLIte2.0_RemoteConfig](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1047128443&range=A3)

**Comment by TLHuang** [comment]
![Screenshot_2020-06-09-16-05-18-792_org mozilla rocket beta](https://user-images.githubusercontent.com/4092794/84123771-e1d14680-aa6c-11ea-867b-9fa098d0334c.jpg)
In the open external link panel, Step 2 should be more closed to step 1, please help to adjust it.
Find the spec here https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5eb9126a648d084a7fabb852/
I will open the following bug and remove design audit for this one.
