### ISSUE TITLE
 [Feature] D0: menu 1/6 (overall)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4965]
Detail of Spec
Doc: https://docs.google.com/document/d/1N186Uefwyk9N1-NY1YIZMQbleO34HuKdRYlgXlR8DJY/edit#

UI UX Spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090395_4-0_Menu

Metrics
https://docs.google.com/spreadsheets/d/1pe-E0LBmqakeBwXu71EGsuzDhsx6_xLdA7fFRkdNipA/edit#gid=888392947

Data Review -> no need for data review (didn't add new telemetry)

**Comment by lanyliu** [comment]
there's no extra telemetry here. we can provide data mapping to UI spec for RD.
and since it's a major adjustment, we'll need audit after implementation.

**Comment by lanyliu** [comment]
**pin short cut (menu)**
- method: pin_shortcut
- object: menu
- value: link
Amplitude name: Click Menu Pin shortcut

**back (toolbar)**
- method: click
- object: toolbar
- value: back
- extra
   - position=[0-9]
Amplitude name: Click Toolbar - Back

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.21(19886)
test case:
1. freshlaunch app
2. tap [menu] -> [screenshots]
3. switch different tab
4. tap system back
5. tap any site
6. tap [menu] -> tap [take screenshot] 
7. tap [yes]

test result: 
2. see library panel with [screenshot][bookmark][history][downloads] icons
3. tab switched successfully
4 see homepage
6. see [access storage] dialog
7. see [view your screenshot onboarding] and [unread star] with a [hand ]

**Comment by tinahsieh** [comment]
UI/ UX review finished. Will file some bugs for future status tracking.

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(19906)

**Comment by yshlin** [comment]
We verified all telemetry pings are correct. Removing need BI audit label.
