### ISSUE TITLE
Awesome bar - effort valuation

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4966]
Doc: https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit

The result of awesome bar : 

- Bookmark
- History
- opened tabs
The ranking method needs to be like Fenix. 

UIUX 
![Clipboard](https://user-images.githubusercontent.com/52307187/82004034-817cfe00-9694-11ea-8b49-9198936cd489.jpg)
When users scroll the result of bookmarks, history, tabs result area, the keyboard will close up but the query area and keyword suggestion area will not close up. 
![Awesome Bar](https://user-images.githubusercontent.com/52307187/82004037-82ae2b00-9694-11ea-808b-c185431caa2c.jpg)

**Comment by cnevinc** [comment]
Making an item fixed above the input area is doable if we customize the UI. For search suggestion it's a quick fix. ( we keep our search suggestion, and only use Bookmark/history...etc for Awesomebar)

 For clipboard it'll take more time (We need to write more customize code). 
![image](https://user-images.githubusercontent.com/1287363/82181031-4c7ede80-9914-11ea-8c1f-00119c12c534.png)

For scrolling and hide the keyboard.
I'll need to spend more time look into it.

**Comment by cnevinc** [comment]
btw, this will increase the APK size ~86.2K
before: 6274202 (5.99 MB)
limit: 6291456.0 (6MB)
after: 6362400 (6.07MB)

**Comment by shsu571** [comment]
Add Source / Bookmark : 5 results
Add Source / History: 5 results
Add Source / Open Tab: 5 results

**Comment by cnevinc** [comment]
partially cover result 
https://drive.google.com/open?id=1vx3worqMSqhXw05jmk3xjU-BVSQQj_vp

**Comment by cnevinc** [comment]
btw, we also need to make sure if we use Android-Components, we need to pin to a specific version to avoid regression.
