### ISSUE TITLE
 [Feature] D0: Set default browser - Command/Deeplink 3/4

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4970]
**User story**
As a user, I can get to new default browser flow after I click an action item

**Acceptance Criteria (how do I know when I’m done?)** 
1.  Action item can be used in push notification
2.  Action item can be used in in app message

**Additional context**

**Comment by shsu571** [comment]
<img width="472" alt="螢幕快照 2020-05-25 下午6 32 50" src="https://user-images.githubusercontent.com/52307187/82805200-2e862080-9eb6-11ea-9a32-8ee088469f26.png">

**Comment by Daisy-pliu** [comment]
verify: ✅
Verify : 2.1.19(19732)
### [Test case 1 ]  ✅
**Test step**
1. given no default browser
2. launch app and insert default browser deeplink on url bar
3. tap [ok]
4. tap [always]

**Test result**
2. see [how to always browser with Lite? ]with [cancel] and [ok]
3. see [browser menu] with [just once] [always]
4. See toast [thanks for choosing lite]

### [ Test case 2]  ❌ 
**test step**
1. given Chrome is default browser
2. launch app and insert default browser deeplink on url bar
3. choose [Firefox Lite ] as default 
4. tap back

**Expect result**
2. see [set lite as default in 30 sec? ]with [cancel] and [go to settings]
3. see [browser menu] with [just once] [always]
4. See toast [thanks for choosing lite]

**Test result**
4. can not back to lite's settings page no matter how many times of back key user tapped.  

Impact : When user keeps tapping back but can not back to Lite , it looks like a broken app. User have to kill app to continue to see it sets Lite as default successfully.

**Comment by Daisy-pliu** [comment]
verify: ✅
[Test case 2 ]
version : 2.1.19 (19747) Preview

**Comment by Daisy-pliu** [comment]
will test on Release build

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.20 (19780) Release build
the behavior is correct.
