### ISSUE TITLE
[Feature] D0: Set default browser - Notification 2/4

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4971]
**User story**
As an user, I would like to get to default browser setting flow through notification.
If users already set Firefox Lite as default browser, this notification should not come out.
For example, click 4 times of menu -> notification popup

<img width="377" alt="螢幕快照 2020-05-18 下午6 48 43" src="https://user-images.githubusercontent.com/52307187/82204940-561a3d80-9938-11ea-9e40-69e07adff3de.png">

**Comment by shsu571** [comment]
If users already set Firefox Lite as default browser, this notification should not come out.

**Comment by shsu571** [comment]
Confirm with engineers. We did check the set default browser statue before we send notification.
cc @tinahsieh

**Comment by Daisy-pliu** [comment]
Version : 2.1.19(19732).beta
### [Test  case 1]
verify: ✅
Test step 
1. fresh launch app
2. tap settings 2 times
3. tap  [set default browser] notification

test result
2. see [set default browser] notification
3. see dialog [select Firefox Lite, always ] with [ok] [cancel]

### [Test  case 2]
verify: ✅
Test step 
1. fresh launch app
2. tap settings 1st  times
3. set chrome as default 
4. tap settings 2nd times

test result
4. see dialog [set lite as default in 30 sec] with [cancel] and [go to settings]

**Comment by Daisy-pliu** [comment]
This test case will not be added in Test case sheet as tap settings 2 times to show notification is included and the behavior of set default browser behavior is included in #4964

**Comment by Daisy-pliu** [comment]
will test on Release build

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.20 (19780) Release build
the behavior is correct.
