### ISSUE TITLE
[Feature] D0: menu 2/6 (Tab)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4973]
Tab menu part:
UX flow: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090397
Visual spec: https://zpl.io/bAJMGNB
Metrics : https://docs.google.com/spreadsheets/d/1pe-E0LBmqakeBwXu71EGsuzDhsx6_xLdA7fFRkdNipA/edit#gid=656282365

**Comment by Daisy-pliu** [comment]
verify ✅
Version: 2.1.21 (19828)
Test case : HOME 001

**Comment by Daisy-pliu** [comment]
This ticket has subtask #5126 about remote config menu bottom bar

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(19906)
