### ISSUE TITLE
 [Feature] D0: menu 3/6 (Libary)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4974]
UX flow:
https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090398
https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090399
Visual Spec: https://zpl.io/aRJ63XK
Metrics : https://docs.google.com/spreadsheets/d/1pe-E0LBmqakeBwXu71EGsuzDhsx6_xLdA7fFRkdNipA/edit#gid=656282365

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.21(19886)
test case:
1. freshlaunch app
2. tap [menu] -> [screenshots]
3. switch different tab
4. tap system back
5. tap any site
6. tap [menu] -> tap [take screenshot] 
7. tap [yes]

test result: 
2. see library panel with [screenshot][bookmark][history][downloads] icons
3. tab switched successfully
4 see homepage
6. see [access storage] dialog
7. see [view your screenshot onboarding] and [unread star] with a [hand ]

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(19906)
