### ISSUE TITLE
 [Feature] D0: menu 4/6 (home) 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4975]
Toolbar part:
UX flow: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090947
Visual spec: https://zpl.io/aXABWxX
Metrics :https://docs.google.com/spreadsheets/d/1pe-E0LBmqakeBwXu71EGsuzDhsx6_xLdA7fFRkdNipA/edit#gid=656282365

**Comment by Daisy-pliu** [comment]
verify  : ✅
version :  2.1.21 (19828)
Test case : TC0002
Test step: 
1. Launch app
2. Tap on Menu

Test result:
2.1 cell view [screenshots, bookmarks][history][downloads]
2.2 list view [private tab] [night mode][setting][clear cache][exit]

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(19906)
