### ISSUE TITLE
Basic Glean SDK integration 

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#4993]
Spike was done in #4954 
Actual commit is at
https://github.com/mozilla-tw/FirefoxLite/commit/1febbb9483386f2857f8eee682f67ef73bf44794

**Comment by chianger** [comment]
carry the P0 from #4954

**Comment by shsu571** [comment]
We will implement this issue after App size health check. 
https://github.com/mozilla-tw/FirefoxLite/issues/4989

**Comment by cnevinc** [comment]
working on Telemetry
