### ISSUE TITLE
[Settings Bug] Clearing History will mess up top site area including pin sites

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4994]
**Describe the bug**
Clearing History (clear browsing data from Settings) will mess up top site area including pin sites

**Steps To Reproduce**
1. Go to Home
2. Pin any sites on the top sites (like Facebook)
3. Remove any top sites (like Twitter)
4. Tap menu and go to settings
5. Tap Clear browsing data and check "Browing history"
6. Tap Clear Data
7. Back to Home

**Expected behavior**
The top site area should not be switched back to the initial state. Only the history tab should be emptied. (The behavior should be the same as going to History panel and clear browsing history.)
-> Pinned sites will keep
-> Removed sites stay removed
-> Frecency sites that are not pinned will be removed

**Actual behavior**
Top site area is reset to default

**Reproduce rate**
10/10

![image](https://user-images.githubusercontent.com/8919308/82549067-ee116480-9b8e-11ea-97c9-7e8c38778916.png)

**Comment by Daisy-pliu** [comment]
verify :  ✅
version: 2.1.21 (19828) Preview
Behavior is expected.

**Comment by Daisy-pliu** [comment]
verify : ✅
version: 2.1.22 (19906) Release
