### ISSUE TITLE
[Telemtry] event correction 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4995]
Pin Topsite.
Need to adjust some parameter

**Comment by shsu571** [comment]
Please check this link: https://docs.google.com/document/d/15ySleZGi8wFzK6ACZKVSAG7wEwD83wNet6iwWYMe3KQ/edit

**Comment by yshlin** [comment]
Found another issue while auditing this ticket:
https://github.com/mozilla-tw/FirefoxLite/issues/5073

**Comment by yshlin** [comment]
Telemetry verified
