### ISSUE TITLE
 [Feature] D0: menu 5/6 (Toolbar)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4996]
Toolbar part: ( only the toolbard area for this issue)
UX flow: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/screens/417090397
Visual spec: https://zpl.io/bAJMGNB
Metrics : https://docs.google.com/spreadsheets/d/1pe-E0LBmqakeBwXu71EGsuzDhsx6_xLdA7fFRkdNipA/edit#gid=656282365

**Comment by Daisy-pliu** [comment]
verify ✅
Version: 2.1.21 (19828)
Test case : modified TC0002
Test step: 
1. Launch Rocket
2. Visit a website
3. Tap [Menu]

Test result: 
2 see toolbar [home][reload][search][tab][menu]
3.1 Turbo mode is on by default
3.2 cell view [screenshots, bookmarks][history][downalods]
3.3 list view [find in page][add to home] [turbo][block image] [night mode] [settings] [clear cache] [exit]
3.4 tool bar [backward] [forward][bookmark][shot][share]

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(19906) Release
