### ISSUE TITLE
Tests Flaky

### ISSUE THREAD

**Issue by denini08** [mozilla-tw/FirefoxLite#4999]
We ran the UI tests (androidTests) 50 times and found 15 flaky tests. Would you like us to send you a pull request describe what tests are flaky and explaining how to reproduce the flaky behavior?
We didn't correct the tests, we just found them.

Best regards

**Comment by Daisy-pliu** [comment]
Thanks for raising out.
In Firefox Lite , the tests we mark @flaky means it failed from time to time, they are flaky on our CI so we won't run there whenever source code changes, instead we will run those flaky tests manually before we release a build.
For those tests not marked @Flaky they are running on our[ Bitrise CI Instrumentation Test](https://devcenter.bitrise.io/testing/device-testing-for-android/) s whenever new PR or PR merged. It runs well on emulators (e.g. NexusLowRes, 23 , en,portrait and NexusLowRes,24,en,portrait) for a long time. If there are failures we will take it down and try fixing it. Could you let me know your Espresso tests environments (e.g. local ,remote , physical, emulators) ?
