### ISSUE TITLE
While using private mode, don't keep the file download record in Download Panel

### ISSUE THREAD

**Issue by cnevinc** [mozilla-tw/FirefoxLite#5000]
**Describe the bug**

**Steps To Reproduce**
1. Go to private mode.
2. Download a file 
3. Back to normal mode and open download panel
4. See the download item in the list

**Expected behavior**
When I use private mode to download stuff, I don't want it appears in my download panel

**Actual behavior**
The file still appears

**Comment by Daisy-pliu** [comment]
verify : ✅
version : v2.1.23(20224) preview
Steps to reproduce the behavior:
1.  Launch app
2. Tap [menu] -> [private mode ]
3. download  a image 
4. tap [private icon ] to back to normal
5. tap [menu] -> [downloads] library

Expect & Actual result:
5. no downloaded file listed here

**Comment by Daisy-pliu** [comment]
will test on Release build

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
