### ISSUE TITLE
Firefox Lite logo text disappear when coming from landscape mode

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5008]
**Steps To Reproduce**
1. Visit any pages
2. Rotate phone to landscape mode
3. Tap tab tray button to open tab tray
4. Tab "+" to add tap

**Expected behavior**
4. See the home screen with Firefox Lite logo text.

**Actual behavior**
4. See the home screen without Firefox Lite logo text.

**Screenshots/videos**
If applicable, add screenshots/videos to help explain your problem.

**Device info (please complete the following information):**
 - Device: Pixel2
 - OS: Android 8.0
 - Version : 2.1.18 (19594) Preview

**Reproduce rate**
5/5
**Additional context**
it is a dogfooding issue reported by @youwenliang pls refer [dogfooding sheet row34](https://docs.google.com/spreadsheets/d/1OQ8kDGnoS0Mnp8FlyNv7_ONLiMVJ9eOcHsnUHYWQLko/edit#gid=1989125966&range=B34)

**Comment by youwenliang** [comment]
@Daisy-pliu sorry I already opened this one! #4982, you can close this one thanks!

**Comment by Daisy-pliu** [comment]
let's trace on #4982
