### ISSUE TITLE
grant view permission on Firefox Lite

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5012]
**Purpose**
George will need view permission on Firefox Lite Release build to do full run testing for certain remote config related test case.
Thank you!

**Permisson**
View permission

**Account**
gli@mozilla.com

**Comment by niyali** [comment]
![Screen Shot 2020-05-26 at 3 02 14 PM](https://user-images.githubusercontent.com/1436482/82870098-f9cfa300-9f61-11ea-9789-798f96ae22a4.png)

Granted the Firebase viewer permission on Firefox Lite.
@swlibi could you please give it a try?
Thanks!

**Comment by swlibi** [comment]
Hey Linear,

It works for me!
Thank you

George Li
