### ISSUE TITLE
Add Audible for top site uploading preparation (India)

### ISSUE THREAD

**Issue by yowazzzup** [mozilla-tw/FirefoxLite#5014]
**Remote config name**
Top Sites for India 

**Audience setting**
India only

For uploading Audible to production:
https://drive.google.com/file/d/1zatx6GR-LksVRi2s-sQlaohDgA8SLJg_/view?usp=sharing

**Expected Online Time**
Tentative time: July 1st 2020 

@shsu571 @youwenliang

**Comment by chianger** [comment]
Scope is to include the logo into resource.
