### ISSUE TITLE
Size check before release

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5028]
As a Firefox Lite team member, you can know the app size before release.
@Conjuror will add the flow to provide the apk size before release ( Sprint week2 Thusday after code freeze build)

**Comment by cnevinc** [comment]
per discussion with @Conjuror, it will be even better if we can make the reviewer aware of the APK bump and make it one of our code review process.  But this will take time to implement.

For now, maybe it's easier to let the Release Manager check the APK size change for us and put in the release check-in meeting.

**Comment by Conjuror** [comment]
Currently, I'll update the apk size from Primary workflow in bitrise in the release check-in document. Let's close the issue for now.
