### ISSUE TITLE
[Home customization] Onboarding 2/5 (Presets UI)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5032]
**User story**
- As a new user, I want to be able to choose my preferred Home screen style during onboarding, so that I can access the features I want or hide the features I don’t need in order to improve my browsing experience.
- As a new user, I want to be able to preview the different Home screen styles during onboarding, so that I can easily select my preferred Home screen style.

*UI for the presets*

**Additional context**
UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234350_1-1_New_User_Onboarding_Flow_-1-2-
UI spec: https://zpl.io/2vJkJDe

Preset information: https://docs.google.com/spreadsheets/d/1C6BUWt_7lAm-BxjMEF24PJCP4QUYprm3ntY5Cp3bICo/edit?usp=sharing
The detail of the presets should be remote configurable.

**Comment by Daisy-pliu** [comment]
verify: ❌
version: 2.1.23(20284)
User scenario: ONBOARD01
Test step: 
1. fresh install to launch app 
2. tap [read trending news]


Test result:
1. see 4 option onboarding
3.1 see "optimizing exp for you..." 
3.2 see [ news, game] based on Vertical Presets doc for global

**Comment by Daisy-pliu** [comment]
To perform testing , remember to take off "str_content_hub_items" and "str_top_sites_default_items" on Preview and Production after #5242 merge

**Comment by Daisy-pliu** [comment]
SC1:  default Settings in User Interests
Test step: 
1. Remote config : set str_content_hub_items"  in India to ""
2. Remote Conifig :set str_top_sites_default_items" in India to ""
3.  launch app & india SIM
4.  tap [Games and videos] 

Test result:
4.1 see correct content hub  [News, Game] in India
4.2 see correct top sites [FRVR,Cricbuzz,Sportskeeda,Gameloft,Youtube,Facebook,Audible,Flipkart,Hotstar,Gamezop,Gmail,Newspoint] in India 

SC1:  Remote config default settings in User Interests
Test step: 
1. remote config : name = "india_interest", user property= "interest", country ="india"
2. Remote Conifig: set str_top_sites_default_items with "india_interest" -> however this setup will affect old users, we should not override this value as new parameter for new users instead we should create new key.
3.  launch app & india SIM
4.  tap [Games and videos] 

Test result:
4.1 see correct content hub  [News, Game] in India
4.2 see correct top sites [FRVR,Cricbuzz,Sportskeeda,Gameloft,Youtube,Facebook,Audible,Flipkart,Hotstar,Gamezop,Gmail,Newspoint] in India

**Comment by Daisy-pliu** [comment]
user properties info: https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit#gid=149972229&range=A14

**Comment by Daisy-pliu** [comment]
verify : ✅
versions: v2.1.23(20333)

### ✅  SC1:  default Settings in User Interests
**Test step:** 
1. Remote config : set str_content_hub_items"  in India to ""
2. Remote Conifig :set str_top_sites_default_items" in India to ""
3.  launch app & india SIM
4.  tap [Games and videos] 

**Test result:**
4.1 see correct content hub  [News, Game] in India
4.2 see correct top sites [FRVR,Cricbuzz,Sportskeeda,Gameloft,Youtube,Facebook,Audible,Flipkart,Hotstar,Gamezop,Gmail,Newspoint] in India 

### ✅  SC1:  Remote config default settings in User Interests
**Test step:** 
1. remote config : name = "india_interest_entertainment", user property= "interest" is "entertainment", debug_local = "India"
2. Remote Conifig: set str_top_sites_default_items_v2_5 with "india_interest_entertainment" as [sample](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_content_hub_items-str_content_hub_items_v2_5)
3. Remote Conifig: set str_content_hub_items_v2_5 with "india_interest_entertainment" as [sample](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_content_hub_items-str_content_hub_items_v2_5)
4.  launch app & india SIM
5.  tap [Games and videos] 

**Test result:**
5.1 see correct content hub as sample 
5.2 see correct top sites  as sample

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
SC1 and SC2

will add SC1 to full run test case sheet

**Comment by Daisy-pliu** [comment]
merge to #5055
