### ISSUE TITLE
[Home customization] Onboarding 3/5 (Animation)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5033]
**User story**
As a new user, I want to be welcomed to Firefox Lite with information such as clear branding statements that can help set expectations on what this browser can offer, so that I can quickly get a sense of what this browser is about and feel comfortable starting to browse.

**Additional context**
UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234350_1-1_New_User_Onboarding_Flow_-1-2-
Visual spec: https://zpl.io/2vJkJDe
Motion spec: https://drive.google.com/open?id=1LrmDJaftaDOZldabA8VGY7mv7UkVhZBV&authuser=hhuang%40mozilla.com&usp=drive_fs

Will provide animation and copy strings detail later.

**Comment by TLHuang** [comment]
Onboarding preview: https://drive.google.com/open?id=1LoNR_6-NXWVVhV0WSJo58NvcpZEKWkrh&authuser=hhuang%40mozilla.com&usp=drive_fs

**Comment by Daisy-pliu** [comment]
verify: ❌
version :  2.1.23(20297)
Device: Samsung 8.0

Test step:
1. fresh install to launch app 
2. tap [browse the web]

Expect result 
1. see 4 option onboarding
3.1 see animation"optimizing exp for you..." 
3.2 see [travel, news, game] based on Vertical Presets docc
3.3 see [choose your theme] 


Actual Result:
3.2 can not see animation

Note: pixel 9.0 is good
