### ISSUE TITLE
[Feature] Awesome bar & metrics - Overall 1/8

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5034]
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

UX/Design
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/dashboard?tag=Awesome%20Bar

Metrics: 
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
since it's a meta bug, I'll give it XL

**Comment by shsu571** [comment]
Data Review :  https://docs.google.com/document/d/1sJmsPDC5HQsylwkAWPfN9le1f24wigCnKHBKE6bmsN4/edit#

**Comment by lanyliu** [comment]
[spec](https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=888392947)
**Amplitude**
name: Enter an url in SearchBar

**Telemetry**
method: open
object: search_bar
value: link
extra: 
- type: history|bookmark|tabtray|clipboard|autocomplete

**Comment by cnevinc** [comment]
still working on Telemetry data

**Comment by cnevinc** [comment]
metrics merged https://github.com/mozilla-tw/FirefoxLite/pull/4913

**Comment by yshlin** [comment]
Problem found:

 - when history/bookmark both exist, should return bookmark in extra (currently it's history)

**Comment by Daisy-pliu** [comment]
No QA efforts for metrics on this ticket

**Comment by lanyliu** [comment]
done telemetry checking
