### ISSUE TITLE
[Home customization] Onboarding 4/5 (Theme Setting) 

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5035]
**User story**
- As a new user, I want to be able to choose my preferred Home screen style during onboarding, so that I can access the features I want or hide the features I don’t need in order to improve my browsing experience.
- As a new user, I want to be able to preview the different Home screen styles during onboarding, so that I can easily select my preferred Home screen style.

**Additional context**
https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234351_1-1_New_User_Onboarding_Flow_-2-2-
Visual spec https://zpl.io/2yA0nzG

**Comment by Daisy-pliu** [comment]
verify:?  
version: 2.1.23 (20297)
Test step: 
1. fresh install to launch app 
2. tap [browser the web]

Test result
1. see 4 option onboarding
2.1 see animation"optimizing exp for you..." 
2.2 see [travel, news, game] based on Vertical Presets docc
2.3 see [choose your theme] dialog and [done] button
