### ISSUE TITLE
 [Feature] Awesome bar - Bookmark 2/8

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5036]
Add Source / Bookmark 

#5034 
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
is done and waiting to merge

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.22 (19949)


**Test Scenario 1**  
1. launch app
2. search "netflix.com"
3. tap [menu] > [bookmark]
4. tap [search icon ]
5. tap [menu] > [bookmark library] 
6. remove "netflix.com" bookmark 
7. tap [search icon ]
8. search "netflix"


Test result : 
4.1 see [open tab icon] [netflix url ] row
4.2 see [history icon] [netflix url ] row
4.3 see [bookmark icon] [netflix url ] row
8.1 see [open tab icon] [netflix url ] row
8.2 see [history icon] [netflix url ] row

**Comment by Daisy-pliu** [comment]
verify : ❌
version : 2.1.23 (20122) Release
no bookmark icon anymore

**Comment by chianger** [comment]
Non blocking sprint4-9 so let's move in S4-10 to track.

**Comment by chianger** [comment]
blocked by https://github.com/mozilla-tw/FirefoxLite/issues/5043

**Comment by shsu571** [comment]
There's spec change
bookmark and history will only show fav icon

**Comment by Daisy-pliu** [comment]
verified in https://github.com/mozilla-tw/FirefoxLite/issues/5043#issuecomment-658052630

**Comment by Daisy-pliu** [comment]
verify in #5043
