### ISSUE TITLE
[Home customization] Onboarding 5/5 (Completion) 

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5037]
**User story**
- As a new user, I want to be able to feel a sense of completion after customizing my home experience, and be able to have an option to set Firefox Lite as my default browser so that I can used my customized Firefox Lite in the future.

**Additional context**
UX Spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234351_1-1_New_User_Onboarding_Flow_-2-2-
Visual spec: https://zpl.io/2yA0nzG

**Comment by Daisy-pliu** [comment]
verify: ✅
version: v2.1.23(20343)

SC 1 : New user onboarding flow ✅
**test step:** 
1. fresh install to launch app 
2. tap [browser the web]
3.  tap [done]
4. tap [pink] color
5. tap [done]
6. tap [set a default]

**test result** 
1. see 4 option onboarding
2.1 see animation"optimizing exp for you..." 
2.2 see [travel, news, game] based on Vertical Presets docc
2.3 see [choose your theme] dialog and [done] button
3. back to home page
4. background color changed
5. see [what to set Lite as deault browser?] [later] button, [set as default] button
6. start set as default browser flow 


SC 2: New user onboarding flow -> set as default -> fail to setup  ✅
**test step:** 
given default browser in not Firefox Lite 
1. fresh install to launch app 
2. tap [browser the web]
3.  tap [done]
4. tap [pink] color
5. tap [done]
6. tap [set a default]
7. tap [ go to settings] ->chose [Chrome]
8. tap system back until it backs to home 


Test result :
8. should see snack bar [do you want to finish set as default ] [yes] button

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
