### ISSUE TITLE
 [Feature] Awesome bar - Open tab 4/8 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5039]
Add Source / Open tab

#5034
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
is done and waiting to merge

**Comment by Daisy-pliu** [comment]
verify : ❌
version : 2.1.22 (19949)

**Test Scenario 1**  ❌
1. launch app
2. search "netflix.com"
3. tap [menu] > [bookmark]
4. tap [menu] > [bookmark library] 
5. remove "netflix.com" bookmark
4. tap [search icon ]
5. search "netflix"
6. tap [bookmark icon] [netflix url ] row

Test result : 
3.1 see [open tab icon] [netflix url ] row
3.2 see [history icon] [netflix url ] row
6. [crash log : UrlInputFragment.kt](https://console.firebase.google.com/u/0/project/rocketnightly/crashlytics/app/android:org.mozilla.rocket.beta/issues/bacdad6fedd6f9b0bd0c548154c57f0f?time=last-seven-days&sessionId=5EF171B0017000011FB3E958E65CD560_DNE_0_v2)

Expect :
6.  open netflix url in tab 

**Test Scenario 2** ❌
1. launch app
2. search "netflix.com"
3. tap [menu] > [bookmark]
4. tap [menu] > [bookmark library] 
5. remove "netflix.com" bookmark
4. tap [home]> [search icon ]
5. search "netflix.com"


Test result : 
3.1 see [history icon] [netflix url ] row

Expect :
3.1 see [open tab icon] [netflix url ] row
3.2 see [history icon] [netflix url ] row

**Comment by shsu571** [comment]
[Bug] Tab UI lack of "switch to tab" string.

**Comment by Daisy-pliu** [comment]
verify : ✅ 
version : 2.1.22 (20025)
Test step : https://github.com/mozilla-tw/FirefoxLite/issues/5039#issuecomment-647880437

**Comment by cnevinc** [comment]
the design had changed.

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22 (20067)
![Screenshot_20200701-144644_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86225111-602c8e80-bbbc-11ea-8dab-e61f21c2cd73.jpg)

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

**Comment by Daisy-pliu** [comment]
added to HOME003
