### ISSUE TITLE
 [Feature] Awesome bar - Copy Clipboard: 5/8 

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5040]
Add Source / Copy Clipboard

#5034
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
done

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22 (19449) preview
Test step 
1. Copy https://www.ted.com/  from other app
2. Launch app 
3. Tap [search icon]

Test result
3.  See [link icon ] [copied url]

**Comment by Daisy-pliu** [comment]
### verify: ✅ 
### version  : 2.1.22 (20025) Preview
Test step: 
1. Copy https://www.ted.com/  (full url)
2. Launch app 
3. Tap [search icon]
4. tap [link icon ] [copied url] row
5. Tap [search icon]
6. Copy https://netflix.com/  (full url) 
7. Tap [search icon]
8. start typing
### Test result
3. See [link icon ] [https://www.ted.com/]
4. open "https://www.ted.com/"
5. see  [link icon ] [https://www.ted.com/] again 
7. see  [link icon ] [https://netflix.com/]
8.  not see [link icon ] [https://netflix.com/] any more

**Comment by Daisy-pliu** [comment]
Will add to FxLite full run test case

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

**Comment by Daisy-pliu** [comment]
Added to HOME004
