### ISSUE TITLE
 [Feature] Awesome bar - Hide keyboard while scrolling 6/8

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5041]
Hide keyboard while scrolling (without animation)

#5034
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
is done and waiting to merge

**Comment by Daisy-pliu** [comment]
verify: ✅
version :  2.1.22(19949) preview

**Test step:** 
1. Given https://www.ted.com/  and https://www.ted.com/talks  in bookmarks
2.User search ted in address bar
3. User scroll the list of awesome bar list

**Test result**
2. User see suggestion based on bookmarks 
3.Keyboard is dismissed 

For now this implementation will not include sorting algorithm, such sorting technique will be added later

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

**Comment by Daisy-pliu** [comment]
Added to HOME002
