### ISSUE TITLE
[Feature] Awesome bar - Awesome BAR UI adjustment 7/8

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5042]
Awesome BAR UI adjustment

![Awesome Bar](https://user-images.githubusercontent.com/52307187/83393376-4404c880-a429-11ea-81a8-68eda19a53ae.jpg)
![Clipboard](https://user-images.githubusercontent.com/52307187/83393390-48c97c80-a429-11ea-84c2-b5ba6f44d03e.jpg)

#5034
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.22(20067) Preview
per discussion with Dev, the latest design change as below.
![Screenshot_20200701-144644_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86217416-04f59e80-bbb2-11ea-9c5c-0854d4a81f3f.jpg)
