### ISSUE TITLE
 [Feature] Awesome bar - source sequence 8/8

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5043]
source sequence - order by source crated time

#5034
Spec :
https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.ada2pp7xljcr

UX/Design
https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/dashboard?tag=Awesome%20Bar

Metrics:
https://docs.google.com/spreadsheets/d/1qIxNH175ngzn12jSpaonhBdIft0lB76-atJzPrzIl7Y/edit#gid=0

**Comment by cnevinc** [comment]
bookmark and tabs don't have timestamp so I can't sort them

**Comment by shsu571** [comment]
Awesome bar ranking (will decid by 7/2)
Option 1. hisotry only (rank by frequency)
Option 2. hsitory + tab  (rank by frequency)
Tab needs to implement data collection ( est 1 sprint)

**Comment by shsu571** [comment]
Awesome bar update

- How to calculate
bookmark closest date limit 100 records ; weight : 1.75
tab closest date limit 100 records ; weight : 1.75
history time + weight same as doc
https://docs.google.com/document/d/10LRRXVGWWWcjEZIZ2YlEmuKkQqh2RaTclStFHNnPqQ8/edit#heading=h.588hanspexub

-Show  fav icon
if possible tab, need to swtich tab directly.

**Comment by Daisy-pliu** [comment]
The sequence is not as expected. It needs redesign and rework.
Since the open tab has highest weight (most important ) it should keep nearest to the search bar but when there are too many suggestions user has to scroll down all along to find the most important tab.

**Comment by shsu571** [comment]
PMs and UX will keep following up this on sprint 4-10

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

**Comment by shsu571** [comment]
Sequence adjustement : https://docs.google.com/document/d/15KiO18DpWQpX9N8HUDvfEHYV1UtxZNBss-HxeCew_Hs/edit#bookmark=id.enhpgs8jmggy
@cnevinc

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23(20627) Preview

## SC1 open tab behavior
### Test step : 
1. fresh launch app
2. tap [Youtube topsite]
3. tap [home] ->  tap [FB topsite]
4. tap [home] ->  tap [Twitter topsite]
5. tap [search icon] and type "m"

### Test Result : 
5.1 see [open tab ] [Twitter topsite] on the top of suggestion
5.2 see [open tab ] [FB topsite] on the 2th row of suggestion
5.3 see [open tab ] [Youtube topsite] on the 3th row of suggestion
5.4 see [twitter fav] ["https://mobile.twitter.com"] on the bottom of suggestion -> this is fine as the site is redirected so it is registered in the history

## SC2 bookmark & history
### Test step : 
1. launch app
2. search "ted.com" as new tab 
3. tap [menu] > [bookmark the site]  and then close the tab
4.search "netflix.com" as new tab 
5. tap [menu] > [bookmark the site]  and then close the tab
6. Tap [search icon] -> type [.com]
7. Tap [search icon] -> clear input -> type [netflix.com]
8. Remove  [netflix.com] from history 
9. Edit  [netflix..] to [my favorite site - netflix ] as name field from bookmark
10.Tap [search icon] -> type [netflix.com]
11. Tap [search icon] -> clear input -> type [ted.com]
12. scroll awesomebar list


3. 5. Bookmark added 
6.1 see [netflix.com fav icon] [netflix.com.tw ] on top row
6.2 see [ted.com fav icon] [ted.com] on 2nd row
7. see [netflix.com fav icon] [netflix.com ] row
10. see [netflix.com fav icon] [netflix.com.tw ] row
11. see [ted.com fav icon] [ted.com ] row
12. Keyboard is dismissed

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
