### ISSUE TITLE
[Home Customization] Menu 1/3 (Items & Hints)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5044]
**User story**
- As an existing user, I want to be able to notify the new abilities to customize my Home screen, so that I can easily discover the new features and try it myself.

- As a user, I want to be able to make further customization such as changing the individual items (Verticals, Searchbar, topsite area, shopping search button...etc.) on the Home screen, so that I can access the features I want or hide the features I don’t need in order to improve my browsing experience.

**Summary**
1. Add three menu items: Content & Services Toggle, Add new top sites, Theme
2. Add hints for first time v2.5 users

**Additional context**
UX Spec:
Visual Spec: https://zpl.io/2jnBdlQ
New menu items x 3: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234353_2-1_Vertical_Settings
1. Content & Services Toggle
2. Add new top sites
3. Theme

Menu with hints: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234364_5-1_Old_User_Onboarding

**Comment by youwenliang** [comment]
Please refer to this ticket for metrics: https://github.com/mozilla-tw/FirefoxLite/issues/5031

**Comment by Daisy-pliu** [comment]
### verify : ✅
### version : 2.1.22 (20025) Preview
### Scenario 1 : upgrade users -  vertical setting - Set a theme
Test step: 
1. Launch app
2. Tap [menu] on home page
3. Tap system back
4. Tap [menu] on home page
5. Turn off [content & service]  

Test result:
1. See [red dot]  on  menu icon  
2. See [red dot] on [show content & services], [add topsites], [themes]
4. [No red dot ]on [show content & services], [add topsites], [themes]
5. No [vertical icons]  on home page

![Screenshot_20200629-100925_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85969224-a1c10c00-b9f9-11ea-9d99-afaf7129227b.jpg)

![Screenshot_20200629-100958_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85969215-9e2d8500-b9f9-11ea-9e3c-1f68ebb94a32.jpg)

**Comment by Daisy-pliu** [comment]
This test case will add to Fxlite full run sheet 2.0

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
