### ISSUE TITLE
[Home Customization] Remove previous onboardings

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5045]
With the new Home design, we will need to remove the "Content & Services" onboarding (highlight), and also for users that don't have Shopping Search as their feature button, we will need to remove the Shopping Search onboarding (highlight).

- remove 1.x -> 2.0 , 2.0->2.1 onboarding
- keep privacy notice onboarding message

**Comment by Daisy-pliu** [comment]
SC1:
Upgrade user:
I Can not test on Preview given we only can install APK now while upgrade need to use Playstore to upgrade. QA will execute this test on Release build.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
Test steps
1. launch app
2. choose [find good deals]
3. tap [done] in theme dialog -> [later] in set default browser dialog
4. kill the app

Test result
3. see shopping search onboardng
