### ISSUE TITLE
 [Home Customization] Topsite 1/7 (Selection Panel)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5046]
**User story**
As a user, I want to be able to customize the top site area, such as pinning webpage to topsite area or entering url to add to topsite area or reordering the topsites or removing the pinned sites, so that I can display websites in my own terms. (And don’t drag browsing history to this area)

**Additional context**
When users tap "Add new topsites" inside menu, there will be a Topsite selection panel showing options for users to add to home screen as their topsite. The content inside the panel should be remote configurable.

UX Spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234356_3-1_Add_New_Top_Sites
Visual spec: https://zpl.io/a7AGrBR

**Comment by TLHuang** [comment]
The visual spec is updated!
https://zpl.io/VxxyB53

**Comment by youwenliang** [comment]
Please refer to this ticket for metrics: https://github.com/mozilla-tw/FirefoxLite/issues/5031

**Comment by youwenliang** [comment]
@proevan for the topsite lists & icons please refer to #5118

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.22(19949)
This ticket focus mainly on UI of selection panel.
![Screenshot_20200623-092028_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85353589-2c59c500-b53b-11ea-8fd9-76d95b53ad4a.jpg)
![Screenshot_20200623-092025_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85353597-31b70f80-b53b-11ea-82e2-59fe33d452d4.jpg)

**Comment by youwenliang** [comment]
@tinahsieh @TLHuang will need to check the UI for this ticket since it is closed and has "need design audit"

**Comment by youwenliang** [comment]
@benjamin-cheng I've updated the icons for Pinterest & Dailymotion (requested by tina)
https://drive.google.com/drive/folders/1UDlDh6mIN9ZMZdGdvK8gGt_Ihc08iGjN?usp=sharing

**Comment by Daisy-pliu** [comment]
No need to add this test case into Fxlite full run sheet 2.0 as the test in #5048 will cover

**Comment by tinahsieh** [comment]
Opened a UX bug #5172 related to this page.

**Comment by tinahsieh** [comment]
🚨 Design audit failed. 
Category titles are not linking to the translated strings.

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
