### ISSUE TITLE
[Home customization] Top site 2/7 (Context Menu)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5047]
**User story**
As a user, I want to be able to customize the top site area, such as pinning webpage to topsite area or entering url to add to topsite area or reordering the topsites or removing the pinned sites, so that I can display websites in my own terms. (And don’t drag browsing history to this area)

**Additional context**
When users long-press any topsite, there will be an option to "Add new topsites" inside the context menu.

UX Spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234356_3-1_Add_New_Top_Sites

**Comment by youwenliang** [comment]
Please refer to this ticket for metrics: https://github.com/mozilla-tw/FirefoxLite/issues/5031

**Comment by Daisy-pliu** [comment]
This ticket mainly focus UI has no topsite edit/add action behavior.
verify: ✅
version : 2.1.22 (19949) Preview
![Screenshot_20200623-092013_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85353599-324fa600-b53b-11ea-8035-2815350548b4.jpg)

**Comment by Daisy-pliu** [comment]
No need to add into Fxlite full run sheet 2.0 as it will merge to #5048

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
