### ISSUE TITLE
[Home customization] Top site 3/7 (Add Topsite) 

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5048]
**User story**
As a user, I want to be able to customize the top site area, such as pinning webpage to topsite area or entering url to add to topsite area or reordering the topsites or removing the pinned sites, so that I can display websites in my own terms. (And don’t drag browsing history to this area)

**Additional context**
When users add any topsite from the Topsite selection panel, add new topsite will pop up with a snackbar prompting users to add more topsite. Will also need to consider when all topsite area is full, or all topsites are removed.

- If users remove browsing data:
1. Pin topsite won't be removed.
2. Topsites that came with presets won't be removed.
3. Topsites that came with presets but were removed by users will stay removed.
4. Topsites that pop-up by frecency will be removed.

Logic: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234362_4-1_Top_Site_Placing_Logic

Overall UX Spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234356_3-1_Add_New_Top_Sites

Visual Spec https://zpl.io/a7AGrBR

**Comment by benjamin-cheng** [comment]
@TLHuang per discussed, please help to release the animation asset which is shown when the top site is added.

**Comment by TLHuang** [comment]
The animation for the highlight is ready, here is the [link].(https://drive.google.com/open?id=1Hgf6F3LEBwRnX_wjSHM57WqqE3nq7ytK&authuser=hhuang%40mozilla.com&usp=drive_fs)

**Comment by youwenliang** [comment]
Please refer to this ticket for metrics: https://github.com/mozilla-tw/FirefoxLite/issues/5031

**Comment by tinahsieh** [comment]
Audit from UX's perspective is done.
Waiting for visual audit.

**Comment by Daisy-pliu** [comment]
Confirm the frecency part is incorrect. so I am going to reopen the ticket.
Apart from that, other functionality is good.

version:  2.1.22 (20098)
### Scenario 1 : Add a topsite until the area is full 
Test case: 
Fresh Launch app
Tap [menu]
Tap [add top sites]
Tap a [non-existing top site]
Keep adding until the first page are full
Keep adding until the all pages are full
long tap [any topsite] -> tap [add top sites]

Test result: 
1.1 See [preset-level-1 sites] 
1.2 see [preset-level-2 sites]
3. See [ top site list menu] matched with Remote config 
4. See [top site added ] snack bar and [add more] button
5. See the site is pinned on the 2nd page 
7. See [please remove a site] snack bar on homepage

**Comment by Daisy-pliu** [comment]
still fail in the frecency part we can track https://github.com/mozilla-tw/FirefoxLite/issues/5197
