### ISSUE TITLE
[Home customization] Onboarding 1/5 (Presets Grouping)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5055]
**User story**
- As a new user, I want to be able to choose my preferred Home screen style during onboarding, so that I can access the features I want or hide the features I don’t need in order to improve my browsing experience.
- As a new user, I want to be able to preview the different Home screen styles during onboarding, so that I can easily select my preferred Home screen style.

*Grouping for the presets*

Onboarding target users:
1. New installed users
2. Clear data users
3. Update users (from 1.x to 2.5)

Onboarding timing:
1. First time open
2. If first time open is from external app -> whenever they go back to home screen we will show the onboarding.

**Additional context**
UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234350_1-1_New_User_Onboarding_Flow_-1-2-

Preset information: https://docs.google.com/spreadsheets/d/1C6BUWt_7lAm-BxjMEF24PJCP4QUYprm3ntY5Cp3bICo/edit?usp=sharing
The detail of the presets should be remote configurable.

**Comment by Daisy-pliu** [comment]
SC1 : Fresh install to see New user onobording
Test case: ONBOARD01
Test step:  
1. fresh install to launch app 
2. tap [browser the web]
3.  tap [done]
4. tap [pink] color


Actual Result & Test result:
1. see 4 option onboarding
2.1 see animation"optimizing exp for you..." 
2.2 see [travel, news, game] based on Vertical Presets docc
2.3 see [choose your theme] dialog and [done] button
3. back to home page
4. background color changed


SC2: Launch app from expternal link to see new user onobording
Test case: ONBOARD02
Test step:  
1. launch lite from external link
2. tap home 
3. relaunch app
4. choose [browse the web]

Actual Result & Test result:
1. see [default preset]
2. see theme dialog
3. see 4 option onboarding
4. see not theme dialog

Upgrade user: 
I Can not test on Preview given we only can install APK now while upgrade needs use Playstore to upgrade.

**Comment by proevan** [comment]
user properties info: https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit#gid=888392947&range=G20

**Comment by Daisy-pliu** [comment]
verify: ❌
Test case: ONBOARD01

**Test step**
1. fresh install to launch app
2. tap [browser the web]

**Actual Result & Test result:**
2 see all verticals

**Comment by Daisy-pliu** [comment]
verify : ✅
versions: 2.5.0(20358) Release

### ✅  SC1:  default Settings in User Interests
**Test step:** 
1. Remote config : set str_content_hub_items"  in India to ""
2. Remote Conifig :set str_top_sites_default_items" in India to ""
3.  launch app & india SIM
4.  tap [Games and videos] 

**Test result:**
4.1 see correct content hub  [News, Game] in India
4.2 see correct top sites [FRVR,Cricbuzz,Sportskeeda,Gameloft,Youtube,Facebook,Audible,Flipkart,Hotstar,Gamezop,Gmail,Newspoint] in India 

### ✅  SC1:  Remote config default settings in User Interests
**Test step:** 
1. Remote Conifig: set str_top_sites_default_items_v2_5 , debug_local = "India"  as [sample](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_content_hub_items_v2_5) 
2. Remote Conifig: set str_content_hub_items_v2_5 , debug_local = "India" as [sample](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_content_hub_items_v2_5)
3.  launch app 
4.  tap [Games and videos] 
5. switch to india_debug

**Test result:**
5.1 see correct content hub as sample 
5.2 see correct top sites  as sample

**Comment by Daisy-pliu** [comment]
added v2.5 shopping search icon https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#enable_shopping_search_v2_5
We have to config on Remote config

**Comment by Daisy-pliu** [comment]
Thanks @joechengla  found this issue !

**Add Upgrade test case:**
verify: ❌
Test step:
1.Upgrade app & launch
2. Tap [menu] on home page
3. Tap system back
4. Tap [menu] on home page
5, Turn off [content & service]  
6. Tap [themes]
7. Choose [purple color]
8. Choose [dark mode]
9. Tap [DONE]

Test result:
1. See [red dot]  on  menu icon  
2. See [red dot] on [show content & services], [add topsites], [themes]
4. [No red dot ]on [show content & services], [add topsites], [themes]
5. No [verticali icons]  on home page
6.  See  [choose your theme dialog ] and [DONE] button
7. See the theme changed to purple
8. See theme in dark theme
9. Dialog is dismissed

**Comment by Daisy-pliu** [comment]
verify : ❌ 
version : 2.5.0(20386) release 
our SC 2 ,SC3 test case failed  as below (while SC1 passed)

### SC2: Launch app from expternal link to see new user onobording
Test case: ONBOARD02
Test step:  
1. launch lite from external link
2. tap home 
3. relaunch app
4. choose [browse the web]

Actual Result 
3. can not see 4 option onboarding


Expect result:
1. see [default preset]
2. see theme dialog
3. see 4 option onboarding
4. see not theme dialog



SC3: Upgrade user:
1. install Fxlite 2.1
2. launch app
3. tap bbc news 7 times to create frecency site
4. upgrade app
5. launch app to check 

Expect result : 
see bbc.com there

Actual Result: 
not see bbc.com there

**Comment by Daisy-pliu** [comment]
❌ sc8  : 
test step
1. install Fxlite 2.1
2. launch app
3.  pin youtube, pin FB
4.  upgrade app
5. launch app to check

Expect result
5. see pinned Youtube ,  pinned FB
Test result 
5. see pinned Youtube , pinned FB ,  pinned amazon , pinned audible

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0 (20390) 
Test case: ONBOARD02

**Comment by Daisy-pliu** [comment]
> ❌ sc8 :
> test step
> 
>     1. install Fxlite 2.1
> 
>     2. launch app
> 
>     3. pin youtube, pin FB
> 
>     4. upgrade app
> 
>     5. launch app to check
> 
> 
> Expect result
> 5. see pinned Youtube , pinned FB
> Test result
> 5. see pinned Youtube , pinned FB , pinned amazon , pinned audible

This issues happened long time since 2.0.
we can download 2.1.21 Release
Test step
1. install v2.1.21 from Github 
2. pin Wiki
3. kill the app to relaunch
Actual result
3. see pinned Wiki and pinned Rediit as they have same topsite id 
expect result
3. see pinned Wiki
