### ISSUE TITLE
[Home customization] Top site 4/7 (Fully Pinned)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5057]
Fully pinned: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234358_3-2-1_Add_New_Top_Sites_-_When_Home_Is_Full_Of_Top_Sites
Visual: https://zpl.io/a7AGrBR

**Comment by Daisy-pliu** [comment]
version:  2.1.22 (20098)
### ✅Scenario 1 : Add a topsite until the area is full 
Test case: 
1. Fresh Launch app
2. Tap [menu]
3. Tap [add top sites]
4. Tap a [non-existing top site]
5. Keep adding until the first page are full
6. Keep adding until the all pages are full
7. long tap [any topsite] -> tap [add top sites]

Test result: 
1.1 See [preset-level-1 sites] 
1.2 see [preset-level-2 sites]
3. See [ top site list menu] matched with Remote config 
4. See [top site added ] snack bar and [add more] button
5. See the site is pinned on the 2nd page 
7. See [please remove a site] snack bar on homepage

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
![Screenshot_20200703-130722_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86437154-78c0b400-bd36-11ea-8042-d09e370ef16f.jpg)
