### ISSUE TITLE
[Home customization] Top site 6/7 (Add Existing)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5058]
Add existing topsite: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234360_3-2-3_Add_New_Top_Sites_-_When_Home_Is_Empty_Copy
Visual spec: https://zpl.io/a7AGrBR

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.22(20098)
### Scenario 2 : Add an existing topsite 
Test case: 
1. Launch app
2. Tap [menu]
3. Tap [add top sites]
4. Tap [any existing topsite] 

Test result:
4.1 See [top site added ] snack bar and [add more] button

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
