### ISSUE TITLE
[Home customization] Top site 5/7 (All Removed)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5059]
All removed: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234359_3-2-2_Add_New_Top_Sites_-_When_Home_Is_Empty
Visual spec: https://zpl.io/a7AGrBR

**Comment by Daisy-pliu** [comment]
###  ✅ Scenario 1 : Remove topsite until the area is empty
Test case: 
1. Given topsites area is  full 
2.Launch app
3. Long tap to remove a topsite
4. Keep removing topsite until it shows [+] button
5. Tap [+] button

Test result:
5. See [add top sites menu]

###  ❌ Scenario 2 : Remove pinned Youtube site
Test case: 
1. Fresh Launch app
2. pin [Youtube] top site
4. Long tap [Youtube] top site
5. Tap [remove]

Test result:
2.  [Youtube site] is pinned
5. see no [Youtube topsite]

Expect result: 
5. still see [Youtube topsite]

**Comment by Daisy-pliu** [comment]
This issue will be tracked in next sprint.  So we will close the ticket.

**Comment by benjamin-cheng** [comment]
> Scenario 2 issue will be tracked in next sprint. So we will close the ticket.

The issue has been fixed by the PR above.

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
Both scenario passed https://github.com/mozilla-tw/FirefoxLite/issues/5059#issuecomment-652895605
