### ISSUE TITLE
[Home customization] Top site 7/7 (Animations) 

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5060]
Add topsite animations:
1. Icon showing up
2. Page change

**Comment by TLHuang** [comment]
Animation spec is ready, please check [here](https://drive.google.com/open?id=1JGMCOXWlLaIQYD3iYQsB2qRscwlMoRKZ&authuser=hhuang%40mozilla.com&usp=drive_fs), and the asset for highlight is uploaded [here](https://drive.google.com/open?id=1Hgf6F3LEBwRnX_wjSHM57WqqE3nq7ytK&authuser=hhuang%40mozilla.com&usp=drive_fs).

**Comment by Daisy-pliu** [comment]
### verify: ✅
### version : 2.1.23 (20224) preview
### SC1 : 
Test steps:
1. given [Youtube ] is not pinned & launch app 
2. long tap on any topsite 
3. tap [add topsites]
4. select [Youtube]

Actual result & Test result:
4. see animation highlighted around [Youtube]

### SC2 : 
Test steps:
1. given [Youtube ] is  pinned & launch app 
2. long tap on any topsite 
3. tap [add topsites]
4. select [Youtube]

Actual result & Test result:
4. see animation highlighted around [Youtube] again


### SC2 : 
Test steps:
1. given [Accuweater ] is not pinned and the first topsite page is fully pinned 
2. launch app 
2. long tap on any site
3. tap [add topsites]
4. select  [Accuweater]

Actual result & Test result:
4.1  it scrolls to on second  page
4.2 see animation highlighted around  [Accuweater] 

### SC3 : 
Test steps:
1. given [Youtube ] is pinned in first page and both 2 topsite pages are fully pinned 
2. launch app and scroll to the second topsite page
2. long tap on any site
3. tap [add topsites]
4. select  [Youtube]

Actual result & Test result:
4.1 it scrolls to on first page
4. see animation highlighted around  [Youtube]

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
