### ISSUE TITLE
[History Bug] Clearing History doesn't remove the frecency top sites immediately

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#5064]
**Describe the bug**
Clearing Browsing History (from the History panel) will not remove the frecency top sites immediately. After switching back from a 3rd party app, the top sites changed. But still not align with what we expected.

**Steps To Reproduce**
1. Go to Home
2. Remove any sites on the top sites (like Facebook)
3. Pin any top sites (like Twitter)
4. Tap menu and go to History
5. Tap clear browsing data 
6. Back to Home (There were no changes on top sites)
7. Switch to another app
8. Switch back to Firefox Lite

**Expected behavior**
The frecency sites should be removed immediately. (The behavior should be the same as going to History panel and clear browsing history.)
-> Pinned sites will keep
-> Removed sites stay removed
-> Frecency sites that are not pinned will be removed

**Actual behavior**
-> There were no changes before switching back to FxLite. (❌ it's a bug)
-> After switching back to FxLite:
   - Pinned sites stayed (✅ aligned with our expectation)   
   - Removed default top sites came back (❌ it's a bug)
   - frecency sites were removed (✅ aligned with our expectation)   
   - A random top site was pinned automatically in a random place (❌ it's a bug)

**Reproduce rate**
10/10

**User feedback**
Feedback from our top site survey:
<img width="525" alt="Screen Shot 2020-06-02 at 3 08 16 PM" src="https://user-images.githubusercontent.com/17559807/83625718-fd4cd500-a5c6-11ea-820d-f46fded4b8fe.png">

**Comment by tinahsieh** [comment]
This bug is related to bug #4994

**Comment by Daisy-pliu** [comment]
verify :  ✅
version: 2.1.21 (19828) Preview
Behavior is expected.

**Comment by Daisy-pliu** [comment]
verify : ✅
version: 2.1.22 (19906) Release
