### ISSUE TITLE
[Home Customization] Menu 3/3 (Shopping Search/Private Mode)

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5067]
**User story**
- As a user, I want to be able to make further customization such as changing the individual items (Verticals, Searchbar, topsite area, shopping search button...etc.) on the Home screen, so that I can access the features I want or hide the features I don’t need in order to improve my browsing experience.

**Summary**
If users have Private mode as their feature button, replace private mode in menu to shopping search, vise versa.

**Additional context**
![Group](https://user-images.githubusercontent.com/8919308/83726520-35f7b780-a676-11ea-90ab-023d119e6800.png)

**Comment by tinahsieh** [comment]
1. UX spec updated: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/417090947_4-5_Home_Menu
2. Need to add a copy string: "Smart Shopping Search"

**Comment by youwenliang** [comment]
Please refer to this ticket for metrics: https://github.com/mozilla-tw/FirefoxLite/issues/5031

**Comment by Daisy-pliu** [comment]
### verify:  ✅
### version : 2.1.22(20025)
### Test steps:
1. Given Preview Firebase Remote Config is enable_shopping_search = false on Japan_Debug
2. launch Lite
3.  switch country to  Japan_Debug
4. kill to relaunch app
5. tap [menu] 
6. tap [shopping search]

### Test result 
4. see [private mode icon] next to url bar
5. see [shopping search icon]
7. open smart shopping search tab

**Comment by Daisy-pliu** [comment]
This test case will add to Fxlite full run sheet 2.0

**Comment by tinahsieh** [comment]
The private mode icon looks a bit off. Need to move up a bit to make it align with the center.

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

**Comment by tinahsieh** [comment]
🚨 Visual audit failed.
The highlight badge position looks a bit off. @TLHuang can you provide a visual spec in a new bug? thanks!

**Comment by tinahsieh** [comment]
Remove the design audit tag due to a follow up bug #5204 is filed.
