### ISSUE TITLE
[Telemetry] pin topsite event correction

### ISSUE THREAD

**Issue by yshlin** [mozilla-tw/FirefoxLite#5073]
**Describe the bug**
Found that "position" extra in Pin Topsite event is incorrect when pinning items on page 2.

**Steps To Reproduce**
1. Go to page 2 topsite
2. Long press on a topsite
3. pin the topsite

**Expected behavior**
for page 2 items, position should start with 8

**Actual behavior**
found that position of page 2 items starts with 16, which is incorrect

**Screenshots/videos**
Seems like a legacy issue:
https://analytics.amplitude.com/mozilla-corp/chart/new/r4sifrr
![Screen Shot 2020-06-05 at 10 20 12 AM](https://user-images.githubusercontent.com/936571/83829748-292aa080-a716-11ea-8f79-a8cf98dd6e42.png)

**Device info (please complete the following information):**
 - Device: Pixel4
 - OS: Android 10
 - Webview 83.0.4103.96
 - Version 19748

**Reproduce rate**
100%

**Additional context**

**Comment by lanyliu** [comment]
done in [Telemtry] event correction #4995
close this ticket
