### ISSUE TITLE
Can't send push notification on production

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5075]
**Describe the bug**
Can't send push notification on production

**Steps To Reproduce**
Goal : To know the reach rate
Reach rate test =  Amplitude : Get Notification / Bigquery: counts
https://accounts.firefox.com/oauth/signin?client_id=bd8e8b17e9359f53&state=push_admin&scope=profile
Send date : 6/5
Test  : deeplink + image
stmoUrl:
https://sql.telemetry.mozilla.org/api/queries/71765/results.json?api_key=hBFlRGFLoTqFZUT9XYaUILnj7f1WBndONRyJgbzd
Title:Try the amazing "Smart Shopping Search"!    
Body: Compare prices across multiple sites at once.  Save money, save time!
msg id : test_0605_1st ; test_0605_2nd
display Timestamp : 1590796800000
 Display time < Send time -> so user will not see this 
2020/05/30 0000 
image URL: https://firebasestorage.googleapis.com/v0/b/rocketnightly.appspot.com/o/FCMImages%2FNotification%20-%20ID.png?alt=media&token=afecced4-4808-4cdb-bcc6-a3d655880739
pushDeepLink:  rocket://content/shopping-search

**Expected behavior**
send push

**Actual behavior**
internal error

**Comment by Daisy-pliu** [comment]
verifed: ✅
env: stable-dev 
Test with long context of body and title to send notification

**Comment by Daisy-pliu** [comment]
Deployed 0.31.1 on Production.
