### ISSUE TITLE
[Bug] Default browser

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5091]
**Describe the bug**
wrong string

**Steps To Reproduce**
Steps to reproduce the behavior: Flow 2 : open a url with no default browser
1. Click on setting
2. Click on 'set as defualt browser'
3. show dialog: 1 select browser app 

**Expected behavior**
 show dialog: 1 select Firefox Lite

**Actual behavior**
show dialog: 1 select browser app

**Comment by Daisy-pliu** [comment]
verify: ✅ 
version : Release build 2.1.21 (19805)
![Screenshot_20200609-152313_Firefox Lite](https://user-images.githubusercontent.com/44990878/84133132-5d38f500-aa79-11ea-990f-68a49e32e866.jpg)
