### ISSUE TITLE
[Remote config] Default browser - set_default_browser_tutorial_images

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5092]
**Remote config name**
str_set_default_browser_tutorial_images

**Audience setting**
Country = 'Indonesai'

**Parameter + Audience**'
{   "flow_1_step_1_image_url": "https://rocketnightly.firebaseapp.com/SD_goto_system_step1_ID.png",   "flow_1_step_2_image_url": "https://rocketnightly.firebaseapp.com/SD_goto_system_step2_ID.png",   "flow_2_step_2_image_url": "https://rocketnightly.firebaseapp.com/SD_open_external_ID.png" }

**Expected Online Time**
before 2.1.20 / Latest release on production 50%

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.21 (19805) Release build 
![Screenshot_20200609-165349_Firefox Lite](https://user-images.githubusercontent.com/44990878/84133907-5e1e5680-aa7a-11ea-9703-4668c485634a.jpg)
Country : indonesia
![Screenshot_20200609-165404_Firefox Lite](https://user-images.githubusercontent.com/44990878/84133905-5c549300-aa7a-11ea-994c-63a632f243bb.jpg)
