### ISSUE TITLE
Check Firebase e Crashlytics SDK versions 17.0.0 by 11/15/2020

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5097]
Do we need to upgrade following sdk?
- Firebase Crashlytics SDK versions 17.0.0+ for Android,
- 6.15.0+ for Unity before November 15, 2020 for the follow projects.

**Comment by niyali** [comment]
FYI. https://firebase.googleblog.com/2020/06/crashlytics-sdk-now-available.html
