### ISSUE TITLE
[Bug] Menu can't detect tap right after scrolling

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5103]
**Describe the bug**
When in a normal tab and open menu, you can trigger tap if you just finish scrolling the menu.

**Steps To Reproduce**
1. Go to any websites
2. Click on menu button to see the menu
3. Scroll down to the bottom to see "Exit" and "Clear Cache"
4. Quickly tap "Exit" or "Clear Cache" (within 1 second after scrolling)

**Expected behavior**
Trigger the click and perform the corresponding actions.

**Actual behavior**
Click is not triggered

**Screenshots/videos**

**Device info (please complete the following information):**
- Redmi Note 7
- Version: 19828

**Reproduce rate**
How many times you can reproduce such issue, given the testing rounds
10/10

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.1.23 (20237)
test step : https://github.com/mozilla-tw/FirefoxLite/issues/5103#issue-636906815

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
