### ISSUE TITLE
[Menu] Adjust the height of list items on menu panel

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#5107]
Design change for increasing the reacting area for each list item. The original height of list item on the menu is 38dp and it feels a bit hard to click on high-resolution phones, so we would like to increase the height to 44dp and enlarge the font size to 14dp(only for list items). Please help to improve it.

This change will affect the menu on home and tab, summary the changes as below,
1. The margin on top/bottom of the divider is changed to 7dp (Prev. was 8dp)
2. Remove the margins between two list items (Prev. had 4dp in between)
3. The height of list item is 44dp (Prev. was 38dp)
4. The font size changes to 14dp (Prev was 13dp)

Please refer to the visual spec for more details https://zpl.io/beEX6KD

**Comment by Daisy-pliu** [comment]
It is purely UI layout minor fix, mainly need visual designer audit so no QA effort here.

**Comment by tinahsieh** [comment]
We found it very easy to tap on the wrong item in our internal user testing. The recommended button height from [Material design](https://material.io/design/usability/accessibility.html#layout-and-typography) is 48dp, so we'd like to try it out:
1. Enlarge the line height to be 48dp (prev. was 44dp)
2. Panel height should be added. (panel height will be updated tomorrow.)

CC @TLHuang
