### ISSUE TITLE
[Menu] Change the option orders

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#5114]
Reorder the menu items based on the feedback from our UR and our telemetry data.
Updated UX spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/417090397_4-2_Toolbar_Menu

**Comment by Daisy-pliu** [comment]
verify: ✅
Version: 2.1.22 (20067)Preview 

![Screenshot_20200701-145030_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86217810-9402b680-bbb2-11ea-87ef-7b12891f22a3.jpg)
![Screenshot_20200701-145034_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86217818-95cc7a00-bbb2-11ea-94ff-bc272d4d6e83.jpg)

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
