### ISSUE TITLE
Topsite Icon issues & updates

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5118]
There are some invalid topsite icons or wrong-sized icons.
And also need new icons for the new topsite design.

## Invalid icons:
- abs-cbn
- cnn indonesia
- gma
- hdtv
- health
- inquirer
- jd
- kapanlagi
- medium
- pantip
- sindonews
- stackoverflow
- twitch

## Wrong-sized icons:
- Wikipedia (160x160)
- Twitter (192x192)
- Snapdeal (192x192) 
- LinkedIn (57x57)
- FRVR (500x500)
- Gamezop (256x256)

## New icons: (WIP)
- AccuWeather
- Airbnb
- Alibaba
- BBC
- BolaSport
- BuzzFeed
- CNBC
- CNN
- Cricbuzz
- Forbes
- Gmail
- Goibibo
- Hi5
- IMDb
- India Today
- IndiaMART
- INDOSPORT
- Just Dial
- MakeMyTrip
- Netflix
- News18.com
- NPR
- NYTimes
- OLX
- OYO
- Paytm
- Pinterest
- Quora
- Rakuten
- Sportskeeda
- The Print
- The Wire
- TikTok
- Traveloka
- Trip.com
- Tripadviser
- Tumblr
- Wattpad
- Yahoo News

**Comment by youwenliang** [comment]
cc @cnevinc @proevan

**Comment by youwenliang** [comment]
Icon files are here: https://drive.google.com/drive/folders/1UDlDh6mIN9ZMZdGdvK8gGt_Ihc08iGjN?usp=sharing

Topsite lists: https://docs.google.com/spreadsheets/d/1C6BUWt_7lAm-BxjMEF24PJCP4QUYprm3ntY5Cp3bICo/edit#gid=0

**Comment by benjamin-cheng** [comment]
@youwenliang 
1. Could you help to create another issue to track invalid icons?
2. Some icons are missing: ESPN, Vimeo, and Dailymotion.
3. Those category names in strings.xml do not match the names in topsites lists.
```
    <!-- top sites categories on the top sites list -->
    <string name="top_site_category_1">Popular Websites</string>
    <string name="top_site_category_2">Social Media</string>
    <string name="top_site_category_3">Entertainment</string>
    <string name="top_site_category_4">Others</string>
```

**Comment by youwenliang** [comment]
1. Here: https://github.com/mozilla-tw/FirefoxLite/issues/5137
2. Missing icons are uploaded
3. Will discuss with @tinahsieh to update this
4. Have fix the url with issues, just follow the display links in the table.

**Comment by youwenliang** [comment]
@benjamin-cheng These are the icons that need to be updated: https://drive.google.com/drive/folders/1fx01R_wxIJ9xqMs4e1x1Cxb7470rTIu1?usp=sharing

**Comment by Daisy-pliu** [comment]
This is a icon reference to #5028 so Testing will mainly be conducted in #5048
