### ISSUE TITLE
Script to automatically generate image url in both Preview and Prod env

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5120]
**Vision**
We will save more back and forth time on feature's images remote config process.

**Current Status**
It originally takes 2 separated times for UX to get Preview image URL and prod image URL 

**Proposed Process**
When we have a feature which needs to be remote configured with image , we would like to have  both image url generated from Preview's env and image url from Prodution's env. 
So the process would be simplified as UX both request Preview URL and Prod URL at once by offering image to Linear.

**Comment by Daisy-pliu** [comment]
please also help provide production image url for `str_set_default_browser_tutorial_images` thank you!

**Comment by niyali** [comment]
Done. 
https://github.com/mozilla-tw/statics/commit/e2022c3d45c148cae283bc68aaaf631cd679a76d
