### ISSUE TITLE
[Bug] Menu - white space under library panel

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5123]
**Describe the bug**
white space under library

**Steps To Reproduce**
1. Go to 'Menu'
2. Click on option on the panel
3. Scroll down to the end of list

**Expected behavior**
no white space 

**Actual behavior**
white space
![Screenshot_20200617-180501](https://user-images.githubusercontent.com/52307187/84885968-5720c500-b0c6-11ea-9dda-50c6bd5bc58d.png)

**Device info (please complete the following information):**
 - Device: Pixel 3a
 - OS:  Android 10
 - Version 2.1.21(19886)

**Reproduce rate**
10/10

**Comment by youwenliang** [comment]
@proevan I can still see the white space, will need @Daisy-pliu to confirm.

**Comment by Daisy-pliu** [comment]
still white space here. Need to check with dev if there is limitation.

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release

![Screenshot_20200703-102157_Firefox Lite](https://user-images.githubusercontent.com/44990878/86428461-6424f180-bd1f-11ea-8706-61edaa08504f.jpg)
