### ISSUE TITLE
[Bug] Menu causes landscape disabled

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5124]
**Describe the bug**
Right after accessing menu, the landscape mode can't be accessed.

**Steps To Reproduce**
1. Go to any webpages
2. Click on menu
3. Dismiss menu
4. Rotate your device

**Expected behavior**
See landscape mode

**Actual behavior**
Still in portrait mode

**Device info (please complete the following information):**
 - Version: 2.1.21(19886)

**Reproduce rate**
10/10

**Comment by Daisy-pliu** [comment]
verify : ✅ 
version : 2.1.22 (20067) Preview
test step: https://github.com/mozilla-tw/FirefoxLite/issues/5124#issue-640336400
looks good to me

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
