### ISSUE TITLE
[Menu] Remote-config setting

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5126]
**Remote config keys** 
https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_bottom_bar_items_v2-str_menu_bottom_bar_items_v2_5-and-str_private_bottom_bar_items

https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_menu_items

**Comment by Daisy-pliu** [comment]
## verify : ❌
## version
2.1.22 (19908)
## Test scenario :Remote config
### Test steps:
1. On Preview remote config,  set up the combination of `str_menu_bottom_bar_items_v2_5` = [   { "type":9 },     { "type":10 },     { "type":11 },     { "type":12 },     { "type":13 } ]
2. launch app
3. tap any tops site
4. see [forward page] [private mode] [trash][empty][backward]
5.tap [empty]cell

![Screenshot_20200618-161120_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/85001799-b2b28780-b186-11ea-90d6-a9a7a0fc8f90.jpg)

### Test restult:
3. see see [forward page] [private mode] [trash][tracker][backward]
5. should be no crash 

**Additional info**
Firebase Crashlytics crash event please see https://console.firebase.google.com/u/0/project/rocketnightly/crashlytics/app/android:org.mozilla.rocket.beta/issues?state=open&time=last-seven-days&type=crash&versions=2.1.22(19908).beta%20(19908)

**Comment by Daisy-pliu** [comment]
verify : ✅
According to Doc In [WIKI remote config](https://github.com/mozilla-tw/FirefoxLite/wiki/Remote-Config#str_menu_items) ,`str_bottom_bar_items_v2 and str_menu_bottom_bar_items_v2_5 has not supported Private Home, Delete Tab and Tracker` 

so this ticket is actually passed .

**Comment by Daisy-pliu** [comment]
Remember to add this key into [Remote config sheet](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1047128443)

**Comment by Daisy-pliu** [comment]
Added these 2 new parameters to [Firefox Lite 2.0 remote config sheet.](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=1047128443)
