### ISSUE TITLE
[Giggle] Integrate giggle on the Preview for test

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5128]
**User story**
As a user, I would like chose Giggle as my default browser in setting - search engine.
https://gggle.co/

**Additional context**
This is only merged with Preview. If we would like to integrate with production, PMs will open another issue.

Confimed with Max : Already in debug view

**Comment by shsu571** [comment]
https://github.com/mozilla-tw/FirefoxLite/pull/5016

**Comment by shsu571** [comment]
PM needs to add icon

**Comment by shsu571** [comment]
Logo
![Giggle log](https://user-images.githubusercontent.com/52307187/85355511-56ad8180-b53f-11ea-928c-5513ecefaf5f.png)

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(20040) Fxlite Preview
test step: 
1. launch app
2. tap [menu] -> [setting] -> [default search engine]
3. select giggle
4. back to home 
5. search "world news"

test result:
5. see search result with giggle search engine.

![Uploading Screenshot_20200630-141341_Firefox Lite Preview.jpg…]()

**Comment by Daisy-pliu** [comment]
verify : ✅
Version : preview 2.1.23(20137)
