### ISSUE TITLE
[Giggle] Giggle into to private mode  as default serach engine on the Preview for test

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5129]
**User story**
As a user, I would like to use Giggle to search directly in private mode.

**Additional context**
This is only merged with Preview. If we would like to integrate with production, PMs will open another issue.

** Requirement**
-We can choose different searching engine as default in different mode
-We want to have : 
Giggle as default search engine in private mode 
Normal mode still keeps Google as default search engine

**Comment by Daisy-pliu** [comment]
### verify: ❓
### version :  2.1.22 (20040)
test step: 
1. launch app
2. tap [private mode]
3. type "best latte"
4. tap [search bar]
5. type  "coffee art" 
6. tap [enter]

Actual result: 
3. see "best latte" search result with Giggle search engine
6.1 keyboard still there 
6.2 see "coffee art" search result with Giggle search engine

Expect result: 
6.1 keyboard not there 


Risk: 
it might not user friendly that users have to disimss keyboard whenever doing a new search

**Comment by youwenliang** [comment]
I agree that the keyboard should be dismissed after performing another search.

**Comment by shsu571** [comment]
This might be Giggle's design. 
Giggle didn't do a whole page refresh, so the keyboard will still be there.
PM will ask engineers from Giggle. 
This is the followup ticket of this issue https://github.com/mozilla-tw/FirefoxLite/issues/5177

**Comment by Daisy-pliu** [comment]
Great then we can track on #5177 while close this issue.

**Comment by Daisy-pliu** [comment]
verify : ✅
Version : preview 2.1.23(20137)
