### ISSUE TITLE
Add more space at the end of add top sites page

### ISSUE THREAD

**Issue by TLHuang** [mozilla-tw/FirefoxLite#5143]
In add top sites page, when the user scrolls to the end of the page, it needs to have some empty space for indicating no more item below. Please refer to the visual spec for more details [Link](https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5ef1ae13a7a4e446be0970e5/)

![Screenshot_2020-06-23-15-43-15-778_org mozilla rocket beta](https://user-images.githubusercontent.com/4092794/85375227-92107600-b568-11ea-9290-80351a475fce.jpg)

**Comment by tinahsieh** [comment]
@benjamin-cheng 
I also noticed that both of this page and settings page are missing the "scroll to the end" feedback. Can we add it back?

**Comment by tinahsieh** [comment]
> @benjamin-cheng
> I also noticed that both of this page and settings page are missing the "scroll to the end" feedback. Can we add it back?

Track this issue in #5172
