### ISSUE TITLE
 [Home customization] Top site  - Remove Fixed top site

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5146]
Remove Fixed top site remote config

- code 

- Firebase

We will not have any fixed top sites after version 2.5 release.

**Comment by Daisy-pliu** [comment]
Slack discussion : https://mozilla.slack.com/archives/CS7KS9DT6/p1592900417155200

**Comment by Daisy-pliu** [comment]
finish config for Taiwan, india, indo  on Nightly.

**Comment by benjamin-cheng** [comment]
Fixed top sites has been removed from code. 
PR: #5182

**Comment by chianger** [comment]
Moving to S4-10 for tracking the remote config on production

**Comment by Daisy-pliu** [comment]
After remove the remote config need to test backward compatibility on previous version.

**Comment by Daisy-pliu** [comment]
I just set  "str_top_sites_default_items" to [] empty array in Preview and Production so that in build under v2.5 user will not receive any fixed topsites

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
