### ISSUE TITLE
[Remote Config] Topsite Recommendation inside selection panel

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5149]
**Remote config name**
str_recommended_sites

**Audience setting**
India users
Indonesia users
Default (Global)

**Parameter + Audience**
Follow this document:
https://docs.google.com/document/d/1iczVTRhrCoxjswLZ5sFpKHEhIL1iFARthElfLPnc5-g/edit?usp=sharing

**Expected Online Time**
Week of 6/29

**Additional context**
This is related to #5046

**Comment by youwenliang** [comment]
@Daisy-pliu the document is updated, let me know if the format is valid, thanks!

**Comment by Daisy-pliu** [comment]
@youwenliang  the doc has good format. It is configured on Preview v.2.1.22(19949), looks good on my side. 
Please double confirm if it meets product expectation. Thanks !

**Comment by youwenliang** [comment]
Looks good to me, currently having some icons replaced with the new ones . Once that's done, we can close this issue.
related to: https://github.com/mozilla-tw/FirefoxLite/issues/5118#issuecomment-648610685

**Comment by chianger** [comment]
Moving to S4-10 for tracking the remote config on production

**Comment by Daisy-pliu** [comment]
setup on str_recommended_sites is configured on Preview and Production on Indo. India, Global.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
