### ISSUE TITLE
Google play test account for India, Indonesia and Nigeria

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5156]
For feature testing and know what users really see on the play store, need to have following account:
-Nigeria
-India
-Indonesia

Different country account of google play on different devices.

**Comment by Daisy-pliu** [comment]
Created accounts please refer [Emerging Markets Playstore Account](https://docs.google.com/document/d/160Tc7D9IEvNvv20EbzbzRLDlN5nhN7cIqMbvC0zafdo/edit#heading=h.ei6o5mnygd5r)
