### ISSUE TITLE
[Home customization] Onboarding  (Android dark theme)

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5157]
Redefine the current night mode to be only adjusting the screen brightness:
Dark theme: UI -> Black (disconnect the brightness adjustment)
Night mode: brightness adjustment (disconnect the UI theme setting)

**Comment by tinahsieh** [comment]
UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/423261690_3-3_Night_Mode_And_Theme

**Comment by Daisy-pliu** [comment]
## verify: ✅
## version: 2.1.23(20297)
### Test step:
1.  launch app
2. tap [menu] -> [theme] 
3. change theme color 
4. turn on [night mode]
5.  swipe to increase brightness bar

### Expect Result & Actual Result:
4.1 see brightness is decreased 
4.2  see night mode is turned on 
4.3 see brightness bar
5. see brightness is increased 

Note : confirmed with PM that "night mode mechnism" will not be implemented this time.

**Comment by Daisy-pliu** [comment]
verify: ✅
version : 2.5.0(20358) Release
