### ISSUE TITLE
[Menu] change the item order in home menu

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#5164]
Please update the home menu items based on the new spec, thank you!
UX spec: https://mozilla.invisionapp.com/share/ABWI1559QRJ#/417090947_4-5_Home_Menu
Visual spec: https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/screen/5ed9c5fc0572feb7d6824951

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.22(20067) Preview
![Screenshot_20200701-150159_Firefox Lite Preview](https://user-images.githubusercontent.com/44990878/86219054-3c654a80-bbb4-11ea-881e-c38979eed12d.jpg)

**Comment by Daisy-pliu** [comment]
verify : ✅
version : 2.1.23 (20122) Release
