### ISSUE TITLE
Preview build - schedule request

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5168]
Start date: 7/1
Add 2 preview building schedule: 14:00 and 17:00 for the team to audit new implemented features.

Current statue: only have 1 build at 12:00 am every day. 
Problem: can't see the new implementation features in time and have time to check the features before release.

**Comment by Daisy-pliu** [comment]
Checked on Bitrise, seems we originally have 3am preview build on weekday. So I kept it as it is.
After adding 2 new schedule time , from now on we will have 14:00, 17:00 and 3:00 preview build on weekdays.
<img width="1662" alt="Screen Shot 2020-06-30 at 4 26 55 PM" src="https://user-images.githubusercontent.com/44990878/86102841-9bf92280-baee-11ea-8d68-796847ffdf94.png">
