### ISSUE TITLE
[Topsite] Icon adjustment for the topsite area

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5173]
With the new topsite design, we want to update the color placements for the websites:

1. All the websites/url with icons will have a white background instead of dominant color background.
2. Keep the Pin icon's color based on the dominant color of the website icon.
3. Will update all the square icons with 4px round corner @TLHuang 
4. Topsites that are added by frecency will also have white backgrounds (and colored pin if pinned)

Here's the mockup:
![Top Sites - Fully Pinned](https://user-images.githubusercontent.com/8919308/86108695-111c2600-baf6-11ea-912c-8c3756484c9b.jpg)

This is related to #5163 and #5046 and #5118

**Comment by youwenliang** [comment]
New updated icons here: https://drive.google.com/drive/folders/1DMDc_FYg039GdAGxhEYqgqUuJWqtrIvQ?usp=sharing

**Comment by benjamin-cheng** [comment]
@youwenliang could you please help on the following asset changes? Thank you! 
1. `ic_idn.webp` should rename to `ic_idntimes.webp`
2. `ic_rakutan.webp` should rename to `ic_rakuten.webp`
3. `ic_sanook.webp` should convert to `png`

**Comment by youwenliang** [comment]
@benjamin-cheng updated!

**Comment by youwenliang** [comment]
per visual's request, the round corner is wrong for the following icons: https://drive.google.com/drive/folders/1f5ryOiOmSfprLB3LLTYUrUSmbkQUSLLw?usp=sharing
@benjamin-cheng Will need to reupload these icons, thanks!

**Comment by Daisy-pliu** [comment]
This ticket focus on Visual design audit so no QA effort here.

**Comment by tinahsieh** [comment]
@benjamin-cheng I've applied 4px round corners to these icons. Please update them, thank you! 
https://drive.google.com/drive/folders/1odGLeRDq2cS6P4agiy9H_GxFoPkUr6hl
