### ISSUE TITLE
[SUMO] Update SUMO pages for Firefox Lite v2.5

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#5174]
Keep track of the progress for updating the SUMO pages for Firefox Lite v2.5

Document here:
https://docs.google.com/document/d/17ZMkLzEaxu-eEDSvqXh6yhcedsV-BGlp6y8TJ3TV-uE/edit?usp=sharing
Missing article: Awesome Bar, What's New page for v2.5

Bugzilla ticket here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1647231

**Comment by chianger** [comment]
according to bugzilla, all updates are live. we might close this bug now?
