### ISSUE TITLE
 Users may not know they could scroll down the menu.

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5185]
**Describe the bug**
New Menu: cannot see "Settings" because it's below the fold.  Users may not know that they need to scroll down the page.

**Steps To Reproduce**
1. Open Menu
2. Look for setting, doesn't see it on the menu and doesn't know I can scroll down the page

**Device info (please complete the following information):**
 - Version: 20002 preview

**Reproduce rate**

**Additional context**
It is a feature enhancement suggested by Cynthia during dogfooding

**Comment by tinahsieh** [comment]
Close this issue because it can be fixed by #5107.
