### ISSUE TITLE
[Add Top Site] Adding a context menu to the blank space

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#5196]
Based on the internal user testing results, we'll slightly change the position of the button "add top sites". 
1. Add a context menu to the blank space with an option "Add top sites".
2. Remove the "Add top sites" from the context menu which is opened by long pressing any top sites.

Please see the "update" label in the UX spec: https://mozilla.invisionapp.com/share/7YXG8U1NEJZ#/419234356_3-1_Add_New_Top_Sites

**Comment by lanyliu** [comment]
update telemetry [spec](https://docs.google.com/spreadsheets/d/1kkLDEpwWSbaMqpR2Pt4ydK7Zt3FSAaEhw0quaTSJJXY/edit#gid=888392947&range=D74) for revised UX design

**Comment by tinahsieh** [comment]
@youwenliang could you please review this to see how can we adjust the telemetry to mapping this design change?

**Comment by youwenliang** [comment]
> @youwenliang could you please review this to see how we can adjust the telemetry to meet this design change?

Thanks @lanyliu for updating the telemetry parameters.

**Comment by lanyliu** [comment]
done telemetry checking
