### ISSUE TITLE
[Menu] Adjust the height of the menu items to 48dp

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#5198]
We found it very easy to tap on the wrong item in our internal user testing. The recommended button height from [Material design](https://material.io/design/usability/accessibility.html#layout-and-typography) is 48dp, so slightly adjust the item height as below:
1. Enlarge the list item height to 48dp for home menu and toolbar menu (prev. was 44dp)
2. Adjust the home menu, toolbar menu, and library panel height to 364dp (prev. was 340dp)

See the adjusted version as the screenshot below:
<img width="665" alt="Screen Shot 2020-07-03 at 12 00 31 PM" src="https://user-images.githubusercontent.com/17559807/86430840-cb45a480-bd25-11ea-9f38-43f29a0b0512.png">

CC @TLHuang

**Comment by Daisy-pliu** [comment]
This ticket focus on Visual design audit so no QA effort here.
