### ISSUE TITLE
[Telemetry] Download spec review

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5213]
data spec: https://docs.google.com/spreadsheets/d/1o8p47imE-MkaArVYqRxIR5Eh2ZQzlC3vfdUuIgfcONc/edit#gid=888392947

Spec: https://docs.google.com/document/d/1Qjtt4Zatzb5CWV2qDBob-rftswhXmg4WizbcHmqPr30/edit#

**Comment by yshlin** [comment]
FIXME:

 -  start file size MB? but end file size become KB?
 -  background cancel: progress/filesize = null

**Comment by lanyliu** [comment]
found another bug
- when download a picture, will get 0 file size in start event.
