### ISSUE TITLE
Build your own browser - test mode

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5229]
Spec detail is here:https://docs.google.com/document/d/1uPhL1RBRnVZ5lxzFy-gvxhCAbHWHCjG_AF1iHXTMhLI/edit#heading=h.v60bcawa5cvv
This issue is for 1 to 4 items about test mode setting

**Comment by shsu571** [comment]
discuss with engineers on 7/28 -> feasibilty is okay

**Comment by hsiangyu69** [comment]
Test mode and database part are feasible
