### ISSUE TITLE
Crashes on DelegateAdapter

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5247]
version : 2.1.23(20097) Preview
Crash report: 
https://console.firebase.google.com/u/0/project/rocketnightly/crashlytics/app/android:org.mozilla.rocket.beta/issues/07d85ff16e68e62224293d97fad6d34d?time=last-seven-days&sessionId=5F0EBC5B03B3000176767DD5094E817D_DNE_0_v2

**Comment by Daisy-pliu** [comment]
version :  2.1.23(20297) 
Test Step: 
1. launch app
2. kill app to skip onboarding
3. tap [games] or  [news]

Actual result:
3. crash

Expect Result:
3. see games or news list page

**Comment by chianger** [comment]
put "need design audit" label just in case the fix will impact on UI/UX.

**Comment by Daisy-pliu** [comment]
verify:  ✅
version : 2.5.0(20358) Release
step: https://github.com/mozilla-tw/FirefoxLite/issues/5247#issuecomment-658663156
