### ISSUE TITLE
Remove remote config "str_content_hub_items" and "str_top_sites_default_items"

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5254]
To perform testing , remember to take off "str_content_hub_items" and "str_top_sites_default_items" on Remote config Preview and Production after #5242 merge

_Originally posted by @Daisy-pliu in https://github.com/mozilla-tw/FirefoxLite/issues/5032#issuecomment-658568935_

**Comment by chianger** [comment]
Together with #5146 , @Daisy-pliu will complete the remote config before v2.5 going to beta.

**Comment by Daisy-pliu** [comment]
Confirmed that str_content_hub_items" and "str_top_sites_default_items will keep as it is for users with build under v2.5. To support new user we will have str_content_hub_items_v2_5 and  str_top_sites_default_items_v2_5
