### ISSUE TITLE
 Build your own browser - pin feasibilty

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5261]
Spec detail is here:https://docs.google.com/document/d/1uPhL1RBRnVZ5lxzFy-gvxhCAbHWHCjG_AF1iHXTMhLI/edit#heading=h.v60bcawa5cvv
This issue is for 5 to 6 items about pin feasibility

**Comment by shsu571** [comment]
discuss with engineers on 7/28 -> feasibilty is okay

**Comment by hsiangyu69** [comment]
After discussing, we might be use share preference to store the pin of a user
@benjamin-cheng @proevan
