### ISSUE TITLE
Themes button doesn't do anything 

### ISSUE THREAD

**Issue by ariefbayu** [mozilla-tw/FirefoxLite#5280]
**Describe the bug**
In the options menu, there are "Themes" button. Tapping it doesn't do anything. 

**Steps To Reproduce**
1. Go to '...' on bottom right corner
2. Options show up
3. Tap on "Themes" 
4. Nothing happens

**Expected behavior**
Something should happen

**Actual behavior**
Nothing happened

**Screenshots/videos**

https://drive.google.com/file/d/1VEZWAj_Uxt0_ma5ZdwlLs87ijFqOZZ5D/view?usp=drivesdk

**Device info (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: Android 9
 - App version: 2.1.23(20138)
 - WebView version: 84.0.4147.89

**Reproduce rate**
Every time

**Comment by ariefbayu** [comment]
Hmm... Now the button disappeared. Did you guys just switched server setting accidentally?

![Screenshot_20200721-172224](https://user-images.githubusercontent.com/55084/88042896-df3b3400-cb76-11ea-9274-1670fcea09ac.png)

**Comment by ariefbayu** [comment]
Sorry, wrong screenshot in the first comment.
![Screenshot_20200721-172521_cropped](https://user-images.githubusercontent.com/55084/88043332-81f3b280-cb77-11ea-85e4-543163b9f38a.png)

**Comment by ariefbayu** [comment]
Found the button again. Apparently, it only shows when no tab is opened.
![Screenshot_20200721-173437_cropped](https://user-images.githubusercontent.com/55084/88045391-a43a0000-cb78-11ea-9dbc-8f0bc29bd8f0.png)

**Comment by shsu571** [comment]
This is an unfinished feature. Could you update to the current version or wait for next update?  We already finished the feature at least version 2.5.0(20400). Thank you!

**Comment by ariefbayu** [comment]
confirmed, feature works in 2.5.0 (latest download from play store).
