### ISSUE TITLE
Should not switch search engine in Private mode 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5285]
**Steps To Reproduce**
1. launch app
2. tap [menu] -> [setting]
3. tap [search engine] -> choose [duckduckGo]
4. back to home 
5. tap [settings] -> [private mode]
6. search "skirt"

**Expected behavior**
6. it shows Google 's skirt search result

**Actual behavior**
6. it shows duckduckGo 's skirt search result

**Device info (please complete the following information):**
all
**Reproduce rate**
5/5

**Additional context**

**Comment by shsu571** [comment]
This is acceptable condition for PMs!
