### ISSUE TITLE
v2.5 crash Launch intent dispatch 

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#5289]
**Describe the bug**
Launch intent dispatch since 2.1.22
https://console.firebase.google.com/u/4/project/zerda-dcf76/crashlytics/app/android:org.mozilla.rocket/issues/ee985ed20c9e88ae9aab38b28343041d?time=last-seven-days&sessionId=5F1E057E0156000145C00C21C82C2294_DNE_0_v2

**Comment by cnevinc** [comment]
Looks like a rash from Firebase.
https://groups.google.com/forum/#!topic/firebase-talk/2kNSAt5gNYE

what we can do is to use the SafeIntent like Fennec and Fenix
https://github.com/mozilla-tw/FirefoxLite/blob/d02931563b077c2dfbaff73593a51202987c85ba/app/src/main/java/org/mozilla/focus/utils/SafeIntent.java#L85

**Comment by shsu571** [comment]
According crash amount, this is P1. 
I will confirm with @cnevinc and @Daisy-pliu to know how this crash affects users.
