### ISSUE TITLE
 Upload APK to distributed channels and verified v2.5.1 

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/FirefoxLite#5293]
Mozilla-Next
XiaomiStore
SamsungStore

**Comment by niyali** [comment]
uploaded to mozilla-next and verified. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1655643
https://bugzilla.mozilla.org/show_bug.cgi?id=1655644

**Comment by Daisy-pliu** [comment]
Also Github is verified https://github.com/mozilla-tw/FirefoxLite/releases/tag/v2.5.1

**Comment by niyali** [comment]
xiaomi store and samsung store latest version verified.
