### ISSUE TITLE
Show the snack bar when toolbar is hiding

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#5295]
If the toolbar is hiding, show the snack bar.
UX Spec 
Download: https://mozilla.invisionapp.com/share/W9Y7ZXOSNHC#/screens/426649501

**Comment by shsu571** [comment]
PM & UX will list all related scenario:

- Download
- Bookmark

**Comment by hsiangyu69** [comment]
After investigating, we are going to fix these related scenario:

- Download

- Bookmark

- permission

-
