### ISSUE TITLE
[PREVIEW] [CRASH]  PrivateModeActivity.kt line 114 

### ISSUE THREAD

**Issue by niyali** [mozilla-tw/FirefoxLite#5323]
[No impact on production] 

URL: https://console.firebase.google.com/project/rocketnightly/crashlytics/app/android:org.mozilla.rocket.beta/issues/1153819fb783aa17f971be954c80e688

The crash starts to be seen at Preview build #20539, commit hash 0c0cecf8e4ee9113817716a20d21baf7b056a78e
There are 3 out of 21 users being affected by this. crash-free rate is 85.71%.

**Comment by niyali** [comment]
@shsu571

**Comment by shsu571** [comment]
I think this might be the risk for the next release. I will ask in the channel  to let engineers to take a look. Thanks!

**Comment by benjamin-cheng** [comment]
Fixed by #5320
