### ISSUE TITLE
Download panel: display progress&status; user interaction: cancel, resume, WIFI download

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#54]

**Comment by chianger** [comment]
this was triaged to be P2 feature

**Comment by mTwTm** [comment]
Cancel itself will be P1, see #151

**Comment by NashTung** [comment]
The resume & WIFI download function does not on user interaction
Video: https://drive.google.com/open?id=1X6AiHgtLe2WQF7n9l1rm8Gn0tHTqaD9_

Device: Redmi 4A
Rocket: 2.1.1(4696).nightly
Android: 7.1.2
Android Webview: 67.0.3396.68

**Comment by mTwTm** [comment]
partially resolved in #3021

**Comment by mTwTm** [comment]
Actually, I tend to believe we can close this one as some of the items are just not possible with Download Manager and some are irrelevant anymore.
