### ISSUE TITLE
ANR after hitting capture screenshot

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/FirefoxLite#559]
**STR**
1. Visit http://m.slashdot.org/story/330789
2. Try to capture a screenshot
3. The content view becomes darker without animation shown
4. No response for about 10 secs
5. System alarms Zerda is not responding
6. Click "Wait"
7. Capture animation shows and loops
8. Capture complete

**DuT:** Advan
**Build:** 702

**Comment by mTwTm** [comment]
This sounds like a won't fix for current implementation. In step 3, we're doing some heavy work on the main thread which is limitation in current implementation and the result is Android might show a warning for lower-ended devices. We've already shift the more lengthier part to another thread.

**Comment by chianger** [comment]
QA tried on Oct12 and Oct13 but no luck to reproduce this.
We'll consider downgrade this to P2.

**Comment by chianger** [comment]
some info from Max: to better reproduce this, try tap on the screen before the screenshot animation shows up, or switch Rocker to background.
Let's sync up with QA on the STRs and summarize with a repro rate. Then we can decide downgrading its priority with that info.

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1-U0c97oS3vvVaFTwovXit4ED4E6ZkRSj

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81
