### ISSUE TITLE
[Smoke Test] Screenshot animation doesn't start right after appearing

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/FirefoxLite#673]
As title. Not 100% reproducible.

Build: 855
DuT: Samsung, Advan, Andromax

**Comment by mTwTm** [comment]
Expected since a part is done on main thread and thus there is a brief while we can't do updates depending on device capability. I'll assign this to Max since he is looking into this.

**Comment by Conjuror** [comment]
related to #559

**Comment by chianger** [comment]
leave it open but #559 likely will fix this as well.

**Comment by Conjuror** [comment]
The issue is still there and we will see the animation flashes a little bit in the beginning.

**Comment by NashTung** [comment]
Work for me.
Video:
https://drive.google.com/open?id=1s74jokX01jcN-W5acf7u2YcLYmUqIdyZ

Device: Advan i5C
Rocket: 2.0.0(4168).nightly
Android: 5.1
Android Webview: 51.0.2704.81
