### ISSUE TITLE
[Smoke Test] "Cannot find the file." shows in some occasions

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/FirefoxLite#790]
**STR**
1. Download a file
2. Open Downloads panel while the download is still in progress
2-1. Tap on the unfinished file
**Oppo** -> "Cannot find the file." (reproduce rate 80%)
**Samsung** -> Jumps to system downloads history
2-2. Tap on the file after the download is finished
**Oppo** -> "Cannot find the file."
**Samsung** -> System gallery tries to open the file but will fail to do it
3. Open/Reopen Downloads panel *after* the download is finished -> works normally

**DuT:** Oppo, Samsung
**Build:** 1050

**Comment by mTwTm** [comment]
Should be fixed now.

**Comment by ivantw08** [comment]
verified.

Device: nexus 5
Rocket: 3.4.1(7717)
Android: 6.0
Android Webview: 69.0.3497.100

Downlaod some images from youtube and files from gmail.
